DROP TRIGGER ASU.TURALGO_BEFORE_INSERT
/

--
-- TURALGO_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TURALGO (Sequence)
--   TURALGO (Table)
--
CREATE OR REPLACE TRIGGER ASU."TURALGO_BEFORE_INSERT" 
BEFORE  INSERT  ON ASU.TURALGO REFERENCING
 NEW AS NEW
 OLD AS OLD
FOR EACH ROW
Begin
  SELECT SEQ_TURALGO.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


