DROP TRIGGER ASU.TLECHPARAM_BEFORE_INSERT
/

--
-- TLECHPARAM_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TLECHPARAM (Sequence)
--   TLECHPARAM (Table)
--
CREATE OR REPLACE TRIGGER ASU."TLECHPARAM_BEFORE_INSERT" 
BEFORE INSERT
ON ASU.TLECHPARAM REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
begin
 SELECT SEQ_TLECHPARAM.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
END;
/
SHOW ERRORS;


