DROP TRIGGER ASU.TLECHCONT_BEFOR_INSERT
/

--
-- TLECHCONT_BEFOR_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TLECHCONT (Sequence)
--   TLECHCONT (Table)
--
CREATE OR REPLACE TRIGGER ASU."TLECHCONT_BEFOR_INSERT" 
BEFORE INSERT
ON ASU.TLECHCONT REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  SELECT SEQ_TLECHCONT.nextval INTO :new.fk_id FROM dual;
END;
/
SHOW ERRORS;


