DROP TRIGGER ASU.TDOGOVOR_BEFORE_INSERT
/

--
-- TDOGOVOR_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TDOGOVOR (Sequence)
--   TDOGOVOR (Table)
--
CREATE OR REPLACE TRIGGER ASU."TDOGOVOR_BEFORE_INSERT" 
BEFORE INSERT
ON ASU.TDOGOVOR REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
Begin
  SELECT SEQ_TDOGOVOR.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


