DROP TRIGGER ASU.TKLADR_UPDATE_BEFORE_INSERT
/

--
-- TKLADR_UPDATE_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TKLADR_UPDATE (Sequence)
--   TKLADR_UPDATE (Table)
--
CREATE OR REPLACE TRIGGER ASU."TKLADR_UPDATE_BEFORE_INSERT" 
 BEFORE INSERT ON ASU.TKLADR_UPDATE  REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
 SELECT SEQ_TKLADR_UPDATE.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
END;
/
SHOW ERRORS;


