DROP TRIGGER ASU.TFILES_AFTER_DELETE
/

--
-- TFILES_AFTER_DELETE  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   TFILES (Table)
--   TBLOBS (Table)
--
CREATE OR REPLACE TRIGGER ASU."TFILES_AFTER_DELETE" 
  AFTER DELETE ON ASU.TFILES   REFERENCING OLD AS OLD NEW AS NEW
  FOR EACH ROW
BEGIN
  DELETE FROM TBLOBS WHERE FK_ID = :old.FK_BLOBID;
END;
/
SHOW ERRORS;


