DROP TRIGGER ASU.TDIAGTEMPLATE_AFTER_DELETE
/

--
-- TDIAGTEMPLATE_AFTER_DELETE  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   TDIAG (Table)
--   TDIAGTEMPLATE (Table)
--
CREATE OR REPLACE TRIGGER ASU."TDIAGTEMPLATE_AFTER_DELETE" 
AFTER  DELETE  ON ASU.TDIAGTEMPLATE REFERENCING
 NEW AS NEW
 OLD AS OLD
FOR EACH ROW
Begin
  DELETE FROM TDIAG WHERE FK_ID=:OLD.FK_TEMPLATEID;
End;
/
SHOW ERRORS;


