DROP TRIGGER ASU.TLOG_BEFORE_INSERT
/

--
-- TLOG_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TLOG (Sequence)
--   TLOG (Table)
--
CREATE OR REPLACE TRIGGER ASU."TLOG_BEFORE_INSERT" 
 BEFORE 
 INSERT
 ON ASU.TLOG  REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
begin
    SELECT SEQ_TLOG.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
end;
/
SHOW ERRORS;


