DROP TRIGGER ASU.TAMBULANCE_A_INS
/

--
-- TAMBULANCE_A_INS  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   TAMBULANCE (Table)
--   TEXP_TPACKART (Table)
--
CREATE OR REPLACE TRIGGER ASU."TAMBULANCE_A_INS"
 AFTER INSERT
 ON ASU.TAMBULANCE  REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
BEGIN
  INSERT INTO ASU.TEXP_TPACKART(FK_PACID, FP_ISABULANCE)
  VALUES(:NEW.FK_ID, 1);
End;
/
SHOW ERRORS;


