DROP TRIGGER ASU.TSLFORMREQUEST_BEFORE_INSERT
/

--
-- TSLFORMREQUEST_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TSLFORMREQUEST (Sequence)
--   TSLFORMREQUEST (Table)
--
CREATE OR REPLACE TRIGGER ASU."TSLFORMREQUEST_BEFORE_INSERT" 
  BEFORE INSERT
  ON ASU.TSLFORMREQUEST   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
Begin
  SELECT SEQ_TSLFORMREQUEST.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


