DROP TRIGGER ASU.TRSD_DBF_ARCHIVE_INSERT
/

--
-- TRSD_DBF_ARCHIVE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TSLUCH_DBF (Sequence)
--   TRSD_DBF_ARCHIVE (Table)
--
CREATE OR REPLACE TRIGGER ASU."TRSD_DBF_ARCHIVE_INSERT" 
 BEFORE
  INSERT
 ON asu.TRSD_DBF_ARCHIVE
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
Begin
  IF :new.fk_id IS NULL THEN
    SELECT asu.SEQ_TSLUCH_DBF.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
  end if;
End;
/
SHOW ERRORS;


