DROP TRIGGER ASU.TCOUNTRY_BEFORE_INSERT
/

--
-- TCOUNTRY_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TCOUNTRY (Sequence)
--   TCOUNTRY (Table)
--
CREATE OR REPLACE TRIGGER ASU."TCOUNTRY_BEFORE_INSERT" 
BEFORE INSERT
ON ASU.TCOUNTRY REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
Begin
  SELECT SEQ_TCOUNTRY.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


