DROP TRIGGER ASU.TPROTIVDIAG_BEFOR_INSER
/

--
-- TPROTIVDIAG_BEFOR_INSER  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TPROTIVDAIG (Sequence)
--   TPROTIVDIAG (Table)
--
CREATE OR REPLACE TRIGGER ASU."TPROTIVDIAG_BEFOR_INSER" 
BEFORE INSERT
ON ASU.TPROTIVDIAG REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
Begin
  select SEQ_TPROTIVDAIG.nextval into :new.fk_id from dual;
End;
/
SHOW ERRORS;


