DROP TRIGGER ASU.TGROUPRIGHT$BI
/

--
-- TGROUPRIGHT$BI  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   TGROUPRIGHT (Table)
--   SEQ_GROUPRIGHT (Sequence)
--
CREATE OR REPLACE TRIGGER ASU."TGROUPRIGHT$BI" 
 BEFORE
 INSERT
 ON ASU.TGROUPRIGHT  REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
begin
    SELECT SEQ_GROUPRIGHT.NextVal INTO :NEW.FK_ID FROM DUAL;
end;
/
SHOW ERRORS;


