DROP TRIGGER ASU.TKURLIST_DEL
/

--
-- TKURLIST_DEL  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   TKURLIST (Table)
--   TKURS (Table)
--
CREATE OR REPLACE TRIGGER ASU."TKURLIST_DEL" 
 BEFORE 
 DELETE
 ON ASU.TKURLIST  REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
BEGIN
   DELETE FROM tKURS
   WHERE       KURLISTid = :OLD.KURLISTid;
END;
/
SHOW ERRORS;


