DROP TRIGGER ASU.TTEMPLISTPIC_AFTER_DELETE
/

--
-- TTEMPLISTPIC_AFTER_DELETE  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   TBLOBS (Table)
--   TTEMPLISTPIC (Table)
--
CREATE OR REPLACE TRIGGER ASU."TTEMPLISTPIC_AFTER_DELETE" 
  AFTER DELETE ON ASU.TTEMPLISTPIC  
  FOR EACH ROW
DECLARE
  -- LOCAL VARIABLES HERE
BEGIN
  DELETE FROM TBLOBS WHERE FK_ID = :OLD.FK_BLOBID;  
END TTEMPLISTPIC_AFTER_DELETE;
/
SHOW ERRORS;


