DROP TRIGGER ASU.TUCHSTOK_BEFORE_INSERT
/

--
-- TUCHSTOK_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TUCHASTOK (Sequence)
--   TUCHASTOK (Table)
--
CREATE OR REPLACE TRIGGER ASU."TUCHSTOK_BEFORE_INSERT" 
  BEFORE INSERT
  ON ASU.TUCHASTOK   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
Begin
  SELECT SEQ_TUCHASTOK.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


