DROP TRIGGER ASU.TMDA_DBF_LOAD_INSERT
/

--
-- TMDA_DBF_LOAD_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TMDA_DBF (Sequence)
--   TMDA_DBF_LOAD (Table)
--
CREATE OR REPLACE TRIGGER ASU."TMDA_DBF_LOAD_INSERT" 
 BEFORE
  INSERT
 ON ASU.TMDA_DBF_LOAD REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
Begin
  IF :new.fk_id IS NULL THEN
    SELECT ASU.SEQ_TMDA_DBF.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
  end if;
End;
/
SHOW ERRORS;


