DROP TRIGGER ASU.TQCKOEFF_RECOVER_BEFORE_INSERT
/

--
-- TQCKOEFF_RECOVER_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TQCKOEFFRECOVER (Sequence)
--   TQCKOEFFRECOVER (Table)
--
CREATE OR REPLACE TRIGGER ASU."TQCKOEFF_RECOVER_BEFORE_INSERT" 
BEFORE INSERT
ON ASU.TQCKOEFFRECOVER REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
Begin
  SELECT SEQ_TQCKOEFFRECOVER.NEXTVAL INTO :NEW.FK_ID FROM DUAl;
End;
/
SHOW ERRORS;


