DROP TRIGGER ASU.TDISP_FILTER_BEFORE_INSERT
/

--
-- TDISP_FILTER_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TDISP_FILTER (Sequence)
--   TDISP_FILTER (Table)
--
CREATE OR REPLACE TRIGGER ASU."TDISP_FILTER_BEFORE_INSERT" 
 BEFORE
  INSERT
 ON tdisp_filter
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
  SELECT SEQ_TDISP_FILTER.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
END;
/
SHOW ERRORS;


