DROP TRIGGER ASU.TDIAGDETAIL_INSERT
/

--
-- TDIAGDETAIL_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TDIAGDETAIL (Sequence)
--   TDIAGDETAIL (Table)
--
CREATE OR REPLACE TRIGGER ASU."TDIAGDETAIL_INSERT" 
  BEFORE INSERT
  ON ASU.TDIAGDETAIL   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
Begin
  select SEQ_TDIAGDETAIL.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


