DROP TRIGGER ASU.TS_ANALIZATOR_BEFORE_INSERT
/

--
-- TS_ANALIZATOR_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TS_ANALIZATOR (Sequence)
--   TS_ANALIZATOR (Table)
--
CREATE OR REPLACE TRIGGER ASU."TS_ANALIZATOR_BEFORE_INSERT" 
 BEFORE 
 INSERT
 ON ASU.TS_ANALIZATOR  REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
begin
    SELECT SEQ_TS_ANALIZATOR.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
end;
/
SHOW ERRORS;


