DROP TRIGGER ASU.TTYPEOBSL_BEFORE_INSERT
/

--
-- TTYPEOBSL_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TTYPEOBSL (Sequence)
--   TTYPEOBSL (Table)
--
CREATE OR REPLACE TRIGGER ASU."TTYPEOBSL_BEFORE_INSERT" 
BEFORE INSERT
ON ASU.TTYPEOBSL REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
Begin
  SELECT SEQ_TTYPEOBSL.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


