DROP TRIGGER ASU.TIBPAC_RAZ_BEFORE_INSERT
/

--
-- TIBPAC_RAZ_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TIBPAC_RAZ (Sequence)
--   TIBPAC_RAZ (Table)
--
CREATE OR REPLACE TRIGGER ASU."TIBPAC_RAZ_BEFORE_INSERT" 
 BEFORE
  INSERT
 ON asu.tibpac_raz
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
Begin
  SELECT SEQ_tibpac_raz.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


