DROP TRIGGER ASU.TSTANDARTDIAG_BEFORE_INSERT
/

--
-- TSTANDARTDIAG_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TSTANDARTDIAG (Sequence)
--   TSTANDARTDIAG (Table)
--
CREATE OR REPLACE TRIGGER ASU."TSTANDARTDIAG_BEFORE_INSERT" 
 BEFORE
  INSERT
 ON asu.tstandartdiag
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
  SELECT SEQ_TSTANDARTDIAG.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
END;
/
SHOW ERRORS;


