DROP TRIGGER ASU.TOPERSCHEMAKAB_BEFORE_INSERT
/

--
-- TOPERSCHEMAKAB_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TOPERSCHEMAKAB (Sequence)
--   TOPERSCHEMAKAB (Table)
--
CREATE OR REPLACE TRIGGER ASU."TOPERSCHEMAKAB_BEFORE_INSERT" 
  BEFORE INSERT
  ON ASU.TOPERSCHEMAKAB   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
Begin
  select seq_TOPERSCHEMAKAB.nextval into :new.fk_id from dual;
End;
/
SHOW ERRORS;


