DROP TRIGGER ASU.TKARTA_A_INS
/

--
-- TKARTA_A_INS  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   TKARTA (Table)
--   TEXP_TPACKART (Table)
--
CREATE OR REPLACE TRIGGER ASU."TKARTA_A_INS"
 AFTER INSERT
 ON ASU.TKARTA  REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
BEGIN
  INSERT INTO ASU.TEXP_TPACKART(FK_PACID)
  VALUES(:NEW.FK_ID);
End;
/
SHOW ERRORS;


