DROP TRIGGER ASU.TNAZAN_SET_RAZDID
/

--
-- TNAZAN_SET_RAZDID  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   TNAZAN (Table)
--   GET_LAB_RAZD (Function)
--
CREATE OR REPLACE TRIGGER ASU."TNAZAN_SET_RAZDID" 
BEFORE INSERT OR UPDATE
ON ASU.TNAZAN REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
Begin
  :NEW.FK_RAZDID:=GET_LAB_RAZD(:NEW.FK_SMID);
End;
/
SHOW ERRORS;


