DROP TRIGGER ASU.TVID_BEFOR_INSERT_UPDATE
/

--
-- TVID_BEFOR_INSERT_UPDATE  (Trigger) 
--
--  Dependencies: 
--   TVID (Table)
--
CREATE OR REPLACE TRIGGER ASU."TVID_BEFOR_INSERT_UPDATE" 
  BEFORE INSERT OR UPDATE ON ASU.TVID   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
Begin
  null;
  /* disabled by TimurLan :NEW.FC_VID:=:NEW.FC_NAME;*/
End;
/
SHOW ERRORS;


