DROP TRIGGER ASU.TNAZMEDZAMENA_BI
/

--
-- TNAZMEDZAMENA_BI  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TNAZMEDZAMENA (Sequence)
--   TNAZMEDZAMENA (Table)
--
CREATE OR REPLACE TRIGGER ASU."TNAZMEDZAMENA_BI" 
BEFORE INSERT
ON ASU.TNAZMEDZAMENA REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  SELECT seq_TNAZMEDZAMENA.NEXTval
    INTO :new.fk_id
    FROM dual;
END;
/
SHOW ERRORS;


