DROP TRIGGER ASU.TISSLRAZDDEPS_BEFORE_INSERT
/

--
-- TISSLRAZDDEPS_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TISSLRAZDDEPS (Sequence)
--   TISSLRAZDDEPS (Table)
--
CREATE OR REPLACE TRIGGER ASU."TISSLRAZDDEPS_BEFORE_INSERT" 
BEFORE  INSERT  ON ASU.TISSLRAZDDEPS REFERENCING
 NEW AS NEW
 OLD AS OLD
FOR EACH ROW
Begin
  SELECT SEQ_TISSLRAZDDEPS.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


