DROP TRIGGER ASU.TDISPUSLOV_INSERT
/

--
-- TDISPUSLOV_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TDISPUSLOV (Sequence)
--   TDISPUSLOV (Table)
--
CREATE OR REPLACE TRIGGER ASU."TDISPUSLOV_INSERT" 
  BEFORE INSERT
  ON ASU.TDISPUSLOV   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
Begin
  select SEQ_TDISPUSLOV.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


