DROP TRIGGER ASU.TPATOLOGY_LECH_INSERT
/

--
-- TPATOLOGY_LECH_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TPATOLOGY_LECH (Sequence)
--   TPATOLOGY_LECH (Table)
--
CREATE OR REPLACE TRIGGER ASU."TPATOLOGY_LECH_INSERT" 
BEFORE INSERT
ON ASU.TPATOLOGY_LECH REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
Begin
  select SEQ_TPATOLOGY_LECH.nextval into :NEW.FK_ID from dual;
End;
/
SHOW ERRORS;


