DROP TRIGGER ASU.TVIDPOLIS_BEFORE_INSERT
/

--
-- TVIDPOLIS_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TVIDPOLIS (Sequence)
--   TVIDPOLIS (Table)
--
CREATE OR REPLACE TRIGGER ASU."TVIDPOLIS_BEFORE_INSERT" 
BEFORE INSERT
ON ASU.TVIDPOLIS REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
Begin
  SELECT SEQ_TVIDPOLIS.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


