DROP TRIGGER ASU.TREPORTSLOG_BEFORE_INSERT
/

--
-- TREPORTSLOG_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TREPORTSLOG (Sequence)
--   TREPORTSLOG (Table)
--
CREATE OR REPLACE TRIGGER ASU."TREPORTSLOG_BEFORE_INSERT" 
BEFORE INSERT
ON ASU.TREPORTSLOG REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
Begin
  select ASU.SEQ_TREPORTSLOG.nextval into :new.FK_ID from dual;
End;
/
SHOW ERRORS;


