DROP TRIGGER ASU.TPOVTOR_BEFORE_INSERT
/

--
-- TPOVTOR_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TPOVTOR (Sequence)
--   TPOVTOR (Table)
--
CREATE OR REPLACE TRIGGER ASU."TPOVTOR_BEFORE_INSERT" 
  BEFORE INSERT
  ON asu.TPOVTOR
  REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
Begin
  SELECT SEQ_TPOVTOR.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


