DROP TRIGGER ASU.TQCSHUHARTCALCFIX_BEFORE_IN
/

--
-- TQCSHUHARTCALCFIX_BEFORE_IN  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TQCSHUHARTCALCFIX (Sequence)
--   TQCSHUHARTCALCFIX (Table)
--
CREATE OR REPLACE TRIGGER ASU."TQCSHUHARTCALCFIX_BEFORE_IN" 
BEFORE INSERT
ON ASU.TQCSHUHARTCALCFIX REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
Begin
  SELECT SEQ_TQCSHUHARTCALCFIX.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


