DROP TRIGGER ASU.TPARTOGRAMMACONSTS_BEFORE_INS
/

--
-- TPARTOGRAMMACONSTS_BEFORE_INS  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TPARTOGRAMMACONSTS (Sequence)
--   TPARTOGRAMMACONSTS (Table)
--
CREATE OR REPLACE TRIGGER ASU."TPARTOGRAMMACONSTS_BEFORE_INS" 
  BEFORE INSERT
  ON ASU.TPARTOGRAMMACONSTS   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
Begin
  SELECT ASU.SEQ_TPARTOGRAMMACONSTS.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


