DROP TRIGGER ASU.TUSD_DBF_ARCHIVE_INSERT
/

--
-- TUSD_DBF_ARCHIVE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TUSL_DBF (Sequence)
--   TUSD_DBF_ARCHIVE (Table)
--
CREATE OR REPLACE TRIGGER ASU."TUSD_DBF_ARCHIVE_INSERT" 
 BEFORE
  INSERT
 ON asu.TUSD_DBF_ARCHIVE
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
Begin
  IF :new.fk_id IS NULL THEN
    SELECT asu.SEQ_TUSL_DBF.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
  END IF;
End;
/
SHOW ERRORS;


