DROP TRIGGER ASU.TSECTIONS_BUTLINE_BEFORE_INSER
/

--
-- TSECTIONS_BUTLINE_BEFORE_INSER  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TSECTION_BUTLINE (Sequence)
--   TSECTION_BUTLINE (Table)
--
CREATE OR REPLACE TRIGGER ASU."TSECTIONS_BUTLINE_BEFORE_INSER" 
 BEFORE 
 INSERT
 ON ASU.TSECTION_BUTLINE  REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
begin
select seq_tsection_butline.NEXTVAL into :new.fk_id from dual;
end;
/
SHOW ERRORS;


