DROP TRIGGER ASU.TLOGCAPT_RIGHTS_BEFORE_INSERT
/

--
-- TLOGCAPT_RIGHTS_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TLOGCAPTION_RIGHTS (Sequence)
--   TLOGCAPTION_RIGHTS (Table)
--
CREATE OR REPLACE TRIGGER ASU."TLOGCAPT_RIGHTS_BEFORE_INSERT" 
 BEFORE
 INSERT
 ON ASU.TLOGCAPTION_RIGHTS  REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
BEGIN
    SELECT SEQ_TLOGCAPTION_RIGHTS.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
END;
/
SHOW ERRORS;


