DROP TRIGGER ASU.TROOM_BEFORE_INSERT
/

--
-- TROOM_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TROOM (Sequence)
--   TROOM (Table)
--
CREATE OR REPLACE TRIGGER ASU."TROOM_BEFORE_INSERT" 
BEFORE INSERT
ON ASU.TROOM REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
Begin
  SELECT SEQ_TROOM.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


