DROP TRIGGER ASU.TSTOM_BEFORE_INSERT
/

--
-- TSTOM_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TSTOM (Sequence)
--   TSTOM (Table)
--
CREATE OR REPLACE TRIGGER ASU."TSTOM_BEFORE_INSERT" 
BEFORE INSERT
ON ASU.TSTOM REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
Begin
  SELECT SEQ_TSTOM.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


