DROP TRIGGER ASU.TCHEMOTHERAPY_BI
/

--
-- TCHEMOTHERAPY_BI  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TCHEMOTHERAPY (Sequence)
--   TCHEMOTHERAPY (Table)
--
CREATE OR REPLACE TRIGGER ASU.TCHEMOTHERAPY_BI
 BEFORE
 INSERT
 ON ASU.TCHEMOTHERAPY  REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
BEGIN
   select asu.SEQ_TCHEMOTHERAPY.nextval into :new.fk_id from dual;
END;
/
SHOW ERRORS;


