DROP TRIGGER ASU.TADR_HISTORY_BI
/

--
-- TADR_HISTORY_BI  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   TADR_HISTORY (Table)
--   SEQ_TADR_HISTORY (Sequence)
--
CREATE OR REPLACE TRIGGER ASU."TADR_HISTORY_BI" 
BEFORE INSERT
ON ASU.TADR_HISTORY REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
   SELECT SEQ_TADR_HISTORY.NEXTVAL INTO :New.FK_ID FROM DUAL;
END ;
/
SHOW ERRORS;


