DROP TRIGGER ASU.TSMID_BEFORE_INSERT
/

--
-- TSMID_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   TSMIDDIAG (Table)
--
CREATE OR REPLACE TRIGGER ASU."TSMID_BEFORE_INSERT" 
 BEFORE 
 INSERT
 ON ASU.TSMIDDIAG  REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
Begin
  null;
  /* disabled by TimurLan SELECT SEQ_TSMID.NEXTVAL INTO :NEW.SMID FROM DUAL;*/
End;
/
SHOW ERRORS;


