DROP TRIGGER ASU.TLIN_MEDIC_BEFORE_INSERT
/

--
-- TLIN_MEDIC_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TLIN_MEDIC (Sequence)
--   TLIN_MEDIC (Table)
--
CREATE OR REPLACE TRIGGER ASU."TLIN_MEDIC_BEFORE_INSERT" 
 BEFORE
 INSERT
 ON ASU.TLIN_MEDIC  REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
BEGIN
    SELECT SEQ_TLIN_MEDIC.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
END;
/
SHOW ERRORS;


