DROP TRIGGER ASU.TPODPIS_RICHV_BEFORE_INSERT
/

--
-- TPODPIS_RICHV_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TPODPIS_RICHVIEWDATA (Sequence)
--   TPODPIS_RICHVIEWDATA (Table)
--
CREATE OR REPLACE TRIGGER ASU."TPODPIS_RICHV_BEFORE_INSERT" 
 BEFORE INSERT ON ASU.TPODPIS_RICHVIEWDATA  REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
BEGIN
 SELECT SEQ_TPODPIS_RICHVIEWDATA.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
END;
/
SHOW ERRORS;


