DROP TRIGGER ASU.TBNK_BEFORE_INSERT
/

--
-- TBNK_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TBNK (Sequence)
--   TBNK (Table)
--
CREATE OR REPLACE TRIGGER ASU."TBNK_BEFORE_INSERT" 
BEFORE INSERT
ON ASU.TBNK REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
Begin
  SELECT SEQ_TBNK.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


