DROP TRIGGER ASU.TURCELLS_BEFORE_INSERT
/

--
-- TURCELLS_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TURCELLS (Sequence)
--   TURCELLS (Table)
--
CREATE OR REPLACE TRIGGER ASU."TURCELLS_BEFORE_INSERT" 
BEFORE  INSERT  ON ASU.TURCELLS REFERENCING
 NEW AS NEW
 OLD AS OLD
FOR EACH ROW
Begin
  SELECT SEQ_TURCELLS.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


