DROP TRIGGER ASU.TTIPROOM_BEFORE_INSERT
/

--
-- TTIPROOM_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TTIPROOM (Sequence)
--   TTIPROOM (Table)
--
CREATE OR REPLACE TRIGGER ASU."TTIPROOM_BEFORE_INSERT" 
BEFORE INSERT
ON ASU.TTIPROOM REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
Begin
  SELECT SEQ_TTIPROOM.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


