DROP TRIGGER ASU.TTYPETIMEDIAG_INSERT
/

--
-- TTYPETIMEDIAG_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TTYPETIMEDIAG (Sequence)
--   TTYPETIMEDIAG (Table)
--
CREATE OR REPLACE TRIGGER ASU."TTYPETIMEDIAG_INSERT" 
  BEFORE INSERT
  ON ASU.TTYPETIMEDIAG   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
Begin
  select SEQ_TTYPETIMEDIAG.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


