DROP TRIGGER ASU.TPLAN_DELETE_ALL
/

--
-- TPLAN_DELETE_ALL  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   TPLAN (Table)
--   TPLANMAIN (Table)
--
CREATE OR REPLACE TRIGGER ASU."TPLAN_DELETE_ALL" 
AFTER DELETE
ON ASU.TPLAN REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
Begin
  Delete from TPLANMAIN where FK_PLANID = :OLD.FK_ID;
end;
/
SHOW ERRORS;


