DROP TRIGGER ASU.TEXSLUCH_INSERT
/

--
-- TEXSLUCH_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TEXSLUCH (Sequence)
--   TEXSLUCH (Table)
--
CREATE OR REPLACE TRIGGER ASU."TEXSLUCH_INSERT" 
 BEFORE
  INSERT
 ON asu.TEXSLUCH
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
Begin
  IF :new.fk_id IS NULL THEN
    SELECT asu.SEQ_TEXSLUCH.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
  end if;
End;
/
SHOW ERRORS;


