DROP TRIGGER ASU.TAMBVRACH_INSERT
/

--
-- TAMBVRACH_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   TAMBVRACH (Table)
--   SEQ_TAMBVRACH (Sequence)
--
CREATE OR REPLACE TRIGGER ASU."TAMBVRACH_INSERT" 
  BEFORE INSERT
  ON ASU.TAMBVRACH   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
Begin
  SELECT SEQ_TAMBVRACH.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


