DROP TRIGGER ASU.TCLEANERS_BEFORE_INSERT
/

--
-- TCLEANERS_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TCLEANERS (Sequence)
--   TCLEANERS (Table)
--
CREATE OR REPLACE TRIGGER ASU."TCLEANERS_BEFORE_INSERT" 
BEFORE INSERT
ON ASU.TCLEANERS REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
Begin
  SELECT SEQ_TCLEANERS.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


