DROP TRIGGER ASU.TSMIDCLOB_BEFORE_INSERT
/

--
-- TSMIDCLOB_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TSMIDCLOB (Sequence)
--   TSMIDCLOB (Table)
--
CREATE OR REPLACE TRIGGER ASU."TSMIDCLOB_BEFORE_INSERT" 
 BEFORE
  INSERT
 ON asu.tsmidclob
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
  SELECT SEQ_TSMIDCLOB.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
END;
/
SHOW ERRORS;


