DROP TRIGGER ASU.TBODY_PARAM_BEFORE_INS
/

--
-- TBODY_PARAM_BEFORE_INS  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TBODY_PARAM (Sequence)
--   TBODY_PARAM (Table)
--
CREATE OR REPLACE TRIGGER ASU."TBODY_PARAM_BEFORE_INS" 
 BEFORE 
 INSERT
 ON ASU.TBODY_PARAM  REFERENCING OLD AS old NEW AS new
 FOR EACH ROW
Begin
  SELECT SEQ_TBODY_PARAM.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


