DROP TRIGGER ASU.TRSF_BEFORE_INSERT
/

--
-- TRSF_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TRSF (Sequence)
--   TRSF (Table)
--
CREATE OR REPLACE TRIGGER ASU.TRSF_BEFORE_INSERT
 BEFORE
 INSERT
 ON ASU.TRSF  REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
Begin
  SELECT SEQ_TRSF.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


