DROP TRIGGER ASU.TQCSHUHARTSPR_BEFORE_INSERT
/

--
-- TQCSHUHARTSPR_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TQCSHUHARTSPR (Sequence)
--   TQCSHUHARTSPR (Table)
--
CREATE OR REPLACE TRIGGER ASU."TQCSHUHARTSPR_BEFORE_INSERT" 
BEFORE INSERT
ON ASU.TQCSHUHARTSPR REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
Begin
  SELECT SEQ_TQCSHUHARTSPR.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


