DROP TRIGGER ASU.TADRESS_A_INS
/

--
-- TADRESS_A_INS  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   TADRESS (Table)
--
CREATE OR REPLACE TRIGGER ASU."TADRESS_A_INS"
 AFTER INSERT
 ON ASU.TADRESS  REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
BEGIN
  --INSERT INTO ASU.TEXP_TADRESS(FK_ADRID)
  --VALUES(:NEW.FK_ID);
  null;
End;
/
SHOW ERRORS;


