DROP TRIGGER ASU.TURFUNCS_BEFORE_DELETE
/

--
-- TURFUNCS_BEFORE_DELETE  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   TURALGO (Table)
--   TURFUNCS (Table)
--   TURFUNCSPARAMS (Table)
--
CREATE OR REPLACE TRIGGER ASU."TURFUNCS_BEFORE_DELETE" 
AFTER DELETE
ON ASU.TURFUNCS REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
Begin
  DELETE FROM TURFUNCSPARAMS WHERE FK_FUNCID=:OLD.FK_ID;
  DELETE FROM TURALGO WHERE FK_FUNCID=:OLD.FK_ID;
End;
/
SHOW ERRORS;


