DROP TRIGGER ASU.TSROKY_AFTER_DELETE
/

--
-- TSROKY_AFTER_DELETE  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   TSROKY (Table)
--   TPERESEL (Table)
--
CREATE OR REPLACE TRIGGER ASU."TSROKY_AFTER_DELETE" 
  AFTER DELETE ON ASU.TSROKY   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
Begin
  DELETE FROM TPERESEL WHERE FK_SROKID = :OLD.FK_ID;
End;
/
SHOW ERRORS;


