DROP TRIGGER ASU.TEXSLUCH_ERR_INSERT
/

--
-- TEXSLUCH_ERR_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TEXSLUCH_ERR (Sequence)
--   TEXSLUCH_ERR (Table)
--
CREATE OR REPLACE TRIGGER ASU."TEXSLUCH_ERR_INSERT" 
 BEFORE
  INSERT
 ON asu.TEXSLUCH_ERR
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
Begin
  IF :new.fk_id IS NULL THEN
    SELECT asu.SEQ_TEXSLUCH_ERR.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
  end if;
End;
/
SHOW ERRORS;


