DROP TRIGGER ASU.MKB308_BEFORE_INSERT
/

--
-- MKB308_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_MKB308 (Sequence)
--   MKB308 (Table)
--
CREATE OR REPLACE TRIGGER ASU.MKB308_BEFORE_INSERT
  BEFORE INSERT
  ON ASU.MKB308   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
BEGIN
  SELECT ASU.SEQ_MKB308.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
END;
/
SHOW ERRORS;


