DROP TRIGGER ASU.TIS_DISP_BI
/

--
-- TIS_DISP_BI  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TIS_DISP (Sequence)
--   TIS_DISP (Table)
--
CREATE OR REPLACE TRIGGER ASU.TIS_DISP_BI
  BEFORE INSERT
  ON ASU.TIS_DISP   REFERENCING OLD AS OLD NEW AS NEW
  FOR EACH ROW
BEGIN
  IF :NEW.fk_id IS NULL
  THEN
    SELECT asu.seq_TIS_DISP.NEXTVAL
      INTO :NEW.fk_id
      FROM DUAL;
  END IF;
END;
/
SHOW ERRORS;


