DROP TRIGGER ASU.TRAZDEL_INSERT
/

--
-- TRAZDEL_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TRAZDEL (Sequence)
--   TRAZDEL (Table)
--
CREATE OR REPLACE TRIGGER ASU."TRAZDEL_INSERT" 
  BEFORE INSERT
  ON ASU.TRAZDEL   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
BEGIN
  SELECT SEQ_TRAZDEL.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
END;
/
SHOW ERRORS;


