DROP TRIGGER ASU.TEXP_VNAZ_BI
/

--
-- TEXP_VNAZ_BI  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TEXP_VNAZ (Sequence)
--   TEXP_VNAZ (Table)
--
CREATE OR REPLACE TRIGGER ASU.TEXP_VNAZ_BI
 BEFORE INSERT
 ON ASU.TEXP_VNAZ REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
 IF :NEW.FK_ID IS NULL THEN
    SELECT ASU.SEQ_TEXP_VNAZ.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
 END IF;
END TEXP_VNAZ_BI;
/
SHOW ERRORS;


