DROP TRIGGER ASU.TINTOWN_BEFORE_INSERT
/

--
-- TINTOWN_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TINTOWN (Sequence)
--   TINTOWN (Table)
--
CREATE OR REPLACE TRIGGER ASU."TINTOWN_BEFORE_INSERT" 
BEFORE INSERT
ON ASU.TINTOWN REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
Begin
  SELECT SEQ_TINTOWN.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


