DROP TRIGGER ASU.TSLFORM_BEFORE_INSERT
/

--
-- TSLFORM_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TSLFORM (Sequence)
--   TSLFORM (Table)
--
CREATE OR REPLACE TRIGGER ASU."TSLFORM_BEFORE_INSERT" 
  BEFORE INSERT
  ON ASU.TSLFORM   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
Begin
  SELECT SEQ_TSLFORM.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


