DROP TRIGGER ASU.TCGEMOSTAZ_AFTER_INSERT
/

--
-- TCGEMOSTAZ_AFTER_INSERT  (Trigger) 
--
--  Dependencies: 
--   TCGEMOSTAZ (Table)
--
CREATE OR REPLACE TRIGGER ASU."TCGEMOSTAZ_AFTER_INSERT" 
AFTER  INSERT  ON ASU.TCGEMOSTAZ 
Begin
  DELETE FROM TCGEMOSTAZ WHERE FK_SMID=-1;
End;
/
SHOW ERRORS;


