DROP TRIGGER ASU.TCOMPANY_BEFORE_INSERT
/

--
-- TCOMPANY_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TCOMPANY (Sequence)
--   TCOMPANY (Table)
--
CREATE OR REPLACE TRIGGER ASU."TCOMPANY_BEFORE_INSERT" 
BEFORE INSERT
ON ASU.TCOMPANY REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
Begin
  SELECT SEQ_TCOMPANY.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


