DROP TRIGGER ASU.TDOC_BEFORE_INSERT
/

--
-- TDOC_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TKARTA (Sequence)
--   TDOC (Table)
--
CREATE OR REPLACE TRIGGER ASU."TDOC_BEFORE_INSERT" 
BEFORE INSERT 
ON tdoc
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
Begin
  SELECT SEQ_TKARTA.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


