DROP TRIGGER ASU.TNAZWIZZARD_EXPAN_BEFORE_INS
/

--
-- TNAZWIZZARD_EXPAN_BEFORE_INS  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TNAZWIZZARD_EXPAN (Sequence)
--   TNAZWIZZARD_EXPAN (Table)
--
CREATE OR REPLACE TRIGGER ASU."TNAZWIZZARD_EXPAN_BEFORE_INS" 
 BEFORE
  INSERT
 ON tnazwizzard_expan
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
begin
  SELECT SEQ_TNAZWIZZARD_EXPAN.nextval INTO :new.fk_id FROM dual;
end;
/
SHOW ERRORS;


