DROP TRIGGER ASU.TFORM1MED_INSERT
/

--
-- TFORM1MED_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TFORM1MED (Sequence)
--   TFORM1MED (Table)
--
CREATE OR REPLACE TRIGGER ASU."TFORM1MED_INSERT" 
 BEFORE
  INSERT
 ON ASU.TFORM1MED REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
Begin
  IF :NEW.FK_ID IS NULL THEN
    SELECT asu.SEQ_TFORM1MED.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
  END IF;
end;
/
SHOW ERRORS;


