DROP TRIGGER ASU.TSCREENING_JOURNAL_BEF_UPDT
/

--
-- TSCREENING_JOURNAL_BEF_UPDT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   TSCREENING_JOURNAL (Table)
--
CREATE OR REPLACE TRIGGER ASU."TSCREENING_JOURNAL_BEF_UPDT"
BEFORE UPDATE
ON ASU.TSCREENING_JOURNAL REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
   SELECT SYSDATE
   INTO :NEW.FD_UPDTDATE
   FROM DUAL;
END;
/
SHOW ERRORS;


