DROP TRIGGER ASU.TSLUCH_DBF_ARCHIVE_INSERT
/

--
-- TSLUCH_DBF_ARCHIVE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TSLUCH_DBF_ARCHIVE (Sequence)
--   TSLUCH_DBF_ARCHIVE (Table)
--
CREATE OR REPLACE TRIGGER ASU."TSLUCH_DBF_ARCHIVE_INSERT" 
 BEFORE
  INSERT
 ON asu.TSLUCH_DBF_ARCHIVE
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
Begin
  SELECT asu.SEQ_TSLUCH_DBF_ARCHIVE.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


