DROP TRIGGER ASU.TPARTOGRAMMANAMES_BEFORE_INS
/

--
-- TPARTOGRAMMANAMES_BEFORE_INS  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TPARTOGRAMMANAMES (Sequence)
--   TPARTOGRAMMANAMES (Table)
--
CREATE OR REPLACE TRIGGER ASU."TPARTOGRAMMANAMES_BEFORE_INS" 
  BEFORE INSERT
  ON ASU.TPARTOGRAMMANAMES   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
Begin
  SELECT SEQ_TPARTOGRAMMANAMES.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


