DROP TRIGGER ASU.TNAZMARK_X_BEFORE_INSERT
/

--
-- TNAZMARK_X_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TNAZMARK_X (Sequence)
--   TNAZMARK_X (Table)
--
CREATE OR REPLACE TRIGGER ASU."TNAZMARK_X_BEFORE_INSERT" 
 BEFORE
  INSERT
 ON asu.tnazmark_x
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
  SELECT SEQ_TNAZMARK_X.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
END;
/
SHOW ERRORS;


