DROP TRIGGER ASU.TDEZHURSPEC_INSERT
/

--
-- TDEZHURSPEC_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TDEZHURSPEC (Sequence)
--   TDEZHURSPEC (Table)
--
CREATE OR REPLACE TRIGGER ASU."TDEZHURSPEC_INSERT" 
  BEFORE INSERT
  ON ASU.TDEZHURSPEC   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
Begin
  select SEQ_TDEZHURSPEC.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


