DROP TRIGGER ASU.TPERESEL_INTERIM_BEFORE_INSERT
/

--
-- TPERESEL_INTERIM_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TPERESEL (Sequence)
--   TPERESEL_INTERIM (Table)
--
CREATE OR REPLACE TRIGGER ASU."TPERESEL_INTERIM_BEFORE_INSERT" 
BEFORE INSERT
ON ASU.TPERESEL_INTERIM REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
Begin
  SELECT SEQ_TPERESEL.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


