DROP TRIGGER ASU.TDIAGNAZ_BEFORE_INSERT
/

--
-- TDIAGNAZ_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TDIAGNAZ (Sequence)
--   TDIAGNAZ (Table)
--
CREATE OR REPLACE TRIGGER ASU."TDIAGNAZ_BEFORE_INSERT" 
  BEFORE INSERT
  ON ASU.TDIAGNAZ   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
Begin
  SELECT SEQ_TDIAGNAZ.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


