DROP TRIGGER ASU.TDISEASE_BEFORE_INSERT
/

--
-- TDISEASE_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TDISEASE (Sequence)
--   TDISEASE (Table)
--
CREATE OR REPLACE TRIGGER ASU."TDISEASE_BEFORE_INSERT" 
BEFORE INSERT
ON ASU.TDISEASE REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
Begin
  SELECT SEQ_TDISEASE.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


