DROP TRIGGER ASU.TKARTA_BEFORE_UPDATE
/

--
-- TKARTA_BEFORE_UPDATE  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   TKARTA (Table)
--
CREATE OR REPLACE TRIGGER ASU."TKARTA_BEFORE_UPDATE" 
 BEFORE
  UPDATE
 ON asu.tkarta
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
Begin
  :NEW.FK_SESSIONID:='-1';
End;
/
SHOW ERRORS;


