DROP TRIGGER ASU.TNAZSOS_INSERT
/

--
-- TNAZSOS_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TNAZSOS (Sequence)
--   TNAZSOS (Table)
--
CREATE OR REPLACE TRIGGER ASU."TNAZSOS_INSERT" 
  BEFORE INSERT
  ON ASU.TNAZSOS   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
DISABLE
Begin
  select SEQ_TNAZSOS.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


