DROP TRIGGER ASU.TSMINI_BEFORE_INSERT
/

--
-- TSMINI_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TSMINI (Sequence)
--   TSMINI (Table)
--
CREATE OR REPLACE TRIGGER ASU."TSMINI_BEFORE_INSERT" 
BEFORE  INSERT  ON ASU.TSMINI FOR EACH ROW
Begin
  SELECT SEQ_TSMINI.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


