DROP TRIGGER ASU.TLABREG_ACCUM_BEFORE_INSERT
/

--
-- TLABREG_ACCUM_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   TLABREG_ACCUM (Table)
--   SEQ_LAB_ACCUMULATE (Sequence)
--
CREATE OR REPLACE TRIGGER ASU."TLABREG_ACCUM_BEFORE_INSERT" 
 BEFORE
 INSERT
 ON ASU.TLABREG_ACCUM  REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
BEGIN
    SELECT SEQ_LAB_ACCUMULATE.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
END;
/
SHOW ERRORS;


