DROP TRIGGER ASU.TMEDKART_BIO$GODEN
/

--
-- TMEDKART_BIO$GODEN  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   TMEDKART (Table)
--
CREATE OR REPLACE TRIGGER ASU."TMEDKART_BIO$GODEN" 
BEFORE INSERT OR UPDATE OF FD_GODEN
ON ASU.TMEDKART REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  :new.fd_goden := TRUNC (:new.fd_goden);
END;
/
SHOW ERRORS;


