DROP TRIGGER ASU.TQCRECOVERCALCFIX_BEFORE_IN
/

--
-- TQCRECOVERCALCFIX_BEFORE_IN  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TQCRECOVERCALCFIX (Sequence)
--   TQCRECOVERCALCFIX (Table)
--
CREATE OR REPLACE TRIGGER ASU."TQCRECOVERCALCFIX_BEFORE_IN" 
BEFORE INSERT
ON ASU.TQCRECOVERCALCFIX REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
Begin
  SELECT SEQ_TQCRECOVERCALCFIX.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


