DROP TRIGGER ASU.TCOMP_STAND_BEFORE_INSERT
/

--
-- TCOMP_STAND_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TCOMPANY_STANDART (Sequence)
--   TCOMPANY_STANDART (Table)
--
CREATE OR REPLACE TRIGGER ASU."TCOMP_STAND_BEFORE_INSERT" 
  BEFORE INSERT
  ON ASU.TCOMPANY_STANDART   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
Begin
  SELECT SEQ_TCOMPANY_STANDART.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


