DROP TRIGGER ASU.TGROUP_BEFORE_INSERT
/

--
-- TGROUP_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TGROUP (Sequence)
--   TGROUP (Table)
--
CREATE OR REPLACE TRIGGER ASU."TGROUP_BEFORE_INSERT" 
BEFORE INSERT
ON ASU.TGROUP REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
Begin
  SELECT SEQ_TGROUP.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


