DROP TRIGGER ASU.TCOC_POL_BEFORE_INSERT
/

--
-- TCOC_POL_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TCOC_POL (Sequence)
--   TCOC_POL (Table)
--
CREATE OR REPLACE TRIGGER ASU."TCOC_POL_BEFORE_INSERT" 
BEFORE INSERT
ON ASU.TCOC_POL REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
Begin
  SELECT SEQ_TCOC_POL.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


