DROP TRIGGER ASU.TSLPERIOD_BEFORE_INSERT
/

--
-- TSLPERIOD_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TSLPERIOD (Sequence)
--   TSLPERIOD (Table)
--
CREATE OR REPLACE TRIGGER ASU."TSLPERIOD_BEFORE_INSERT" 
  BEFORE INSERT
  ON ASU.TSLPERIOD   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
Begin
  SELECT SEQ_TSLPERIOD.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


