DROP TRIGGER ASU.TQCRECOVERSPR_AFTER_DELETE
/

--
-- TQCRECOVERSPR_AFTER_DELETE  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   TQCRECOVERDATA (Table)
--   TQCRECOVERSPR (Table)
--
CREATE OR REPLACE TRIGGER ASU."TQCRECOVERSPR_AFTER_DELETE" 
AFTER  DELETE  ON ASU.TQCRECOVERSPR REFERENCING
 NEW AS NEW
 OLD AS OLD
FOR EACH ROW
Begin
  DELETE FROM TQCRECOVERDATA WHERE FK_SMID=:OLD.FK_SMID;
End;
/
SHOW ERRORS;


