DROP TRIGGER ASU.TQCDAILYMEEN_AFTER_INSERT
/

--
-- TQCDAILYMEEN_AFTER_INSERT  (Trigger) 
--
--  Dependencies: 
--   TQCDAILYMEEN (Table)
--
CREATE OR REPLACE TRIGGER ASU."TQCDAILYMEEN_AFTER_INSERT" 
AFTER INSERT
ON ASU.TQCDAILYMEEN 
Begin
  DELETE FROM TQCDAILYMEEN WHERE FK_SMID=-1;
End;
/
SHOW ERRORS;


