DROP TRIGGER ASU.TRECIPE_DLO_IMP_REQ_DEL
/

--
-- TRECIPE_DLO_IMP_REQ_DEL  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   TRECIPE_DLO_IMP_REQ (Table)
--   TRECIPE_DLO_IMP_REQ_MEDIC (Table)
--
CREATE OR REPLACE TRIGGER ASU."TRECIPE_DLO_IMP_REQ_DEL"
 BEFORE
  DELETE
 ON ASU.TRECIPE_DLO_IMP_REQ REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
begin
  delete from asu.TRECIPE_DLO_IMP_REQ_MEDIC t
   where t.FK_UNIQCODE = :OLD.UNIQCODE;
end;
/
SHOW ERRORS;


