DROP TRIGGER ASU.TINSURCOMPANY_BEFORE_INSERT
/

--
-- TINSURCOMPANY_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TINSURCOMPANY (Sequence)
--   TINSURCOMPANY (Table)
--
CREATE OR REPLACE TRIGGER ASU."TINSURCOMPANY_BEFORE_INSERT" 
  BEFORE INSERT
  ON ASU.TINSURCOMPANY   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
Begin
  SELECT SEQ_TINSURCOMPANY.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


