DROP TRIGGER ASU.TPACCONVOY_BEFORE_INSERT
/

--
-- TPACCONVOY_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TPACCONVOY (Sequence)
--   TPACCONVOY (Table)
--
CREATE OR REPLACE TRIGGER ASU."TPACCONVOY_BEFORE_INSERT" 
BEFORE INSERT
ON ASU.TPACCONVOY REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
Begin
  SELECT SEQ_TPACCONVOY.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


