DROP TRIGGER ASU.WEB_BUFFER_TRANSFER2$BI
/

--
-- WEB_BUFFER_TRANSFER2$BI  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_WEB_BUFFER_TRANSFFER (Sequence)
--   WEB_BUFFER_TRANSFER2 (Table)
--
CREATE OR REPLACE TRIGGER ASU."WEB_BUFFER_TRANSFER2$BI"
  BEFORE INSERT ON ASU.WEB_BUFFER_TRANSFER2   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
BEGIN
  SELECT ASU.SEQ_WEB_BUFFER_TRANSFFER.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
SHOW ERRORS;


