DROP TRIGGER ASU.TRICHVIEW_TEMPL_BEFORE_INSERT
/

--
-- TRICHVIEW_TEMPL_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TRICHVIEWDATA (Sequence)
--   TRICHVIEW_TEMPL (Table)
--
CREATE OR REPLACE TRIGGER ASU."TRICHVIEW_TEMPL_BEFORE_INSERT" 
 BEFORE 
 INSERT
 ON ASU.TRICHVIEW_TEMPL  FOR EACH ROW
BEGIN
    if :new.FK_ID is null then
      select SEQ_TRICHVIEWDATA.NEXTVAL INTO :new.FK_ID from dual;
    end if;
END;
/
SHOW ERRORS;


