DROP TRIGGER ASU.VMP_11_BEFORE_INSERT
/

--
-- VMP_11_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_VMP_11 (Sequence)
--   VMP_11 (Table)
--
CREATE OR REPLACE TRIGGER ASU.VMP_11_BEFORE_INSERT
  BEFORE INSERT
  ON ASU.VMP_11   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
BEGIN
  SELECT ASU.SEQ_VMP_11.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
END;
/
SHOW ERRORS;


