DROP TRIGGER ASU.TUCHVRACH_BEFORE_INSERT
/

--
-- TUCHVRACH_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TUCHVRACH (Sequence)
--   TUCHVRACH (Table)
--
CREATE OR REPLACE TRIGGER ASU."TUCHVRACH_BEFORE_INSERT" 
  BEFORE INSERT
  ON ASU.TUCHVRACH   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
Begin
  SELECT SEQ_TUCHVRACH.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


