DROP TRIGGER ASU.TDISPCARD_BEFORE_INSERT
/

--
-- TDISPCARD_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TDISPCARD (Sequence)
--   TDISPCARD (Table)
--
CREATE OR REPLACE TRIGGER ASU."TDISPCARD_BEFORE_INSERT" 
 BEFORE
  INSERT
 ON tdispcard
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
Begin
  SELECT SEQ_TDispCard.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


