DROP TRIGGER ASU.TQCDAILYMEENSPR_BEFORE_INSERT
/

--
-- TQCDAILYMEENSPR_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TQCDAILYMEENSPR (Sequence)
--   TQCDAILYMEENSPR (Table)
--
CREATE OR REPLACE TRIGGER ASU."TQCDAILYMEENSPR_BEFORE_INSERT" 
BEFORE INSERT
ON ASU.TQCDAILYMEENSPR REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
Begin
  SELECT SEQ_TQCDAILYMEENSPR.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


