DROP TRIGGER ASU.TPICS_BEFORE_INSERT
/

--
-- TPICS_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TPICS (Sequence)
--   TPICS (Table)
--
CREATE OR REPLACE TRIGGER ASU."TPICS_BEFORE_INSERT" 
  BEFORE INSERT ON ASU.TPICS   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
Begin
  SELECT SEQ_TPICS.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


