DROP TRIGGER ASU.TURFUNCS_BEFORE_INSERT
/

--
-- TURFUNCS_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TURFUNCS (Sequence)
--   TURFUNCS (Table)
--
CREATE OR REPLACE TRIGGER ASU."TURFUNCS_BEFORE_INSERT" 
BEFORE INSERT
ON ASU.TURFUNCS REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
Begin
  SELECT SEQ_TURFUNCS.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


