DROP TRIGGER ASU.TSLRIGHTS_BEFORE_INSERT
/

--
-- TSLRIGHTS_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TSLRIGHTS (Sequence)
--   TSLRIGHTS (Table)
--
CREATE OR REPLACE TRIGGER ASU."TSLRIGHTS_BEFORE_INSERT" 
  BEFORE INSERT
  ON ASU.TSLRIGHTS   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
Begin
  SELECT SEQ_TSLRIGHTS.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


