DROP TRIGGER ASU.TRECIPE_DLO_FED_PAC_DEL
/

--
-- TRECIPE_DLO_FED_PAC_DEL  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   TRECIPE_DLO_FED_PAC (Table)
--   TRECIPE_DLO_FED_PAC_CATEG (Table)
--
CREATE OR REPLACE TRIGGER ASU."TRECIPE_DLO_FED_PAC_DEL"
 BEFORE
  DELETE
 ON ASU.TRECIPE_DLO_FED_PAC REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
begin
  delete from asu.TRECIPE_DLO_FED_PAC_CATEG t
   where t.FK_FEDPACID = :OLD.FK_ID;
end;
/
SHOW ERRORS;


