DROP TRIGGER ASU.TSKUD_PEOPLES_BEF_INS
/

--
-- TSKUD_PEOPLES_BEF_INS  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TSKUD_PEOPLES (Sequence)
--   TSKUD_PEOPLES (Table)
--
CREATE OR REPLACE TRIGGER ASU."TSKUD_PEOPLES_BEF_INS"
BEFORE INSERT
ON ASU.TSKUD_PEOPLES REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
Begin
  IF :NEW.FK_ID IS NULL THEN
     SELECT ASU.SEQ_TSKUD_PEOPLES.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
  END IF;
End;
/
SHOW ERRORS;


