DROP TRIGGER ASU.TWPHISTORY_BEFORE_INSERT
/

--
-- TWPHISTORY_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TWORK_PLACE_HISTORY (Sequence)
--   TWORK_PLACE_HISTORY (Table)
--
CREATE OR REPLACE TRIGGER ASU."TWPHISTORY_BEFORE_INSERT"
BEFORE INSERT
ON ASU.TWORK_PLACE_HISTORY REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
Begin
  select SEQ_TWORK_PLACE_HISTORY.nextval into :new.fk_id from dual;
End;
/
SHOW ERRORS;


