DROP TRIGGER ASU.TPISMA_AFTER_DELETE
/

--
-- TPISMA_AFTER_DELETE  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   TKARTA (Table)
--   TPISMA (Table)
--
CREATE OR REPLACE TRIGGER ASU."TPISMA_AFTER_DELETE" 
AFTER DELETE
ON ASU.TPISMA REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
Begin
  DELETE FROM TKARTA WHERE FK_KOD=:OLD.FK_ID AND FK_KOD2=1 AND FP_TEK_COC=1;
End;
/
SHOW ERRORS;


