DROP TRIGGER ASU.TPROTPOKFF_BEFOR_INSERT
/

--
-- TPROTPOKFF_BEFOR_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TPROTPOKFF (Sequence)
--   TPROTPOKFF (Table)
--
CREATE OR REPLACE TRIGGER ASU."TPROTPOKFF_BEFOR_INSERT" 
  BEFORE INSERT
  ON ASU.TPROTPOKFF   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
Begin
  select SEQ_TPROTPOKFF.nextval into :new.fk_id from dual;
End;
/
SHOW ERRORS;


