DROP TRIGGER ASU.TLEVEL_BEFORE_INSERT
/

--
-- TLEVEL_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TLEVEL (Sequence)
--   TLEVEL (Table)
--
CREATE OR REPLACE TRIGGER ASU."TLEVEL_BEFORE_INSERT" 
  BEFORE INSERT
  ON ASU.TLEVEL   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
Begin
  SELECT SEQ_TLEVEL.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


