DROP PROCEDURE ASU.DO_CHANGE_REGION
/

--
-- DO_CHANGE_REGION  (Procedure) 
--
--  Dependencies: 
--   STANDARD (Package)
--   SYS_STUB_FOR_PURITY_ANALYSIS (Package)
--   TREGION (Table)
--
CREATE OR REPLACE PROCEDURE ASU."DO_CHANGE_REGION" 
   ( pFK_ID IN NUMBER,pFC_NAME IN VARCHAR2)
   IS
BEGIN
  UPDATE TREGION SET FC_NAME=pFC_NAME WHERE FK_ID=pFK_ID;
END; -- Procedure
/

SHOW ERRORS;


