DROP PROCEDURE ASU.DO_INSERT_STREET
/

--
-- DO_INSERT_STREET  (Procedure) 
--
--  Dependencies: 
--   STANDARD (Package)
--   SYS_STUB_FOR_PURITY_ANALYSIS (Package)
--   TSTREET (Table)
--
CREATE OR REPLACE PROCEDURE ASU."DO_INSERT_STREET" 
   ( FC_TEXT IN VARCHAR2)
   IS
BEGIN
  INSERT INTO TSTREET(FK_ID,FC_NAME) VALUES(1,FC_TEXT);
END; -- Procedure
/

SHOW ERRORS;


