DROP PROCEDURE ASU.DO_UPDATE_TSMINI
/

--
-- DO_UPDATE_TSMINI  (Procedure) 
--
--  Dependencies: 
--   STANDARD (Package)
--   TSMINI (Table)
--
CREATE OR REPLACE PROCEDURE ASU."DO_UPDATE_TSMINI" (PNUM NUMBER) IS 

PRAGMA AUTONOMOUS_TRANSACTION;

BEGIN
  UPDATE TSMINI SET FC_VALUE = TO_CHAR(pNUM) WHERE FC_SECTION = 'XRAY_NAPRAVLENIE' AND FC_KEY = 'ID_NUMBER';
  COMMIT;
END; -- Procedure
/

SHOW ERRORS;


