DROP PROCEDURE ASU.DO_DELETE_TPAC_INSURANCE
/

--
-- DO_DELETE_TPAC_INSURANCE  (Procedure) 
--
--  Dependencies: 
--   STANDARD (Package)
--   SYS_STUB_FOR_PURITY_ANALYSIS (Package)
--   TPAC_INSURANCE (Table)
--
CREATE OR REPLACE PROCEDURE ASU."DO_DELETE_TPAC_INSURANCE"
   (pFK_PACID IN NUMBER)
   IS
BEGIN
  DELETE FROM ASU.TPAC_INSURANCE I WHERE I.FK_PACID = pFK_PACID;
END "DO_DELETE_TPAC_INSURANCE"; -- Procedure
/

SHOW ERRORS;


