DROP PACKAGE ASU.PKG_R_FREEROOM
/

--
-- PKG_R_FREEROOM  (Package) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE PACKAGE ASU."PKG_R_FREEROOM" 
 is
 FUNCTION DO_CALC_REPORT(pTAB_NAME IN VARCHAR2, pFD_DATE IN DATE, pFK_VRACHID IN NUMBER) RETURN NUMBER;
end PKG_R_FREEROOM;
/

SHOW ERRORS;


