DROP PACKAGE ASU.PKG_DAILY_BUH_OLD
/

--
-- PKG_DAILY_BUH_OLD  (Package) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE PACKAGE ASU."PKG_DAILY_BUH_OLD" 
  IS
FUNCTION DO_CALC_REPORT(pFD_DATA IN DATE,pFC_REMARK IN VARCHAR2,pFK_VRACHID IN NUMBER) RETURN NUMBER;
END; -- Package Specification PKG_DAILY_BUH
/

SHOW ERRORS;


