DROP PACKAGE ASU.PKG_DELETE
/

--
-- PKG_DELETE  (Package) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE PACKAGE ASU."PKG_DELETE" IS
FUNCTION DELETE_FROM_TEPIKRIZ(PFK_ID IN NUMBER,pSotrId NUMBER) RETURN NUMBER ;
FUNCTION DELETE_FROM_VNAZ(PFK_ID IN NUMBER,pSotrId NUMBER) RETURN NUMBER ;

END; -- Package spec
/

SHOW ERRORS;


