DROP PACKAGE ASU.PKG_R_DAILYBUH
/

--
-- PKG_R_DAILYBUH  (Package) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE PACKAGE ASU."PKG_R_DAILYBUH" 
 IS
 FUNCTION DO_CALC_REPORT(pFD_DATA IN DATE,pFC_REMARK IN VARCHAR2,pFK_VRACHID IN NUMBER,pFK_KORPID IN NUMBER) RETURN NUMBER;
END;
/

SHOW ERRORS;


