DROP PACKAGE ASU.PKG_R_RASPPUTMASH
/

--
-- PKG_R_RASPPUTMASH  (Package) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE PACKAGE ASU."PKG_R_RASPPUTMASH" 
 is
  TYPE TMonth IS RECORD (sName VARCHAR2(20),dData1 DATE,dData2 DATE);
  TYPE TMonths IS TABLE OF TMonth INDEX BY BINARY_INTEGER;
  Month TMonths;
 FUNCTION DO_CALC_REPORT (nMonth1 IN NUMBER, nMonth2 IN NUMBER, nYear IN NUMBER, pFK_VRACHID IN NUMBER) RETURN NUMBER;
end PKG_R_RASPPUTMASH;
/

SHOW ERRORS;


