DROP PACKAGE ASU.PKG_PLAN_GORKA
/

--
-- PKG_PLAN_GORKA  (Package) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE PACKAGE ASU."PKG_PLAN_GORKA" IS -- Created by TimurLan
  FUNCTION DO_GRAPH_FOR_PLAN (pFK_MAINID IN NUMBER, pFK_VRACHID IN NUMBER) RETURN NUMBER;
END;
/

SHOW ERRORS;


