DROP PACKAGE ASU.PKG_R_LISTOFLEAVINGS
/

--
-- PKG_R_LISTOFLEAVINGS  (Package) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE PACKAGE ASU."PKG_R_LISTOFLEAVINGS" 
 IS

 FUNCTION DO_CALC_REPORT(pFD_DATA IN DATE,pFK_VRACHID IN NUMBER,pFK_VID IN NUMBER) RETURN NUMBER;

END;
/

SHOW ERRORS;


