DROP PACKAGE ASU.PKG_R_PLAN_YEAR
/

--
-- PKG_R_PLAN_YEAR  (Package) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE PACKAGE ASU."PKG_R_PLAN_YEAR" 
 is
  FUNCTION DO_CALC_REPORT(pFC_YEAR IN VARCHAR2,pFK_VRACHID IN NUMBER) RETURN NUMBER;
end PKG_R_PLAN_YEAR;
/

SHOW ERRORS;


