DROP PACKAGE ASU.PKG_R_MONTHIB
/

--
-- PKG_R_MONTHIB  (Package) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE PACKAGE ASU."PKG_R_MONTHIB" 
 is
 FUNCTION DO_CALC_REPORT_BY_ALL(pFD_DATA1 IN DATE,pFD_DATA2 IN DATE,pFK_VRACHID IN NUMBER) RETURN NUMBER;
 FUNCTION DO_CALC_REPORT_BY_KORP(pFD_DATA1 IN DATE,pFD_DATA2 IN DATE,pFK_VRACHID IN NUMBER,pFK_KORPID IN NUMBER) RETURN NUMBER;
end PKG_R_MONTHIB;
/

SHOW ERRORS;


