DROP PACKAGE ASU.PKG_R_PERESEL
/

--
-- PKG_R_PERESEL  (Package) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE PACKAGE ASU."PKG_R_PERESEL" 
 is
  FUNCTION DO_CALC_REPORT(pFD_DATA IN DATE,pFK_VRACHID IN NUMBER) RETURN NUMBER;
end PKG_R_PERESEL;
/

SHOW ERRORS;


