DROP PACKAGE ASU.PKG_R_FULLSTAT
/

--
-- PKG_R_FULLSTAT  (Package) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE PACKAGE ASU."PKG_R_FULLSTAT" 
 is
 FUNCTION DO_CALC_REPORT(pFD_DATA1 IN DATE,pFD_DATA2 IN DATE,pFK_VRACHID IN NUMBER) RETURN NUMBER;
end PKG_R_FULLSTAT;
/

SHOW ERRORS;


