CREATE OR REPLACE TRIGGER "ASU"."TDIGITAL_SIGN_BEFORE_INSERT"
 BEFORE
 INSERT
 ON asu.TDIGITAL_SIGNATURE
 REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
begin
  if :NEW.FK_ID is null then
    SELECT seq_TDIGITAL_SIGNATURE.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
  end if;  
end;
/
