CREATE INDEX ASU.TDIGITAL_SIGN_FK_SQL_RULEID ON ASU.TDIGITAL_SIGNATURE (  FK_SQL_RULEID ASC  ) 
 COMPUTE STATISTICS 
/

CREATE INDEX ASU.TDIGITAL_SIGN_FK_MAINTABLEID ON ASU.TDIGITAL_SIGNATURE (  FK_MAINTABLEID ASC  ) 
 COMPUTE STATISTICS 
/
