ALTER TABLE MED.TPRICE_MONITOR_OST 
 ADD (
  FN_PRICE NUMBER DEFAULT 0,
  FN_MNF_PRICE NUMBER DEFAULT 0
 )
/
COMMENT ON COLUMN MED.TPRICE_MONITOR_OST.FN_PRICE IS 'цена (закупочная у поставщика со всеми налогами и надбавками)'
/
COMMENT ON COLUMN MED.TPRICE_MONITOR_OST.FN_MNF_PRICE IS 'цена производителя'
/
