DROP TABLE ASU.DOA_DEMO_QUEUE_TABLE CASCADE CONSTRAINTS
/

--
-- DOA_DEMO_QUEUE_TABLE  (Table) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DOA_DEMO_QUEUE_TYPE (Type)
--
CREATE TABLE ASU.DOA_DEMO_QUEUE_TABLE
(
  Q_NAME             VARCHAR2(30 BYTE),
  MSGID              RAW(16),
  CORRID             VARCHAR2(128 BYTE),
  PRIORITY           NUMBER,
  STATE              NUMBER,
  DELAY              TIMESTAMP(6),
  EXPIRATION         NUMBER,
  TIME_MANAGER_INFO  TIMESTAMP(6),
  LOCAL_ORDER_NO     NUMBER,
  CHAIN_NO           NUMBER,
  CSCN               NUMBER,
  DSCN               NUMBER,
  ENQ_TIME           TIMESTAMP(6),
  ENQ_UID            NUMBER,
  ENQ_TID            VARCHAR2(30 BYTE),
  DEQ_TIME           TIMESTAMP(6),
  DEQ_UID            NUMBER,
  DEQ_TID            VARCHAR2(30 BYTE),
  RETRY_COUNT        NUMBER,
  EXCEPTION_QSCHEMA  VARCHAR2(30 BYTE),
  EXCEPTION_QUEUE    VARCHAR2(30 BYTE),
  STEP_NO            NUMBER,
  RECIPIENT_KEY      NUMBER,
  DEQUEUE_MSGID      RAW(16),
  USER_DATA          ASU.DOA_DEMO_QUEUE_TYPE
)
COLUMN USER_DATA NOT SUBSTITUTABLE AT ALL LEVELS
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


