DROP TABLE ASU.LOG_ERRORS_TAB CASCADE CONSTRAINTS
/

--
-- LOG_ERRORS_TAB  (Table) 
--
CREATE TABLE ASU.LOG_ERRORS_TAB
(
  ERROR        VARCHAR2(30 BYTE),
  TIMESTAMP    DATE,
  USERNAME     VARCHAR2(30 BYTE),
  OSUSER       VARCHAR2(30 BYTE),
  MACHINE      VARCHAR2(64 BYTE),
  PROCESS      VARCHAR2(12 BYTE),
  PROGRAM      VARCHAR2(64 BYTE),
  MODULE       VARCHAR2(48 BYTE),
  ACTION       VARCHAR2(32 BYTE),
  CLIENT_INFO  VARCHAR2(32 BYTE),
  SQL_TEXT     VARCHAR2(4000 BYTE),
  CALL_STACK   VARCHAR2(4000 BYTE)
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          3808K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT
/

COMMENT ON TABLE ASU.LOG_ERRORS_TAB IS 'Таблица системных ошибок by TimurLan'
/

COMMENT ON COLUMN ASU.LOG_ERRORS_TAB.ERROR IS 'Код ошибки'
/

COMMENT ON COLUMN ASU.LOG_ERRORS_TAB.TIMESTAMP IS 'время записи'
/

COMMENT ON COLUMN ASU.LOG_ERRORS_TAB.USERNAME IS 'пользователь БД'
/

COMMENT ON COLUMN ASU.LOG_ERRORS_TAB.OSUSER IS 'пользователь ОС'
/

COMMENT ON COLUMN ASU.LOG_ERRORS_TAB.MACHINE IS 'имя терминала'
/

COMMENT ON COLUMN ASU.LOG_ERRORS_TAB.PROCESS IS 'ИД процесса'
/

COMMENT ON COLUMN ASU.LOG_ERRORS_TAB.PROGRAM IS 'имя программы'
/

COMMENT ON COLUMN ASU.LOG_ERRORS_TAB.MODULE IS 'module'
/

COMMENT ON COLUMN ASU.LOG_ERRORS_TAB.ACTION IS 'action'
/

COMMENT ON COLUMN ASU.LOG_ERRORS_TAB.CLIENT_INFO IS 'GET_SOTRNAME'
/

COMMENT ON COLUMN ASU.LOG_ERRORS_TAB.SQL_TEXT IS 'Текст ошибки'
/

COMMENT ON COLUMN ASU.LOG_ERRORS_TAB.CALL_STACK IS 'format_call_stack и format_error_stack'
/


