DROP TABLE ASU.MLOG$_TPEOPLES CASCADE CONSTRAINTS
/

--
-- MLOG$_TPEOPLES  (Table) 
--
CREATE TABLE ASU.MLOG$_TPEOPLES
(
  FK_ID            NUMBER(15),
  SNAPTIME$$       DATE,
  DMLTYPE$$        VARCHAR2(1 BYTE),
  OLD_NEW$$        VARCHAR2(1 BYTE),
  CHANGE_VECTOR$$  RAW(255)
)
TABLESPACE USR
PCTUSED    0
PCTFREE    60
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
PARALLEL ( DEGREE DEFAULT INSTANCES DEFAULT )
MONITORING
/

COMMENT ON TABLE ASU.MLOG$_TPEOPLES IS 'snapshot log for master table ASU.TPEOPLES'
/


