DROP TABLE ASU.T_TEMPTOMP CASCADE CONSTRAINTS
/

--
-- T_TEMPTOMP  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE ASU.T_TEMPTOMP
(
  FC_ID         VARCHAR2(21 BYTE),
  CODE          VARCHAR2(15 BYTE),
  FC_NAME       VARCHAR2(490 BYTE),
  FC_PARENT     VARCHAR2(15 BYTE),
  FK_HEALID     NUMBER,
  FK_COMPANYID  NUMBER,
  FK_COSTID     NUMBER,
  FD_DATE1      DATE,
  FN_COST       NUMBER,
  FL_KIOSK      NUMBER(1)                       DEFAULT 0,
  FK_DOGOVORID  NUMBER
)
ON COMMIT PRESERVE ROWS
NOCACHE
/

COMMENT ON COLUMN ASU.T_TEMPTOMP.FC_ID IS 'длина 21 - префикс + 15 симполов на ID'
/


