DROP TABLE ASU.TACTIONTIME CASCADE CONSTRAINTS
/

--
-- TACTIONTIME  (Table) 
--
CREATE TABLE ASU.TACTIONTIME
(
  FK_ACTIONID  NUMBER,
  FD_DATE      DATE,
  FK_SOTRID    NUMBER,
  FD_READ      DATE,
  FL_DEL       NUMBER,
  FK_ID        NUMBER,
  FK_CLOBID    NUMBER
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          176K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON COLUMN ASU.TACTIONTIME.FK_ACTIONID IS '—сылка на TACTION'
/

COMMENT ON COLUMN ASU.TACTIONTIME.FK_ID IS 'SEQUENCE=[SEQ_TACTIONTIME]'
/


--
-- TACTIONTIME_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   TACTIONTIME (Table)
--
CREATE OR REPLACE TRIGGER ASU."TACTIONTIME_BEFORE_INSERT" 
 BEFORE
 INSERT
 ON ASU.TACTIONTIME  REFERENCING OLD AS Old NEW AS New
 FOR EACH ROW
Begin
  SELECT SEQ_TACTIONTIME.NEXTVAL INTO :New.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


