DROP TABLE ASU.TALGORITHM CASCADE CONSTRAINTS
/

--
-- TALGORITHM  (Table) 
--
CREATE TABLE ASU.TALGORITHM
(
  FK_ID       NUMBER(9),
  FC_NAME     VARCHAR2(50 BYTE),
  FC_FUNC     VARCHAR2(50 BYTE),
  FC_COMMENT  VARCHAR2(256 BYTE)
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          520K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TALGORITHM IS 'список алгоритмов'
/

COMMENT ON COLUMN ASU.TALGORITHM.FC_FUNC IS 'вызываемая PL SQL функция'
/


