DROP TABLE ASU.TAMBTALON_TMP20091222 CASCADE CONSTRAINTS
/

--
-- TAMBTALON_TMP20091222  (Table) 
--
CREATE TABLE ASU.TAMBTALON_TMP20091222
(
  TALONID  NUMBER,
  OLDDOP   NUMBER,
  NEWDOP   NUMBER
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


