DROP TABLE ASU.TAMBTALON_NAZ_TMP20100126 CASCADE CONSTRAINTS
/

--
-- TAMBTALON_NAZ_TMP20100126  (Table) 
--
CREATE TABLE ASU.TAMBTALON_NAZ_TMP20100126
(
  FK_TALONID  NUMBER(15)                        NOT NULL,
  FK_AMBID    NUMBER(15),
  FK_NAZID    NUMBER(15)                        NOT NULL,
  FD_INS      DATE
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


