ALTER TABLE ASU.TAMBULANCE_INFO
 DROP PRIMARY KEY CASCADE
/

DROP TABLE ASU.TAMBULANCE_INFO CASCADE CONSTRAINTS
/

--
-- TAMBULANCE_INFO  (Table) 
--
CREATE TABLE ASU.TAMBULANCE_INFO
(
  FK_AMBID          NUMBER,
  FK_CARD_STATUSID  NUMBER,
  FK_PRICREP_UCH    NUMBER,
  FK_LAST_APPSOTR   NUMBER,
  FD_LAST_APPSOTR   DATE
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TAMBULANCE_INFO IS 'Таблица для информации по пацику, чтобы не мучить таблицу TAMBULANCE  author: Marriage'
/

COMMENT ON COLUMN ASU.TAMBULANCE_INFO.FK_CARD_STATUSID IS 'TSMID.FK_ID'
/

COMMENT ON COLUMN ASU.TAMBULANCE_INFO.FK_PRICREP_UCH IS 'TSMID.FK_ID'
/

COMMENT ON COLUMN ASU.TAMBULANCE_INFO.FK_LAST_APPSOTR IS 'TAPPSOTR.FK_ID  Кто последний редактировал данные'
/

COMMENT ON COLUMN ASU.TAMBULANCE_INFO.FD_LAST_APPSOTR IS 'Когда'
/


--
-- TAMBULANCE_INFO_PK  (Index) 
--
--  Dependencies: 
--   TAMBULANCE_INFO (Table)
--
CREATE UNIQUE INDEX ASU.TAMBULANCE_INFO_PK ON ASU.TAMBULANCE_INFO
(FK_AMBID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


-- 
-- Non Foreign Key Constraints for Table TAMBULANCE_INFO 
-- 
ALTER TABLE ASU.TAMBULANCE_INFO ADD (
  CONSTRAINT TAMBULANCE_INFO_PK
 PRIMARY KEY
 (FK_AMBID)
    USING INDEX 
    TABLESPACE USR
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ))
/

