DROP TABLE ASU.TAPPENDIX_NAZ CASCADE CONSTRAINTS
/

--
-- TAPPENDIX_NAZ  (Table) 
--
CREATE TABLE ASU.TAPPENDIX_NAZ
(
  FK_APPENDIXID  NUMBER,
  FK_PACID       NUMBER,
  FK_NAZID       NUMBER,
  FK_HEAL        NUMBER
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TAPPENDIX_NAZ IS 'Назначения в рамках приложения'
/

COMMENT ON COLUMN ASU.TAPPENDIX_NAZ.FK_APPENDIXID IS 'TAPPENDIX.FK_ID'
/

COMMENT ON COLUMN ASU.TAPPENDIX_NAZ.FK_NAZID IS 'VNAZ.FK_ID'
/


--
-- TAPPENDIX_NAZ_FK_APPENDIXID  (Index) 
--
--  Dependencies: 
--   TAPPENDIX_NAZ (Table)
--
CREATE INDEX ASU.TAPPENDIX_NAZ_FK_APPENDIXID ON ASU.TAPPENDIX_NAZ
(FK_APPENDIXID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- TAPPENDIX_NAZ_FK_NAZID  (Index) 
--
--  Dependencies: 
--   TAPPENDIX_NAZ (Table)
--
CREATE INDEX ASU.TAPPENDIX_NAZ_FK_NAZID ON ASU.TAPPENDIX_NAZ
(FK_NAZID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


