DROP TABLE ASU.TAPTEKA CASCADE CONSTRAINTS
/

--
-- TAPTEKA  (Table) 
--
CREATE TABLE ASU.TAPTEKA
(
  FN_FAS   NUMBER(16,4),
  FC_ED    VARCHAR2(20 BYTE),
  FC_EDF   VARCHAR2(20 BYTE),
  FC_NAME  VARCHAR2(250 BYTE),
  FN_SUM   NUMBER(19,2),
  FN_OST   NUMBER(16,4)
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          520K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TAPTEKA IS 'Остатки аптеки'
/

COMMENT ON COLUMN ASU.TAPTEKA.FN_FAS IS 'Расфасовка'
/

COMMENT ON COLUMN ASU.TAPTEKA.FC_ED IS 'Единицы измерения'
/

COMMENT ON COLUMN ASU.TAPTEKA.FC_EDF IS 'Единицы измерения фасовки'
/

COMMENT ON COLUMN ASU.TAPTEKA.FC_NAME IS 'Наименование медикамента'
/

COMMENT ON COLUMN ASU.TAPTEKA.FN_SUM IS 'Цена'
/

COMMENT ON COLUMN ASU.TAPTEKA.FN_OST IS 'Остаток в аптеке'
/


