ALTER TABLE ASU.TBIRTH_CERTIFICATION
 DROP PRIMARY KEY CASCADE
/

DROP TABLE ASU.TBIRTH_CERTIFICATION CASCADE CONSTRAINTS
/

--
-- TBIRTH_CERTIFICATION  (Table) 
--
CREATE TABLE ASU.TBIRTH_CERTIFICATION
(
  FK_ID                   NUMBER                NOT NULL,
  FK_BLANKID              NUMBER                DEFAULT 0,
  FK_PEPLID               NUMBER,
  FK_INSURDOCID           NUMBER,
  FD_GIVING               DATE,
  FN_PERIOD_GIVING        NUMBER,
  FD_REGISTRATION         DATE,
  FN_PERIOD_REGISTRATION  NUMBER,
  FC_INSURSER             VARCHAR2(50 BYTE),
  FC_INSURNUM             VARCHAR2(50 BYTE)
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TBIRTH_CERTIFICATION IS 'Данные родовых сертификатов'
/

COMMENT ON COLUMN ASU.TBIRTH_CERTIFICATION.FK_ID IS 'SEQUENCE=[SEQ_TBIRTH_CERTIFICATION]'
/

COMMENT ON COLUMN ASU.TBIRTH_CERTIFICATION.FK_BLANKID IS 'Код бланка TCERTIFICATION_BLANK.FK_ID'
/

COMMENT ON COLUMN ASU.TBIRTH_CERTIFICATION.FK_PEPLID IS 'Код человека TPEOPLES.FK_ID'
/

COMMENT ON COLUMN ASU.TBIRTH_CERTIFICATION.FK_INSURDOCID IS 'Код страхового полиса TINSURDOCS.FK_ID'
/

COMMENT ON COLUMN ASU.TBIRTH_CERTIFICATION.FD_GIVING IS 'Дата выдачи сертификата'
/

COMMENT ON COLUMN ASU.TBIRTH_CERTIFICATION.FN_PERIOD_GIVING IS 'Срок беременности на момент выдачи сертификата'
/

COMMENT ON COLUMN ASU.TBIRTH_CERTIFICATION.FD_REGISTRATION IS 'Дата регистарции'
/

COMMENT ON COLUMN ASU.TBIRTH_CERTIFICATION.FN_PERIOD_REGISTRATION IS 'Срок беременности на момент выдачи сертификата'
/

COMMENT ON COLUMN ASU.TBIRTH_CERTIFICATION.FC_INSURSER IS 'Серия страхового полиса'
/

COMMENT ON COLUMN ASU.TBIRTH_CERTIFICATION.FC_INSURNUM IS 'Номер срахового полиса'
/


--
-- TBIRTH_CERTIFICATION_BY_ID  (Index) 
--
--  Dependencies: 
--   TBIRTH_CERTIFICATION (Table)
--
CREATE UNIQUE INDEX ASU.TBIRTH_CERTIFICATION_BY_ID ON ASU.TBIRTH_CERTIFICATION
(FK_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- TBIRTH_CERT_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   TBIRTH_CERTIFICATION (Table)
--
CREATE OR REPLACE TRIGGER ASU."TBIRTH_CERT_BEFORE_INSERT" 
  BEFORE INSERT
  ON ASU.TBIRTH_CERTIFICATION   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
Begin
  SELECT SEQ_TBIRTH_CERTIFICATION.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


-- 
-- Non Foreign Key Constraints for Table TBIRTH_CERTIFICATION 
-- 
ALTER TABLE ASU.TBIRTH_CERTIFICATION ADD (
  CONSTRAINT TBIRTH_CERTIFICATION_BY_ID
 PRIMARY KEY
 (FK_ID)
    USING INDEX 
    TABLESPACE INDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          160K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ))
/

