DROP TABLE ASU.TBODY_PARAM CASCADE CONSTRAINTS
/

--
-- TBODY_PARAM  (Table) 
--
CREATE TABLE ASU.TBODY_PARAM
(
  FK_ID         INTEGER,
  FC_DIRECTORY  VARCHAR2(100 BYTE),
  FN_AGE        INTEGER,
  FN_3          NUMBER(22,2),
  FN_10         NUMBER(22,2),
  FN_25         NUMBER(22,2),
  FN_75         NUMBER(22,2),
  FN_90         NUMBER(22,2),
  FN_97         NUMBER(22,2)
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TBODY_PARAM IS 'Параметры тела детей'
/

COMMENT ON COLUMN ASU.TBODY_PARAM.FK_ID IS 'SEQUENCE=[SEQ_TBODY_PARAM]'
/

COMMENT ON COLUMN ASU.TBODY_PARAM.FC_DIRECTORY IS 'Синоним справочника'
/

COMMENT ON COLUMN ASU.TBODY_PARAM.FN_AGE IS 'Возраст'
/

COMMENT ON COLUMN ASU.TBODY_PARAM.FN_3 IS '3'
/

COMMENT ON COLUMN ASU.TBODY_PARAM.FN_10 IS '10'
/

COMMENT ON COLUMN ASU.TBODY_PARAM.FN_25 IS '25'
/

COMMENT ON COLUMN ASU.TBODY_PARAM.FN_75 IS '75'
/

COMMENT ON COLUMN ASU.TBODY_PARAM.FN_90 IS '90'
/

COMMENT ON COLUMN ASU.TBODY_PARAM.FN_97 IS '97'
/


--
-- TBODY_PARAM_BEFORE_INS  (Trigger) 
--
--  Dependencies: 
--   TBODY_PARAM (Table)
--
CREATE OR REPLACE TRIGGER ASU."TBODY_PARAM_BEFORE_INS" 
 BEFORE 
 INSERT
 ON ASU.TBODY_PARAM  REFERENCING OLD AS old NEW AS new
 FOR EACH ROW
Begin
  SELECT SEQ_TBODY_PARAM.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


