DROP TABLE ASU.TBRONINFO CASCADE CONSTRAINTS
/

--
-- TBRONINFO  (Table) 
--
CREATE TABLE ASU.TBRONINFO
(
  FK_ID         NUMBER                          NOT NULL,
  FK_OTDELID    NUMBER,
  FK_KOMFORTID  NUMBER,
  FK_TYPEDOCID  NUMBER,
  FK_TARIFID    NUMBER,
  FK_SROKID     NUMBER,
  FC_DIAG       VARCHAR2(256 BYTE),
  FK_PROFID     NUMBER,
  FK_VRACHID    NUMBER,
  FC_FAM        VARCHAR2(256 BYTE),
  FC_IM         VARCHAR2(256 BYTE),
  FC_OTCH       VARCHAR2(256 BYTE),
  FD_ROJD       DATE,
  FP_SEX        NUMBER(1),
  FK_PACID      NUMBER
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON COLUMN ASU.TBRONINFO.FK_OTDELID IS 'Код отделения'
/

COMMENT ON COLUMN ASU.TBRONINFO.FK_KOMFORTID IS 'TKOMFORT.FK_ID'
/

COMMENT ON COLUMN ASU.TBRONINFO.FK_TYPEDOCID IS 'TTYPEDOC.FK_ID'
/

COMMENT ON COLUMN ASU.TBRONINFO.FK_TARIFID IS 'TSTANDART.FK_ID'
/

COMMENT ON COLUMN ASU.TBRONINFO.FK_SROKID IS 'TSROKY.FK_ID'
/

COMMENT ON COLUMN ASU.TBRONINFO.FC_DIAG IS '----'
/

COMMENT ON COLUMN ASU.TBRONINFO.FK_PROFID IS 'TTIPROOM.FK_ID'
/


--
-- TBRONINFO_INSERT  (Trigger) 
--
--  Dependencies: 
--   TBRONINFO (Table)
--
CREATE OR REPLACE TRIGGER ASU."TBRONINFO_INSERT" 
  BEFORE INSERT
  ON ASU.TBRONINFO   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
Begin
  select SEQ_TBRONINFO.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


