DROP TABLE ASU.TCHEMOTHERAPY_TEMPL_ITEMS CASCADE CONSTRAINTS
/

--
-- TCHEMOTHERAPY_TEMPL_ITEMS  (Table) 
--
--  Dependencies: 
--   TCHEMOTHERAPY_TEMPL (Table)
--
CREATE TABLE ASU.TCHEMOTHERAPY_TEMPL_ITEMS
(
  FK_ID          NUMBER                         NOT NULL,
  FK_TEMPLID     NUMBER                         NOT NULL,
  FK_MEDICID     NUMBER                         NOT NULL,
  FN_DOZA        NUMBER,
  FK_DOZA_EI     NUMBER,
  FK_VVODPATH    NUMBER,
  FB_PRIEMGRAPH  VARCHAR2(30 BYTE),
  FC_NAME        VARCHAR2(750 BYTE)
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TCHEMOTHERAPY_TEMPL_ITEMS IS 'Препараты в шаблоне химиотерапии. Author: Neronov A.S. 10.08.2012'
/

COMMENT ON COLUMN ASU.TCHEMOTHERAPY_TEMPL_ITEMS.FK_ID IS '[SEQ_TCHEMOTHERAPY_TEMPL_ITEMS] - Первичный ключ'
/

COMMENT ON COLUMN ASU.TCHEMOTHERAPY_TEMPL_ITEMS.FK_TEMPLID IS 'ASU.TCHEMOTHERAPY_TEMPL - Ссылка на шаблон курса'
/

COMMENT ON COLUMN ASU.TCHEMOTHERAPY_TEMPL_ITEMS.FK_MEDICID IS 'MED.TMEDIC - Медикамент'
/

COMMENT ON COLUMN ASU.TCHEMOTHERAPY_TEMPL_ITEMS.FN_DOZA IS 'Доза на 1 кв. м. площади тела'
/

COMMENT ON COLUMN ASU.TCHEMOTHERAPY_TEMPL_ITEMS.FK_DOZA_EI IS 'MED.TMASSUNITS - Единица изм. дозы'
/

COMMENT ON COLUMN ASU.TCHEMOTHERAPY_TEMPL_ITEMS.FK_VVODPATH IS 'ASU.TVVODPATH - Путь введения'
/

COMMENT ON COLUMN ASU.TCHEMOTHERAPY_TEMPL_ITEMS.FB_PRIEMGRAPH IS 'График приема (например: 1,5 = 1-ый и 5 день; 2-6 = со 2-ого по 6-ой день)'
/

COMMENT ON COLUMN ASU.TCHEMOTHERAPY_TEMPL_ITEMS.FC_NAME IS 'Наименование объекта учета (копия из med.tmedic.fc_name, при добавлении записи в шаблон)'
/


--
-- TCHEMOTHERAPY_TEMPL_ITEMS_BI  (Trigger) 
--
--  Dependencies: 
--   TCHEMOTHERAPY_TEMPL_ITEMS (Table)
--
CREATE OR REPLACE TRIGGER ASU."TCHEMOTHERAPY_TEMPL_ITEMS_BI" 
 BEFORE
 INSERT
 ON ASU.TCHEMOTHERAPY_TEMPL_ITEMS  REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
BEGIN
   select SEQ_TCHEMOTHERAPY_TEMPL_ITEMS.nextval into :new.fk_id from dual;
END;
/
SHOW ERRORS;


-- 
-- Foreign Key Constraints for Table TCHEMOTHERAPY_TEMPL_ITEMS 
-- 
ALTER TABLE ASU.TCHEMOTHERAPY_TEMPL_ITEMS ADD (
  CONSTRAINT TCHEMOTHERAPY_TEMPL_FK 
 FOREIGN KEY (FK_TEMPLID) 
 REFERENCES ASU.TCHEMOTHERAPY_TEMPL (FK_ID))
/

