ALTER TABLE ASU.TCHEMOTHERAPY_TEMPL
 DROP PRIMARY KEY CASCADE
/

DROP TABLE ASU.TCHEMOTHERAPY_TEMPL CASCADE CONSTRAINTS
/

--
-- TCHEMOTHERAPY_TEMPL  (Table) 
--
CREATE TABLE ASU.TCHEMOTHERAPY_TEMPL
(
  FK_ID         NUMBER                          NOT NULL,
  FC_NAME       VARCHAR2(50 BYTE)               NOT NULL,
  FK_SMIDOWNER  NUMBER
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TCHEMOTHERAPY_TEMPL IS 'Шаблоны курсов химиотерапии. Author: Neronov A.S. 10.08.2012'
/

COMMENT ON COLUMN ASU.TCHEMOTHERAPY_TEMPL.FK_ID IS '[SEQ_TCHEMOTHERAPY_TEMPL] - Первичный ключ'
/

COMMENT ON COLUMN ASU.TCHEMOTHERAPY_TEMPL.FC_NAME IS 'Название курса'
/

COMMENT ON COLUMN ASU.TCHEMOTHERAPY_TEMPL.FK_SMIDOWNER IS 'Схема химиотерапии (ветка в TSMID с синонимом CHEMOTHERAPY_SCHEMA)'
/


--
-- TCHEMOTHERAPY_TEMPL_PK  (Index) 
--
--  Dependencies: 
--   TCHEMOTHERAPY_TEMPL (Table)
--
CREATE UNIQUE INDEX ASU.TCHEMOTHERAPY_TEMPL_PK ON ASU.TCHEMOTHERAPY_TEMPL
(FK_ID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- TCHEMOTHERAPY_TEMPL_BI  (Trigger) 
--
--  Dependencies: 
--   TCHEMOTHERAPY_TEMPL (Table)
--
CREATE OR REPLACE TRIGGER ASU."TCHEMOTHERAPY_TEMPL_BI" 
 BEFORE
 INSERT
 ON ASU.TCHEMOTHERAPY_TEMPL  REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
BEGIN
   select SEQ_TCHEMOTHERAPY_TEMPL.nextval into :new.fk_id from dual;
END;
/
SHOW ERRORS;


-- 
-- Non Foreign Key Constraints for Table TCHEMOTHERAPY_TEMPL 
-- 
ALTER TABLE ASU.TCHEMOTHERAPY_TEMPL ADD (
  CONSTRAINT TCHEMOTHERAPY_TEMPL_PK
 PRIMARY KEY
 (FK_ID)
    USING INDEX 
    TABLESPACE USR
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ))
/

