DROP TABLE ASU.TDATATEST CASCADE CONSTRAINTS
/

--
-- TDATATEST  (Table) 
--
CREATE TABLE ASU.TDATATEST
(
  FK_ID      NUMBER(15),
  FK_PACID   NUMBER(15),
  FC_TEST    VARCHAR2(40 BYTE),
  FN_TEST    NUMBER(2),
  FN_GRPRIB  NUMBER(1),
  FN_GRVYB   NUMBER(1)
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          520K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


