ALTER TABLE ASU.TDEZHURSPECLINK
 DROP PRIMARY KEY CASCADE
/

DROP TABLE ASU.TDEZHURSPECLINK CASCADE CONSTRAINTS
/

--
-- TDEZHURSPECLINK  (Table) 
--
CREATE TABLE ASU.TDEZHURSPECLINK
(
  FK_DEZHURSPECID  NUMBER                       NOT NULL,
  FK_SPRAVID       NUMBER                       NOT NULL
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON COLUMN ASU.TDEZHURSPECLINK.FK_DEZHURSPECID IS 'TDEZHURSPEC.FK_ID'
/

COMMENT ON COLUMN ASU.TDEZHURSPECLINK.FK_SPRAVID IS 'TS_SPRAV.FK_ID'
/


--
-- TDEZHURSPECLINK_DEZHSPRAV  (Index) 
--
--  Dependencies: 
--   TDEZHURSPECLINK (Table)
--
CREATE UNIQUE INDEX ASU.TDEZHURSPECLINK_DEZHSPRAV ON ASU.TDEZHURSPECLINK
(FK_DEZHURSPECID, FK_SPRAVID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


-- 
-- Non Foreign Key Constraints for Table TDEZHURSPECLINK 
-- 
ALTER TABLE ASU.TDEZHURSPECLINK ADD (
  CONSTRAINT TDEZHURSPECLINK_DEZHSPRAV
 PRIMARY KEY
 (FK_DEZHURSPECID, FK_SPRAVID)
    USING INDEX 
    TABLESPACE USR
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ))
/

