DROP TABLE ASU.TDIALIZ_LIST CASCADE CONSTRAINTS
/

--
-- TDIALIZ_LIST  (Table) 
--
CREATE TABLE ASU.TDIALIZ_LIST
(
  FK_ID          NUMBER                         NOT NULL,
  FK_PACID       NUMBER,
  FD_DATE        DATE,
  FL_PODPIS      NUMBER(1),
  FD_PODPIS      DATE,
  FK_AMBTALON    NUMBER,
  FC_CONCENTRAT  VARCHAR2(50 BYTE),
  FN_POTOK       NUMBER,
  FK_SMID        NUMBER
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON COLUMN ASU.TDIALIZ_LIST.FD_DATE IS 'месяц и год, число не важно'
/

COMMENT ON COLUMN ASU.TDIALIZ_LIST.FL_PODPIS IS 'флаг подписи'
/

COMMENT ON COLUMN ASU.TDIALIZ_LIST.FD_PODPIS IS 'дата подписи'
/

COMMENT ON COLUMN ASU.TDIALIZ_LIST.FC_CONCENTRAT IS 'диализный концентрат'
/

COMMENT ON COLUMN ASU.TDIALIZ_LIST.FN_POTOK IS 'поток диализата'
/


--
-- I_TDIALIZ_LIST_ID  (Index) 
--
--  Dependencies: 
--   TDIALIZ_LIST (Table)
--
CREATE INDEX ASU.I_TDIALIZ_LIST_ID ON ASU.TDIALIZ_LIST
(FK_ID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- TDIALIZ_LIST_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   TDIALIZ_LIST (Table)
--
CREATE OR REPLACE TRIGGER ASU."TDIALIZ_LIST_BEFORE_INSERT"
  BEFORE INSERT
  ON ASU.TDIALIZ_LIST   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
BEGIN
  SELECT ASU.SEQ_TDIALIZ_LIST.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
END;
/
SHOW ERRORS;


