ALTER TABLE ASU.TDISTRICT_NAME
 DROP PRIMARY KEY CASCADE
/

DROP TABLE ASU.TDISTRICT_NAME CASCADE CONSTRAINTS
/

--
-- TDISTRICT_NAME  (Table) 
--
CREATE TABLE ASU.TDISTRICT_NAME
(
  FK_ID           NUMBER                        NOT NULL,
  FC_NAME         VARCHAR2(100 BYTE),
  FC_DESCRIPTION  VARCHAR2(100 BYTE),
  FK_SOTR         NUMBER,
  FK_THERPOINT    NUMBER,
  FK_VRACHKAB     NUMBER,
  FC_CAR          CHAR(1 BYTE),
  FC_WARE         CHAR(1 BYTE),
  FN_S_CAB        NUMBER,
  FN_S_DR         NUMBER,
  FK_TYPEID       NUMBER,
  FK_LPUID        NUMBER
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TDISTRICT_NAME IS 'Терапевтические участки -- Created 20081007 by Linnikov'
/

COMMENT ON COLUMN ASU.TDISTRICT_NAME.FC_NAME IS 'Наименование участка'
/

COMMENT ON COLUMN ASU.TDISTRICT_NAME.FC_DESCRIPTION IS 'Описание участка (комментарий)'
/

COMMENT ON COLUMN ASU.TDISTRICT_NAME.FK_SOTR IS 'Терапевт (TSOTR.FK_ID)'
/

COMMENT ON COLUMN ASU.TDISTRICT_NAME.FK_THERPOINT IS 'Старый FK_ID'
/

COMMENT ON COLUMN ASU.TDISTRICT_NAME.FK_VRACHKAB IS 'TVRACHKAB.FK_ID (При добавлении участка добавляется осмотр участкового педиатраи кабинет FC_NAME)'
/

COMMENT ON COLUMN ASU.TDISTRICT_NAME.FC_CAR IS 'Есть ли автомобилль  1/0'
/

COMMENT ON COLUMN ASU.TDISTRICT_NAME.FC_WARE IS 'Оборудован ли участок 1/0'
/

COMMENT ON COLUMN ASU.TDISTRICT_NAME.FN_S_CAB IS 'Площадь кабинета'
/

COMMENT ON COLUMN ASU.TDISTRICT_NAME.FN_S_DR IS 'Площадь доп. помещений'
/

COMMENT ON COLUMN ASU.TDISTRICT_NAME.FK_TYPEID IS 'Тип участка из TSMID'
/

COMMENT ON COLUMN ASU.TDISTRICT_NAME.FK_LPUID IS 'ID ЛПУ'
/


--
-- TDISTRICT_NAME_PK  (Index) 
--
--  Dependencies: 
--   TDISTRICT_NAME (Table)
--
CREATE UNIQUE INDEX ASU.TDISTRICT_NAME_PK ON ASU.TDISTRICT_NAME
(FK_ID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- TDISTRICT_NAME_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   TDISTRICT_NAME (Table)
--
CREATE OR REPLACE TRIGGER ASU."TDISTRICT_NAME_BEFORE_INSERT" 
BEFORE INSERT 
ON ASU.TDISTRICT_NAME REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN
 IF :NEW.FK_ID IS NULL THEN
  SELECT ASU.SEQ_TDISTRICT_NAME.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
 END IF;
END;
/
SHOW ERRORS;


-- 
-- Non Foreign Key Constraints for Table TDISTRICT_NAME 
-- 
ALTER TABLE ASU.TDISTRICT_NAME ADD (
  CONSTRAINT TDISTRICT_NAME_PK
 PRIMARY KEY
 (FK_ID)
    USING INDEX 
    TABLESPACE USR
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ))
/

