ALTER TABLE ASU.TDISPGROUPNAZLISTPERIOD
 DROP PRIMARY KEY CASCADE
/

DROP TABLE ASU.TDISPGROUPNAZLISTPERIOD CASCADE CONSTRAINTS
/

--
-- TDISPGROUPNAZLISTPERIOD  (Table) 
--
CREATE TABLE ASU.TDISPGROUPNAZLISTPERIOD
(
  FK_ID                  NUMBER                 NOT NULL,
  FK_DISPGROUPNAZLISTID  NUMBER,
  FD_BEGIN               DATE,
  FD_END                 DATE
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON COLUMN ASU.TDISPGROUPNAZLISTPERIOD.FK_DISPGROUPNAZLISTID IS 'TDispgroupnazlist.FK_ID'
/

COMMENT ON COLUMN ASU.TDISPGROUPNAZLISTPERIOD.FD_BEGIN IS 'Начало лействия периода (>=)'
/

COMMENT ON COLUMN ASU.TDISPGROUPNAZLISTPERIOD.FD_END IS 'Окончание действия периода (<=)'
/


--
-- TDISPGROUPNAZLISTPERIOD_ID  (Index) 
--
--  Dependencies: 
--   TDISPGROUPNAZLISTPERIOD (Table)
--
CREATE UNIQUE INDEX ASU.TDISPGROUPNAZLISTPERIOD_ID ON ASU.TDISPGROUPNAZLISTPERIOD
(FK_ID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- TDISPGROUPNAZLISTPERIOD_BI  (Trigger) 
--
--  Dependencies: 
--   TDISPGROUPNAZLISTPERIOD (Table)
--
CREATE OR REPLACE TRIGGER ASU."TDISPGROUPNAZLISTPERIOD_BI" 
BEFORE INSERT
ON ASU.TDISPGROUPNAZLISTPERIOD REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
Begin
  SELECT SEQ_TDISPGROUPNAZLISTPERIOD.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


-- 
-- Non Foreign Key Constraints for Table TDISPGROUPNAZLISTPERIOD 
-- 
ALTER TABLE ASU.TDISPGROUPNAZLISTPERIOD ADD (
  CONSTRAINT TDISPGROUPNAZLISTPERIOD_ID
 PRIMARY KEY
 (FK_ID)
    USING INDEX 
    TABLESPACE USR
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ))
/

