DROP TABLE ASU.TEXCHUPLOAD_TMP CASCADE CONSTRAINTS
/

--
-- TEXCHUPLOAD_TMP  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE ASU.TEXCHUPLOAD_TMP
(
  FK_PACID       NUMBER,
  FK_INSURDOCID  NUMBER,
  FK_COMPANYID   NUMBER,
  FK_REGIONID    NUMBER,
  FK_TALONID     NUMBER,
  FK_PEPLID      NUMBER,
  FP_POLY        NUMBER,
  FK_ADRID       NUMBER
)
ON COMMIT PRESERVE ROWS
NOCACHE
/

COMMENT ON TABLE ASU.TEXCHUPLOAD_TMP IS 'Временная таблица №1 для выгрузки страховых данных -- Created 20080401 by Linnikov'
/

COMMENT ON COLUMN ASU.TEXCHUPLOAD_TMP.FK_PACID IS 'TKARTA.FK_ID'
/

COMMENT ON COLUMN ASU.TEXCHUPLOAD_TMP.FK_INSURDOCID IS 'TINSURDOCS.FK_ID'
/

COMMENT ON COLUMN ASU.TEXCHUPLOAD_TMP.FK_COMPANYID IS 'TCOMPANY.FK_ID'
/

COMMENT ON COLUMN ASU.TEXCHUPLOAD_TMP.FK_REGIONID IS 'TREGION.FK_ID'
/

COMMENT ON COLUMN ASU.TEXCHUPLOAD_TMP.FK_TALONID IS 'TAMBTALON.FK_ID'
/

COMMENT ON COLUMN ASU.TEXCHUPLOAD_TMP.FK_PEPLID IS 'TPEOPLES.FK_ID'
/

COMMENT ON COLUMN ASU.TEXCHUPLOAD_TMP.FP_POLY IS '0 - стационар, 1 - поликлиника'
/

COMMENT ON COLUMN ASU.TEXCHUPLOAD_TMP.FK_ADRID IS 'TADRESS.FK_ID'
/


--
-- TEXCHUPLOAD_TMP_IDX  (Index) 
--
--  Dependencies: 
--   TEXCHUPLOAD_TMP (Table)
--
CREATE INDEX ASU.TEXCHUPLOAD_TMP_IDX ON ASU.TEXCHUPLOAD_TMP
(FK_INSURDOCID, FK_PACID, FK_ADRID, FK_TALONID)
/


