ALTER TABLE ASU.TGARANTLETTERS_PEOPLES
 DROP PRIMARY KEY CASCADE
/

DROP TABLE ASU.TGARANTLETTERS_PEOPLES CASCADE CONSTRAINTS
/

--
-- TGARANTLETTERS_PEOPLES  (Table) 
--
CREATE TABLE ASU.TGARANTLETTERS_PEOPLES
(
  FK_ID      NUMBER                             NOT NULL,
  FK_PEOPLE  NUMBER,
  FK_LETTER  NUMBER
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TGARANTLETTERS_PEOPLES IS 'Связка гарантийных писем и пиплов A.Nakorjakov 070804'
/

COMMENT ON COLUMN ASU.TGARANTLETTERS_PEOPLES.FK_ID IS 'SEQUENCE=[SEQ_TGARANTLETTERS_PEOPLES]'
/

COMMENT ON COLUMN ASU.TGARANTLETTERS_PEOPLES.FK_PEOPLE IS 'TPEOPLES.FK_ID'
/

COMMENT ON COLUMN ASU.TGARANTLETTERS_PEOPLES.FK_LETTER IS 'TGARANTLETTERS.FK_ID'
/


--
-- PK_GARANTLETTERS_PEOPLES  (Index) 
--
--  Dependencies: 
--   TGARANTLETTERS_PEOPLES (Table)
--
CREATE UNIQUE INDEX ASU.PK_GARANTLETTERS_PEOPLES ON ASU.TGARANTLETTERS_PEOPLES
(FK_ID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- TGARANTLETTERS_PEOPLES_BEFORE_  (Trigger) 
--
--  Dependencies: 
--   TGARANTLETTERS_PEOPLES (Table)
--
CREATE OR REPLACE TRIGGER ASU."TGARANTLETTERS_PEOPLES_BEFORE_" 
 BEFORE
 INSERT
 ON ASU.TGARANTLETTERS_PEOPLES  REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
BEGIN
  SELECT SEQ_TGARANTLETTERS_PEOPLES.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
END;
/
SHOW ERRORS;


-- 
-- Non Foreign Key Constraints for Table TGARANTLETTERS_PEOPLES 
-- 
ALTER TABLE ASU.TGARANTLETTERS_PEOPLES ADD (
  CONSTRAINT PK_GARANTLETTERS_PEOPLES
 PRIMARY KEY
 (FK_ID)
    USING INDEX 
    TABLESPACE USR
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ))
/

