DROP TABLE ASU.TGRAPH_SHABLON CASCADE CONSTRAINTS
/

--
-- TGRAPH_SHABLON  (Table) 
--
CREATE TABLE ASU.TGRAPH_SHABLON
(
  FK_ID          NUMBER,
  FK_SOTR        NUMBER,
  FC_NAME        VARCHAR2(50 BYTE),
  FN_PERIOD      NUMBER,
  FC_COMMENT     VARCHAR2(250 BYTE),
  FN_TYPEPERIOD  NUMBER,
  FK_PARAMID     NUMBER,
  FN_TYPE        NUMBER
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
PARALLEL ( DEGREE DEFAULT INSTANCES DEFAULT )
MONITORING
/

COMMENT ON TABLE ASU.TGRAPH_SHABLON IS 'Шаблоны расписаний '
/

COMMENT ON COLUMN ASU.TGRAPH_SHABLON.FK_ID IS 'SEQUENCE=[SEQ_TGRAPH_SHABLON]'
/

COMMENT ON COLUMN ASU.TGRAPH_SHABLON.FK_SOTR IS 'TSOTR.FK_ID'
/

COMMENT ON COLUMN ASU.TGRAPH_SHABLON.FC_NAME IS 'Наименование шаблона'
/

COMMENT ON COLUMN ASU.TGRAPH_SHABLON.FN_PERIOD IS 'Период (в днях)'
/

COMMENT ON COLUMN ASU.TGRAPH_SHABLON.FC_COMMENT IS 'Комментарии'
/

COMMENT ON COLUMN ASU.TGRAPH_SHABLON.FN_TYPEPERIOD IS '0- недели ,1 - дни'
/

COMMENT ON COLUMN ASU.TGRAPH_SHABLON.FK_PARAMID IS 'Пока это ID врача'
/

COMMENT ON COLUMN ASU.TGRAPH_SHABLON.FN_TYPE IS 'Тип шаболна, на врача или на связку кабинет/врач. Сcылется на TSMID.FK_ID'
/


--
-- TGRAPH_SHABLON$FK_SOTR  (Index) 
--
--  Dependencies: 
--   TGRAPH_SHABLON (Table)
--
CREATE INDEX ASU.TGRAPH_SHABLON$FK_SOTR ON ASU.TGRAPH_SHABLON
(FK_SOTR)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- TGRAPH_SHABLON_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   TGRAPH_SHABLON (Table)
--
CREATE OR REPLACE TRIGGER ASU."TGRAPH_SHABLON_BEFORE_INSERT" 
BEFORE INSERT 
ON tgraph_shablon
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
Begin
select seq_tgraph_shablon.nextval into :new.fk_id from dual;
End;
/
SHOW ERRORS;


