DROP TABLE ASU.THEAL_SLOGN CASCADE CONSTRAINTS
/

--
-- THEAL_SLOGN  (Table) 
--
CREATE TABLE ASU.THEAL_SLOGN
(
  FK_ID       NUMBER                            NOT NULL,
  FK_HEAL     NUMBER,
  FK_SUBHEAL  NUMBER
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.THEAL_SLOGN IS 'составные услуги Author: Melnikov 2016.01.27'
/


--
-- THEAL_SLOGN_BI  (Trigger) 
--
--  Dependencies: 
--   THEAL_SLOGN (Table)
--
CREATE OR REPLACE TRIGGER ASU.THEAL_SLOGN_BI
 BEFORE INSERT
 ON ASU.THEAL_SLOGN REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
 IF :NEW.FK_ID IS NULL THEN
    SELECT ASU.SEQ_THEAL_SLOGN.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
 END IF;
END;
/
SHOW ERRORS;


