DROP TABLE ASU.THONORARY_STANDART CASCADE CONSTRAINTS
/

--
-- THONORARY_STANDART  (Table) 
--
CREATE TABLE ASU.THONORARY_STANDART
(
  FK_ID          NUMBER,
  FK_STANDARTID  NUMBER,
  FK_COMPANYID   NUMBER,
  FD_DATE1       DATE,
  FD_DATE2       DATE
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.THONORARY_STANDART IS 'Неоплачиваемые стандарты by Serg 20060728'
/

COMMENT ON COLUMN ASU.THONORARY_STANDART.FK_ID IS 'SEQUENCE=[SEQ_THONORARY_STANDART]'
/

COMMENT ON COLUMN ASU.THONORARY_STANDART.FK_STANDARTID IS 'Код стандарта на который завязан неоплачиваемый диагноз'
/

COMMENT ON COLUMN ASU.THONORARY_STANDART.FK_COMPANYID IS 'Код компании'
/

COMMENT ON COLUMN ASU.THONORARY_STANDART.FD_DATE1 IS 'Начало действия'
/

COMMENT ON COLUMN ASU.THONORARY_STANDART.FD_DATE2 IS 'Окончание действия'
/


--
-- THONORARY_STAND_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   THONORARY_STANDART (Table)
--
CREATE OR REPLACE TRIGGER ASU."THONORARY_STAND_BEFORE_INSERT" 
  BEFORE INSERT
  ON ASU.THONORARY_STANDART   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
Begin
  SELECT SEQ_THONORARY_STANDART.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


