DROP TABLE ASU.TINSURCOMPANY CASCADE CONSTRAINTS
/

--
-- TINSURCOMPANY  (Table) 
--
CREATE TABLE ASU.TINSURCOMPANY
(
  FK_ID    NUMBER                               NOT NULL,
  FC_NAME  VARCHAR2(255 BYTE)
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON COLUMN ASU.TINSURCOMPANY.FK_ID IS 'SEQUENCE=[SEQ_TINSURCOMPANY]'
/

COMMENT ON COLUMN ASU.TINSURCOMPANY.FC_NAME IS 'Наименование страховой компании'
/


--
-- TINSURCOMPANY_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   TINSURCOMPANY (Table)
--
CREATE OR REPLACE TRIGGER ASU."TINSURCOMPANY_BEFORE_INSERT" 
  BEFORE INSERT
  ON ASU.TINSURCOMPANY   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
Begin
  SELECT SEQ_TINSURCOMPANY.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


