ALTER TABLE ASU.TIS_RESETTLEMENT_ASSIST
 DROP PRIMARY KEY CASCADE
/

DROP TABLE ASU.TIS_RESETTLEMENT_ASSIST CASCADE CONSTRAINTS
/

--
-- TIS_RESETTLEMENT_ASSIST  (Table) 
--
--  Dependencies: 
--   TIS_RESETTLEMENT (Table)
--
CREATE TABLE ASU.TIS_RESETTLEMENT_ASSIST
(
  FK_ID                  NUMBER                 NOT NULL,
  FK_ASSISTTYPEID        NUMBER,
  FN_ASSISTNORMATIVE     NUMBER(15,2),
  FN_ASSISTRECOURSE      NUMBER,
  FN_ASSISTAMOUNT        NUMBER(15,2),
  FK_IS_RESETTLEMENT_ID  NUMBER
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


--
-- PK_TIS_RESSETLEMENT_ASSIST  (Index) 
--
--  Dependencies: 
--   TIS_RESETTLEMENT_ASSIST (Table)
--
CREATE UNIQUE INDEX ASU.PK_TIS_RESSETLEMENT_ASSIST ON ASU.TIS_RESETTLEMENT_ASSIST
(FK_ID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- TIS_RESETTLEMENT_ASSIST_BI  (Trigger) 
--
--  Dependencies: 
--   TIS_RESETTLEMENT_ASSIST (Table)
--
CREATE OR REPLACE TRIGGER ASU.TIS_RESETTLEMENT_ASSIST_BI
  BEFORE INSERT
  ON "ASU"."TIS_RESETTLEMENT_ASSIST"
  REFERENCING OLD AS OLD NEW AS NEW
  FOR EACH ROW
BEGIN
  IF :NEW.fk_id IS NULL
  THEN
    SELECT asu.seq_TIS_RESETTLEMENT_ASSIST.NEXTVAL
      INTO :NEW.fk_id
      FROM DUAL;
  END IF;
END;
/
SHOW ERRORS;


-- 
-- Non Foreign Key Constraints for Table TIS_RESETTLEMENT_ASSIST 
-- 
ALTER TABLE ASU.TIS_RESETTLEMENT_ASSIST ADD (
  CONSTRAINT PK_TIS_RESSETLEMENT_ASSIST
 PRIMARY KEY
 (FK_ID)
    USING INDEX 
    TABLESPACE USR
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ))
/

-- 
-- Foreign Key Constraints for Table TIS_RESETTLEMENT_ASSIST 
-- 
ALTER TABLE ASU.TIS_RESETTLEMENT_ASSIST ADD (
  CONSTRAINT FK_TIS_RESS_REFERENCE_TIS_RESS 
 FOREIGN KEY (FK_IS_RESETTLEMENT_ID) 
 REFERENCES ASU.TIS_RESETTLEMENT (FK_ID))
/

