ALTER TABLE ASU.TIS_DISP_POPULDATA_IND_RISK
 DROP PRIMARY KEY CASCADE
/

DROP TABLE ASU.TIS_DISP_POPULDATA_IND_RISK CASCADE CONSTRAINTS
/

--
-- TIS_DISP_POPULDATA_IND_RISK  (Table) 
--
--  Dependencies: 
--   TIS_DISP_POPULDATA_INDICATOR (Table)
--
CREATE TABLE ASU.TIS_DISP_POPULDATA_IND_RISK
(
  FK_ID                        NUMBER           NOT NULL,
  FK_RISKCODEID                NUMBER,
  FN_PEOPLECOUNT               NUMBER,
  FN_DISPSUPERVISIONDOCTOR     NUMBER,
  FN_DISPSUPERVISIONCENTER     NUMBER,
  FK_IS_DISP_POPULDATA_IND_ID  NUMBER
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


--
-- PK_TIS_DISP_POPULDATA_IND_RIS3  (Index) 
--
--  Dependencies: 
--   TIS_DISP_POPULDATA_IND_RISK (Table)
--
CREATE UNIQUE INDEX ASU.PK_TIS_DISP_POPULDATA_IND_RIS3 ON ASU.TIS_DISP_POPULDATA_IND_RISK
(FK_ID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- TIS_DISP_POPULDATA_IND_RISK_BI  (Trigger) 
--
--  Dependencies: 
--   TIS_DISP_POPULDATA_IND_RISK (Table)
--
CREATE OR REPLACE TRIGGER ASU.TIS_DISP_POPULDATA_IND_RISK_BI
  BEFORE INSERT
  ON ASU.TIS_DISP_POPULDATA_IND_RISK   REFERENCING OLD AS OLD NEW AS NEW
  FOR EACH ROW
BEGIN
  IF :NEW.fk_id IS NULL
  THEN
    SELECT asu.seq_TIS_DISP_POPULDATA_IND_RIS.NEXTVAL
      INTO :NEW.fk_id
      FROM DUAL;
  END IF;
END;
/
SHOW ERRORS;


-- 
-- Non Foreign Key Constraints for Table TIS_DISP_POPULDATA_IND_RISK 
-- 
ALTER TABLE ASU.TIS_DISP_POPULDATA_IND_RISK ADD (
  CONSTRAINT PK_TIS_DISP_POPULDATA_IND_RIS3
 PRIMARY KEY
 (FK_ID)
    USING INDEX 
    TABLESPACE USR
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ))
/

-- 
-- Foreign Key Constraints for Table TIS_DISP_POPULDATA_IND_RISK 
-- 
ALTER TABLE ASU.TIS_DISP_POPULDATA_IND_RISK ADD (
  CONSTRAINT FK_TIS_DISP_REFERENCE_TIS_DIS6 
 FOREIGN KEY (FK_IS_DISP_POPULDATA_IND_ID) 
 REFERENCES ASU.TIS_DISP_POPULDATA_INDICATOR (FK_ID))
/

