DROP TABLE ASU.TISSLRAZDROWS CASCADE CONSTRAINTS
/

--
-- TISSLRAZDROWS  (Table) 
--
CREATE TABLE ASU.TISSLRAZDROWS
(
  FK_ID     NUMBER(9)                           DEFAULT -1,
  FC_NAME   VARCHAR2(200 BYTE),
  FN_ORDER  NUMBER(4)                           DEFAULT 0,
  FK_SMID   NUMBER(9)                           DEFAULT -1
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TISSLRAZDROWS IS 'Таблица показываемых колонок в отчете о проведенных исследованиях'
/

COMMENT ON COLUMN ASU.TISSLRAZDROWS.FK_ID IS 'SEQUENCE=[SEQ_TISSLRAZDROWS]'
/

COMMENT ON COLUMN ASU.TISSLRAZDROWS.FC_NAME IS 'Наименование'
/

COMMENT ON COLUMN ASU.TISSLRAZDROWS.FN_ORDER IS 'Порядок'
/

COMMENT ON COLUMN ASU.TISSLRAZDROWS.FK_SMID IS 'Код по TSMID'
/


--
-- TISSLRAZDROWS_BY_ID  (Index) 
--
--  Dependencies: 
--   TISSLRAZDROWS (Table)
--
CREATE UNIQUE INDEX ASU.TISSLRAZDROWS_BY_ID ON ASU.TISSLRAZDROWS
(FK_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- TISSLRAZDROWS_BY_ID_ORDER  (Index) 
--
--  Dependencies: 
--   TISSLRAZDROWS (Table)
--
CREATE UNIQUE INDEX ASU.TISSLRAZDROWS_BY_ID_ORDER ON ASU.TISSLRAZDROWS
(FK_ID, FN_ORDER)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- TOSSLRAZDROWS_BY_ID_SMID  (Index) 
--
--  Dependencies: 
--   TISSLRAZDROWS (Table)
--
CREATE UNIQUE INDEX ASU.TOSSLRAZDROWS_BY_ID_SMID ON ASU.TISSLRAZDROWS
(FK_ID, FK_SMID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- TISSLRAZDROWS_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   TISSLRAZDROWS (Table)
--
CREATE OR REPLACE TRIGGER ASU."TISSLRAZDROWS_BEFORE_INSERT" 
BEFORE  INSERT  ON ASU.TISSLRAZDROWS REFERENCING
 NEW AS NEW
 OLD AS OLD
FOR EACH ROW
Begin
  SELECT SEQ_TISSLRAZDROWS.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


--
-- TISSLRAZDROWS_AFTER_DELETE  (Trigger) 
--
--  Dependencies: 
--   TISSLRAZDROWS (Table)
--
CREATE OR REPLACE TRIGGER ASU."TISSLRAZDROWS_AFTER_DELETE" 
AFTER  DELETE  ON ASU.TISSLRAZDROWS REFERENCING
 NEW AS NEW
 OLD AS OLD
FOR EACH ROW
Begin
  DELETE FROM TISSLRAZDDEPS WHERE FK_ROWID=:OLD.FK_ID;
End;
/
SHOW ERRORS;


