DROP TABLE ASU.TKARTASOOTVETBYCHECKPACDATA CASCADE CONSTRAINTS
/

--
-- TKARTASOOTVETBYCHECKPACDATA  (Table) 
--
CREATE TABLE ASU.TKARTASOOTVETBYCHECKPACDATA
(
  FK_FROMPACID  NUMBER,
  FK_TOPACID    NUMBER,
  FD_FROMTO     DATE                            DEFAULT SYSDATE
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TKARTASOOTVETBYCHECKPACDATA IS 'Таблица соответствия, когда карта создавалась из модуля дозаполнение инфы author:Marriage'
/

COMMENT ON COLUMN ASU.TKARTASOOTVETBYCHECKPACDATA.FK_FROMPACID IS 'Из какой карты создавали'
/

COMMENT ON COLUMN ASU.TKARTASOOTVETBYCHECKPACDATA.FK_TOPACID IS 'Какая карта создалась'
/

COMMENT ON COLUMN ASU.TKARTASOOTVETBYCHECKPACDATA.FD_FROMTO IS 'Когда зафигачили'
/


