DROP TABLE ASU.TLABSORTREG CASCADE CONSTRAINTS
/

--
-- TLABSORTREG  (Table) 
--
CREATE TABLE ASU.TLABSORTREG
(
  FK_LABREG  NUMBER,
  FK_LABLOT  NUMBER
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


