ALTER TABLE ASU.TLABREPTEST_INISMID
 DROP PRIMARY KEY CASCADE
/

DROP TABLE ASU.TLABREPTEST_INISMID CASCADE CONSTRAINTS
/

--
-- TLABREPTEST_INISMID  (Table) 
--
CREATE TABLE ASU.TLABREPTEST_INISMID
(
  FK_ID          INTEGER                        NOT NULL,
  FK_LABREPNAME  INTEGER                        NOT NULL,
  FK_SMID        INTEGER                        NOT NULL
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TLABREPTEST_INISMID IS 'Наборы значений к настрйкам по отчету "Журнал зарегистрированных проб"
Author: Ura'
/

COMMENT ON COLUMN ASU.TLABREPTEST_INISMID.FK_ID IS 'SEQUENCE=[SEQ_TLABREPTEST]'
/

COMMENT ON COLUMN ASU.TLABREPTEST_INISMID.FK_LABREPNAME IS 'TLABREPTEST_ININAME.FK_ID'
/

COMMENT ON COLUMN ASU.TLABREPTEST_INISMID.FK_SMID IS 'TSMID.FK_ID'
/


--
-- IX_TLABREPTESTINISM_FK_SMID  (Index) 
--
--  Dependencies: 
--   TLABREPTEST_INISMID (Table)
--
CREATE INDEX ASU.IX_TLABREPTESTINISM_FK_SMID ON ASU.TLABREPTEST_INISMID
(FK_SMID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- IX_TLABREPTEST_IS_FK_LABREPNAM  (Index) 
--
--  Dependencies: 
--   TLABREPTEST_INISMID (Table)
--
CREATE INDEX ASU.IX_TLABREPTEST_IS_FK_LABREPNAM ON ASU.TLABREPTEST_INISMID
(FK_LABREPNAME)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- PK_TLABREPTEST_INISMID  (Index) 
--
--  Dependencies: 
--   TLABREPTEST_INISMID (Table)
--
CREATE UNIQUE INDEX ASU.PK_TLABREPTEST_INISMID ON ASU.TLABREPTEST_INISMID
(FK_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- TLABREPTEST_INISMID_BEFORE_INS  (Trigger) 
--
--  Dependencies: 
--   TLABREPTEST_INISMID (Table)
--
CREATE OR REPLACE TRIGGER ASU."TLABREPTEST_INISMID_BEFORE_INS" 
 BEFORE
  INSERT
 ON tlabreptest_inismid
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
  IF :NEW.FK_ID IS NULL THEN
    SELECT  SEQ_TLABREPTEST.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
  END IF;
END;
/
SHOW ERRORS;


-- 
-- Non Foreign Key Constraints for Table TLABREPTEST_INISMID 
-- 
ALTER TABLE ASU.TLABREPTEST_INISMID ADD (
  CONSTRAINT PK_TLABREPTEST_INISMID
 PRIMARY KEY
 (FK_ID)
    USING INDEX 
    TABLESPACE INDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          128K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ))
/

