DROP TABLE ASU.TLAB_PCR_REGIST CASCADE CONSTRAINTS
/

--
-- TLAB_PCR_REGIST  (Table) 
--
CREATE TABLE ASU.TLAB_PCR_REGIST
(
  FK_ID      NUMBER,
  FK_SOTRID  NUMBER,
  FD_REGIST  DATE,
  FK_LOTID   NUMBER,
  FN_PLACE   NUMBER,
  FK_NAZID   NUMBER,
  FN_SOS     NUMBER                             DEFAULT 0
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TLAB_PCR_REGIST IS 'ПЦР Лаборатория. Регистрация проб.'
/

COMMENT ON COLUMN ASU.TLAB_PCR_REGIST.FK_ID IS 'ID'
/

COMMENT ON COLUMN ASU.TLAB_PCR_REGIST.FK_SOTRID IS 'TSOTR.FK_ID сотрудник '
/

COMMENT ON COLUMN ASU.TLAB_PCR_REGIST.FD_REGIST IS 'Дата регистрации'
/

COMMENT ON COLUMN ASU.TLAB_PCR_REGIST.FK_LOTID IS 'TLAB_PCR_LOT.FK_ID'
/

COMMENT ON COLUMN ASU.TLAB_PCR_REGIST.FN_PLACE IS 'Номер ячейки'
/

COMMENT ON COLUMN ASU.TLAB_PCR_REGIST.FK_NAZID IS 'TNAZNAN.FK_ID'
/

COMMENT ON COLUMN ASU.TLAB_PCR_REGIST.FN_SOS IS '0 - В ячейке, 1 - отработан'
/


--
-- TLAB_PCR_REGIST_BY_NAZID  (Index) 
--
--  Dependencies: 
--   TLAB_PCR_REGIST (Table)
--
CREATE UNIQUE INDEX ASU.TLAB_PCR_REGIST_BY_NAZID ON ASU.TLAB_PCR_REGIST
(FK_NAZID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


