DROP TABLE ASU.TLAB_PCR_SOURCE_VIDEL CASCADE CONSTRAINTS
/

--
-- TLAB_PCR_SOURCE_VIDEL  (Table) 
--
CREATE TABLE ASU.TLAB_PCR_SOURCE_VIDEL
(
  FK_ID        NUMBER,
  FK_SOURCEID  NUMBER,
  FK_VIDELID   NUMBER
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON COLUMN ASU.TLAB_PCR_SOURCE_VIDEL.FK_ID IS 'ID'
/

COMMENT ON COLUMN ASU.TLAB_PCR_SOURCE_VIDEL.FK_SOURCEID IS 'TSMID.FK_ID типы материалов'
/

COMMENT ON COLUMN ASU.TLAB_PCR_SOURCE_VIDEL.FK_VIDELID IS 'TSMID.FK_ID типы выделений'
/


