ALTER TABLE ASU.TLECHPARAM
 DROP PRIMARY KEY CASCADE
/

DROP TABLE ASU.TLECHPARAM CASCADE CONSTRAINTS
/

--
-- TLECHPARAM  (Table) 
--
CREATE TABLE ASU.TLECHPARAM
(
  FK_ID       NUMBER(9)                         NOT NULL,
  FK_SMID     NUMBER(9)                         NOT NULL,
  FC_NAME     VARCHAR2(250 BYTE),
  FC_TYPE     VARCHAR2(20 BYTE),
  FC_DEFAULT  VARCHAR2(100 BYTE),
  FK_OWNER    NUMBER(9),
  FK_DEFAULT  NUMBER(9)
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TLECHPARAM IS 'Параметры для назначения'
/

COMMENT ON COLUMN ASU.TLECHPARAM.FK_ID IS 'SEQUENCE=[SEQ_TLECHPARAM]'
/

COMMENT ON COLUMN ASU.TLECHPARAM.FK_SMID IS 'кому принадлежит параметр в TSMID'
/

COMMENT ON COLUMN ASU.TLECHPARAM.FC_NAME IS 'название'
/

COMMENT ON COLUMN ASU.TLECHPARAM.FC_TYPE IS 'тип'
/

COMMENT ON COLUMN ASU.TLECHPARAM.FC_DEFAULT IS 'значение по умолчанию'
/

COMMENT ON COLUMN ASU.TLECHPARAM.FK_OWNER IS 'дерево'
/

COMMENT ON COLUMN ASU.TLECHPARAM.FK_DEFAULT IS 'ссылка на tlechshablon'
/


--
-- TLECHPARAM#ID  (Index) 
--
--  Dependencies: 
--   TLECHPARAM (Table)
--
CREATE UNIQUE INDEX ASU.TLECHPARAM#ID ON ASU.TLECHPARAM
(FK_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- TLECHPARAM_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   TLECHPARAM (Table)
--
CREATE OR REPLACE TRIGGER ASU."TLECHPARAM_BEFORE_INSERT" 
BEFORE INSERT
ON ASU.TLECHPARAM REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
begin
 SELECT SEQ_TLECHPARAM.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
END;
/
SHOW ERRORS;


-- 
-- Non Foreign Key Constraints for Table TLECHPARAM 
-- 
ALTER TABLE ASU.TLECHPARAM ADD (
  CONSTRAINT TLECHPARAM#ID
 PRIMARY KEY
 (FK_ID)
    USING INDEX 
    TABLESPACE INDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          128K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ))
/

