ALTER TABLE ASU.TLECHSHABLON
 DROP PRIMARY KEY CASCADE
/

DROP TABLE ASU.TLECHSHABLON CASCADE CONSTRAINTS
/

--
-- TLECHSHABLON  (Table) 
--
--  Dependencies: 
--   TLECHPARAM (Table)
--
CREATE TABLE ASU.TLECHSHABLON
(
  FK_ID           NUMBER(9)                     NOT NULL,
  FK_SMID         NUMBER(9),
  FK_LECHPARAM    NUMBER(9),
  FK_VALUEID      NUMBER(9),
  FC_VALUE        VARCHAR2(4000 BYTE),
  FN_VALUE        NUMBER(9),
  FK_VRACHID      NUMBER(9),
  FC_NAME         VARCHAR2(100 BYTE),
  FK_SHABLONNAME  NUMBER(9)
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON COLUMN ASU.TLECHSHABLON.FK_ID IS 'SEQUENCE=[SEQ_TLECHSHABLON]'
/

COMMENT ON COLUMN ASU.TLECHSHABLON.FK_SMID IS 'Код SMID'
/

COMMENT ON COLUMN ASU.TLECHSHABLON.FK_LECHPARAM IS 'Код параметра'
/

COMMENT ON COLUMN ASU.TLECHSHABLON.FK_VALUEID IS 'Код значения'
/

COMMENT ON COLUMN ASU.TLECHSHABLON.FC_VALUE IS 'Значение'
/

COMMENT ON COLUMN ASU.TLECHSHABLON.FN_VALUE IS 'Значение'
/

COMMENT ON COLUMN ASU.TLECHSHABLON.FK_VRACHID IS 'Врач'
/

COMMENT ON COLUMN ASU.TLECHSHABLON.FC_NAME IS 'Название'
/

COMMENT ON COLUMN ASU.TLECHSHABLON.FK_SHABLONNAME IS 'код имени шаблона'
/


--
-- TLECHSHABLON#ID  (Index) 
--
--  Dependencies: 
--   TLECHSHABLON (Table)
--
CREATE UNIQUE INDEX ASU.TLECHSHABLON#ID ON ASU.TLECHSHABLON
(FK_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- TLECHSHABLON_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   TLECHSHABLON (Table)
--
CREATE OR REPLACE TRIGGER ASU."TLECHSHABLON_BEFORE_INSERT" 
BEFORE INSERT
ON ASU.TLECHSHABLON REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
begin
 SELECT SEQ_TLECHSHABLON.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
END;
/
SHOW ERRORS;


-- 
-- Non Foreign Key Constraints for Table TLECHSHABLON 
-- 
ALTER TABLE ASU.TLECHSHABLON ADD (
  CONSTRAINT TLECHSHABLON#ID
 PRIMARY KEY
 (FK_ID)
    USING INDEX 
    TABLESPACE INDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          128K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ))
/

-- 
-- Foreign Key Constraints for Table TLECHSHABLON 
-- 
ALTER TABLE ASU.TLECHSHABLON ADD (
  CONSTRAINT TLECHSHABLON#PARAM 
 FOREIGN KEY (FK_LECHPARAM) 
 REFERENCES ASU.TLECHPARAM (FK_ID)
    ON DELETE CASCADE,
  CONSTRAINT TLECHSHABLON#VALUE 
 FOREIGN KEY (FK_VALUEID) 
 REFERENCES ASU.TLECHPARAM (FK_ID)
    ON DELETE CASCADE)
/

