DROP TABLE ASU.TLEVEL CASCADE CONSTRAINTS
/

--
-- TLEVEL  (Table) 
--
CREATE TABLE ASU.TLEVEL
(
  FK_ID     NUMBER(15),
  FC_NAME   VARCHAR2(30 BYTE),
  FK_PRIOR  NUMBER(1)
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          520K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TLEVEL IS 'Уровни доступа к пациентам by TimurLan'
/

COMMENT ON COLUMN ASU.TLEVEL.FK_ID IS 'SEQUENCE=[SEQ_TLEVEL]'
/

COMMENT ON COLUMN ASU.TLEVEL.FC_NAME IS 'Название'
/

COMMENT ON COLUMN ASU.TLEVEL.FK_PRIOR IS 'Код приоритета врача'
/


--
-- TLEVEL_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   TLEVEL (Table)
--
CREATE OR REPLACE TRIGGER ASU."TLEVEL_BEFORE_INSERT" 
  BEFORE INSERT
  ON ASU.TLEVEL   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
Begin
  SELECT SEQ_TLEVEL.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


