DROP TABLE ASU.TLIN_PAC_MONITOR CASCADE CONSTRAINTS
/

--
-- TLIN_PAC_MONITOR  (Table) 
--
CREATE TABLE ASU.TLIN_PAC_MONITOR
(
  FK_ID     NUMBER,
  FK_SMID   NUMBER,
  FN_VALUE  NUMBER,
  FK_INDEX  NUMBER,
  FC_VALUE  VARCHAR2(50 BYTE),
  FK_PACID  NUMBER,
  FD_DATE   DATE
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TLIN_PAC_MONITOR IS 'Лист интенсивного наблюдения (монитор основных показателей) Author: Neronov A.S.'
/

COMMENT ON COLUMN ASU.TLIN_PAC_MONITOR.FK_ID IS '[SEQ_TLIN_PAC_MONITOR]'
/

COMMENT ON COLUMN ASU.TLIN_PAC_MONITOR.FK_SMID IS 'TSMID.FK_ID - содержимое из ветки ''PAC_INDEXES'''
/

COMMENT ON COLUMN ASU.TLIN_PAC_MONITOR.FN_VALUE IS 'Числовое значение'
/

COMMENT ON COLUMN ASU.TLIN_PAC_MONITOR.FK_INDEX IS 'Индекс значения из комбобокса (ссылка на TSMID подветку из FK_SMID)'
/

COMMENT ON COLUMN ASU.TLIN_PAC_MONITOR.FC_VALUE IS 'Строковое значение'
/

COMMENT ON COLUMN ASU.TLIN_PAC_MONITOR.FK_PACID IS 'TKARTA.FK_ID - ID пациента'
/

COMMENT ON COLUMN ASU.TLIN_PAC_MONITOR.FD_DATE IS 'Дата и время'
/


--
-- TLIN_PAC_MONITOR_BY_DATE  (Index) 
--
--  Dependencies: 
--   TLIN_PAC_MONITOR (Table)
--
CREATE INDEX ASU.TLIN_PAC_MONITOR_BY_DATE ON ASU.TLIN_PAC_MONITOR
(FD_DATE)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- TLIN_PAC_MONITOR_BY_PACID  (Index) 
--
--  Dependencies: 
--   TLIN_PAC_MONITOR (Table)
--
CREATE INDEX ASU.TLIN_PAC_MONITOR_BY_PACID ON ASU.TLIN_PAC_MONITOR
(FK_PACID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- TLIN_PAC_MONITOR_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   TLIN_PAC_MONITOR (Table)
--
CREATE OR REPLACE TRIGGER ASU."TLIN_PAC_MONITOR_BEFORE_INSERT" 
 BEFORE
 INSERT
 ON ASU.TLIN_PAC_MONITOR  REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
BEGIN
    SELECT SEQ_TLIN_PAC_MONITOR.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
END;
/
SHOW ERRORS;


