DROP TABLE ASU.TLOGEXTNAZ CASCADE CONSTRAINTS
/

--
-- TLOGEXTNAZ  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE ASU.TLOGEXTNAZ
(
  FD_DATE       DATE,
  FK_OWNER      NUMBER,
  FC_USER       VARCHAR2(4000 BYTE),
  FC_FAM        VARCHAR2(4000 BYTE),
  FC_IM         VARCHAR2(4000 BYTE),
  FC_OTCH       VARCHAR2(4000 BYTE),
  FD_ROJD       DATE,
  FC_ISPOL_OLD  VARCHAR2(4000 BYTE),
  FD_NAZ_OLD    DATE,
  FD_RUN_OLD    DATE,
  FC_NAME_OLD   VARCHAR2(4000 BYTE),
  FC_SOS_OLD    VARCHAR2(4000 BYTE),
  FC_DIAGN_OLD  VARCHAR2(4000 BYTE),
  FC_DIAGP_OLD  VARCHAR2(4000 BYTE),
  FC_DIAGS_OLD  VARCHAR2(4000 BYTE),
  FC_DIAGZ_OLD  VARCHAR2(4000 BYTE),
  FC_ISPOL_NEW  VARCHAR2(4000 BYTE),
  FD_NAZ_NEW    DATE,
  FD_RUN_NEW    DATE,
  FC_NAME_NEW   VARCHAR2(4000 BYTE),
  FC_SOS_NEW    VARCHAR2(4000 BYTE),
  FC_DIAGN_NEW  VARCHAR2(4000 BYTE),
  FC_DIAGP_NEW  VARCHAR2(4000 BYTE),
  FC_DIAGS_NEW  VARCHAR2(4000 BYTE),
  FC_DIAGZ_NEW  VARCHAR2(4000 BYTE),
  FC_ACTION     VARCHAR2(4000 BYTE),
  FC_IDENT      VARCHAR2(4000 BYTE)
)
ON COMMIT PRESERVE ROWS
NOCACHE
/

COMMENT ON TABLE ASU.TLOGEXTNAZ IS '“аблица дл€ подробных логов по назначению'
/


