DROP TABLE ASU.TLOGEXTDIAG CASCADE CONSTRAINTS
/

--
-- TLOGEXTDIAG  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE ASU.TLOGEXTDIAG
(
  FD_DATE          DATE,
  FK_OWNER         NUMBER,
  FC_USER          VARCHAR2(4000 BYTE),
  FC_FAM           VARCHAR2(4000 BYTE),
  FC_IM            VARCHAR2(4000 BYTE),
  FC_OTCH          VARCHAR2(4000 BYTE),
  FD_ROJD          DATE,
  FK_SMDIAGID_OLD  VARCHAR2(4000 BYTE),
  FP_TYPE_OLD      VARCHAR2(4000 BYTE),
  FL_FIRST_OLD     VARCHAR2(4000 BYTE),
  FC_WRITE_OLD     VARCHAR2(3000 BYTE),
  FD_DATE_OLD      DATE,
  FK_VRACHID_OLD   VARCHAR2(4000 BYTE),
  FL_MAIN_OLD      VARCHAR2(4000 BYTE),
  FK_SMDIAGID_NEW  VARCHAR2(4000 BYTE),
  FP_TYPE_NEW      VARCHAR2(4000 BYTE),
  FL_FIRST_NEW     VARCHAR2(4000 BYTE),
  FC_WRITE_NEW     VARCHAR2(3000 BYTE),
  FD_DATE_NEW      DATE,
  FK_VRACHID_NEW   VARCHAR2(4000 BYTE),
  FL_MAIN_NEW      VARCHAR2(4000 BYTE),
  FC_ACTION        VARCHAR2(4000 BYTE),
  FC_IDENT         VARCHAR2(4000 BYTE)
)
ON COMMIT PRESERVE ROWS
NOCACHE
/

COMMENT ON TABLE ASU.TLOGEXTDIAG IS 'Таблица для подробных логов по Диагнозам'
/


