DROP TABLE ASU.TLOGEXTTALON CASCADE CONSTRAINTS
/

--
-- TLOGEXTTALON  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE ASU.TLOGEXTTALON
(
  FD_DATE               DATE,
  FK_OWNER              NUMBER,
  FC_USER               VARCHAR2(4000 BYTE),
  FC_FAM                VARCHAR2(4000 BYTE),
  FC_IM                 VARCHAR2(4000 BYTE),
  FC_OTCH               VARCHAR2(4000 BYTE),
  FD_ROJD               DATE,
  FD_OPENED_OLD         DATE,
  FN_SOS_OLD            VARCHAR2(4000 BYTE),
  FK_DIAGMAIN_OLD       VARCHAR2(4000 BYTE),
  FK_INSURANCEID_OLD    VARCHAR2(4000 BYTE),
  FK_RESULT_OLD         VARCHAR2(4000 BYTE),
  FK_DOPISHODID_OLD     VARCHAR2(4000 BYTE),
  FK_DIAGMAINPRED_OLD   VARCHAR2(4000 BYTE),
  FD_NAPRDATE_OLD       DATE,
  FC_NAPRNUM_OLD        VARCHAR2(4000 BYTE),
  FC_TALON_COMMENT_OLD  VARCHAR2(4000 BYTE),
  FD_OPENED_NEW         DATE,
  FN_SOS_NEW            VARCHAR2(4000 BYTE),
  FK_DIAGMAIN_NEW       VARCHAR2(4000 BYTE),
  FK_INSURANCEID_NEW    VARCHAR2(4000 BYTE),
  FK_RESULT_NEW         VARCHAR2(4000 BYTE),
  FK_DOPISHODID_NEW     VARCHAR2(4000 BYTE),
  FK_DIAGMAINPRED_NEW   VARCHAR2(4000 BYTE),
  FD_NAPRDATE_NEW       DATE,
  FC_NAPRNUM_NEW        VARCHAR2(4000 BYTE),
  FC_TALON_COMMENT_NEW  VARCHAR2(4000 BYTE),
  FC_ACTION             VARCHAR2(4000 BYTE),
  FC_IDENT              VARCHAR2(4000 BYTE)
)
ON COMMIT PRESERVE ROWS
NOCACHE
/

COMMENT ON TABLE ASU.TLOGEXTTALON IS 'Таблица для подробных логов по талона'
/


