DROP TABLE ASU.TMP_TSROKY_23092013 CASCADE CONSTRAINTS
/

--
-- TMP_TSROKY_23092013  (Table) 
--
CREATE TABLE ASU.TMP_TSROKY_23092013
(
  FK_ID        NUMBER(15),
  FK_PACID     NUMBER(15),
  FK_PRYB      NUMBER(1),
  FK_VYB       NUMBER(1),
  FN_KOL       NUMBER(3),
  FD_DATA1     DATE,
  FD_DATA2     DATE,
  FD_DATA3     DATE,
  FN_SUM       NUMBER,
  FK_OPLID     NUMBER(16),
  FL_BUH       NUMBER(15),
  FC_DOCUMENT  VARCHAR2(30 BYTE),
  FK_VYBID     NUMBER(15)
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


