DROP TABLE ASU.TMP_TPERESEL_23092013 CASCADE CONSTRAINTS
/

--
-- TMP_TPERESEL_23092013  (Table) 
--
CREATE TABLE ASU.TMP_TPERESEL_23092013
(
  FK_ID          NUMBER(15),
  FK_PALATAID    NUMBER(15),
  FK_PACID       NUMBER(15),
  FD_DATA1       DATE,
  FD_DATA2       DATE,
  FK_SROKID      NUMBER(15),
  FL_BUH         NUMBER,
  FK_KOYKAVIDID  NUMBER,
  FK_DOCOBSLID   NUMBER
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


