DROP TABLE ASU.TMP_SANKARTA CASCADE CONSTRAINTS
/

--
-- TMP_SANKARTA  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE ASU.TMP_SANKARTA
(
  FK_ID      NUMBER(9),
  FK_RAZDEL  NUMBER(9),
  FP_SELECT  NUMBER(1)                          DEFAULT 1,
  FC_NAME    VARCHAR2(100 BYTE)
)
ON COMMIT PRESERVE ROWS
NOCACHE
/

COMMENT ON COLUMN ASU.TMP_SANKARTA.FK_ID IS 'SEQUENCE=[SEQ_TNAZSOS]'
/


--
-- TMP_SANKARTA_BEFOR_INSERT  (Trigger) 
--
--  Dependencies: 
--   TMP_SANKARTA (Table)
--
CREATE OR REPLACE TRIGGER ASU."TMP_SANKARTA_BEFOR_INSERT" 
 BEFORE 
 INSERT
 ON ASU.TMP_SANKARTA  REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
begin
  select seq_tnazsos.nextval into :new.fk_id from dual;
end;
/
SHOW ERRORS;


