DROP TABLE ASU.TMP_TSTANDART_COST CASCADE CONSTRAINTS
/

--
-- TMP_TSTANDART_COST  (Table) 
--
CREATE TABLE ASU.TMP_TSTANDART_COST
(
  FK_ID          NUMBER                         NOT NULL,
  FK_STANDARTID  NUMBER,
  FD_DATE1       DATE,
  FD_DATE2       DATE,
  FN_COST        NUMBER,
  FK_COMPANYID   NUMBER,
  FN_COST2       NUMBER
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


