DROP TABLE ASU.TMP_PACAGES CASCADE CONSTRAINTS
/

--
-- TMP_PACAGES  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE ASU.TMP_PACAGES
(
  FK_PACID    NUMBER(9),
  FN_AGE      NUMBER,
  FP_RESLECH  NUMBER(1),
  FD_VYB      DATE,
  FK_VRACHID  NUMBER(9),
  FK_OTDID    NUMBER(9)
)
ON COMMIT PRESERVE ROWS
NOCACHE
/


--
-- TMP_PACAGES$AGE  (Index) 
--
--  Dependencies: 
--   TMP_PACAGES (Table)
--
CREATE INDEX ASU.TMP_PACAGES$AGE ON ASU.TMP_PACAGES
(FN_AGE)
/


--
-- TMP_PACAGES$OTDID  (Index) 
--
--  Dependencies: 
--   TMP_PACAGES (Table)
--
CREATE INDEX ASU.TMP_PACAGES$OTDID ON ASU.TMP_PACAGES
(FK_OTDID)
/


--
-- TMP_PACAGES$PACID  (Index) 
--
--  Dependencies: 
--   TMP_PACAGES (Table)
--
CREATE UNIQUE INDEX ASU.TMP_PACAGES$PACID ON ASU.TMP_PACAGES
(FK_PACID)
/


--
-- TMP_PACAGES$RESLECH  (Index) 
--
--  Dependencies: 
--   TMP_PACAGES (Table)
--
CREATE INDEX ASU.TMP_PACAGES$RESLECH ON ASU.TMP_PACAGES
(FP_RESLECH)
/


--
-- TMP_PACAGES$VRACHID  (Index) 
--
--  Dependencies: 
--   TMP_PACAGES (Table)
--
CREATE INDEX ASU.TMP_PACAGES$VRACHID ON ASU.TMP_PACAGES
(FK_VRACHID)
/


--
-- TMP_PACAGES$VYB  (Index) 
--
--  Dependencies: 
--   TMP_PACAGES (Table)
--
CREATE INDEX ASU.TMP_PACAGES$VYB ON ASU.TMP_PACAGES
(FD_VYB)
/


