DROP TABLE ASU.TNAZHEAL_DEL CASCADE CONSTRAINTS
/

--
-- TNAZHEAL_DEL  (Table) 
--
CREATE TABLE ASU.TNAZHEAL_DEL
(
  FK_ID      NUMBER(15)                         NOT NULL,
  FK_NAZID   NUMBER(15),
  FK_HEALID  NUMBER(15)
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


