DROP TABLE ASU.TNAZDEGVYP CASCADE CONSTRAINTS
/

--
-- TNAZDEGVYP  (Table) 
--
CREATE TABLE ASU.TNAZDEGVYP
(
  FK_ID        NUMBER(15),
  FD_DATA      DATE,
  FK_NAZDEGID  NUMBER(15),
  FN_KOL       NUMBER(15)
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          520K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


