DROP TABLE ASU.TNAZOPER_GROUPS CASCADE CONSTRAINTS
/

--
-- TNAZOPER_GROUPS  (Table) 
--
CREATE TABLE ASU.TNAZOPER_GROUPS
(
  FK_GROUPID  NUMBER,
  FK_OTDELID  NUMBER
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON COLUMN ASU.TNAZOPER_GROUPS.FK_GROUPID IS 'tsmid.fk_id - идентификатор группы'
/

COMMENT ON COLUMN ASU.TNAZOPER_GROUPS.FK_OTDELID IS 'totdel.fk_id - идентификатор отдела'
/


