DROP TABLE ASU.TNAZSHAB_TIB CASCADE CONSTRAINTS
/

--
-- TNAZSHAB_TIB  (Table) 
--
CREATE TABLE ASU.TNAZSHAB_TIB
(
  FK_ID        NUMBER(15),
  FK_SHABID    NUMBER(15),
  FC_CHAR      VARCHAR2(4000 BYTE),
  FN_NUM       NUMBER(25,10),
  FK_BID       NUMBER(15),
  FK_PACID     NUMBER(15),
  FK_SMID      NUMBER(15),
  FK_SMEDITID  NUMBER(15),
  FK_VRACHID   NUMBER(15),
  FD_DATE      DATE
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TNAZSHAB_TIB IS 'Праметры процедур к шаблонам назначений'
/

COMMENT ON COLUMN ASU.TNAZSHAB_TIB.FK_ID IS 'SEQUENCE=[SEQ_TNAZSHAB_TIB]'
/

COMMENT ON COLUMN ASU.TNAZSHAB_TIB.FK_SHABID IS 'Код шаблона  TSHABLON.FK_ID'
/

COMMENT ON COLUMN ASU.TNAZSHAB_TIB.FC_CHAR IS 'Текстовое значение'
/

COMMENT ON COLUMN ASU.TNAZSHAB_TIB.FN_NUM IS 'Числовое значение'
/

COMMENT ON COLUMN ASU.TNAZSHAB_TIB.FK_BID IS 'Служебное поле'
/

COMMENT ON COLUMN ASU.TNAZSHAB_TIB.FK_PACID IS 'Код назначения'
/

COMMENT ON COLUMN ASU.TNAZSHAB_TIB.FK_SMID IS 'Код параметра из TSMID'
/

COMMENT ON COLUMN ASU.TNAZSHAB_TIB.FK_SMEDITID IS 'Служебное поле'
/

COMMENT ON COLUMN ASU.TNAZSHAB_TIB.FK_VRACHID IS 'Код врача'
/

COMMENT ON COLUMN ASU.TNAZSHAB_TIB.FD_DATE IS 'Дата записи'
/


--
-- TNAZSHAB_TIB_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   TNAZSHAB_TIB (Table)
--
CREATE OR REPLACE TRIGGER ASU."TNAZSHAB_TIB_BEFORE_INSERT" 
BEFORE INSERT
ON tnazshab_tib
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
Begin
  select seq_tnazshab_tib.nextval into :new.fk_id from dual;
End;
/
SHOW ERRORS;


