ALTER TABLE ASU.TNAZEXCLUDEFROMREESTR
 DROP PRIMARY KEY CASCADE
/

DROP TABLE ASU.TNAZEXCLUDEFROMREESTR CASCADE CONSTRAINTS
/

--
-- TNAZEXCLUDEFROMREESTR  (Table) 
--
CREATE TABLE ASU.TNAZEXCLUDEFROMREESTR
(
  FK_NAZID  NUMBER                              NOT NULL
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   10
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TNAZEXCLUDEFROMREESTR IS 'Таблица FK_NAZID, которые не должны попадать в реестр'
/

COMMENT ON COLUMN ASU.TNAZEXCLUDEFROMREESTR.FK_NAZID IS 'ASU.VNAZ.FK_ID - назначение, которое не должно попадать в реестры'
/


--
-- PK_TNAZEXCLUDEFROMREESTR  (Index) 
--
--  Dependencies: 
--   TNAZEXCLUDEFROMREESTR (Table)
--
CREATE UNIQUE INDEX ASU.PK_TNAZEXCLUDEFROMREESTR ON ASU.TNAZEXCLUDEFROMREESTR
(FK_NAZID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


-- 
-- Non Foreign Key Constraints for Table TNAZEXCLUDEFROMREESTR 
-- 
ALTER TABLE ASU.TNAZEXCLUDEFROMREESTR ADD (
  CONSTRAINT PK_TNAZEXCLUDEFROMREESTR
 PRIMARY KEY
 (FK_NAZID))
/

