DROP TABLE ASU.TNAZSHAB_NAZ CASCADE CONSTRAINTS
/

--
-- TNAZSHAB_NAZ  (Table) 
--
CREATE TABLE ASU.TNAZSHAB_NAZ
(
  FK_ID           NUMBER(15),
  FK_SMID         NUMBER(15),
  FC_REMARK       VARCHAR2(100 BYTE),
  FK_ROOMID       NUMBER(9)                     DEFAULT 0,
  FK_RESULTID     NUMBER(15),
  FC_NAME         VARCHAR2(100 BYTE),
  FL_PLAT         VARCHAR2(3 BYTE),
  FC_TYPE         VARCHAR2(20 BYTE),
  FL_ISVRACHVIEW  NUMBER(1),
  FL_MORE_PUT     NUMBER(5)                     DEFAULT 0,
  FK_OWNERID      NUMBER(15),
  FK_SHABID       NUMBER(15),
  FN_NAZTYPE      NUMBER(1),
  FK_ISPOLID      NUMBER(10)
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          7000K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TNAZSHAB_NAZ IS 'Назначения шаблона назначений'
/

COMMENT ON COLUMN ASU.TNAZSHAB_NAZ.FK_ID IS 'SEQUENCE=[SEQ_TNAZSHAB_NAZ]'
/

COMMENT ON COLUMN ASU.TNAZSHAB_NAZ.FK_SMID IS 'Код проводимого назначения'
/

COMMENT ON COLUMN ASU.TNAZSHAB_NAZ.FC_REMARK IS 'Комментарий'
/

COMMENT ON COLUMN ASU.TNAZSHAB_NAZ.FK_ROOMID IS 'Кабинет проведения назначения'
/

COMMENT ON COLUMN ASU.TNAZSHAB_NAZ.FK_RESULTID IS 'Код исполнителя назначения'
/

COMMENT ON COLUMN ASU.TNAZSHAB_NAZ.FC_NAME IS 'Название назначения'
/

COMMENT ON COLUMN ASU.TNAZSHAB_NAZ.FL_PLAT IS 'Признак необходимости оплаты назначения'
/

COMMENT ON COLUMN ASU.TNAZSHAB_NAZ.FC_TYPE IS 'Служебное поле'
/

COMMENT ON COLUMN ASU.TNAZSHAB_NAZ.FL_ISVRACHVIEW IS 'Служебное поле'
/

COMMENT ON COLUMN ASU.TNAZSHAB_NAZ.FL_MORE_PUT IS 'Служебное поле'
/

COMMENT ON COLUMN ASU.TNAZSHAB_NAZ.FK_OWNERID IS 'Владелец'
/

COMMENT ON COLUMN ASU.TNAZSHAB_NAZ.FK_SHABID IS 'Код шаблона TNAZSHABLON.FK_ID'
/

COMMENT ON COLUMN ASU.TNAZSHAB_NAZ.FN_NAZTYPE IS 'Тип назначения'
/


--
-- TNAZSHAB_NAZ_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   TNAZSHAB_NAZ (Table)
--
CREATE OR REPLACE TRIGGER ASU."TNAZSHAB_NAZ_BEFORE_INSERT" 
BEFORE INSERT
ON tnazshab_naz
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
begin
select seq_tnazshab_naz.NEXTVAL into :New.fk_id from dual;
end;
/
SHOW ERRORS;


