DROP TABLE ASU.TNAZSTATWOM CASCADE CONSTRAINTS
/

--
-- TNAZSTATWOM  (Table) 
--
CREATE TABLE ASU.TNAZSTATWOM
(
  FN_NUM     NUMBER,
  FC_DIAG    VARCHAR2(100 BYTE),
  FC_NAZ     VARCHAR2(4000 BYTE),
  FK_DIAGID  NUMBER(15),
  FK_NAZID   NUMBER,
  FL_RUN     VARCHAR2(10 BYTE)
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          520K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


