DROP TABLE ASU.TNAZSHAB_RESIS CASCADE CONSTRAINTS
/

--
-- TNAZSHAB_RESIS  (Table) 
--
CREATE TABLE ASU.TNAZSHAB_RESIS
(
  FK_ID        NUMBER,
  FK_SMID      NUMBER,
  FD_INS       DATE,
  FC_RES       VARCHAR2(4000 BYTE),
  FK_BLOBID    NUMBER(15),
  FN_RES       NUMBER,
  FC_TYPE      VARCHAR2(30 BYTE),
  FK_VRACHID   NUMBER,
  FK_PACID     NUMBER(15),
  FK_NAZID     NUMBER(15),
  FK_PATNAME   NUMBER(15)                       DEFAULT 0                     NOT NULL,
  FC_COMENT    VARCHAR2(100 BYTE),
  FK_SOS       NUMBER(9),
  FL_PATFIRST  NUMBER(1)                        DEFAULT 0,
  FK_PATID     NUMBER(9),
  FK_SHABID    NUMBER(15)
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          9240K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TNAZSHAB_RESIS IS 'Таблица результатов исследований для шаблонов назначений'
/

COMMENT ON COLUMN ASU.TNAZSHAB_RESIS.FK_ID IS 'SEQUENCE=[SEQ_TNAZSHABLON]'
/

COMMENT ON COLUMN ASU.TNAZSHAB_RESIS.FK_SMID IS 'Код проводимого назначения'
/

COMMENT ON COLUMN ASU.TNAZSHAB_RESIS.FD_INS IS 'Дата ввода результата'
/

COMMENT ON COLUMN ASU.TNAZSHAB_RESIS.FC_RES IS 'Результаты'
/

COMMENT ON COLUMN ASU.TNAZSHAB_RESIS.FK_BLOBID IS 'TBLOBS.FK_ID'
/

COMMENT ON COLUMN ASU.TNAZSHAB_RESIS.FN_RES IS 'Служебное поле'
/

COMMENT ON COLUMN ASU.TNAZSHAB_RESIS.FC_TYPE IS 'Тип'
/

COMMENT ON COLUMN ASU.TNAZSHAB_RESIS.FK_VRACHID IS 'Врач выполнивший'
/

COMMENT ON COLUMN ASU.TNAZSHAB_RESIS.FK_PACID IS 'Код пациента'
/

COMMENT ON COLUMN ASU.TNAZSHAB_RESIS.FK_NAZID IS 'Код назначения'
/

COMMENT ON COLUMN ASU.TNAZSHAB_RESIS.FK_PATNAME IS 'Служебное поле'
/

COMMENT ON COLUMN ASU.TNAZSHAB_RESIS.FC_COMENT IS 'Комментарии'
/

COMMENT ON COLUMN ASU.TNAZSHAB_RESIS.FK_SOS IS 'Статус'
/

COMMENT ON COLUMN ASU.TNAZSHAB_RESIS.FL_PATFIRST IS 'Служебное поле'
/

COMMENT ON COLUMN ASU.TNAZSHAB_RESIS.FK_PATID IS 'Служебное поле'
/

COMMENT ON COLUMN ASU.TNAZSHAB_RESIS.FK_SHABID IS 'Код шаблона  TSHABLON.FK_ID'
/


--
-- TNAZSHAB_RESIS  (Trigger) 
--
--  Dependencies: 
--   TNAZSHAB_RESIS (Table)
--   STANDARD (Package)
--   DUAL (Synonym)
--   SEQ_TNAZSHABLON (Sequence)
--
CREATE OR REPLACE TRIGGER ASU."TNAZSHAB_RESIS" 
BEFORE INSERT
ON tnazshab_resis
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
begin
 select SEQ_TNAZSHABLON.nextval  into :new.fk_id from dual;
end;
/
SHOW ERRORS;


