DROP TABLE ASU.TOPERSCHEMAOPERBLOCK CASCADE CONSTRAINTS
/

--
-- TOPERSCHEMAOPERBLOCK  (Table) 
--
CREATE TABLE ASU.TOPERSCHEMAOPERBLOCK
(
  FK_ID            NUMBER                       NOT NULL,
  FK_OPERSCHEMAID  NUMBER,
  FK_OTDELID       NUMBER
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TOPERSCHEMAOPERBLOCK IS 'отделени€ оперблока'
/

COMMENT ON COLUMN ASU.TOPERSCHEMAOPERBLOCK.FK_ID IS '”никальный код'
/

COMMENT ON COLUMN ASU.TOPERSCHEMAOPERBLOCK.FK_OPERSCHEMAID IS 'TOPERSCHEMA.FK_ID'
/

COMMENT ON COLUMN ASU.TOPERSCHEMAOPERBLOCK.FK_OTDELID IS 'TOTDEL.FK_ID'
/


--
-- TOPERSCHEMAOPBLK_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   TOPERSCHEMAOPERBLOCK (Table)
--
CREATE OR REPLACE TRIGGER ASU."TOPERSCHEMAOPBLK_BEFORE_INSERT" 
  BEFORE INSERT
  ON ASU.TOPERSCHEMAOPERBLOCK   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
Begin
  select SEQ_TOPERSCHEMAOPERBLOCK.nextval into :new.fk_id from dual;
End;
/
SHOW ERRORS;


