DROP TABLE ASU.TOPERSCHEMASURGEON CASCADE CONSTRAINTS
/

--
-- TOPERSCHEMASURGEON  (Table) 
--
CREATE TABLE ASU.TOPERSCHEMASURGEON
(
  FK_ID            NUMBER                       NOT NULL,
  FK_OPERSCHEMAID  NUMBER,
  FK_OTDELID       NUMBER
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TOPERSCHEMASURGEON IS 'отделени€ хирургов'
/

COMMENT ON COLUMN ASU.TOPERSCHEMASURGEON.FK_ID IS '”никальный код'
/

COMMENT ON COLUMN ASU.TOPERSCHEMASURGEON.FK_OPERSCHEMAID IS 'TOPERSCHEMA.FK_ID'
/

COMMENT ON COLUMN ASU.TOPERSCHEMASURGEON.FK_OTDELID IS 'TOTDEL.FK_ID'
/


--
-- TOPERSCHEMASURG_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   TOPERSCHEMASURGEON (Table)
--
CREATE OR REPLACE TRIGGER ASU."TOPERSCHEMASURG_BEFORE_INSERT" 
  BEFORE INSERT
  ON ASU.TOPERSCHEMASURGEON   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
Begin
  select seq_TOPERSCHEMASURGEON.nextval into :new.fk_id from dual;
End;
/
SHOW ERRORS;


