ALTER TABLE ASU.TOUTSOTRPARAM
 DROP PRIMARY KEY CASCADE
/

DROP TABLE ASU.TOUTSOTRPARAM CASCADE CONSTRAINTS
/

--
-- TOUTSOTRPARAM  (Table) 
--
CREATE TABLE ASU.TOUTSOTRPARAM
(
  FK_ID     NUMBER                              NOT NULL,
  LPU_ID    VARCHAR2(30 BYTE),
  DOK_INN   VARCHAR2(12 BYTE),
  VID_SPEC  NUMBER,
  KOD_SPEC  NUMBER,
  DATE_STR  DATE,
  FILENAME  VARCHAR2(255 BYTE),
  FILEDATE  DATE
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          192K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


--
-- PK_TOUTSOTRPARAM  (Index) 
--
--  Dependencies: 
--   TOUTSOTRPARAM (Table)
--
CREATE UNIQUE INDEX ASU.PK_TOUTSOTRPARAM ON ASU.TOUTSOTRPARAM
(FK_ID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- TOUTSOTRPARAM_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   TOUTSOTRPARAM (Table)
--
CREATE OR REPLACE TRIGGER ASU.TOUTSOTRPARAM_BEFORE_INSERT
 BEFORE
 INSERT
 ON ASU.TOUTSOTRPARAM  REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
Begin
  SELECT ASU.SEQ_TOUTSOTRPARAM.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
 End;
/
SHOW ERRORS;


-- 
-- Non Foreign Key Constraints for Table TOUTSOTRPARAM 
-- 
ALTER TABLE ASU.TOUTSOTRPARAM ADD (
  CONSTRAINT PK_TOUTSOTRPARAM
 PRIMARY KEY
 (FK_ID))
/

