DROP TABLE ASU.TPERESEL_INTERIM CASCADE CONSTRAINTS
/

--
-- TPERESEL_INTERIM  (Table) 
--
CREATE TABLE ASU.TPERESEL_INTERIM
(
  FK_ID          NUMBER(15)                     DEFAULT -1,
  FK_PALATAID    NUMBER(15)                     DEFAULT -1,
  FK_PACID       NUMBER(15)                     DEFAULT -1,
  FD_DATA1       DATE,
  FD_DATA2       DATE,
  FK_PERESELID   NUMBER(15)                     DEFAULT -1,
  FK_KOYKAVIDID  NUMBER,
  FK_VRACHID     NUMBER(15),
  FL_DEL         NUMBER(1)                      DEFAULT 0                     NOT NULL,
  FL_LEAVE       NUMBER(1)                      DEFAULT 0                     NOT NULL
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TPERESEL_INTERIM IS 'Переводы в раенимацию (создана в связи с задачей 8044) Author:Efimov  '
/

COMMENT ON COLUMN ASU.TPERESEL_INTERIM.FK_ID IS 'SEQUENCE=[SEQ_TPERESEL_INTERIM]'
/

COMMENT ON COLUMN ASU.TPERESEL_INTERIM.FK_PALATAID IS 'TROOM.FK_ID'
/

COMMENT ON COLUMN ASU.TPERESEL_INTERIM.FK_PACID IS 'код пациента'
/

COMMENT ON COLUMN ASU.TPERESEL_INTERIM.FD_DATA1 IS 'начало периода'
/

COMMENT ON COLUMN ASU.TPERESEL_INTERIM.FD_DATA2 IS 'конец периода'
/

COMMENT ON COLUMN ASU.TPERESEL_INTERIM.FK_PERESELID IS 'TPERESEL.FK_ID'
/

COMMENT ON COLUMN ASU.TPERESEL_INTERIM.FK_KOYKAVIDID IS 'Профиль койки'
/

COMMENT ON COLUMN ASU.TPERESEL_INTERIM.FK_VRACHID IS 'Врач реанимации'
/

COMMENT ON COLUMN ASU.TPERESEL_INTERIM.FL_DEL IS 'Признак удаления записи (1 - удалён)'
/

COMMENT ON COLUMN ASU.TPERESEL_INTERIM.FL_LEAVE IS 'Признак выбытия из реанимации (1 - выбыл)'
/


--
-- TPERESEL_INTERIM_BY_D1_D2  (Index) 
--
--  Dependencies: 
--   TPERESEL_INTERIM (Table)
--
CREATE INDEX ASU.TPERESEL_INTERIM_BY_D1_D2 ON ASU.TPERESEL_INTERIM
(FD_DATA1, FD_DATA2)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1664K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- TPERESEL_INTERIM_BY_FD_DATA2  (Index) 
--
--  Dependencies: 
--   TPERESEL_INTERIM (Table)
--
CREATE INDEX ASU.TPERESEL_INTERIM_BY_FD_DATA2 ON ASU.TPERESEL_INTERIM
(FD_DATA2)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1536K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- TPERESEL_INTERIM_BY_ID  (Index) 
--
--  Dependencies: 
--   TPERESEL_INTERIM (Table)
--
CREATE UNIQUE INDEX ASU.TPERESEL_INTERIM_BY_ID ON ASU.TPERESEL_INTERIM
(FK_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          512K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- TPERESEL_INTERIM_BY_PACID  (Index) 
--
--  Dependencies: 
--   TPERESEL_INTERIM (Table)
--
CREATE INDEX ASU.TPERESEL_INTERIM_BY_PACID ON ASU.TPERESEL_INTERIM
(FK_PACID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- TPERESEL_INTERIM_BY_PALATAID  (Index) 
--
--  Dependencies: 
--   TPERESEL_INTERIM (Table)
--
CREATE INDEX ASU.TPERESEL_INTERIM_BY_PALATAID ON ASU.TPERESEL_INTERIM
(FK_PALATAID, FK_PACID, FK_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          896K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- TPERESEL_INTERIM_FD_DATA1  (Index) 
--
--  Dependencies: 
--   TPERESEL_INTERIM (Table)
--
CREATE INDEX ASU.TPERESEL_INTERIM_FD_DATA1 ON ASU.TPERESEL_INTERIM
(FD_DATA1)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- TPERESEL_INTERIM_I_D2_D1  (Index) 
--
--  Dependencies: 
--   TPERESEL_INTERIM (Table)
--
CREATE INDEX ASU.TPERESEL_INTERIM_I_D2_D1 ON ASU.TPERESEL_INTERIM
(FD_DATA2, FD_DATA1)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1920K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- TPERESEL_INTERIM_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   TPERESEL_INTERIM (Table)
--
CREATE OR REPLACE TRIGGER ASU."TPERESEL_INTERIM_BEFORE_INSERT" 
BEFORE INSERT
ON ASU.TPERESEL_INTERIM REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
Begin
  SELECT SEQ_TPERESEL.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


