DROP TABLE ASU.TPLANDATA_TESTOKB CASCADE CONSTRAINTS
/

--
-- TPLANDATA_TESTOKB  (Table) 
--
CREATE TABLE ASU.TPLANDATA_TESTOKB
(
  FK_ID       NUMBER(15)                        DEFAULT NULL,
  FD_DATE     DATE                              DEFAULT NULL,
  FK_OTDELID  NUMBER(15),
  FN_POSTUP   NUMBER(3)                         DEFAULT NULL,
  FN_DIED     NUMBER(3)                         DEFAULT NULL,
  FN_NOWALL   NUMBER(3)                         DEFAULT NULL,
  FN_VIPIS    NUMBER(3)                         DEFAULT NULL,
  FN_OPER     NUMBER(3)                         DEFAULT NULL
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON COLUMN ASU.TPLANDATA_TESTOKB.FK_ID IS 'SEQUENCE=[SEQ_TPLANDATA_TESTOKB]'
/

COMMENT ON COLUMN ASU.TPLANDATA_TESTOKB.FD_DATE IS 'дата регистрации показателей'
/

COMMENT ON COLUMN ASU.TPLANDATA_TESTOKB.FK_OTDELID IS 'Код отделения'
/

COMMENT ON COLUMN ASU.TPLANDATA_TESTOKB.FN_POSTUP IS 'Поступило больных'
/

COMMENT ON COLUMN ASU.TPLANDATA_TESTOKB.FN_DIED IS 'Умерло'
/

COMMENT ON COLUMN ASU.TPLANDATA_TESTOKB.FN_NOWALL IS 'Состоит больных всего'
/

COMMENT ON COLUMN ASU.TPLANDATA_TESTOKB.FN_VIPIS IS 'Выписано больных'
/

COMMENT ON COLUMN ASU.TPLANDATA_TESTOKB.FN_OPER IS 'Произведено операций'
/


--
-- TPLANDATA_TESTOKB_BEFORE_INS  (Trigger) 
--
--  Dependencies: 
--   TPLANDATA_TESTOKB (Table)
--
CREATE OR REPLACE TRIGGER ASU."TPLANDATA_TESTOKB_BEFORE_INS" 
 BEFORE 
 INSERT
 ON ASU.TPLANDATA_TESTOKB  REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
Begin
  SELECT seq_tplandata_testokb.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


