DROP TABLE ASU.TPROM CASCADE CONSTRAINTS
/

--
-- TPROM  (Table) 
--
CREATE TABLE ASU.TPROM
(
  FK_ID    NUMBER,
  FC_NAME  VARCHAR2(30 BYTE),
  FC_MASC  VARCHAR2(7 BYTE)
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          520K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TPROM IS 'Справочник промежутков'
/

COMMENT ON COLUMN ASU.TPROM.FK_ID IS 'SEQUENCE=[SEQ_TPROM]'
/


--
-- TPROM_BEFOR_INSERT  (Trigger) 
--
--  Dependencies: 
--   TPROM (Table)
--
CREATE OR REPLACE TRIGGER ASU."TPROM_BEFOR_INSERT" 
  BEFORE INSERT
  ON ASU.TPROM   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
Begin
  select SEQ_TPROM.NEXTVAL into :new.FK_ID from dual;
End;
/
SHOW ERRORS;


