DROP TABLE ASU.TQC_PRODUCER CASCADE CONSTRAINTS
/

--
-- TQC_PRODUCER  (Table) 
--
CREATE TABLE ASU.TQC_PRODUCER
(
  FK_ID    NUMBER                               NOT NULL,
  FC_NAME  VARCHAR2(255 BYTE),
  FL_DEL   NUMBER                               DEFAULT 0
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TQC_PRODUCER IS 'Контроль качества
Таблица производителей материалов'
/

COMMENT ON COLUMN ASU.TQC_PRODUCER.FK_ID IS 'ID'
/

COMMENT ON COLUMN ASU.TQC_PRODUCER.FC_NAME IS 'Название производителя'
/

COMMENT ON COLUMN ASU.TQC_PRODUCER.FL_DEL IS 'Признак удаления'
/


--
-- TQC_PRODUCER_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   TQC_PRODUCER (Table)
--
CREATE OR REPLACE TRIGGER ASU."TQC_PRODUCER_BEFORE_INSERT" 
 BEFORE
 INSERT
 ON ASU.TQC_PRODUCER  REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
BEGIN
    SELECT SEQ_QC_LAB.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
END;
/
SHOW ERRORS;


