DROP TABLE ASU.TQC_LOT CASCADE CONSTRAINTS
/

--
-- TQC_LOT  (Table) 
--
CREATE TABLE ASU.TQC_LOT
(
  FK_ID        INTEGER                          NOT NULL,
  FK_MLEVELID  INTEGER,
  FD_DATE      DATE,
  FL_DEL       NUMBER                           DEFAULT 0,
  FC_NUMBER    VARCHAR2(50 BYTE),
  FN_PROBE     NUMBER
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON COLUMN ASU.TQC_LOT.FK_ID IS 'ID'
/

COMMENT ON COLUMN ASU.TQC_LOT.FK_MLEVELID IS 'TQC_MLEVEL.FK_ID'
/

COMMENT ON COLUMN ASU.TQC_LOT.FD_DATE IS 'Срок годности'
/

COMMENT ON COLUMN ASU.TQC_LOT.FC_NUMBER IS 'Номер лота'
/

COMMENT ON COLUMN ASU.TQC_LOT.FN_PROBE IS 'Номер пробы'
/


--
-- TQC_LOT_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   TQC_LOT (Table)
--
CREATE OR REPLACE TRIGGER ASU."TQC_LOT_BEFORE_INSERT" 
 BEFORE
  INSERT
 ON ASU.TQC_LOT REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    SELECT SEQ_QC_LAB.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
END;
/
SHOW ERRORS;


