DROP TABLE ASU.TQC_METHOD CASCADE CONSTRAINTS
/

--
-- TQC_METHOD  (Table) 
--
CREATE TABLE ASU.TQC_METHOD
(
  FK_ID                   NUMBER                NOT NULL,
  FK_MGROUP               NUMBER,
  FC_NAME                 VARCHAR2(255 BYTE),
  FK_ANALYSTID            NUMBER,
  FN_MTYPE                NUMBER,
  FC_IFA_CHECK_NAME_1     VARCHAR2(50 BYTE),
  FN_IFA_CHECK_ENABLED_1  NUMBER,
  FN_OP_CHECK_VALUE_1     NUMBER(18,5),
  FC_IFA_CHECK_NAME_2     VARCHAR2(50 BYTE),
  FN_IFA_CHECK_ENABLED_2  NUMBER,
  FN_OP_CHECK_VALUE_2     NUMBER(18,5),
  FN_IFA_VARIATION        NUMBER(18,5),
  FL_DEL                  NUMBER,
  FK_EDISMID              NUMBER,
  FK_COMPARID             NUMBER
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON COLUMN ASU.TQC_METHOD.FK_MGROUP IS 'TQC_MGROUP.FK_ID'
/

COMMENT ON COLUMN ASU.TQC_METHOD.FC_NAME IS 'Наименование методики'
/

COMMENT ON COLUMN ASU.TQC_METHOD.FK_ANALYSTID IS 'TQC_ANALYST.FK_ID'
/

COMMENT ON COLUMN ASU.TQC_METHOD.FN_MTYPE IS 'Тип методики: 0 - количественная; 1 - качественная ИФА'
/

COMMENT ON COLUMN ASU.TQC_METHOD.FN_OP_CHECK_VALUE_1 IS 'ОП nc'
/

COMMENT ON COLUMN ASU.TQC_METHOD.FN_OP_CHECK_VALUE_2 IS 'ОП pc'
/

COMMENT ON COLUMN ASU.TQC_METHOD.FN_IFA_VARIATION IS 'ОП крит.'
/


--
-- TQC_METHOD_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   TQC_METHOD (Table)
--
CREATE OR REPLACE TRIGGER ASU."TQC_METHOD_BEFORE_INSERT" 
 BEFORE
  INSERT
 ON ASU.TQC_METHOD REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    SELECT SEQ_QC_LAB.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
END;
/
SHOW ERRORS;


