DROP TABLE ASU.TQCKOEFFRECOVER CASCADE CONSTRAINTS
/

--
-- TQCKOEFFRECOVER  (Table) 
--
CREATE TABLE ASU.TQCKOEFFRECOVER
(
  FK_ID       NUMBER(9)                         DEFAULT -1,
  FN_CONTROL  NUMBER(6,2)                       DEFAULT 0,
  FN_WARNING  NUMBER(6,2)                       DEFAULT 0,
  FN_COUNT    NUMBER(2)                         DEFAULT 0
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          200K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TQCKOEFFRECOVER IS 'Таблица коэффициентов для репликатов предупредительных и контрольных границ'
/

COMMENT ON COLUMN ASU.TQCKOEFFRECOVER.FK_ID IS 'SEQUENCE=[SEQ_TQCKOEFFRECOVER]'
/

COMMENT ON COLUMN ASU.TQCKOEFFRECOVER.FN_CONTROL IS 'Контроьная граница'
/

COMMENT ON COLUMN ASU.TQCKOEFFRECOVER.FN_WARNING IS 'Предупредительная граница'
/

COMMENT ON COLUMN ASU.TQCKOEFFRECOVER.FN_COUNT IS 'Количество ежедневных репликатов'
/


--
-- TQCKOEFF_RECOVER_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   TQCKOEFFRECOVER (Table)
--
CREATE OR REPLACE TRIGGER ASU."TQCKOEFF_RECOVER_BEFORE_INSERT" 
BEFORE INSERT
ON ASU.TQCKOEFFRECOVER REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
Begin
  SELECT SEQ_TQCKOEFFRECOVER.NEXTVAL INTO :NEW.FK_ID FROM DUAl;
End;
/
SHOW ERRORS;


