DROP TABLE ASU.TQCRECOVERFIX CASCADE CONSTRAINTS
/

--
-- TQCRECOVERFIX  (Table) 
--
CREATE TABLE ASU.TQCRECOVERFIX
(
  FK_ID     NUMBER(9)                           DEFAULT -1,
  FK_SMID   NUMBER(9),
  FN_R      NUMBER(9,4),
  FD_DATA1  DATE,
  FD_DATA2  DATE
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          520K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TQCRECOVERFIX IS 'Фиксированные значения R'
/

COMMENT ON COLUMN ASU.TQCRECOVERFIX.FK_ID IS 'SEQUENCE=[SEQ_TQCRECOVERFIX]'
/

COMMENT ON COLUMN ASU.TQCRECOVERFIX.FK_SMID IS 'TSMID->FK_ID'
/

COMMENT ON COLUMN ASU.TQCRECOVERFIX.FN_R IS 'R'
/

COMMENT ON COLUMN ASU.TQCRECOVERFIX.FD_DATA1 IS 'Дата фиксирования'
/

COMMENT ON COLUMN ASU.TQCRECOVERFIX.FD_DATA2 IS 'Дата 2'
/


--
-- TQCRECOVERFIX_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   TQCRECOVERFIX (Table)
--
CREATE OR REPLACE TRIGGER ASU."TQCRECOVERFIX_BEFORE_INSERT" 
BEFORE  INSERT  ON ASU.TQCRECOVERFIX FOR EACH ROW
Begin
  SELECT SEQ_TQCRECOVERFIX.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


