DROP TABLE ASU.TQCRECOVERDATA CASCADE CONSTRAINTS
/

--
-- TQCRECOVERDATA  (Table) 
--
CREATE TABLE ASU.TQCRECOVERDATA
(
  FK_ID       NUMBER(9)                         DEFAULT -1,
  FN_VALUE    NUMBER(9,2)                       DEFAULT 0,
  FD_DATE     DATE,
  FN_NUM      VARCHAR2(2 BYTE)                  DEFAULT 1,
  FK_SMID     NUMBER(9),
  FC_COMMENT  VARCHAR2(4000 BYTE),
  FK_FIXID    NUMBER(9)
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TQCRECOVERDATA IS 'Данные для контроля качества на воспроизводимость'
/

COMMENT ON COLUMN ASU.TQCRECOVERDATA.FK_ID IS 'SEQUENCE=[SEQ_TQCRECOVERDATA]'
/

COMMENT ON COLUMN ASU.TQCRECOVERDATA.FN_VALUE IS 'Значение'
/

COMMENT ON COLUMN ASU.TQCRECOVERDATA.FD_DATE IS 'дата произведения контроля'
/

COMMENT ON COLUMN ASU.TQCRECOVERDATA.FN_NUM IS 'Номер забора'
/

COMMENT ON COLUMN ASU.TQCRECOVERDATA.FK_SMID IS 'Код из TSMID'
/

COMMENT ON COLUMN ASU.TQCRECOVERDATA.FC_COMMENT IS 'Комментарий'
/

COMMENT ON COLUMN ASU.TQCRECOVERDATA.FK_FIXID IS 'TQCRECOVERFIX->FK_ID'
/


--
-- TQCRECOVERDATA  (Index) 
--
--  Dependencies: 
--   TQCRECOVERDATA (Table)
--
CREATE UNIQUE INDEX ASU.TQCRECOVERDATA ON ASU.TQCRECOVERDATA
(FK_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- TQCRECOVERDATA_BY_DATE_SMID_NU  (Index) 
--
--  Dependencies: 
--   TQCRECOVERDATA (Table)
--
CREATE UNIQUE INDEX ASU.TQCRECOVERDATA_BY_DATE_SMID_NU ON ASU.TQCRECOVERDATA
(FD_DATE, FK_SMID, FN_NUM)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- TQCRECOVERDATA_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   TQCRECOVERDATA (Table)
--
CREATE OR REPLACE TRIGGER ASU."TQCRECOVERDATA_BEFORE_INSERT" 
BEFORE INSERT
ON ASU.TQCRECOVERDATA REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
Begin
  SELECT SEQ_TQCRECOVERDATA.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


