DROP TABLE ASU.TQCRECOVERCALCFIX CASCADE CONSTRAINTS
/

--
-- TQCRECOVERCALCFIX  (Table) 
--
CREATE TABLE ASU.TQCRECOVERCALCFIX
(
  FK_ID      NUMBER(9)                          DEFAULT -1,
  FN_PROBA   NUMBER(3),
  FN_NUM     NUMBER(3),
  FN_VALUE   NUMBER(12,5),
  FK_PERIOD  NUMBER(9)
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          520K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TQCRECOVERCALCFIX IS 'Таблица для рассчета фиксированных значений для контроля на воспроизводимость'
/

COMMENT ON COLUMN ASU.TQCRECOVERCALCFIX.FK_ID IS 'SEQUENCE=[SEQ_TQCRECOVERCALCFIX]'
/

COMMENT ON COLUMN ASU.TQCRECOVERCALCFIX.FN_PROBA IS 'Номер пробы'
/

COMMENT ON COLUMN ASU.TQCRECOVERCALCFIX.FN_NUM IS 'Номер в пробе'
/

COMMENT ON COLUMN ASU.TQCRECOVERCALCFIX.FN_VALUE IS 'Значение'
/

COMMENT ON COLUMN ASU.TQCRECOVERCALCFIX.FK_PERIOD IS 'TQCRECOVERFIX->FK_ID'
/


--
-- TQCRECOVERCALCFIX_BEFORE_IN  (Trigger) 
--
--  Dependencies: 
--   TQCRECOVERCALCFIX (Table)
--
CREATE OR REPLACE TRIGGER ASU."TQCRECOVERCALCFIX_BEFORE_IN" 
BEFORE INSERT
ON ASU.TQCRECOVERCALCFIX REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
Begin
  SELECT SEQ_TQCRECOVERCALCFIX.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


