DROP TABLE ASU.TQUEUEVIEW CASCADE CONSTRAINTS
/

--
-- TQUEUEVIEW  (Table) 
--
CREATE TABLE ASU.TQUEUEVIEW
(
  FC_TALON   VARCHAR2(10 BYTE),
  FK_WINDOW  NUMBER,
  FC_WINDOW  VARCHAR2(50 BYTE),
  FL_SAY     NUMBER,
  FD_DATE    DATE
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TQUEUEVIEW IS 'информация для отображалки'
/

COMMENT ON COLUMN ASU.TQUEUEVIEW.FC_TALON IS 'талон'
/

COMMENT ON COLUMN ASU.TQUEUEVIEW.FK_WINDOW IS 'id окна'
/

COMMENT ON COLUMN ASU.TQUEUEVIEW.FC_WINDOW IS 'окно'
/

COMMENT ON COLUMN ASU.TQUEUEVIEW.FL_SAY IS '1 - нужно озвучить, 0 - озвучено'
/

COMMENT ON COLUMN ASU.TQUEUEVIEW.FD_DATE IS 'дата изменения записи'
/


