ALTER TABLE ASU.TRECIPEPAYTYPE
 DROP PRIMARY KEY CASCADE
/

DROP TABLE ASU.TRECIPEPAYTYPE CASCADE CONSTRAINTS
/

--
-- TRECIPEPAYTYPE  (Table) 
--
CREATE TABLE ASU.TRECIPEPAYTYPE
(
  FK_ID    NUMBER(10)                           NOT NULL,
  FC_NAME  VARCHAR2(150 BYTE)
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TRECIPEPAYTYPE IS 'Sill - источник финансирования рецептов'
/

COMMENT ON COLUMN ASU.TRECIPEPAYTYPE.FK_ID IS 'Первичный ключ'
/

COMMENT ON COLUMN ASU.TRECIPEPAYTYPE.FC_NAME IS 'Название'
/


--
-- TRECIPEPAYTYPE_BY_ID  (Index) 
--
--  Dependencies: 
--   TRECIPEPAYTYPE (Table)
--
CREATE UNIQUE INDEX ASU.TRECIPEPAYTYPE_BY_ID ON ASU.TRECIPEPAYTYPE
(FK_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


-- 
-- Non Foreign Key Constraints for Table TRECIPEPAYTYPE 
-- 
ALTER TABLE ASU.TRECIPEPAYTYPE ADD (
  CONSTRAINT TRECIPEPAYTYPE_BY_ID
 PRIMARY KEY
 (FK_ID)
    USING INDEX 
    TABLESPACE INDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          128K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ))
/

