DROP TABLE ASU.TRECIPE_DLO_EXP_FARMGR CASCADE CONSTRAINTS
/

--
-- TRECIPE_DLO_EXP_FARMGR  (Table) 
--
CREATE TABLE ASU.TRECIPE_DLO_EXP_FARMGR
(
  C_FARG     NUMBER,
  FNAME_FRG  VARCHAR2(200 BYTE),
  SNAME_FRG  VARCHAR2(50 BYTE),
  MSG_TEXT   VARCHAR2(100 BYTE),
  C_PER      NUMBER                             DEFAULT 0,
  C_FINL     NUMBER                             DEFAULT 0
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TRECIPE_DLO_EXP_FARMGR IS 'Фармгруппы для выгрузки. Author:Voronov'
/

COMMENT ON COLUMN ASU.TRECIPE_DLO_EXP_FARMGR.C_FARG IS 'ключ'
/

COMMENT ON COLUMN ASU.TRECIPE_DLO_EXP_FARMGR.FNAME_FRG IS 'название'
/

COMMENT ON COLUMN ASU.TRECIPE_DLO_EXP_FARMGR.SNAME_FRG IS 'краткое наименование'
/

COMMENT ON COLUMN ASU.TRECIPE_DLO_EXP_FARMGR.MSG_TEXT IS 'Комментарий'
/

COMMENT ON COLUMN ASU.TRECIPE_DLO_EXP_FARMGR.C_PER IS 'Код перечня'
/

COMMENT ON COLUMN ASU.TRECIPE_DLO_EXP_FARMGR.C_FINL IS 'Источник финансирования'
/


--
-- TRECIPE_DLO_EXP_FARMGR_ID  (Index) 
--
--  Dependencies: 
--   TRECIPE_DLO_EXP_FARMGR (Table)
--
CREATE UNIQUE INDEX ASU.TRECIPE_DLO_EXP_FARMGR_ID ON ASU.TRECIPE_DLO_EXP_FARMGR
(C_FARG, C_FINL)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


