ALTER TABLE ASU.TRECIPE_DLO_IMP_MEDIC
 DROP PRIMARY KEY CASCADE
/

DROP TABLE ASU.TRECIPE_DLO_IMP_MEDIC CASCADE CONSTRAINTS
/

--
-- TRECIPE_DLO_IMP_MEDIC  (Table) 
--
--  Dependencies: 
--   TRECIPE_DLO_IMP (Table)
--
CREATE TABLE ASU.TRECIPE_DLO_IMP_MEDIC
(
  FK_ID             NUMBER,
  FK_RECIPE_IMP_ID  NUMBER,
  C_LSFO            NUMBER,
  KO_ALL            NUMBER(18,8),
  PRICE             NUMBER(18,4),
  PARTIA            NUMBER,
  C_PFS             VARCHAR2(10 BYTE),
  NOMK_LS           VARCHAR2(10 BYTE),
  DOZ_ME            VARCHAR2(5 BYTE),
  SL_ALL            NUMBER(18,4),
  CODEORG           NUMBER,
  ID_GK             NUMBER,
  ID_SPEC           NUMBER,
  SERIA             VARCHAR2(40 BYTE),
  SRGODN            NUMBER,
  ID_PZ             NUMBER,
  ID_PZ_D           NUMBER
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TRECIPE_DLO_IMP_MEDIC IS 'ДЛО. Позиции отпущенных рецептов'
/

COMMENT ON COLUMN ASU.TRECIPE_DLO_IMP_MEDIC.FK_ID IS 'ключ'
/

COMMENT ON COLUMN ASU.TRECIPE_DLO_IMP_MEDIC.FK_RECIPE_IMP_ID IS 'ссылка на импортированный рецепт'
/

COMMENT ON COLUMN ASU.TRECIPE_DLO_IMP_MEDIC.C_LSFO IS 'Код ЛС поставщика'
/

COMMENT ON COLUMN ASU.TRECIPE_DLO_IMP_MEDIC.KO_ALL IS 'Количество упаковок отпущенного ЛС'
/

COMMENT ON COLUMN ASU.TRECIPE_DLO_IMP_MEDIC.PRICE IS 'Цена упаковки отпущенного ЛС'
/

COMMENT ON COLUMN ASU.TRECIPE_DLO_IMP_MEDIC.PARTIA IS 'Партия'
/

COMMENT ON COLUMN ASU.TRECIPE_DLO_IMP_MEDIC.C_PFS IS 'Код Росздравнадзора для цены отпущенного ЛС'
/

COMMENT ON COLUMN ASU.TRECIPE_DLO_IMP_MEDIC.NOMK_LS IS 'Номенклатурный Код отпущенного ЛС'
/

COMMENT ON COLUMN ASU.TRECIPE_DLO_IMP_MEDIC.DOZ_ME IS 'Кол-во доз в МЕ'
/

COMMENT ON COLUMN ASU.TRECIPE_DLO_IMP_MEDIC.SL_ALL IS 'Сумма возмещения'
/

COMMENT ON COLUMN ASU.TRECIPE_DLO_IMP_MEDIC.CODEORG IS 'Код Юр.лица - исполнителя ГК'
/

COMMENT ON COLUMN ASU.TRECIPE_DLO_IMP_MEDIC.ID_GK IS 'Код ГК'
/

COMMENT ON COLUMN ASU.TRECIPE_DLO_IMP_MEDIC.ID_SPEC IS 'Код спецификации'
/

COMMENT ON COLUMN ASU.TRECIPE_DLO_IMP_MEDIC.SERIA IS 'Серия ЛС'
/

COMMENT ON COLUMN ASU.TRECIPE_DLO_IMP_MEDIC.SRGODN IS 'Срок годности ЛС'
/

COMMENT ON COLUMN ASU.TRECIPE_DLO_IMP_MEDIC.ID_PZ IS 'ид плановой заявки'
/

COMMENT ON COLUMN ASU.TRECIPE_DLO_IMP_MEDIC.ID_PZ_D IS 'ид доп. ПЗ'
/


--
-- TRECIPE_DLO_IMP_MEDIC_FK_IDX  (Index) 
--
--  Dependencies: 
--   TRECIPE_DLO_IMP_MEDIC (Table)
--
CREATE INDEX ASU.TRECIPE_DLO_IMP_MEDIC_FK_IDX ON ASU.TRECIPE_DLO_IMP_MEDIC
(FK_RECIPE_IMP_ID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- TRECIPE_DLO_IMP_MEDIC_PK  (Index) 
--
--  Dependencies: 
--   TRECIPE_DLO_IMP_MEDIC (Table)
--
CREATE UNIQUE INDEX ASU.TRECIPE_DLO_IMP_MEDIC_PK ON ASU.TRECIPE_DLO_IMP_MEDIC
(FK_ID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- TRECIPE_DLO_IMP_MEDIC_INS  (Trigger) 
--
--  Dependencies: 
--   TRECIPE_DLO_IMP_MEDIC (Table)
--
CREATE OR REPLACE TRIGGER ASU."TRECIPE_DLO_IMP_MEDIC_INS"
 BEFORE
  INSERT
 ON ASU.TRECIPE_DLO_IMP_MEDIC REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
begin
  if (:new.fk_id is null) then
    select ASU.SEQ_TRECIPE_DLO_IMP_MEDIC.nextval into :new.fk_id from dual;
  end if;
end;
/
SHOW ERRORS;


-- 
-- Non Foreign Key Constraints for Table TRECIPE_DLO_IMP_MEDIC 
-- 
ALTER TABLE ASU.TRECIPE_DLO_IMP_MEDIC ADD (
  CONSTRAINT TRECIPE_DLO_IMP_MEDIC_PK
 PRIMARY KEY
 (FK_ID))
/

-- 
-- Foreign Key Constraints for Table TRECIPE_DLO_IMP_MEDIC 
-- 
ALTER TABLE ASU.TRECIPE_DLO_IMP_MEDIC ADD (
  CONSTRAINT TRECIPE_DLO_IMP_MED_RECIPE_FK 
 FOREIGN KEY (FK_RECIPE_IMP_ID) 
 REFERENCES ASU.TRECIPE_DLO_IMP (FK_ID))
/

