DROP TABLE ASU.TRECEPTNAZ CASCADE CONSTRAINTS
/

--
-- TRECEPTNAZ  (Table) 
--
CREATE TABLE ASU.TRECEPTNAZ
(
  FK_ID        NUMBER(9),
  FK_SMID      NUMBER(9),
  FK_PARAMID   NUMBER(9),
  FK_RECEPTID  NUMBER(9)
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON COLUMN ASU.TRECEPTNAZ.FK_ID IS 'SEQUENCE=[SEQ_TRECEPTNAZ]'
/


--
-- TRECEPTNAZ_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   TRECEPTNAZ (Table)
--
CREATE OR REPLACE TRIGGER ASU."TRECEPTNAZ_BEFORE_INSERT" 
BEFORE INSERT
ON ASU.TRECEPTNAZ REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
begin
 SELECT SEQ_TRECEPTNAZ.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
END;
/
SHOW ERRORS;


