DROP TABLE ASU.TREPAPP CASCADE CONSTRAINTS
/

--
-- TREPAPP  (Table) 
--
CREATE TABLE ASU.TREPAPP
(
  FK_ID        NUMBER(15),
  FK_APPID     NUMBER(15),
  FK_APPREPID  NUMBER(15),
  FC_NAME      VARCHAR2(45 BYTE)
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          520K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TREPAPP IS 'Соответствие отчетов приложениям by TimurLan'
/

COMMENT ON COLUMN ASU.TREPAPP.FK_ID IS 'ID'
/

COMMENT ON COLUMN ASU.TREPAPP.FK_APPID IS 'код приложения'
/

COMMENT ON COLUMN ASU.TREPAPP.FK_APPREPID IS 'код отчета'
/

COMMENT ON COLUMN ASU.TREPAPP.FC_NAME IS 'имя'
/


