DROP TABLE ASU.TRESMEDFARMGR_TMP CASCADE CONSTRAINTS
/

--
-- TRESMEDFARMGR_TMP  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE ASU.TRESMEDFARMGR_TMP
(
  FK_ID     NUMBER(9)                           NOT NULL,
  FC_NAME   VARCHAR2(255 BYTE),
  FL_NEED   NUMBER(1),
  FN_ORDER  NUMBER(1)
)
ON COMMIT PRESERVE ROWS
NOCACHE
/


