DROP TABLE ASU.TRGCODES CASCADE CONSTRAINTS
/

--
-- TRGCODES  (Table) 
--
CREATE TABLE ASU.TRGCODES
(
  FK_ID    NUMBER(9),
  FN_CODE  VARCHAR2(2 BYTE)
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          520K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TRGCODES IS ' оды которые надо поднимать из русского гост€ к нам...'
/

COMMENT ON COLUMN ASU.TRGCODES.FK_ID IS 'SEQUENCE=[SEQ_TRGCODES]'
/

COMMENT ON COLUMN ASU.TRGCODES.FN_CODE IS 'Code'
/


--
-- TRGCODES_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   TRGCODES (Table)
--
CREATE OR REPLACE TRIGGER ASU."TRGCODES_BEFORE_INSERT" 
BEFORE INSERT
ON trgcodes
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
Begin
  SELECT SEQ_TRGCODES.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


