DROP TABLE ASU.TRSF_TEMPLATE_COLUMNS CASCADE CONSTRAINTS
/

--
-- TRSF_TEMPLATE_COLUMNS  (Table) 
--
CREATE TABLE ASU.TRSF_TEMPLATE_COLUMNS
(
  FK_ID            NUMBER                       NOT NULL,
  FK_RSF_TEMPLATE  NUMBER                       NOT NULL,
  FC_NAME          VARCHAR2(255 BYTE),
  FN_ORDER         NUMBER                       NOT NULL
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TRSF_TEMPLATE_COLUMNS IS 'Список колонок для реестров (и шаблонов). Author: Neronov A.S. 16.06.2011'
/

COMMENT ON COLUMN ASU.TRSF_TEMPLATE_COLUMNS.FK_ID IS 'SEQUENCE=[SEQ_TRSF_TEMPLATE_COLUMNS]'
/

COMMENT ON COLUMN ASU.TRSF_TEMPLATE_COLUMNS.FK_RSF_TEMPLATE IS 'TRSF_TEMPLATE.FK_ID - ссылка на шаблон'
/

COMMENT ON COLUMN ASU.TRSF_TEMPLATE_COLUMNS.FC_NAME IS 'Название колонки'
/

COMMENT ON COLUMN ASU.TRSF_TEMPLATE_COLUMNS.FN_ORDER IS 'Порядок сортировки'
/


--
-- TRSF_TEMPLATE_COLUMNS_BI  (Trigger) 
--
--  Dependencies: 
--   TRSF_TEMPLATE_COLUMNS (Table)
--
CREATE OR REPLACE TRIGGER ASU.TRSF_TEMPLATE_COLUMNS_BI
 BEFORE
 INSERT
 ON ASU.TRSF_TEMPLATE_COLUMNS  REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
Begin
  SELECT SEQ_TRSF_TEMPLATE_COLUMNS.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


