DROP TABLE ASU.TSECTION_BUTLINE CASCADE CONSTRAINTS
/

--
-- TSECTION_BUTLINE  (Table) 
--
CREATE TABLE ASU.TSECTION_BUTLINE
(
  FK_ID        NUMBER(15),
  FK_SECID     NUMBER(15),
  FK_APPID     NUMBER(15),
  FC_NAME      VARCHAR2(30 BYTE),
  FC_FUNCNAME  VARCHAR2(50 BYTE)
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON COLUMN ASU.TSECTION_BUTLINE.FK_ID IS 'SEQUENCE=[SEQ_TSECTION_BUTLINE]'
/


--
-- TSECTION_BUTLIN_SECID  (Index) 
--
--  Dependencies: 
--   TSECTION_BUTLINE (Table)
--
CREATE INDEX ASU.TSECTION_BUTLIN_SECID ON ASU.TSECTION_BUTLINE
(FK_SECID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- TSECTIONS_BUTLINE_BEFORE_INSER  (Trigger) 
--
--  Dependencies: 
--   TSECTION_BUTLINE (Table)
--
CREATE OR REPLACE TRIGGER ASU."TSECTIONS_BUTLINE_BEFORE_INSER" 
 BEFORE 
 INSERT
 ON ASU.TSECTION_BUTLINE  REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
begin
select seq_tsection_butline.NEXTVAL into :new.fk_id from dual;
end;
/
SHOW ERRORS;


