DROP TABLE ASU.TSLUCH_DBF_GRID CASCADE CONSTRAINTS
/

--
-- TSLUCH_DBF_GRID  (Table) 
--
CREATE TABLE ASU.TSLUCH_DBF_GRID
(
  OWN                VARCHAR2(83 BYTE),
  TYPE_FIN           VARCHAR2(83 BYTE),
  GLOBAL_ID          VARCHAR2(83 BYTE),
  YEAR               VARCHAR2(83 BYTE),
  MONTH              VARCHAR2(83 BYTE),
  LPU_ID             VARCHAR2(83 BYTE),
  TER_OKATO          VARCHAR2(13 BYTE),
  OKATOG             VARCHAR2(25 BYTE),
  OKATOP             VARCHAR2(25 BYTE),
  LPU_NAPR           VARCHAR2(83 BYTE),
  PERSON_IDL         VARCHAR2(83 BYTE),
  ID_ILL             NUMBER,
  POLICYSER          VARCHAR2(23 BYTE),
  POLICYNUM          VARCHAR2(43 BYTE),
  FAM                VARCHAR2(53 BYTE),
  IM                 VARCHAR2(53 BYTE),
  OTCH               VARCHAR2(53 BYTE),
  DATE_B_DAY         VARCHAR2(23 BYTE),
  POL                VARCHAR2(5 BYTE),
  DIA_SD             VARCHAR2(19 BYTE),
  DIA_O              VARCHAR2(19 BYTE),
  DIA_C              VARCHAR2(19 BYTE),
  DIA_E              VARCHAR2(19 BYTE),
  DATE_S             VARCHAR2(23 BYTE),
  DATE_E             VARCHAR2(23 BYTE),
  D_DATE_E           DATE,
  DATE_NAPR          VARCHAR2(23 BYTE),
  DESTROY            VARCHAR2(83 BYTE),
  Q_Z                VARCHAR2(83 BYTE),
  RES_G              VARCHAR2(83 BYTE),
  RESG_DOP           VARCHAR2(83 BYTE),
  DISP               VARCHAR2(83 BYTE),
  TOTAL              VARCHAR2(41 BYTE),
  N_NAPR             VARCHAR2(41 BYTE),
  N_MAP              VARCHAR2(41 BYTE),
  N_MAP_AMB          VARCHAR2(41 BYTE),
  OPER_ID            VARCHAR2(83 BYTE),
  NARKOZ_ID          VARCHAR2(83 BYTE),
  SMK_NAME           VARCHAR2(103 BYTE),
  SN_PASP            VARCHAR2(43 BYTE),
  Q_U                VARCHAR2(83 BYTE),
  D_TYPE             VARCHAR2(13 BYTE),
  P_ID_ILL           NUMBER,
  LPU_INTR           VARCHAR2(83 BYTE),
  TFOMS_REG          VARCHAR2(83 BYTE),
  DATE_NPOL          VARCHAR2(23 BYTE),
  DATE_EPOL          VARCHAR2(23 BYTE),
  STAT_P             VARCHAR2(83 BYTE),
  NOVOR              VARCHAR2(23 BYTE),
  FAMP               VARCHAR2(63 BYTE),
  IMP                VARCHAR2(43 BYTE),
  OTP                VARCHAR2(43 BYTE),
  C_OKSM             VARCHAR2(9 BYTE),
  C_DOC              VARCHAR2(83 BYTE),
  S_DOC              VARCHAR2(23 BYTE),
  N_DOC              VARCHAR2(19 BYTE),
  R_NAME             VARCHAR2(303 BYTE),
  C_NAME             VARCHAR2(303 BYTE),
  Q_NP               VARCHAR2(83 BYTE),
  NP_NAME            VARCHAR2(303 BYTE),
  Q_UL               VARCHAR2(83 BYTE),
  UL_NAME            VARCHAR2(303 BYTE),
  DOM                VARCHAR2(17 BYTE),
  KOR                VARCHAR2(13 BYTE),
  KV                 VARCHAR2(13 BYTE),
  STAT_Z             VARCHAR2(83 BYTE),
  V_MU               VARCHAR2(83 BYTE),
  PR_MP              VARCHAR2(83 BYTE),
  TYPE_MP            VARCHAR2(83 BYTE),
  PRVS               VARCHAR2(83 BYTE),
  VID_P              VARCHAR2(83 BYTE),
  Q_OGRN             VARCHAR2(33 BYTE),
  STANDARD           VARCHAR2(83 BYTE),
  MR                 VARCHAR2(203 BYTE),
  SNILS              VARCHAR2(31 BYTE),
  POLP               VARCHAR2(5 BYTE),
  DRP                VARCHAR2(23 BYTE),
  TYPE_V_MU          VARCHAR2(83 BYTE),
  AMB_PR             VARCHAR2(10 BYTE),
  DISP_KAT           VARCHAR2(10 BYTE),
  GZ                 VARCHAR2(10 BYTE),
  DISP_RES           VARCHAR2(10 BYTE),
  MODERN             VARCHAR2(83 BYTE),
  SUM_MODERN         VARCHAR2(41 BYTE),
  Z$FL_POLY          VARCHAR2(43 BYTE),
  OWN_SOURCE         NUMBER,
  TYPE_FIN_SOURCE    NUMBER,
  GLOBAL_ID_SOURCE   NUMBER,
  YEAR_SOURCE        NUMBER,
  MONTH_SOURCE       NUMBER,
  LPU_ID_SOURCE      NUMBER,
  TER_OKATO_SOURCE   NUMBER,
  OKATOG_SOURCE      NUMBER,
  OKATOP_SOURCE      NUMBER,
  LPU_NAPR_SOURCE    NUMBER,
  PERSON_IDL_SOURCE  NUMBER,
  POLICYSER_SOURCE   NUMBER,
  POLICYNUM_SOURCE   NUMBER,
  FAM_SOURCE         NUMBER,
  IM_SOURCE          NUMBER,
  OTCH_SOURCE        NUMBER,
  DATE_B_DAY_SOURCE  NUMBER,
  POL_SOURCE         NUMBER,
  DIA_SD_SOURCE      NUMBER,
  DIA_O_SOURCE       NUMBER,
  DIA_C_SOURCE       NUMBER,
  DIA_E_SOURCE       NUMBER,
  DATE_S_SOURCE      NUMBER,
  DATE_E_SOURCE      NUMBER,
  DATE_NAPR_SOURCE   NUMBER,
  DESTROY_SOURCE     NUMBER,
  Q_Z_SOURCE         NUMBER,
  RES_G_SOURCE       NUMBER,
  RESG_DOP_SOURCE    NUMBER,
  DISP_SOURCE        NUMBER,
  TOTAL_SOURCE       NUMBER,
  N_NAPR_SOURCE      NUMBER,
  N_MAP_SOURCE       NUMBER,
  N_MAP_AMB_SOURCE   NUMBER,
  OPER_ID_SOURCE     NUMBER,
  NARKOZ_ID_SOURCE   NUMBER,
  SMK_NAME_SOURCE    NUMBER,
  SN_PASP_SOURCE     NUMBER,
  Q_U_SOURCE         NUMBER,
  D_TYPE_SOURCE      NUMBER,
  LPU_INTR_SOURCE    NUMBER,
  TFOMS_REG_SOURCE   NUMBER,
  DATE_NPOL_SOURCE   NUMBER,
  DATE_EPOL_SOURCE   NUMBER,
  STAT_P_SOURCE      NUMBER,
  NOVOR_SOURCE       NUMBER,
  FAMP_SOURCE        NUMBER,
  IMP_SOURCE         NUMBER,
  OTP_SOURCE         NUMBER,
  C_OKSM_SOURCE      NUMBER,
  C_DOC_SOURCE       NUMBER,
  S_DOC_SOURCE       NUMBER,
  N_DOC_SOURCE       NUMBER,
  R_NAME_SOURCE      NUMBER,
  C_NAME_SOURCE      NUMBER,
  Q_NP_SOURCE        NUMBER,
  NP_NAME_SOURCE     NUMBER,
  Q_UL_SOURCE        NUMBER,
  UL_NAME_SOURCE     NUMBER,
  DOM_SOURCE         NUMBER,
  KOR_SOURCE         NUMBER,
  KV_SOURCE          NUMBER,
  STAT_Z_SOURCE      NUMBER,
  V_MU_SOURCE        NUMBER,
  PR_MP_SOURCE       NUMBER,
  TYPE_MP_SOURCE     NUMBER,
  PRVS_SOURCE        NUMBER,
  VID_P_SOURCE       NUMBER,
  Q_OGRN_SOURCE      NUMBER,
  STANDARD_SOURCE    NUMBER,
  MR_SOURCE          NUMBER,
  SNILS_SOURCE       NUMBER,
  POLP_SOURCE        NUMBER,
  DRP_SOURCE         NUMBER,
  TYPE_V_MU_SOURCE   NUMBER,
  AMB_PR_SOURCE      NUMBER,
  DISP_KAT_SOURCE    NUMBER,
  GZ_SOURCE          NUMBER,
  DISP_RES_SOURCE    NUMBER,
  MODERN_SOURCE      NUMBER,
  SUM_MODERN_SOURCE  NUMBER,
  Z$FL_POLY_SOURCE   NUMBER,
  SMO                VARCHAR2(255 BYTE),
  FN_IS_LOAD         NUMBER,
  FN_IS_CALC         NUMBER,
  FN_IS_BOTH         NUMBER,
  FN_IS_ERR          NUMBER,
  FN_SOURCE          NUMBER,
  FK_ID_TS           NUMBER,
  FK_ID_TSL          NUMBER,
  N_TOTAL_TS         NUMBER(10,2),
  N_TOTAL_TSL        NUMBER(10,2),
  N_SUM_MODERN_TS    NUMBER(10,2),
  N_SUM_MODERN_TSL   NUMBER(10,2),
  N_SUM_MODERN_SBJ   NUMBER,
  N_SUM_MODERN_FED   NUMBER,
  KOL_EOSUM          NUMBER,
  KOL_EOSUM_L        NUMBER,
  FK_GROUPSLUCHID    NUMBER(15),
  FN_AGEINYEARS      NUMBER,
  FL_COMPEARUSL      NUMBER,
  SMK_ID_P           VARCHAR2(10 BYTE),
  TOTAL_SMO          NUMBER(10,2),
  SANK_KOD           NUMBER(5),
  UDR_MEK            NUMBER(10,2),
  UDR_MEE            NUMBER(10,2),
  UDR_EKMP           NUMBER(10,2),
  SHTR_MEK           NUMBER(10,2),
  SHTR_MEE           NUMBER(10,2),
  SHTR_EKMP          NUMBER(10,2),
  MSG_DEF            VARCHAR2(120 BYTE),
  N_OWN_TS           NUMBER,
  KOL_MUSUM          NUMBER,
  KOL_MUSUM_L        NUMBER,
  FK_INSURDOCID      NUMBER,
  FK_PACID           NUMBER,
  POLICYSER_TSL      VARCHAR2(100 BYTE),
  POLICYNUM_TSL      VARCHAR2(100 BYTE),
  OWN_TSL            NUMBER(1),
  VID_P_TSL          NUMBER(1),
  FK_SOTRID          NUMBER(15),
  FC_SOTRFAM         VARCHAR2(30 BYTE),
  FC_SOTRNAME        VARCHAR2(30 BYTE),
  FC_SOTROTCH        VARCHAR2(30 BYTE),
  FK_OTDELID_VYP     NUMBER(15),
  FC_OTDELNAME_VYP   VARCHAR2(255 BYTE)
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             8K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


--
-- I_SLUCH_DBF_GRID_FK_ID_TS  (Index) 
--
--  Dependencies: 
--   TSLUCH_DBF_GRID (Table)
--
CREATE INDEX ASU.I_SLUCH_DBF_GRID_FK_ID_TS ON ASU.TSLUCH_DBF_GRID
(FK_ID_TS)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- I_SLUCH_DBF_GRID_FK_ID_TSL  (Index) 
--
--  Dependencies: 
--   TSLUCH_DBF_GRID (Table)
--
CREATE INDEX ASU.I_SLUCH_DBF_GRID_FK_ID_TSL ON ASU.TSLUCH_DBF_GRID
(FK_ID_TSL)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


