DROP TABLE ASU.TSMIDDIAG CASCADE CONSTRAINTS
/

--
-- TSMIDDIAG  (Table) 
--
CREATE TABLE ASU.TSMIDDIAG
(
  SMID        NUMBER,
  OWNERID     NUMBER,
  MKBID       VARCHAR2(6 BYTE),
  FC_NAME     VARCHAR2(255 BYTE),
  PATOLOGYID  NUMBER,
  FC_SYNONYM  VARCHAR2(100 BYTE),
  FL_DEL      NUMBER(1)
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1040K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON COLUMN ASU.TSMIDDIAG.PATOLOGYID IS 'from TDic'
/


--
-- TSMID_ID  (Index) 
--
--  Dependencies: 
--   TSMIDDIAG (Table)
--
CREATE UNIQUE INDEX ASU.TSMID_ID ON ASU.TSMIDDIAG
(SMID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          256K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- TSMID_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   TSMIDDIAG (Table)
--
CREATE OR REPLACE TRIGGER ASU."TSMID_BEFORE_INSERT" 
 BEFORE 
 INSERT
 ON ASU.TSMIDDIAG  REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
Begin
  null;
  /* disabled by TimurLan SELECT SEQ_TSMID.NEXTVAL INTO :NEW.SMID FROM DUAL;*/
End;
/
SHOW ERRORS;


