DROP TABLE ASU.TSMID_SOOTV_OKB_SHABL CASCADE CONSTRAINTS
/

--
-- TSMID_SOOTV_OKB_SHABL  (Table) 
--
CREATE TABLE ASU.TSMID_SOOTV_OKB_SHABL
(
  FK_ID         NUMBER                          NOT NULL,
  FK_SMIDMAIN   NUMBER,
  FK_SMIDOKB    NUMBER,
  FK_SMIDFIRST  NUMBER
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          18720K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TSMID_SOOTV_OKB_SHABL IS 'Соответствия смидов для переноса шаблонов на СОКБ: Косов'
/

COMMENT ON COLUMN ASU.TSMID_SOOTV_OKB_SHABL.FK_SMIDMAIN IS 'Ветки последние'
/

COMMENT ON COLUMN ASU.TSMID_SOOTV_OKB_SHABL.FK_SMIDOKB IS 'Ветки до падения'
/

COMMENT ON COLUMN ASU.TSMID_SOOTV_OKB_SHABL.FK_SMIDFIRST IS 'Первоночальные ветки'
/


--
-- TSMID_SOOTV_OKB_SHABL$FK_ID  (Index) 
--
--  Dependencies: 
--   TSMID_SOOTV_OKB_SHABL (Table)
--
CREATE UNIQUE INDEX ASU.TSMID_SOOTV_OKB_SHABL$FK_ID ON ASU.TSMID_SOOTV_OKB_SHABL
(FK_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- TSMIDSOOTVOKBSHABL$FK_SMIDMAIN  (Index) 
--
--  Dependencies: 
--   TSMID_SOOTV_OKB_SHABL (Table)
--
CREATE INDEX ASU.TSMIDSOOTVOKBSHABL$FK_SMIDMAIN ON ASU.TSMID_SOOTV_OKB_SHABL
(FK_SMIDMAIN)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- TSMID_SOOTV_OKB_SH_BEF_INSERT  (Trigger) 
--
--  Dependencies: 
--   TSMID_SOOTV_OKB_SHABL (Table)
--
CREATE OR REPLACE TRIGGER ASU."TSMID_SOOTV_OKB_SH_BEF_INSERT"
  BEFORE INSERT ON ASU.TSMID_SOOTV_OKB_SHABL   REFERENCING OLD AS OLD NEW AS NEW
  FOR EACH ROW
BEGIN
  IF (:NEW.FK_ID IS NULL OR :NEW.FK_ID < 0) THEN
    SELECT SEQ_TSMID_SOOTV_OKB_SHABL.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
  END IF;
End;
/
SHOW ERRORS;


