DROP TABLE ASU.TSMID_RIGHTS_DISMISSED CASCADE CONSTRAINTS
/

--
-- TSMID_RIGHTS_DISMISSED  (Table) 
--
CREATE TABLE ASU.TSMID_RIGHTS_DISMISSED
(
  FK_SOTRID  NUMBER,
  FK_SMID    NUMBER,
  FK_ID      NUMBER                             NOT NULL
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          18720K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TSMID_RIGHTS_DISMISSED IS 'опюбю днярсою янрпсдмхйнб й мюгмювемхъл(сбнкеммше) Autor:Kosov E.'
/

COMMENT ON COLUMN ASU.TSMID_RIGHTS_DISMISSED.FK_SOTRID IS 'TSOTR.FK_ID'
/

COMMENT ON COLUMN ASU.TSMID_RIGHTS_DISMISSED.FK_SMID IS 'TSMID.FK_ID'
/

COMMENT ON COLUMN ASU.TSMID_RIGHTS_DISMISSED.FK_ID IS 'SEQUENCE=[SEQ_T_EXP]'
/


