DROP TABLE ASU.TSMSPEC CASCADE CONSTRAINTS
/

--
-- TSMSPEC  (Table) 
--
CREATE TABLE ASU.TSMSPEC
(
  FK_ID      NUMBER(15),
  FK_SMID    NUMBER(15),
  FK_SPECID  NUMBER(15)
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          520K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON COLUMN ASU.TSMSPEC.FK_ID IS 'SEQUENCE=[SEQ_TSMSPEC]'
/


--
-- TSMSPEC_BEFOR_INSERT  (Trigger) 
--
--  Dependencies: 
--   TSMSPEC (Table)
--
CREATE OR REPLACE TRIGGER ASU."TSMSPEC_BEFOR_INSERT" 
  BEFORE INSERT
  ON ASU.TSMSPEC   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
Begin
  SELECT SEQ_TSMSPEC.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


