DROP TABLE ASU.TSTANDARTDIAG CASCADE CONSTRAINTS
/

--
-- TSTANDARTDIAG  (Table) 
--
CREATE TABLE ASU.TSTANDARTDIAG
(
  FK_ID          NUMBER                         NOT NULL,
  FK_PACID       NUMBER,
  FK_DIAGID      NUMBER,
  FK_STANDARTID  NUMBER,
  FD_DATE        DATE
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON COLUMN ASU.TSTANDARTDIAG.FK_ID IS 'SEQUENCE=[SEQ_TSTANDARTDIAG]'
/

COMMENT ON COLUMN ASU.TSTANDARTDIAG.FK_PACID IS 'TKARTA.FK_ID'
/

COMMENT ON COLUMN ASU.TSTANDARTDIAG.FK_DIAGID IS 'TSMID.FK_ID'
/

COMMENT ON COLUMN ASU.TSTANDARTDIAG.FK_STANDARTID IS 'TSTANDART.FK_ID'
/

COMMENT ON COLUMN ASU.TSTANDARTDIAG.FD_DATE IS 'Дата'
/


--
-- TSTANDARTDIAG_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   TSTANDARTDIAG (Table)
--
CREATE OR REPLACE TRIGGER ASU."TSTANDARTDIAG_BEFORE_INSERT" 
 BEFORE
  INSERT
 ON asu.tstandartdiag
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
  SELECT SEQ_TSTANDARTDIAG.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
END;
/
SHOW ERRORS;


GRANT SELECT ON ASU.TSTANDARTDIAG TO EXCH43
/

