DROP TABLE ASU.TTEMPTABIMPXLS33706 CASCADE CONSTRAINTS
/

--
-- TTEMPTABIMPXLS33706  (Table) 
--
CREATE TABLE ASU.TTEMPTABIMPXLS33706
(
  FC_NAME      VARCHAR2(300 BYTE),
  F2           VARCHAR2(300 BYTE),
  F3           VARCHAR2(300 BYTE),
  F4           VARCHAR2(300 BYTE),
  FK_MKB10     VARCHAR2(300 BYTE),
  FC_TYPE      VARCHAR2(300 BYTE),
  FN_ORDER     NUMBER,
  FL_REQUIRED  VARCHAR2(300 BYTE),
  FC_SYNONIM   VARCHAR2(300 BYTE)
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TTEMPTABIMPXLS33706 IS 'Temporary Table for Imp_XLSfiles (by Gray)'
/


