DROP TABLE ASU.TTMPRASP CASCADE CONSTRAINTS
/

--
-- TTMPRASP  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE ASU.TTMPRASP
(
  FD_TIME            DATE,
  FL_SEX             NUMBER,
  FN_COUNT           NUMBER(9),
  FT_TIME            VARCHAR2(2 BYTE),
  FT_MIN             VARCHAR2(2 BYTE),
  FK_ID              NUMBER(9)                  NOT NULL,
  FK_KABINETTALONID  NUMBER
)
ON COMMIT PRESERVE ROWS
NOCACHE
/

COMMENT ON TABLE ASU.TTMPRASP IS ' '
/

COMMENT ON COLUMN ASU.TTMPRASP.FD_TIME IS 'Дата'
/

COMMENT ON COLUMN ASU.TTMPRASP.FL_SEX IS 'Пол'
/

COMMENT ON COLUMN ASU.TTMPRASP.FN_COUNT IS 'Кол-во человек'
/

COMMENT ON COLUMN ASU.TTMPRASP.FT_TIME IS 'Час'
/

COMMENT ON COLUMN ASU.TTMPRASP.FT_MIN IS 'Минуты'
/

COMMENT ON COLUMN ASU.TTMPRASP.FK_ID IS 'SEQUENCE=[SEQ_TTMPRASP]'
/

COMMENT ON COLUMN ASU.TTMPRASP.FK_KABINETTALONID IS 'Для кардиоцентра. Если часто выгоняют из одного кабинета в другой'
/


--
-- TTMPRASP_BEFOR_INSERT  (Trigger) 
--
--  Dependencies: 
--   TTMPRASP (Table)
--
CREATE OR REPLACE TRIGGER ASU."TTMPRASP_BEFOR_INSERT" 
BEFORE INSERT
ON ASU.TTMPRASP REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
Begin
  select SEQ_TTMPRASP.NEXTVAL into :new.FK_ID from Dual;
End;
/
SHOW ERRORS;


