DROP TABLE ASU.TTMP_LGOT_MEDVED CASCADE CONSTRAINTS
/

--
-- TTMP_LGOT_MEDVED  (Table) 
--
CREATE TABLE ASU.TTMP_LGOT_MEDVED
(
  UCOD        VARCHAR2(25 BYTE),
  SS          VARCHAR2(14 BYTE),
  SN_POL      VARCHAR2(25 BYTE),
  FAM         VARCHAR2(40 BYTE),
  IM          VARCHAR2(40 BYTE),
  OT          VARCHAR2(40 BYTE),
  W           VARCHAR2(1 BYTE),
  DR          VARCHAR2(10 BYTE),
  SN_DOC      VARCHAR2(16 BYTE),
  C_DOC       VARCHAR2(2 BYTE),
  OKATO_REG   VARCHAR2(5 BYTE),
  ADRES       VARCHAR2(200 BYTE),
  DOM         VARCHAR2(7 BYTE),
  KOR         VARCHAR2(5 BYTE),
  KV          VARCHAR2(5 BYTE),
  OGRN        VARCHAR2(13 BYTE),
  IDPR        VARCHAR2(1 BYTE),
  DINCLUDED   DATE,
  DEXCLUDED   DATE,
  IDLOCALITY  VARCHAR2(13 BYTE),
  IDSTREET    VARCHAR2(17 BYTE)
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.TTMP_LGOT_MEDVED IS 'Льготники для выгрузки'
/

COMMENT ON COLUMN ASU.TTMP_LGOT_MEDVED.UCOD IS 'Региональный код льготника '
/

COMMENT ON COLUMN ASU.TTMP_LGOT_MEDVED.SS IS 'СНИЛС'
/

COMMENT ON COLUMN ASU.TTMP_LGOT_MEDVED.SN_POL IS 'Серия и номер полиса ОМС'
/

COMMENT ON COLUMN ASU.TTMP_LGOT_MEDVED.FAM IS 'Фамилия'
/

COMMENT ON COLUMN ASU.TTMP_LGOT_MEDVED.IM IS 'Имя'
/

COMMENT ON COLUMN ASU.TTMP_LGOT_MEDVED.OT IS 'Отчество'
/

COMMENT ON COLUMN ASU.TTMP_LGOT_MEDVED.W IS 'Пол'
/

COMMENT ON COLUMN ASU.TTMP_LGOT_MEDVED.DR IS 'Дата рождения (ГГГГ/ММ/ДД)'
/

COMMENT ON COLUMN ASU.TTMP_LGOT_MEDVED.SN_DOC IS 'Серия и номер документа, удостоверяющего личность'
/

COMMENT ON COLUMN ASU.TTMP_LGOT_MEDVED.C_DOC IS 'Тип документа, удостоверяющего личность '
/

COMMENT ON COLUMN ASU.TTMP_LGOT_MEDVED.OKATO_REG IS 'Код территории проживания'
/

COMMENT ON COLUMN ASU.TTMP_LGOT_MEDVED.ADRES IS 'Адрес по месту регистрации'
/

COMMENT ON COLUMN ASU.TTMP_LGOT_MEDVED.DOM IS 'Номер дома (владение)'
/

COMMENT ON COLUMN ASU.TTMP_LGOT_MEDVED.KOR IS 'Корпус/строение'
/

COMMENT ON COLUMN ASU.TTMP_LGOT_MEDVED.KV IS 'Квартира/комната'
/

COMMENT ON COLUMN ASU.TTMP_LGOT_MEDVED.OGRN IS 'ОГРН лечебного учреждения'
/

COMMENT ON COLUMN ASU.TTMP_LGOT_MEDVED.IDPR IS 'Код места проживания (1-город, 2-село)'
/

COMMENT ON COLUMN ASU.TTMP_LGOT_MEDVED.DINCLUDED IS 'Дата включения в регистр'
/

COMMENT ON COLUMN ASU.TTMP_LGOT_MEDVED.DEXCLUDED IS 'Дата исключения из регистра'
/

COMMENT ON COLUMN ASU.TTMP_LGOT_MEDVED.IDLOCALITY IS 'Код населенного пункта (согласно КЛАДР)'
/

COMMENT ON COLUMN ASU.TTMP_LGOT_MEDVED.IDSTREET IS 'Код улицы (согласно КЛАДР)'
/


