DROP TABLE ASU.TUCHVRACH CASCADE CONSTRAINTS
/

--
-- TUCHVRACH  (Table) 
--
CREATE TABLE ASU.TUCHVRACH
(
  FK_ID          NUMBER(16)                     NOT NULL,
  FK_UCHASTOKID  NUMBER(16)                     NOT NULL,
  FK_VRACHID     NUMBER(16)                     NOT NULL
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          520K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON COLUMN ASU.TUCHVRACH.FK_ID IS 'SEQUENCE=[SEQ_TUCHVRACH]'
/


--
-- TUCHVRACH_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   TUCHVRACH (Table)
--
CREATE OR REPLACE TRIGGER ASU."TUCHVRACH_BEFORE_INSERT" 
  BEFORE INSERT
  ON ASU.TUCHVRACH   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
Begin
  SELECT SEQ_TUCHVRACH.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


