DROP TABLE ASU.TUCHASTOK CASCADE CONSTRAINTS
/

--
-- TUCHASTOK  (Table) 
--
CREATE TABLE ASU.TUCHASTOK
(
  FK_ID       NUMBER(16)                        NOT NULL,
  FC_NAME     VARCHAR2(30 BYTE),
  FC_OPIS     VARCHAR2(100 BYTE),
  FK_KORPID   NUMBER(16)                        NOT NULL,
  FK_VRACHID  NUMBER(16)
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          560K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON COLUMN ASU.TUCHASTOK.FK_ID IS 'SEQUENCE=[SEQ_TUCHASTOK]'
/


--
-- TUCHSTOK_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   TUCHASTOK (Table)
--
CREATE OR REPLACE TRIGGER ASU."TUCHSTOK_BEFORE_INSERT" 
  BEFORE INSERT
  ON ASU.TUCHASTOK   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
Begin
  SELECT SEQ_TUCHASTOK.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


--
-- TUCHSTOK_BEFORE_DELETE  (Trigger) 
--
--  Dependencies: 
--   TUCHASTOK (Table)
--
CREATE OR REPLACE TRIGGER ASU."TUCHSTOK_BEFORE_DELETE" 
  BEFORE DELETE
  ON ASU.TUCHASTOK   REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
Begin
  DELETE FROM TUCHVRACH WHERE FK_UCHASTOKID=:OLD.FK_ID;
End;
/
SHOW ERRORS;


