DROP TABLE ASU.TVIDPOLIS CASCADE CONSTRAINTS
/

--
-- TVIDPOLIS  (Table) 
--
CREATE TABLE ASU.TVIDPOLIS
(
  FK_ID    NUMBER(16)                           NOT NULL,
  FC_NAME  VARCHAR2(30 BYTE)
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          520K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON COLUMN ASU.TVIDPOLIS.FK_ID IS 'SEQUENCE=[SEQ_TVIDPOLIS]'
/


--
-- TVIDPOLIS_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   TVIDPOLIS (Table)
--
CREATE OR REPLACE TRIGGER ASU."TVIDPOLIS_BEFORE_INSERT" 
BEFORE INSERT
ON ASU.TVIDPOLIS REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
Begin
  SELECT SEQ_TVIDPOLIS.NEXTVAL INTO :NEW.FK_ID FROM DUAL;
End;
/
SHOW ERRORS;


