DROP TABLE ASU.TWORK_PLACE_HISTORY CASCADE CONSTRAINTS
/

--
-- TWORK_PLACE_HISTORY  (Table) 
--
CREATE TABLE ASU.TWORK_PLACE_HISTORY
(
  FK_ID          NUMBER,
  FK_COMPANYID   NUMBER,
  FK_OTDELID     NUMBER,
  FK_DOLGNOSTID  NUMBER,
  FC_RABOTA      VARCHAR2(4000 BYTE),
  FK_PEPLID      NUMBER,
  FP_MAIN        NUMBER                         DEFAULT 0,
  FD_BEGIN       DATE,
  FD_END         DATE
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON COLUMN ASU.TWORK_PLACE_HISTORY.FP_MAIN IS 'Вид работы 1 - основная, 0 - по совместительству'
/


--
-- TWPHISTORY_BEFORE_INSERT  (Trigger) 
--
--  Dependencies: 
--   TWORK_PLACE_HISTORY (Table)
--
CREATE OR REPLACE TRIGGER ASU."TWPHISTORY_BEFORE_INSERT"
BEFORE INSERT
ON ASU.TWORK_PLACE_HISTORY REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
Begin
  select SEQ_TWORK_PLACE_HISTORY.nextval into :new.fk_id from dual;
End;
/
SHOW ERRORS;


