DROP TABLE ASU.VID_ANAL CASCADE CONSTRAINTS
/

--
-- VID_ANAL  (Table) 
--
CREATE TABLE ASU.VID_ANAL
(
  PROFIL_     VARCHAR2(1 BYTE),
  KLASS       VARCHAR2(6 BYTE),
  KOD_ANAL    VARCHAR2(6 BYTE),
  NOMER_P_P   VARCHAR2(6 BYTE),
  NAIMENOWAN  VARCHAR2(40 BYTE),
  SOKR_NAIME  VARCHAR2(10 BYTE),
  NORMA_WREM  VARCHAR2(6 BYTE),
  KOD_REZTA   VARCHAR2(6 BYTE),
  EST__RASHE  VARCHAR2(1 BYTE),
  REZERW      VARCHAR2(6 BYTE)
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


