DROP TABLE ASU.VNAZ_COST_HEAL_CUT CASCADE CONSTRAINTS
/

--
-- VNAZ_COST_HEAL_CUT  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE ASU.VNAZ_COST_HEAL_CUT
(
  TYPEDOC_SYN  VARCHAR2(50 BYTE)
)
ON COMMIT PRESERVE ROWS
NOCACHE
/

COMMENT ON TABLE ASU.VNAZ_COST_HEAL_CUT IS '“аблица содержит синонимы типов оплаты, услуги относ€щиес€ к этим типам будут исключены из asu.vnaz_cost Author:Efimov'
/


--
-- I_NAZ_COST_HEAL_CUT_TDS  (Index) 
--
--  Dependencies: 
--   VNAZ_COST_HEAL_CUT (Table)
--
CREATE INDEX ASU.I_NAZ_COST_HEAL_CUT_TDS ON ASU.VNAZ_COST_HEAL_CUT
(TYPEDOC_SYN)
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON ASU.VNAZ_COST_HEAL_CUT TO EXCH79
/

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON ASU.VNAZ_COST_HEAL_CUT TO PILE
/

