DROP TABLE ASU.VRESAN CASCADE CONSTRAINTS
/

--
-- VRESAN  (Table) 
--
CREATE TABLE ASU.VRESAN
(
  FN_ED        NUMBER(5,2),
  FK_NAZID     NUMBER(15),
  FP_SEX       NUMBER,
  FK_NAZSOSID  NUMBER(15),
  FD_INS       DATE,
  FK_RAZDID    NUMBER,
  FK_PACID     NUMBER(15),
  FN_VOZR      NUMBER,
  FL_PATFIRST  NUMBER,
  FL_AMB       NUMBER,
  FK_OTDELID   NUMBER,
  FK_ISSLID    NUMBER,
  FN_RES       NUMBER,
  FN_RES2      NUMBER,
  FK_PATID     NUMBER,
  FK_SMID      NUMBER,
  FK_ID        NUMBER,
  FK_NAPRID    NUMBER,
  FD_OUT       DATE,
  FK_COLID     NUMBER(9)
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


