DROP TABLE ASU.WEB_SCHEDULE_GRAPH CASCADE CONSTRAINTS
/

--
-- WEB_SCHEDULE_GRAPH  (Table) 
--
CREATE TABLE ASU.WEB_SCHEDULE_GRAPH
(
  SCHEDULE_ID  CHAR(36 BYTE),
  GRAPH_ID     NUMBER
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


--
-- IX_SCHEDULE_GRAPH$GRAPH_ID  (Index) 
--
--  Dependencies: 
--   WEB_SCHEDULE_GRAPH (Table)
--
CREATE INDEX ASU.IX_SCHEDULE_GRAPH$GRAPH_ID ON ASU.WEB_SCHEDULE_GRAPH
(GRAPH_ID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


