DROP TABLE ASU.WEB_LPU_OTDEL CASCADE CONSTRAINTS
/

--
-- WEB_LPU_OTDEL  (Table) 
--
CREATE TABLE ASU.WEB_LPU_OTDEL
(
  LPU    VARCHAR2(36 BYTE),
  OTDEL  NUMBER
)
TABLESPACE USR
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE ASU.WEB_LPU_OTDEL IS 'Сопоставление отделений с ЛПУ'
/

COMMENT ON COLUMN ASU.WEB_LPU_OTDEL.LPU IS 'OID ЛПУ из Самозапись.ру'
/

COMMENT ON COLUMN ASU.WEB_LPU_OTDEL.OTDEL IS 'Код отделения из МИС Пациент'
/


