unit PkgPrihrash;

// Oracle Package Wizard 1.0.3
// File PkgPrihrash.pas generated by Vladim on 13.11.2002 1:36:03
// This unit contains interface objects for oracle package MED.PKG_PRIHRASH
// WARNING: Modifications made to this file will be lost after regeneration!

interface

uses Classes, SysUtils, Oracle;

type
  TPkgPrihrash = class(TOracleCustomPackage)
  public
    function  Checkenter(Amedicid: Double; Adpid: Double): Double;
    function  Checkinkart(Akartid: Double; Adpid: Double): Double;
    function  Checkmoidtreb(Amoid: Double; Adocplanid: Double;
      AfpDezh: Double): Double;
    function  Createshablon(AfpVid: Double; AfpVidmove: Integer): Integer;
    procedure Dodel(Adpid: Double);
// добавил Воронов О.А.
// Удаление всех упоминаний о приходе - документ, движение партий и сами партии.
    procedure doDel_DOC_DPC_Kart(Adpid: Double);
    
    procedure Dodelrash(Akartid: Double; Adpcid: Double);
    procedure Dodelkart(Akartid: Double; Adpcid: Double);
    procedure Dodelnull(Amoid: Double; Adpid: Double);
    procedure Dodeltreb(Adpid: Double);
    procedure Dodeltrebvid(Adpid: Double);
    procedure Dodelvoz(Adpid: Double);
    procedure Doset(AfnPrice: Double; const AfcComment: string;
      const AfcDoc: string; AFDInvoiceDATA: TDateTime; AfdData: TDateTime; Amotoid, amo_group_toid: Double;
      Adpid: Double; Amofromid, amo_group_fromid: Double; Prizn: Double; SpisanieVid: Double = 0);
//    function  Dosetnewprice(Adpid: Double; Akol: Double; Aprice: Double;
//      Akartid: Double; Adata: TDateTime; Adpcid: Double; Prizn: Double): Double;
    function  DoSetPrihRash(Adpid: Double; Akol: Double; Aprice: Double;
      Akartid: Double; Adpcid: Double; Prizn: Double; aReservDocID : Double = -1): Double;
    procedure DoDelkartmedic(Adpid: Double; Amedicid: Double);
    function  Getcheckcountkart(Adpid: Double): Double;
    function  Getrashdata(Adata: TDateTime): TDateTime;
    function  Getsumdoc(Adpid: Double; Prizn: Double): Double;
    function  GetCurdate(Adpid: Double): TDateTime;
    function  GetDate(Adpid: Double): TDateTime;
    function  GetFullnamepac(AfkPacid: Double): string;
    function  GetKoldpid(Adpid: Double; Amedicid: Double): Double;
    function  GetLastnewprice(Akartid: Double; Adata: TDateTime;
      Amoid: Double): Double;
    function  GetLastnewprice1(Akartid: Double; Adata: TDateTime): Double;
    function  GetMoidkart(Akartid: Double): Double;
    function  GetMoneystr(Source: Double): string;
    function  GetNewpricemedic(Adpid: Double; Amedicid: Double): Double;
    function  GetSumcurkl: Double;
    function  GetTrebkolmedic(Amedicid: Double; Adpid: Double;
      Amoid: Double; AfpDezh: Double): Double;
    procedure SetBegindocid(Adpid: Double; Amoid: Double; AfpDezh: Double);
    procedure SetDocid(Apacid: Double; Adocid: Double);
    procedure SetNewdate(Adpid: Double; Adata: TDateTime);
    function  SetTreb(Adpid: Double; Amoid: Double; Amotoid: Double;
	  Amedicid: Double; Atrebkol: Double; Acheck: Double; FlTreb: Double): Double;
	function Setsumdockart(nDPID: Double; nKartID: Double; nNewSum: Double): Double;
    procedure Create_treb(ADPID: Integer;AMOID: Integer);
    procedure SetUchgrInKartsByDoc ( ADpid : Double );
  procedure DO_AUTOFILL_PLAN ( pFK_TREBID, pFK_FINSOURCE_ID, pUseComplexAutoFill : Double; pFC_QUOTA_CODE : string; out pPLAN : TOracleObject ) ;
  procedure DO_AUTOFILL ( pDPID : Double; pPLAN : TOracleObject );
  published
    property Name;
    property Session;
    property Cursor;
  end;

var
  DefaultPLSQLTableSize: Integer = 100; // Default size of a PL/SQL Table

implementation

// PKG_PRIHRASH.SETSUMDOCKART
function TPkgPrihrash.Setsumdockart(nDPID: Double; nKartID: Double; nNewSum: Double): Double;
begin
  GetQuery;
  OCPQuery.DeclareVariable('function_result', otFloat);
  OCPQuery.DeclareVariable('NDPID', otFloat);
  OCPQuery.SetVariable('NDPID', Ndpid);
  OCPQuery.DeclareVariable('NKARTID', otFloat);
  OCPQuery.SetVariable('NKARTID', Nkartid);
  OCPQuery.DeclareVariable('NNEWSUM', otFloat);
  OCPQuery.SetVariable('NNEWSUM', Nnewsum);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  :function_result := "MED"."PKG_PRIHRASH"."SETSUMDOCKART"(');
  OCPQuery.SQL.Add('    NDPID => :NDPID,');
  OCPQuery.SQL.Add('    NKARTID => :NKARTID,');
  OCPQuery.SQL.Add('    NNEWSUM => :NNEWSUM);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  Result := ConvertVariant(OCPQuery.GetVariable('function_result'));
end;

// PKG_PRIHRASH.CHECKENTER
function TPkgPrihrash.Checkenter(Amedicid: Double; Adpid: Double): Double;
begin
  GetQuery;
  OCPQuery.DeclareVariable('function_result', otFloat);
  OCPQuery.DeclareVariable('AMEDICID', otFloat);
  OCPQuery.SetVariable('AMEDICID', Amedicid);
  OCPQuery.DeclareVariable('ADPID', otFloat);
  OCPQuery.SetVariable('ADPID', Adpid);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  :function_result := "MED"."PKG_PRIHRASH"."CHECKENTER"(');
  OCPQuery.SQL.Add('    AMEDICID => :AMEDICID,');
  OCPQuery.SQL.Add('    ADPID => :ADPID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  Result := ConvertVariant(OCPQuery.GetVariable('function_result'));
end;

// PKG_PRIHRASH.CHECKINKART
function TPkgPrihrash.Checkinkart(Akartid: Double; Adpid: Double): Double;
begin
  GetQuery;
  OCPQuery.DeclareVariable('function_result', otFloat);
  OCPQuery.DeclareVariable('AKARTID', otFloat);
  OCPQuery.SetVariable('AKARTID', Akartid);
  OCPQuery.DeclareVariable('ADPID', otFloat);
  OCPQuery.SetVariable('ADPID', Adpid);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  :function_result := "MED"."PKG_PRIHRASH"."CHECKINKART"(');
  OCPQuery.SQL.Add('    AKARTID => :AKARTID,');
  OCPQuery.SQL.Add('    ADPID => :ADPID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  Result := ConvertVariant(OCPQuery.GetVariable('function_result'));
end;

// PKG_PRIHRASH.CHECKMOIDTREB
function TPkgPrihrash.Checkmoidtreb(Amoid: Double; Adocplanid: Double; 
  AfpDezh: Double): Double;
begin
  GetQuery;
  OCPQuery.DeclareVariable('function_result', otFloat);
  OCPQuery.DeclareVariable('AMOID', otFloat);
  OCPQuery.SetVariable('AMOID', Amoid);
  OCPQuery.DeclareVariable('ADOCPLANID', otFloat);
  OCPQuery.SetVariable('ADOCPLANID', Adocplanid);
  OCPQuery.DeclareVariable('AFP_DEZH', otFloat);
  OCPQuery.SetVariable('AFP_DEZH', AfpDezh);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  :function_result := "MED"."PKG_PRIHRASH"."CHECKMOIDTREB"(');
  OCPQuery.SQL.Add('    AMOID => :AMOID,');
  OCPQuery.SQL.Add('    ADOCPLANID => :ADOCPLANID,');
  OCPQuery.SQL.Add('    AFP_DEZH => :AFP_DEZH);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  Result := ConvertVariant(OCPQuery.GetVariable('function_result'));
end;

// PKG_PRIHRASH.CREATESHABLON
function TPkgPrihrash.Createshablon(AfpVid: Double; AfpVidmove: Integer): Integer;
begin
  GetQuery;
  OCPQuery.DeclareVariable('function_result', otFloat);
  OCPQuery.DeclareVariable('AFP_VID', otFloat);
  OCPQuery.SetVariable('AFP_VID', AfpVid);
  OCPQuery.DeclareVariable('AFP_VIDMOVE', otFloat);
  OCPQuery.SetVariable('AFP_VIDMOVE', AfpVidmove);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  :function_result := "MED"."PKG_PRIHRASH"."CREATESHABLON"(');
  OCPQuery.SQL.Add('    AFP_VID => :AFP_VID,');
  OCPQuery.SQL.Add('    AFP_VIDMOVE => :AFP_VIDMOVE);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  Result := TRUNC(ConvertVariant(OCPQuery.GetVariable('function_result')));
end;

// PKG_PRIHRASH.DODEL
procedure TPkgPrihrash.Dodel(Adpid: Double);
begin
  GetQuery;
  OCPQuery.DeclareVariable('ADPID', otFloat);
  OCPQuery.SetVariable('ADPID', Adpid);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  "MED"."PKG_PRIHRASH"."DODEL"(ADPID => :ADPID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
end;

// добавил Воронов О.А.
// Удаление всех упоминаний о приходе - документ, движение партий и сами партии.
// PKG_PRIHRASH.doDel_DOC_DPC_Kart
procedure TPkgPrihrash.doDel_DOC_DPC_Kart(Adpid: Double);
begin
  GetQuery;
  OCPQuery.DeclareVariable('ADPID', otFloat);
  OCPQuery.SetVariable('ADPID', Adpid);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  "MED"."PKG_PRIHRASH"."DODEL_DOC_DPC_KART"(ADPID => :ADPID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
end;


// PKG_PRIHRASH.DODELKART
procedure TPkgPrihrash.Dodelrash(Akartid: Double; Adpcid: Double);
begin
  GetQuery;
  OCPQuery.DeclareVariable('AKARTID', otFloat);
  OCPQuery.SetVariable('AKARTID', Akartid);
  OCPQuery.DeclareVariable('ADPCID', otFloat);
  OCPQuery.SetVariable('ADPCID', Adpcid);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  "MED"."PKG_PRIHRASH"."DODELRASH"(');
  OCPQuery.SQL.Add('    AKARTID => :AKARTID,');
  OCPQuery.SQL.Add('    ADPCID => :ADPCID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
end;

// PKG_PRIHRASH.DODELKART
procedure TPkgPrihrash.Dodelkart(Akartid: Double; Adpcid: Double);
begin
  GetQuery;
  OCPQuery.DeclareVariable('AKARTID', otFloat);
  OCPQuery.SetVariable('AKARTID', Akartid);
  OCPQuery.DeclareVariable('ADPCID', otFloat);
  OCPQuery.SetVariable('ADPCID', Adpcid);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  "MED"."PKG_PRIHRASH"."DODELKART"(');
  OCPQuery.SQL.Add('    AKARTID => :AKARTID,');
  OCPQuery.SQL.Add('    ADPCID => :ADPCID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
end;

// PKG_PRIHRASH.DODELNULL
procedure TPkgPrihrash.Dodelnull(Amoid: Double; Adpid: Double);
begin
  GetQuery;
  OCPQuery.DeclareVariable('AMOID', otFloat);
  OCPQuery.SetVariable('AMOID', Amoid);
  OCPQuery.DeclareVariable('ADPID', otFloat);
  OCPQuery.SetVariable('ADPID', Adpid);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  "MED"."PKG_PRIHRASH"."DODELNULL"(');
  OCPQuery.SQL.Add('    AMOID => :AMOID,');
  OCPQuery.SQL.Add('    ADPID => :ADPID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
end;

// PKG_PRIHRASH.DODELTREB
procedure TPkgPrihrash.Dodeltreb(Adpid: Double);
begin
  GetQuery;
  OCPQuery.DeclareVariable('ADPID', otFloat);
  OCPQuery.SetVariable('ADPID', Adpid);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  "MED"."PKG_PRIHRASH"."DODELTREB"(ADPID => :ADPID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
end;

// PKG_PRIHRASH.DODELTREBVID
procedure TPkgPrihrash.Dodeltrebvid(Adpid: Double);
begin
  GetQuery;
  OCPQuery.DeclareVariable('ADPID', otFloat);
  OCPQuery.SetVariable('ADPID', Adpid);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  "MED"."PKG_PRIHRASH"."DODELTREBVID"(ADPID => :ADPID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
end;

// PKG_PRIHRASH.DODELVOZ
procedure TPkgPrihrash.Dodelvoz(Adpid: Double);
begin
  GetQuery;
  OCPQuery.DeclareVariable('ADPID', otFloat);
  OCPQuery.SetVariable('ADPID', Adpid);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  "MED"."PKG_PRIHRASH"."DODELVOZ"(ADPID => :ADPID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
end;

// PKG_PRIHRASH.DOSET
procedure TPkgPrihrash.Doset(AfnPrice: Double; const AfcComment: string;
  const AfcDoc: string; AFDInvoiceDATA: TDateTime; AfdData: TDateTime; Amotoid, amo_group_toid: Double;
  Adpid: Double; Amofromid, amo_group_fromid: Double; Prizn: Double; SpisanieVid: Double = 0);
begin
  GetQuery;
  OCPQuery.DeclareVariable('AFN_PRICE', otFloat);
  OCPQuery.SetVariable('AFN_PRICE', AfnPrice);
  OCPQuery.DeclareVariable('AFC_COMMENT', otString);
  OCPQuery.SetVariable('AFC_COMMENT', AfcComment);
  OCPQuery.DeclareVariable('AFC_DOC', otString);
  OCPQuery.SetVariable('AFC_DOC', AfcDoc);
  OCPQuery.DeclareVariable('AFD_DATA', otDate);
  OCPQuery.SetVariable('AFD_DATA', AfdData);
  OCPQuery.DeclareVariable('AFD_InvoiceDATA', otDate);
  OCPQuery.SetVariable('AFD_InvoiceDATA', AFDInvoiceDATA);
  OCPQuery.DeclareVariable('AMOTOID', otFloat);
  OCPQuery.SetVariable('AMOTOID', Amotoid);
  OCPQuery.DeclareVariable('AMO_GROUP_TOID', otFloat);
  OCPQuery.SetVariable('AMO_GROUP_TOID', amo_group_toid);
  OCPQuery.DeclareVariable('ADPID', otFloat);
  OCPQuery.SetVariable('ADPID', Adpid);
  OCPQuery.DeclareVariable('AMOFROMID', otFloat);
  OCPQuery.SetVariable('AMOFROMID', Amofromid);
  OCPQuery.DeclareVariable('AMO_GROUP_FROMID', otFloat);
  OCPQuery.SetVariable('AMO_GROUP_FROMID', amo_group_fromid);
  OCPQuery.DeclareVariable('PRIZN', otFloat);
  OCPQuery.SetVariable('PRIZN', Prizn);
  OCPQuery.DeclareVariable('SPISANIEVID', otFloat);
  OCPQuery.SetVariable('SPISANIEVID', SpisanieVid);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  "MED"."PKG_PRIHRASH"."DOSET"(');
  OCPQuery.SQL.Add('    AFN_PRICE => :AFN_PRICE,');
  OCPQuery.SQL.Add('    AFC_COMMENT => :AFC_COMMENT,');
  OCPQuery.SQL.Add('    AFC_DOC => :AFC_DOC,');
  OCPQuery.SQL.Add('    AFD_InvoiceDATA => :AFD_InvoiceDATA,');
  OCPQuery.SQL.Add('    AFD_DATA => :AFD_DATA,');
  OCPQuery.SQL.Add('    AMOTOID => :AMOTOID,');
  OCPQuery.SQL.Add('    AMO_GROUP_TOID => :AMO_GROUP_TOID,');
  OCPQuery.SQL.Add('    ADPID => :ADPID,');
  OCPQuery.SQL.Add('    AMOFROMID => :AMOFROMID,');
  OCPQuery.SQL.Add('    AMO_GROUP_FROMID => :AMO_GROUP_FROMID,');
  OCPQuery.SQL.Add('    PRIZN => :PRIZN,');
  OCPQuery.SQL.Add('    SPISANIEVID => :SPISANIEVID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
end;

// PKG_PRIHRASH.DOSETNEWPRICE
//function TPkgPrihrash.Dosetnewprice(Adpid: Double; Akol: Double; Aprice: Double;
//  Akartid: Double; Adata: TDateTime; Adpcid: Double; Prizn: Double): Double;
//begin
//  GetQuery;
//  OCPQuery.DeclareVariable('function_result', otFloat);
//  OCPQuery.DeclareVariable('ADPID', otFloat);
//  OCPQuery.SetVariable('ADPID', Adpid);
//  OCPQuery.DeclareVariable('AKOL', otFloat);
//  OCPQuery.SetVariable('AKOL', Akol);
//  OCPQuery.DeclareVariable('APRICE', otFloat);
//  OCPQuery.SetVariable('APRICE', Aprice);
//  OCPQuery.DeclareVariable('AKARTID', otFloat);
//  OCPQuery.SetVariable('AKARTID', Akartid);
//  OCPQuery.DeclareVariable('ADATA', otDate);
//  OCPQuery.SetVariable('ADATA', Adata);
//  OCPQuery.DeclareVariable('ADPCID', otFloat);
//  OCPQuery.SetVariable('ADPCID', Adpcid);
//  OCPQuery.DeclareVariable('PRIZN', otFloat);
//  OCPQuery.SetVariable('PRIZN', Prizn);
//  OCPQuery.SQL.Add('begin');
//  OCPQuery.SQL.Add('  :function_result := "MED"."PKG_PRIHRASH"."DOSETNEWPRICE"(');
//  OCPQuery.SQL.Add('    ADPID => :ADPID,');
//  OCPQuery.SQL.Add('    AKOL => :AKOL,');
//  OCPQuery.SQL.Add('    APRICE => :APRICE,');
//  OCPQuery.SQL.Add('    AKARTID => :AKARTID,');
//  OCPQuery.SQL.Add('    ADATA => :ADATA,');
//  OCPQuery.SQL.Add('    ADPCID => :ADPCID,');
//  OCPQuery.SQL.Add('    PRIZN => :PRIZN);');
//  OCPQuery.SQL.Add('end;');
//  OCPQuery.Execute;
//  Result := ConvertVariant(OCPQuery.GetVariable('function_result'));
//end;

// PKG_PRIHRASH.DO_DELKARTMEDIC
procedure TPkgPrihrash.DoDelkartmedic(Adpid: Double; Amedicid: Double);
begin
  GetQuery;
  OCPQuery.DeclareVariable('ADPID', otFloat);
  OCPQuery.SetVariable('ADPID', Adpid);
  OCPQuery.DeclareVariable('AMEDICID', otFloat);
  OCPQuery.SetVariable('AMEDICID', Amedicid);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  "MED"."PKG_PRIHRASH"."DO_DELKARTMEDIC"(');
  OCPQuery.SQL.Add('    ADPID => :ADPID,');
  OCPQuery.SQL.Add('    AMEDICID => :AMEDICID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
end;

// PKG_PRIHRASH.GETCHECKCOUNTKART
function TPkgPrihrash.Getcheckcountkart(Adpid: Double): Double;
begin
  GetQuery;
  OCPQuery.DeclareVariable('function_result', otFloat);
  OCPQuery.DeclareVariable('ADPID', otFloat);
  OCPQuery.SetVariable('ADPID', Adpid);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  :function_result := "MED"."PKG_PRIHRASH"."GETCHECKCOUNTKART"(ADPID => :ADPID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  Result := ConvertVariant(OCPQuery.GetVariable('function_result'));
end;

// PKG_PRIHRASH.GETRASHDATA
function TPkgPrihrash.Getrashdata(Adata: TDateTime): TDateTime;
begin
  GetQuery;
  OCPQuery.DeclareVariable('function_result', otDate);
  OCPQuery.DeclareVariable('ADATA', otDate);
  OCPQuery.SetVariable('ADATA', Adata);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  :function_result := "MED"."PKG_PRIHRASH"."GETRASHDATA"(ADATA => :ADATA);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  Result := ConvertVariant(OCPQuery.GetVariable('function_result'));
end;

// PKG_PRIHRASH.GETSUMDOC
function TPkgPrihrash.Getsumdoc(Adpid: Double; Prizn: Double): Double;
begin
  GetQuery;
  OCPQuery.DeclareVariable('function_result', otFloat);
  OCPQuery.DeclareVariable('ADPID', otFloat);
  OCPQuery.SetVariable('ADPID', Adpid);
  OCPQuery.DeclareVariable('PRIZN', otFloat);
  OCPQuery.SetVariable('PRIZN', Prizn);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  :function_result := "MED"."PKG_PRIHRASH"."GETSUMDOC"(');
  OCPQuery.SQL.Add('    ADPID => :ADPID,');
  OCPQuery.SQL.Add('    PRIZN => :PRIZN);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  Result := ConvertVariant(OCPQuery.GetVariable('function_result'));
end;

// PKG_PRIHRASH.GET_CURDATE
function TPkgPrihrash.GetCurdate(Adpid: Double): TDateTime;
begin
  GetQuery;
  OCPQuery.DeclareVariable('function_result', otDate);
  OCPQuery.DeclareVariable('ADPID', otFloat);
  OCPQuery.SetVariable('ADPID', Adpid);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  :function_result := "MED"."PKG_PRIHRASH"."GET_CURDATE"(ADPID => :ADPID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  Result := ConvertVariant(OCPQuery.GetVariable('function_result'));
end;

// PKG_PRIHRASH.GET_DATE
function TPkgPrihrash.GetDate(Adpid: Double): TDateTime;
begin
  GetQuery;
  OCPQuery.DeclareVariable('function_result', otDate);
  OCPQuery.DeclareVariable('ADPID', otFloat);
  OCPQuery.SetVariable('ADPID', Adpid);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  :function_result := "MED"."PKG_PRIHRASH"."GET_DATE"(ADPID => :ADPID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  Result := ConvertVariant(OCPQuery.GetVariable('function_result'));
end;

// PKG_PRIHRASH.GET_FULLNAMEPAC
function TPkgPrihrash.GetFullnamepac(AfkPacid: Double): string;
begin
  GetQuery;
  OCPQuery.DeclareVariable('function_result', otString);
  OCPQuery.DeclareVariable('AFK_PACID', otFloat);
  OCPQuery.SetVariable('AFK_PACID', AfkPacid);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  :function_result := "MED"."PKG_PRIHRASH"."GET_FULLNAMEPAC"(AFK_PACID => :AFK_PACID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  Result := ConvertVariant(OCPQuery.GetVariable('function_result'));
end;

// PKG_PRIHRASH.GET_KOLDPID
function TPkgPrihrash.GetKoldpid(Adpid: Double; Amedicid: Double): Double;
begin
  GetQuery;
  OCPQuery.DeclareVariable('function_result', otFloat);
  OCPQuery.DeclareVariable('ADPID', otFloat);
  OCPQuery.SetVariable('ADPID', Adpid);
  OCPQuery.DeclareVariable('AMEDICID', otFloat);
  OCPQuery.SetVariable('AMEDICID', Amedicid);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  :function_result := "MED"."PKG_PRIHRASH"."GET_KOLDPID"(');
  OCPQuery.SQL.Add('    ADPID => :ADPID,');
  OCPQuery.SQL.Add('    AMEDICID => :AMEDICID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  Result := ConvertVariant(OCPQuery.GetVariable('function_result'));
end;

// PKG_PRIHRASH.GET_LASTNEWPRICE
function TPkgPrihrash.GetLastnewprice(Akartid: Double; Adata: TDateTime; 
  Amoid: Double): Double;
begin
  GetQuery;
  OCPQuery.DeclareVariable('function_result', otFloat);
  OCPQuery.DeclareVariable('AKARTID', otFloat);
  OCPQuery.SetVariable('AKARTID', Akartid);
  OCPQuery.DeclareVariable('ADATA', otDate);
  OCPQuery.SetVariable('ADATA', Adata);
  OCPQuery.DeclareVariable('AMOID', otFloat);
  OCPQuery.SetVariable('AMOID', Amoid);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  :function_result := "MED"."PKG_PRIHRASH"."GET_LASTNEWPRICE"(');
  OCPQuery.SQL.Add('    AKARTID => :AKARTID,');
  OCPQuery.SQL.Add('    ADATA => :ADATA,');
  OCPQuery.SQL.Add('    AMOID => :AMOID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  Result := ConvertVariant(OCPQuery.GetVariable('function_result'));
end;

// PKG_PRIHRASH.GET_LASTNEWPRICE1
function TPkgPrihrash.GetLastnewprice1(Akartid: Double; Adata: TDateTime): Double;
begin
  GetQuery;
  OCPQuery.DeclareVariable('function_result', otFloat);
  OCPQuery.DeclareVariable('AKARTID', otFloat);
  OCPQuery.SetVariable('AKARTID', Akartid);
  OCPQuery.DeclareVariable('ADATA', otDate);
  OCPQuery.SetVariable('ADATA', Adata);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  :function_result := "MED"."PKG_PRIHRASH"."GET_LASTNEWPRICE1"(');
  OCPQuery.SQL.Add('    AKARTID => :AKARTID,');
  OCPQuery.SQL.Add('    ADATA => :ADATA);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  Result := ConvertVariant(OCPQuery.GetVariable('function_result'));
end;

// PKG_PRIHRASH.GET_MOIDKART
function TPkgPrihrash.GetMoidkart(Akartid: Double): Double;
begin
  GetQuery;
  OCPQuery.DeclareVariable('function_result', otFloat);
  OCPQuery.DeclareVariable('AKARTID', otFloat);
  OCPQuery.SetVariable('AKARTID', Akartid);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  :function_result := "MED"."PKG_PRIHRASH"."GET_MOIDKART"(AKARTID => :AKARTID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  Result := ConvertVariant(OCPQuery.GetVariable('function_result'));
end;

// PKG_PRIHRASH.GET_MONEYSTR
function TPkgPrihrash.GetMoneystr(Source: Double): string;
begin
  GetQuery;
  OCPQuery.DeclareVariable('function_result', otString);
  OCPQuery.DeclareVariable('SOURCE', otFloat);
  OCPQuery.SetVariable('SOURCE', Source);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  :function_result := "MED"."PKG_PRIHRASH"."GET_MONEYSTR"(SOURCE => :SOURCE);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  Result := ConvertVariant(OCPQuery.GetVariable('function_result'));
end;

// PKG_PRIHRASH.GET_NEWPRICEMEDIC
function TPkgPrihrash.GetNewpricemedic(Adpid: Double; Amedicid: Double): Double;
begin
  GetQuery;
  OCPQuery.DeclareVariable('function_result', otFloat);
  OCPQuery.DeclareVariable('ADPID', otFloat);
  OCPQuery.SetVariable('ADPID', Adpid);
  OCPQuery.DeclareVariable('AMEDICID', otFloat);
  OCPQuery.SetVariable('AMEDICID', Amedicid);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  :function_result := "MED"."PKG_PRIHRASH"."GET_NEWPRICEMEDIC"(');
  OCPQuery.SQL.Add('    ADPID => :ADPID,');
  OCPQuery.SQL.Add('    AMEDICID => :AMEDICID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  Result := ConvertVariant(OCPQuery.GetVariable('function_result'));
end;

// PKG_PRIHRASH.GET_SUMCURKL
function TPkgPrihrash.GetSumcurkl: Double;
begin
  GetQuery;
  OCPQuery.DeclareVariable('function_result', otFloat);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  :function_result := "MED"."PKG_PRIHRASH"."GET_SUMCURKL";');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  Result := ConvertVariant(OCPQuery.GetVariable('function_result'));
end;

// PKG_PRIHRASH.GET_TREBKOLMEDIC
function TPkgPrihrash.GetTrebkolmedic(Amedicid: Double; Adpid: Double; 
  Amoid: Double; AfpDezh: Double): Double;
begin
  GetQuery;
  OCPQuery.DeclareVariable('function_result', otFloat);
  OCPQuery.DeclareVariable('AMEDICID', otFloat);
  OCPQuery.SetVariable('AMEDICID', Amedicid);
  OCPQuery.DeclareVariable('ADPID', otFloat);
  OCPQuery.SetVariable('ADPID', Adpid);
  OCPQuery.DeclareVariable('AMOID', otFloat);
  OCPQuery.SetVariable('AMOID', Amoid);
  OCPQuery.DeclareVariable('AFP_DEZH', otFloat);
  OCPQuery.SetVariable('AFP_DEZH', AfpDezh);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  :function_result := "MED"."PKG_PRIHRASH"."GET_TREBKOLMEDIC"(');
  OCPQuery.SQL.Add('    AMEDICID => :AMEDICID,');
  OCPQuery.SQL.Add('    ADPID => :ADPID,');
  OCPQuery.SQL.Add('    AMOID => :AMOID,');
  OCPQuery.SQL.Add('    AFP_DEZH => :AFP_DEZH);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  Result := ConvertVariant(OCPQuery.GetVariable('function_result'));
end;

// PKG_PRIHRASH.SET_BEGINDOCID
procedure TPkgPrihrash.SetBegindocid(Adpid: Double; Amoid: Double; AfpDezh: Double);
begin
  GetQuery;
  OCPQuery.DeclareVariable('ADPID', otFloat);
  OCPQuery.SetVariable('ADPID', Adpid);
  OCPQuery.DeclareVariable('AMOID', otFloat);
  OCPQuery.SetVariable('AMOID', Amoid);
  OCPQuery.DeclareVariable('AFP_DEZH', otFloat);
  OCPQuery.SetVariable('AFP_DEZH', AfpDezh);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  "MED"."PKG_PRIHRASH"."SET_BEGINDOCID"(');
  OCPQuery.SQL.Add('    ADPID => :ADPID,');
  OCPQuery.SQL.Add('    AMOID => :AMOID,');
  OCPQuery.SQL.Add('    AFP_DEZH => :AFP_DEZH);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
end;

// PKG_PRIHRASH.SET_DOCID
procedure TPkgPrihrash.SetDocid(Apacid: Double; Adocid: Double);
begin
  GetQuery;
  OCPQuery.DeclareVariable('APACID', otFloat);
  OCPQuery.SetVariable('APACID', Apacid);
  OCPQuery.DeclareVariable('ADOCID', otFloat);
  OCPQuery.SetVariable('ADOCID', Adocid);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  "MED"."PKG_PRIHRASH"."SET_DOCID"(');
  OCPQuery.SQL.Add('    APACID => :APACID,');
  OCPQuery.SQL.Add('    ADOCID => :ADOCID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
end;

// PKG_PRIHRASH.SET_NEWDATE
procedure TPkgPrihrash.SetNewdate(Adpid: Double; Adata: TDateTime);
begin
  GetQuery;
  OCPQuery.DeclareVariable('ADPID', otFloat);
  OCPQuery.SetVariable('ADPID', Adpid);
  OCPQuery.DeclareVariable('ADATA', otDate);
  OCPQuery.SetVariable('ADATA', Adata);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  "MED"."PKG_PRIHRASH"."SET_NEWDATE"(');
  OCPQuery.SQL.Add('    ADPID => :ADPID,');
  OCPQuery.SQL.Add('    ADATA => :ADATA);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
end;

// PKG_PRIHRASH.SET_TREB
function TPkgPrihrash.SetTreb(Adpid: Double; Amoid: Double; Amotoid: Double;
  Amedicid: Double; Atrebkol: Double; Acheck: Double; FlTreb: Double): Double;
begin
  GetQuery;
  OCPQuery.DeclareVariable('function_result', otFloat);
  OCPQuery.DeclareVariable('ADPID', otFloat);
  OCPQuery.SetVariable('ADPID', Adpid);
  OCPQuery.DeclareVariable('AMOID', otFloat);
  OCPQuery.SetVariable('AMOID', Amoid);
  OCPQuery.DeclareVariable('AMOTOID', otFloat);
  OCPQuery.SetVariable('AMOTOID', Amotoid);
  OCPQuery.DeclareVariable('AMEDICID', otFloat);
  OCPQuery.SetVariable('AMEDICID', Amedicid);
  OCPQuery.DeclareVariable('ATREBKOL', otFloat);
  OCPQuery.SetVariable('ATREBKOL', Atrebkol);
  OCPQuery.DeclareVariable('ACHECK', otFloat);
  OCPQuery.SetVariable('ACHECK', Acheck);
  OCPQuery.DeclareVariable('FL_TREB', otFloat);
  OCPQuery.SetVariable('FL_TREB', FlTreb);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  :function_result := "MED"."PKG_PRIHRASH"."SET_TREB"(');
  OCPQuery.SQL.Add('    ADPID => :ADPID,');
  OCPQuery.SQL.Add('    AMOID => :AMOID,');
  OCPQuery.SQL.Add('    AMOTOID => :AMOTOID,');
  OCPQuery.SQL.Add('    AMEDICID => :AMEDICID,');
  OCPQuery.SQL.Add('    ATREBKOL => :ATREBKOL,');
  OCPQuery.SQL.Add('    ACHECK => :ACHECK,');
  OCPQuery.SQL.Add('    FL_TREB => :FL_TREB);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  Result := ConvertVariant(OCPQuery.GetVariable('function_result'));
end;

procedure TPkgPrihrash.Create_treb(ADPID, AMOID: Integer);
begin
  GetQuery;
  OCPQuery.DeclareVariable('ADPID', otInteger);
  OCPQuery.DeclareVariable('AMOID', otInteger);
  OCPQuery.SetVariable('ADPID',ADPID);
  OCPQuery.SetVariable('AMOID',AMOID);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('   "MED"."PKG_PRIHRASH"."CREATE_TREB"(');
  OCPQuery.SQL.Add('    ADPID => :ADPID,');
  OCPQuery.SQL.Add('    AMOID => :AMOID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
end;

function TPkgPrihrash.DoSetPrihRash(Adpid, Akol, Aprice, Akartid, Adpcid, Prizn: Double;  aReservDocID : Double = -1): Double;
begin
  GetQuery;
  OCPQuery.DeclareVariable('function_result', otFloat);
  OCPQuery.DeclareVariable('ADPID', otFloat);
  OCPQuery.SetVariable('ADPID', Adpid);
  OCPQuery.DeclareVariable('AKOL', otFloat);
  OCPQuery.SetVariable('AKOL', Akol);
  OCPQuery.DeclareVariable('APRICE', otFloat);
  OCPQuery.SetVariable('APRICE', Aprice);
  OCPQuery.DeclareVariable('AKARTID', otFloat);
  OCPQuery.SetVariable('AKARTID', Akartid);

  OCPQuery.DeclareVariable('ADPCID', otFloat);
  OCPQuery.SetVariable('ADPCID', Adpcid);
  OCPQuery.DeclareVariable('PRIZN', otFloat);
  OCPQuery.SetVariable('PRIZN', Prizn);
  OCPQuery.DeclareVariable('ARESERVDOCID', otFloat);
  OCPQuery.SetVariable('ARESERVDOCID', aReservDocID);

  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  :function_result := "MED"."PKG_PRIHRASH"."DOSETPRIHRASH"(');
  OCPQuery.SQL.Add('    ADPID => :ADPID,');
  OCPQuery.SQL.Add('    AKOL => :AKOL,');
  OCPQuery.SQL.Add('    APRICE => :APRICE,');
  OCPQuery.SQL.Add('    AKARTID => :AKARTID,');
  OCPQuery.SQL.Add('    ADPCID => :ADPCID,');
  OCPQuery.SQL.Add('    PRIZN => :PRIZN,');
  OCPQuery.SQL.Add('    ARESERVDOCID => :ARESERVDOCID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  Result := ConvertVariant(OCPQuery.GetVariable('function_result'));
end;

// pkg_prihrash.DoSetUchgrInKartsByDoc
procedure TPkgPrihrash.SetUchgrInKartsByDoc( ADpid: Double);
begin
  try
    GetQuery;
    with OCPQuery do
    begin
      DeclareVariable('ADPID', otFloat );
      SetVariable('ADPID', ADpid);
      SQL.Add('begin');
      SQL.Add('   "MED"."PKG_PRIHRASH"."DOSETUCHGRINKARTSBYDOC"(');
      SQL.Add('    ADPID => :ADPID);');
      SQL.Add('end;');
      Execute;
    end;
  finally

  end;
end;

procedure TPkgPrihrash.DO_AUTOFILL_PLAN( pFK_TREBID, pFK_FINSOURCE_ID, pUseComplexAutoFill : Double; pFC_QUOTA_CODE : string; out pPLAN : TOracleObject ) ;
begin
  try
    GetQuery;
    pPLAN := TOracleObject.Create( OCPQuery.Session, 'MED.O_RASH_AUTOFILLPLAN_TABLE', '' )  ;
    with OCPQuery do
    begin
      DeclareVariable( 'function_result', otObject );
      SetComplexVariable( 'function_result', pPLAN );
      DeclareAndSet('PFK_TREBID', otFloat, pFK_TREBID );
      DeclareAndSet('PFK_FINSOURCE_ID', otFloat, pFK_FINSOURCE_ID );
      DeclareAndSet('PUSECOMPLEXAUTOFILL', otFloat, pUseComplexAutoFill );
      DeclareAndSet('PFC_QUOTA_CODE', otString, pFC_QUOTA_CODE );

      SQL.Add('begin');
      SQL.Add('  :function_result := "MED"."PKG_PRIHRASH"."DO_AUTOFILL_PLAN"(');
      SQL.Add('    PFK_TREBID => :PFK_TREBID,');
      SQL.Add('    PFK_FINSOURCE_ID => :PFK_FINSOURCE_ID,');
      SQL.Add('    PUSECOMPLEXAUTOFILL => :PUSECOMPLEXAUTOFILL,');
      SQL.Add('    PFC_QUOTA_CODE => :PFC_QUOTA_CODE);');
      SQL.Add('end;');
      Execute;

      pPLAN := TOracleObject( GetComplexVariable ('function_result') );
    end;
  Except
    pPLAN := nil;
  end;
end;

procedure TPkgPrihrash.DO_AUTOFILL(pDPID: Double; pPLAN: TOracleObject);
begin
  try
    GetQuery;
    with OCPQuery do
    begin
      DeclareAndSet('PDPID', otFloat, pDPID );
      DeclareVariable( 'PAUTOFILLPLAN', otObject );
      SetComplexVariable( 'PAUTOFILLPLAN', pPLAN );

      SQL.Add('begin');
      SQL.Add('  "MED"."PKG_PRIHRASH"."DO_AUTOFILL"(');
      SQL.Add('    PDPID => :PDPID,');
      SQL.Add('    PAUTOFILLPLAN => :PAUTOFILLPLAN);');
      SQL.Add('end;');
      Execute;                                         
    end;
  finally
  end;   
end;



end.
