unit PKGTPOSTAV;

// Oracle Package Wizard 1.0.3
// File PKGTPOSTAV.pas generated by Delphi5 on 23.10.2006 11:34:15
// This unit contains interface objects for oracle package MED.PKGTPOSTAV
// WARNING: Modifications made to this file will be lost after regeneration!

interface

uses Classes, SysUtils, Oracle;

type
(*
PACKAGE PKGTPOSTAV
IS

/*
* Select Procedure for the table "MED"."TPOSTAV"
*/
   PROCEDURE tpostav_sel (
      postavid_in       IN       med.tpostav.postavid%TYPE,
      fc_name_out       OUT      med.tpostav.fc_name%TYPE,
      fc_bossdolg_out   OUT      med.tpostav.fc_bossdolg%TYPE,
      fc_bossfio_out    OUT      med.tpostav.fc_bossfio%TYPE
   );


/*
* Insert Procedure for the table "MED"."TPOSTAV"
*/
   FUNCTION tpostav_set (
      postavid_in      IN   med.tpostav.postavid%TYPE,
      fc_name_in       IN   med.tpostav.fc_name%TYPE,
      fc_bossdolg_in   IN   med.tpostav.fc_bossdolg%TYPE,
      fc_bossfio_in    IN   med.tpostav.fc_bossfio%TYPE
   )
      RETURN NUMBER;


/*
* Delete Procedure for the table "MED"."TPOSTAV"
*/
   PROCEDURE tpostav_del (postavid_in IN med.tpostav.postavid%TYPE);


/*
* GetNameByID
*/
   FUNCTION GetNameByID (postavid IN med.tpostav.postavid%TYPE)
      RETURN tpostav.fc_name%TYPE;

FUNCTION GET_PRODUCE_POSTAV
--получение POSTAVID ПОСТАВЩИКА, который производит медикаменты
   RETURN NUMBER;

END; /* pkgtpostav */
*)
  TPKGTPOSTAV = class(TOracleCustomPackage)
  public
    function  GETNAMEBYID(POSTAVID: Double): string;
    function  GETPRODUCEPOSTAV: Double;
    procedure TPOSTAVDEL(POSTAVIDIN: Double);
    procedure TPOSTAVSEL(POSTAVIDIN: Double; out FCNAMEOUT: string; 
      out FCBOSSDOLGOUT: string; out FCBOSSFIOOUT: string; out FCREKVIZITIOUT  : string );
    function  TPOSTAVSET(POSTAVIDIN: Double; const FCNAMEIN: string;
      const FCBOSSDOLGIN: string; const FCBOSSFIOIN: string;  const FCREKVIZITIIN  : string ): Double;
  published
    property Name;
    property Session;
    property Cursor;
  end;

var
  DefaultPLSQLTableSize: Integer = 100; // Default size of a PL/SQL Table

implementation

// PKGTPOSTAV.GETNAMEBYID
function TPKGTPOSTAV.GETNAMEBYID(POSTAVID: Double): string;
begin
  GetQuery;
  OCPQuery.DeclareVariable('function_result', otString);
  OCPQuery.DeclareVariable('POSTAVID', otFloat);
  OCPQuery.SetVariable('POSTAVID', POSTAVID);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  :function_result := "MED"."PKGTPOSTAV"."GETNAMEBYID"(POSTAVID => :POSTAVID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  Result := ConvertVariant(OCPQuery.GetVariable('function_result'));
end;

// PKGTPOSTAV.GET_PRODUCE_POSTAV
function TPKGTPOSTAV.GETPRODUCEPOSTAV: Double;
begin
  GetQuery;
  OCPQuery.DeclareVariable('function_result', otFloat);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  :function_result := "MED"."PKGTPOSTAV"."GET_PRODUCE_POSTAV";');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  Result := ConvertVariant(OCPQuery.GetVariable('function_result'));
end;

// PKGTPOSTAV.TPOSTAV_DEL
procedure TPKGTPOSTAV.TPOSTAVDEL(POSTAVIDIN: Double);
begin
  GetQuery;
  OCPQuery.DeclareVariable('POSTAVID_IN', otFloat);
  OCPQuery.SetVariable('POSTAVID_IN', POSTAVIDIN);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  "MED"."PKGTPOSTAV"."TPOSTAV_DEL"(POSTAVID_IN => :POSTAVID_IN);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
end;

// PKGTPOSTAV.TPOSTAV_SEL
procedure TPKGTPOSTAV.TPOSTAVSEL(POSTAVIDIN: Double; out FCNAMEOUT: string; 
  out FCBOSSDOLGOUT: string; out FCBOSSFIOOUT: string; out FCREKVIZITIOUT  : string );
begin
  GetQuery;
  OCPQuery.DeclareVariable('POSTAVID_IN', otFloat);
  OCPQuery.SetVariable('POSTAVID_IN', POSTAVIDIN);
  OCPQuery.DeclareVariable('FC_NAME_OUT', otString);
  OCPQuery.DeclareVariable('FC_BOSSDOLG_OUT', otString);
  OCPQuery.DeclareVariable('FC_BOSSFIO_OUT', otString);
  OCPQuery.DeclareVariable('FC_REKVIZITI_OUT', otString);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  "MED"."PKGTPOSTAV"."TPOSTAV_SEL"(');
  OCPQuery.SQL.Add('    POSTAVID_IN => :POSTAVID_IN,');
  OCPQuery.SQL.Add('    FC_NAME_OUT => :FC_NAME_OUT,');
  OCPQuery.SQL.Add('    FC_BOSSDOLG_OUT => :FC_BOSSDOLG_OUT,');
  OCPQuery.SQL.Add('    FC_BOSSFIO_OUT => :FC_BOSSFIO_OUT,');
  OCPQuery.SQL.Add('    FC_REKVIZITI_OUT => :FC_REKVIZITI_OUT);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  FCNAMEOUT := ConvertVariant(OCPQuery.GetVariable('FC_NAME_OUT'));
  FCBOSSDOLGOUT := ConvertVariant(OCPQuery.GetVariable('FC_BOSSDOLG_OUT'));
  FCBOSSFIOOUT := ConvertVariant(OCPQuery.GetVariable('FC_BOSSFIO_OUT'));
  FCREKVIZITIOUT := ConvertVariant(OCPQuery.GetVariable('FC_REKVIZITI_OUT'));
end;

// PKGTPOSTAV.TPOSTAV_SET
function TPKGTPOSTAV.TPOSTAVSET(POSTAVIDIN: Double; const FCNAMEIN: string; 
  const FCBOSSDOLGIN: string; const FCBOSSFIOIN: string;  const FCREKVIZITIIN  : string ): Double;
begin
  GetQuery;
  OCPQuery.DeclareVariable('function_result', otFloat);
  OCPQuery.DeclareVariable('POSTAVID_IN', otFloat);
  OCPQuery.SetVariable('POSTAVID_IN', POSTAVIDIN);
  OCPQuery.DeclareVariable('FC_NAME_IN', otString);
  OCPQuery.SetVariable('FC_NAME_IN', FCNAMEIN);
  OCPQuery.DeclareVariable('FC_BOSSDOLG_IN', otString);
  OCPQuery.SetVariable('FC_BOSSDOLG_IN', FCBOSSDOLGIN);
  OCPQuery.DeclareVariable('FC_BOSSFIO_IN', otString);
  OCPQuery.SetVariable('FC_BOSSFIO_IN', FCBOSSFIOIN);
  OCPQuery.DeclareVariable('FC_REKVIZITI_IN', otString);
  OCPQuery.SetVariable('FC_REKVIZITI_IN', FCREKVIZITIIN);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  :function_result := "MED"."PKGTPOSTAV"."TPOSTAV_SET"(');
  OCPQuery.SQL.Add('    POSTAVID_IN => :POSTAVID_IN,');
  OCPQuery.SQL.Add('    FC_NAME_IN => :FC_NAME_IN,');
  OCPQuery.SQL.Add('    FC_BOSSDOLG_IN => :FC_BOSSDOLG_IN,');
  OCPQuery.SQL.Add('    FC_BOSSFIO_IN => :FC_BOSSFIO_IN,');
  OCPQuery.SQL.Add('    FC_REKVIZITI_IN => :FC_REKVIZITI_IN);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  Result := ConvertVariant(OCPQuery.GetVariable('function_result'));
end;

end.
