unit PKGTEDIZM;

// Oracle Package Wizard 1.0.3
// File PKGTEDIZM.pas generated by Sergey on 14.04.2006 14:51:14
// This unit contains interface objects for oracle package MED.PKGTEDIZM
// WARNING: Modifications made to this file will be lost after regeneration!

interface

uses Classes, SysUtils, Oracle;

type
  TPKGTEDIZM = class(TOracleCustomPackage)
  public
    procedure DODELCASCADE(const PEIID: Variant);
    procedure DOSET(const PFCNAME: Variant; const PFCOKEI: Variant; 
      const PRLSDRUGFORM: Variant; const PEIID: Variant);
    procedure GETBYID(const PEIID: Variant; out PFCNAME: Variant; 
      out PFCOKEI: Variant; out PDRUGFORMID: Variant);
    function  GETNAMEBYID(const PEIID: Variant): Variant;
    function  GETNAMEBYIDOKEI(const PEIID: Variant): Variant;
  published
    property Name;
    property Session;
    property Cursor;
  end;

var
  DefaultPLSQLTableSize: Integer = 100; // Default size of a PL/SQL Table

implementation

// PKGTEDIZM.DODELCASCADE
procedure TPKGTEDIZM.DODELCASCADE(const PEIID: Variant);
begin
  GetQuery;
  OCPQuery.DeclareVariable('PEIID', otFloat);
  OCPQuery.SetVariable('PEIID', PEIID);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  "MED"."PKGTEDIZM"."DODELCASCADE"(PEIID => :PEIID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
end;

// PKGTEDIZM.DOSET
procedure TPKGTEDIZM.DOSET(const PFCNAME: Variant; const PFCOKEI: Variant; 
  const PRLSDRUGFORM: Variant; const PEIID: Variant);
begin
  GetQuery;
  OCPQuery.DeclareVariable('PFC_NAME', otString);
  OCPQuery.SetVariable('PFC_NAME', PFCNAME);
  OCPQuery.DeclareVariable('PFC_OKEI', otString);
  OCPQuery.SetVariable('PFC_OKEI', PFCOKEI);
  OCPQuery.DeclareVariable('PRLSDRUGFORM', otFloat);
  OCPQuery.SetVariable('PRLSDRUGFORM', PRLSDRUGFORM);
  OCPQuery.DeclareVariable('PEIID', otFloat);
  OCPQuery.SetVariable('PEIID', PEIID);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  "MED"."PKGTEDIZM"."DOSET"(');
  OCPQuery.SQL.Add('    PFC_NAME => :PFC_NAME,');
  OCPQuery.SQL.Add('    PFC_OKEI => :PFC_OKEI,');
  OCPQuery.SQL.Add('    PRLSDRUGFORM => :PRLSDRUGFORM,');
  OCPQuery.SQL.Add('    PEIID => :PEIID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
end;

// PKGTEDIZM.GETBYID
procedure TPKGTEDIZM.GETBYID(const PEIID: Variant; out PFCNAME: Variant; 
  out PFCOKEI: Variant; out PDRUGFORMID: Variant);
begin
  GetQuery;
  OCPQuery.DeclareVariable('PEIID', otFloat);
  OCPQuery.SetVariable('PEIID', PEIID);
  OCPQuery.DeclareVariable('PFC_NAME', otString);
  OCPQuery.DeclareVariable('PFC_OKEI', otString);
  OCPQuery.DeclareVariable('PDRUGFORMID', otFloat);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  "MED"."PKGTEDIZM"."GETBYID"(');
  OCPQuery.SQL.Add('    PEIID => :PEIID,');
  OCPQuery.SQL.Add('    PFC_NAME => :PFC_NAME,');
  OCPQuery.SQL.Add('    PFC_OKEI => :PFC_OKEI,');
  OCPQuery.SQL.Add('    PDRUGFORMID => :PDRUGFORMID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  PFCNAME := OCPQuery.GetVariable('PFC_NAME');
  PFCOKEI := OCPQuery.GetVariable('PFC_OKEI');
  PDRUGFORMID := OCPQuery.GetVariable('PDRUGFORMID');
end;

// PKGTEDIZM.GETNAMEBYID
function TPKGTEDIZM.GETNAMEBYID(const PEIID: Variant): Variant;
begin
  GetQuery;
  OCPQuery.DeclareVariable('function_result', otString);
  OCPQuery.DeclareVariable('PEIID', otFloat);
  OCPQuery.SetVariable('PEIID', PEIID);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  :function_result := "MED"."PKGTEDIZM"."GETNAMEBYID"(PEIID => :PEIID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  Result := OCPQuery.GetVariable('function_result');
end;

// PKGTEDIZM.GETNAMEBYIDOKEI
function TPKGTEDIZM.GETNAMEBYIDOKEI(const PEIID: Variant): Variant;
begin
  GetQuery;
  OCPQuery.DeclareVariable('function_result', otString);
  OCPQuery.DeclareVariable('PEIID', otFloat);
  OCPQuery.SetVariable('PEIID', PEIID);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  :function_result := "MED"."PKGTEDIZM"."GETNAMEBYIDOKEI"(PEIID => :PEIID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  Result := OCPQuery.GetVariable('function_result');
end;

end.
