unit PKGTMEDIC;

// Oracle Package Wizard 1.0.3
// File PKGTMEDIC.pas generated by Delphi5 on 04.11.2006 15:12:49
// This unit contains interface objects for oracle package MED.PKGTMEDIC
// WARNING: Modifications made to this file will be lost after regeneration!

interface

uses Classes, SysUtils, Oracle;

type
  TPKGTMEDIC = class(TOracleCustomPackage)
  public
    procedure DODEL(PMEDICID: Double);
    procedure DOINVISIBLE(PMEDICID: Double); //Added by Neronov A.S. 02.02.2012
    procedure DOVISIBLE(PMEDICID: Double); //Added by Neronov A.S. 29.05.2012
    procedure DOSETUCHGROUP(PUCHGRIP, PMEDICID: Double); //Added by Neronov A.S. 03.02.2012
    procedure DODELCASCADE(PMEDICID: Double);
    function  DOSET(const PFCNAME: string; const PFCCOMMENT: string;
      PUCHGRID: Double; PEIID: Double; PFARMGRID: Double; PLEVELID: Double;
      PFKTYPE: Double; PFKPAYTYPE: Double; PMEDICID: Double;
      PFKNOMENRLS: Double; const PFCEANCONE: string; PKOLFINU: Double;
      PFEDIZMID: Double; PFNDOZKA: Double; PFKDOZKAUNIT: Double;
      PFKNARCO: Double; PFLLGOTA: Double; const PFCNAMELAT: string; PFL_PRINT_LAT_NAME: Double = 0): Double;
    function  DOSETAUTONOMUS(const PFCNAME: string;
      const PFCCOMMENT: string; PUCHGRID: Double; PEIID: Double;
      PFARMGRID: Double; PLEVELID: Double; PFKTYPE: Double; 
      PFKPAYTYPE: Double; PMEDICID: Double; PFKNOMENRLS: Double; 
      const PFCEANCONE: string; PKOLFINU: Double; PFEDIZMID: Double; 
      PFNDOZKA: Double; PFKDOZKAUNIT: Double; PFKNARCO: Double; BRLS: Double; PFL_PRINT_LAT_NAME: Double = 0): Double;
    procedure GETBYID(PMEDICID: Double; out PFCNAME: string; 
      out PFCCOMMENT: string; out PUCHGRID: Double; out PEIID: Double; 
      out PLEVELID: Double; out PFARMGRID: Double; out PPKU: Double; 
      out PFLLGOTA: Double; out PFCNAMELAT: string; out PFL_PRINT_LAT_NAME: Double);
    function  GETEDIZM(PMEDICID: Double): Double;
    function  GETEDIZMNAME(PMEDICID: Double): string;
    function  GETEDIZMNAMEOKEI(PMEDICID: Double): string;
    function  GETFARMGRID(PMEDICID: Double): Double;
    function  GETKOLNEOTLOZH(AMEDIC: Double; AMOID: Double): Double;
    function  GETNAMEBYID(PMEDICID: Double): string;
    function  GETUCHGRID(PMEDICID: Double): Double;
    procedure MEDICCOMPLEXADD(PMEDICPARENT: Double; PMEDICITEM: Double);
    function  MEDICCOMPLEXCANDEL(PMEDICITEM: Double): Double;
    procedure MEDICCOMPLEXDEL(PMEDICPARENT: Double; PMEDICITEM: Double);
    procedure MEDICCOMPLEXSETAMOUNT(PMEDICITEM: Double; PAMOUNT: Double);
    procedure SETUCHGRCHANGEHISTORY ( PMEDICID: Double; PUCHGRID : Double; PNEWUCHGRID : Double; PMOID : Double );
    procedure SETUCHGRFORKARTS ( PMEDICID: Double; PNEWUCHGRID : Double; PDATE : TDateTime );
  published
    property Name;
    property Session;
    property Cursor;
  end;

var
  DefaultPLSQLTableSize: Integer = 100; // Default size of a PL/SQL Table

implementation

// PKGTMEDIC.DODEL
procedure TPKGTMEDIC.DODEL(PMEDICID: Double);
begin
  GetQuery;
  OCPQuery.DeclareVariable('PMEDICID', otFloat);
  OCPQuery.SetVariable('PMEDICID', PMEDICID);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  "MED"."PKGTMEDIC"."DODEL"(PMEDICID => :PMEDICID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
end;

// PKGTMEDIC.DOINVISIBLE
procedure TPKGTMEDIC.DOINVISIBLE(PMEDICID: Double);
begin
  GetQuery;
  OCPQuery.DeclareVariable('PMEDICID', otFloat);
  OCPQuery.SetVariable('PMEDICID', PMEDICID);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  "MED"."PKGTMEDIC"."DOINVISIBLE"(PMEDICID => :PMEDICID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
end;   

// PKGTMEDIC.DOINVISIBLE
procedure TPKGTMEDIC.DOVISIBLE(PMEDICID: Double);
begin
  GetQuery;
  OCPQuery.DeclareVariable('PMEDICID', otFloat);
  OCPQuery.SetVariable('PMEDICID', PMEDICID);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  "MED"."PKGTMEDIC"."DOVISIBLE"(PMEDICID => :PMEDICID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
end;

// PKGTMEDIC.DOSETUCHGROUP
procedure TPKGTMEDIC.DOSETUCHGROUP(PUCHGRIP, PMEDICID: Double);
begin
  GetQuery;
  OCPQuery.DeclareVariable('PMEDICID', otFloat);
  OCPQuery.SetVariable('PMEDICID', PMEDICID);   
  OCPQuery.DeclareVariable('PUCHGRIP', otFloat);
  OCPQuery.SetVariable('PUCHGRIP', PUCHGRIP);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  "MED"."PKGTMEDIC"."DOSETUCHGROUP"(PUCHGRIP => :PUCHGRIP, PMEDICID => :PMEDICID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
end;

// PKGTMEDIC.DODELCASCADE
procedure TPKGTMEDIC.DODELCASCADE(PMEDICID: Double);
begin
  GetQuery;
  OCPQuery.DeclareVariable('PMEDICID', otFloat);
  OCPQuery.SetVariable('PMEDICID', PMEDICID);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  "MED"."PKGTMEDIC"."DODELCASCADE"(PMEDICID => :PMEDICID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
end;

// PKGTMEDIC.DOSET
function TPKGTMEDIC.DOSET(const PFCNAME: string; const PFCCOMMENT: string; 
  PUCHGRID: Double; PEIID: Double; PFARMGRID: Double; PLEVELID: Double; 
  PFKTYPE: Double; PFKPAYTYPE: Double; PMEDICID: Double; 
  PFKNOMENRLS: Double; const PFCEANCONE: string; PKOLFINU: Double; 
  PFEDIZMID: Double; PFNDOZKA: Double; PFKDOZKAUNIT: Double; 
  PFKNARCO: Double; PFLLGOTA: Double; const PFCNAMELAT: string; PFL_PRINT_LAT_NAME: Double = 0): Double;
begin
  GetQuery;
  OCPQuery.DeclareVariable('function_result', otFloat);
  OCPQuery.DeclareVariable('PFC_NAME', otString);
  OCPQuery.SetVariable('PFC_NAME', PFCNAME);
  OCPQuery.DeclareVariable('PFC_COMMENT', otString);
  OCPQuery.SetVariable('PFC_COMMENT', PFCCOMMENT);
  OCPQuery.DeclareVariable('PUCHGRID', otFloat);
  OCPQuery.SetVariable('PUCHGRID', PUCHGRID);
  OCPQuery.DeclareVariable('PEIID', otFloat);
  OCPQuery.SetVariable('PEIID', PEIID);
  OCPQuery.DeclareVariable('PFARMGRID', otFloat);
  OCPQuery.SetVariable('PFARMGRID', PFARMGRID);
  OCPQuery.DeclareVariable('PLEVELID', otFloat);
  OCPQuery.SetVariable('PLEVELID', PLEVELID);
  OCPQuery.DeclareVariable('PFK_TYPE', otFloat);
  OCPQuery.SetVariable('PFK_TYPE', PFKTYPE);
  OCPQuery.DeclareVariable('PFK_PAYTYPE', otFloat);
  OCPQuery.SetVariable('PFK_PAYTYPE', PFKPAYTYPE);
  OCPQuery.DeclareVariable('PMEDICID', otFloat);
  OCPQuery.SetVariable('PMEDICID', PMEDICID);
  OCPQuery.DeclareVariable('PFK_NOMEN_RLS', otFloat);
  OCPQuery.SetVariable('PFK_NOMEN_RLS', PFKNOMENRLS);
  OCPQuery.DeclareVariable('PFC_EANCONE', otString);
  OCPQuery.SetVariable('PFC_EANCONE', PFCEANCONE);
  OCPQuery.DeclareVariable('PKOLFINU', otFloat);
  OCPQuery.SetVariable('PKOLFINU', PKOLFINU);
  OCPQuery.DeclareVariable('PFEDIZMID', otFloat);
  OCPQuery.SetVariable('PFEDIZMID', PFEDIZMID);
  OCPQuery.DeclareVariable('PFN_DOZKA', otFloat);
  OCPQuery.SetVariable('PFN_DOZKA', PFNDOZKA);
  OCPQuery.DeclareVariable('PFK_DOZKAUNIT', otFloat);
  OCPQuery.SetVariable('PFK_DOZKAUNIT', PFKDOZKAUNIT);
  OCPQuery.DeclareVariable('PFK_NARCO', otFloat);
  OCPQuery.SetVariable('PFK_NARCO', PFKNARCO);
  OCPQuery.DeclareVariable('PFL_LGOTA', otFloat);
  OCPQuery.SetVariable('PFL_LGOTA', PFLLGOTA);
  OCPQuery.DeclareVariable('PFC_NAME_LAT', otString);
  OCPQuery.SetVariable('PFC_NAME_LAT', PFCNAMELAT);
  OCPQuery.DeclareVariable('PFL_PRINT_LAT_NAME', otFloat);
  OCPQuery.SetVariable('PFL_PRINT_LAT_NAME', PFL_PRINT_LAT_NAME);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  :function_result := "MED"."PKGTMEDIC"."DOSET"(');
  OCPQuery.SQL.Add('    PFC_NAME => :PFC_NAME,');
  OCPQuery.SQL.Add('    PFC_COMMENT => :PFC_COMMENT,');
  OCPQuery.SQL.Add('    PUCHGRID => :PUCHGRID,');
  OCPQuery.SQL.Add('    PEIID => :PEIID,');
  OCPQuery.SQL.Add('    PFARMGRID => :PFARMGRID,');
  OCPQuery.SQL.Add('    PLEVELID => :PLEVELID,');
  OCPQuery.SQL.Add('    PFK_TYPE => :PFK_TYPE,');
  OCPQuery.SQL.Add('    PFK_PAYTYPE => :PFK_PAYTYPE,');
  OCPQuery.SQL.Add('    PMEDICID => :PMEDICID,');
  OCPQuery.SQL.Add('    PFK_NOMEN_RLS => :PFK_NOMEN_RLS,');
  OCPQuery.SQL.Add('    PFC_EANCONE => :PFC_EANCONE,');
  OCPQuery.SQL.Add('    PKOLFINU => :PKOLFINU,');
  OCPQuery.SQL.Add('    PFEDIZMID => :PFEDIZMID,');
  OCPQuery.SQL.Add('    PFN_DOZKA => :PFN_DOZKA,');
  OCPQuery.SQL.Add('    PFK_DOZKAUNIT => :PFK_DOZKAUNIT,');
  OCPQuery.SQL.Add('    PFK_NARCO => :PFK_NARCO,');
  OCPQuery.SQL.Add('    PFL_LGOTA => :PFL_LGOTA,');
  OCPQuery.SQL.Add('    PFC_NAME_LAT => :PFC_NAME_LAT,');
  OCPQuery.SQL.Add('    PFL_PRINT_LAT_NAME => :PFL_PRINT_LAT_NAME);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  Result := ConvertVariant(OCPQuery.GetVariable('function_result'));
end;

// PKGTMEDIC.DO_SET_AUTONOMUS
function TPKGTMEDIC.DOSETAUTONOMUS(const PFCNAME: string; 
  const PFCCOMMENT: string; PUCHGRID: Double; PEIID: Double; 
  PFARMGRID: Double; PLEVELID: Double; PFKTYPE: Double; 
  PFKPAYTYPE: Double; PMEDICID: Double; PFKNOMENRLS: Double; 
  const PFCEANCONE: string; PKOLFINU: Double; PFEDIZMID: Double; 
  PFNDOZKA: Double; PFKDOZKAUNIT: Double; PFKNARCO: Double; BRLS: Double; PFL_PRINT_LAT_NAME: Double = 0): Double;
begin
  GetQuery;
  OCPQuery.DeclareVariable('function_result', otFloat);
  OCPQuery.DeclareVariable('PFC_NAME', otString);
  OCPQuery.SetVariable('PFC_NAME', PFCNAME);
  OCPQuery.DeclareVariable('PFC_COMMENT', otString);
  OCPQuery.SetVariable('PFC_COMMENT', PFCCOMMENT);
  OCPQuery.DeclareVariable('PUCHGRID', otFloat);
  OCPQuery.SetVariable('PUCHGRID', PUCHGRID);
  OCPQuery.DeclareVariable('PEIID', otFloat);
  OCPQuery.SetVariable('PEIID', PEIID);
  OCPQuery.DeclareVariable('PFARMGRID', otFloat);
  OCPQuery.SetVariable('PFARMGRID', PFARMGRID);
  OCPQuery.DeclareVariable('PLEVELID', otFloat);
  OCPQuery.SetVariable('PLEVELID', PLEVELID);
  OCPQuery.DeclareVariable('PFK_TYPE', otFloat);
  OCPQuery.SetVariable('PFK_TYPE', PFKTYPE);
  OCPQuery.DeclareVariable('PFK_PAYTYPE', otFloat);
  OCPQuery.SetVariable('PFK_PAYTYPE', PFKPAYTYPE);
  OCPQuery.DeclareVariable('PMEDICID', otFloat);
  OCPQuery.SetVariable('PMEDICID', PMEDICID);
  OCPQuery.DeclareVariable('PFK_NOMEN_RLS', otFloat);
  OCPQuery.SetVariable('PFK_NOMEN_RLS', PFKNOMENRLS);
  OCPQuery.DeclareVariable('PFC_EANCONE', otString);
  OCPQuery.SetVariable('PFC_EANCONE', PFCEANCONE);
  OCPQuery.DeclareVariable('PKOLFINU', otFloat);
  OCPQuery.SetVariable('PKOLFINU', PKOLFINU);
  OCPQuery.DeclareVariable('PFEDIZMID', otFloat);
  OCPQuery.SetVariable('PFEDIZMID', PFEDIZMID);
  OCPQuery.DeclareVariable('PFN_DOZKA', otFloat);
  OCPQuery.SetVariable('PFN_DOZKA', PFNDOZKA);
  OCPQuery.DeclareVariable('PFK_DOZKAUNIT', otFloat);
  OCPQuery.SetVariable('PFK_DOZKAUNIT', PFKDOZKAUNIT);
  OCPQuery.DeclareVariable('PFK_NARCO', otFloat);
  OCPQuery.SetVariable('PFK_NARCO', PFKNARCO);
  OCPQuery.DeclareVariable('BRLS', otFloat);
  OCPQuery.SetVariable('BRLS', BRLS);
  OCPQuery.DeclareVariable('PFL_PRINT_LAT_NAME', otFloat);
  OCPQuery.SetVariable('PFL_PRINT_LAT_NAME', PFL_PRINT_LAT_NAME);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  :function_result := "MED"."PKGTMEDIC"."DO_SET_AUTONOMUS"(');
  OCPQuery.SQL.Add('    PFC_NAME => :PFC_NAME,');
  OCPQuery.SQL.Add('    PFC_COMMENT => :PFC_COMMENT,');
  OCPQuery.SQL.Add('    PUCHGRID => :PUCHGRID,');
  OCPQuery.SQL.Add('    PEIID => :PEIID,');
  OCPQuery.SQL.Add('    PFARMGRID => :PFARMGRID,');
  OCPQuery.SQL.Add('    PLEVELID => :PLEVELID,');
  OCPQuery.SQL.Add('    PFK_TYPE => :PFK_TYPE,');
  OCPQuery.SQL.Add('    PFK_PAYTYPE => :PFK_PAYTYPE,');
  OCPQuery.SQL.Add('    PMEDICID => :PMEDICID,');
  OCPQuery.SQL.Add('    PFK_NOMEN_RLS => :PFK_NOMEN_RLS,');
  OCPQuery.SQL.Add('    PFC_EANCONE => :PFC_EANCONE,');
  OCPQuery.SQL.Add('    PKOLFINU => :PKOLFINU,');
  OCPQuery.SQL.Add('    PFEDIZMID => :PFEDIZMID,');
  OCPQuery.SQL.Add('    PFN_DOZKA => :PFN_DOZKA,');
  OCPQuery.SQL.Add('    PFK_DOZKAUNIT => :PFK_DOZKAUNIT,');
  OCPQuery.SQL.Add('    PFK_NARCO => :PFK_NARCO,');
  OCPQuery.SQL.Add('    BRLS => :BRLS,');
  OCPQuery.SQL.Add('    PFL_PRINT_LAT_NAME => :PFL_PRINT_LAT_NAME);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  Result := ConvertVariant(OCPQuery.GetVariable('function_result'));
end;

// PKGTMEDIC.GETBYID
procedure TPKGTMEDIC.GETBYID(PMEDICID: Double; out PFCNAME: string; 
  out PFCCOMMENT: string; out PUCHGRID: Double; out PEIID: Double; 
  out PLEVELID: Double; out PFARMGRID: Double; out PPKU: Double; 
  out PFLLGOTA: Double; out PFCNAMELAT: string; out PFL_PRINT_LAT_NAME: Double);
begin
  GetQuery;
  OCPQuery.DeclareVariable('PMEDICID', otFloat);
  OCPQuery.SetVariable('PMEDICID', PMEDICID);
  OCPQuery.DeclareVariable('PFC_NAME', otString);
  OCPQuery.DeclareVariable('PFC_COMMENT', otString);
  OCPQuery.DeclareVariable('PUCHGRID', otFloat);
  OCPQuery.DeclareVariable('PEIID', otFloat);
  OCPQuery.DeclareVariable('PLEVELID', otFloat);
  OCPQuery.DeclareVariable('PFARMGRID', otFloat);
  OCPQuery.DeclareVariable('PPKU', otFloat);
  OCPQuery.DeclareVariable('PFL_LGOTA', otFloat);
  OCPQuery.DeclareVariable('PFC_NAME_LAT', otString);
  OCPQuery.DeclareVariable('PFL_PRINT_LAT_NAME', otFloat);
  OCPQuery.SetVariable('PFL_PRINT_LAT_NAME', PFL_PRINT_LAT_NAME);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  "MED"."PKGTMEDIC"."GETBYID"(');
  OCPQuery.SQL.Add('    PMEDICID => :PMEDICID,');
  OCPQuery.SQL.Add('    PFC_NAME => :PFC_NAME,');
  OCPQuery.SQL.Add('    PFC_COMMENT => :PFC_COMMENT,');
  OCPQuery.SQL.Add('    PUCHGRID => :PUCHGRID,');
  OCPQuery.SQL.Add('    PEIID => :PEIID,');
  OCPQuery.SQL.Add('    PLEVELID => :PLEVELID,');
  OCPQuery.SQL.Add('    PFARMGRID => :PFARMGRID,');
  OCPQuery.SQL.Add('    PPKU => :PPKU,');
  OCPQuery.SQL.Add('    PFL_LGOTA => :PFL_LGOTA,');
  OCPQuery.SQL.Add('    PFC_NAME_LAT => :PFC_NAME_LAT,');
  OCPQuery.SQL.Add('    PFL_PRINT_LAT_NAME => :PFL_PRINT_LAT_NAME);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  PFCNAME := ConvertVariant(OCPQuery.GetVariable('PFC_NAME'));
  PFCCOMMENT := ConvertVariant(OCPQuery.GetVariable('PFC_COMMENT'));
  PUCHGRID := ConvertVariant(OCPQuery.GetVariable('PUCHGRID'));
  PEIID := ConvertVariant(OCPQuery.GetVariable('PEIID'));
  PLEVELID := ConvertVariant(OCPQuery.GetVariable('PLEVELID'));
  PFARMGRID := ConvertVariant(OCPQuery.GetVariable('PFARMGRID'));
  PPKU := ConvertVariant(OCPQuery.GetVariable('PPKU'));
  PFLLGOTA := ConvertVariant(OCPQuery.GetVariable('PFL_LGOTA'));
  PFCNAMELAT := ConvertVariant(OCPQuery.GetVariable('PFC_NAME_LAT'));
  PFL_PRINT_LAT_NAME := ConvertVariant(OCPQuery.GetVariable('PFL_PRINT_LAT_NAME'));
end;

// PKGTMEDIC.GETEDIZM
function TPKGTMEDIC.GETEDIZM(PMEDICID: Double): Double;
begin
  GetQuery;
  OCPQuery.DeclareVariable('function_result', otFloat);
  OCPQuery.DeclareVariable('PMEDICID', otFloat);
  OCPQuery.SetVariable('PMEDICID', PMEDICID);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  :function_result := "MED"."PKGTMEDIC"."GETEDIZM"(PMEDICID => :PMEDICID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  Result := ConvertVariant(OCPQuery.GetVariable('function_result'));
end;

// PKGTMEDIC.GETEDIZMNAME
function TPKGTMEDIC.GETEDIZMNAME(PMEDICID: Double): string;
begin
  GetQuery;
  OCPQuery.DeclareVariable('function_result', otString);
  OCPQuery.DeclareVariable('PMEDICID', otFloat);
  OCPQuery.SetVariable('PMEDICID', PMEDICID);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  :function_result := "MED"."PKGTMEDIC"."GETEDIZMNAME"(PMEDICID => :PMEDICID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  Result := ConvertVariant(OCPQuery.GetVariable('function_result'));
end;

// PKGTMEDIC.GETEDIZMNAMEOKEI
function TPKGTMEDIC.GETEDIZMNAMEOKEI(PMEDICID: Double): string;
begin
  GetQuery;
  OCPQuery.DeclareVariable('function_result', otString);
  OCPQuery.DeclareVariable('PMEDICID', otFloat);
  OCPQuery.SetVariable('PMEDICID', PMEDICID);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  :function_result := "MED"."PKGTMEDIC"."GETEDIZMNAMEOKEI"(PMEDICID => :PMEDICID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  Result := ConvertVariant(OCPQuery.GetVariable('function_result'));
end;

// PKGTMEDIC.GETFARMGRID
function TPKGTMEDIC.GETFARMGRID(PMEDICID: Double): Double;
begin
  GetQuery;
  OCPQuery.DeclareVariable('function_result', otFloat);
  OCPQuery.DeclareVariable('PMEDICID', otFloat);
  OCPQuery.SetVariable('PMEDICID', PMEDICID);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  :function_result := "MED"."PKGTMEDIC"."GETFARMGRID"(PMEDICID => :PMEDICID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  Result := ConvertVariant(OCPQuery.GetVariable('function_result'));
end;

// PKGTMEDIC.GETKOLNEOTLOZH
function TPKGTMEDIC.GETKOLNEOTLOZH(AMEDIC: Double; AMOID: Double): Double;
begin
  GetQuery;
  OCPQuery.DeclareVariable('function_result', otFloat);
  OCPQuery.DeclareVariable('AMEDIC', otFloat);
  OCPQuery.SetVariable('AMEDIC', AMEDIC);
  OCPQuery.DeclareVariable('AMOID', otFloat);
  OCPQuery.SetVariable('AMOID', AMOID);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  :function_result := "MED"."PKGTMEDIC"."GETKOLNEOTLOZH"(');
  OCPQuery.SQL.Add('    AMEDIC => :AMEDIC,');
  OCPQuery.SQL.Add('    AMOID => :AMOID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  Result := ConvertVariant(OCPQuery.GetVariable('function_result'));
end;

// PKGTMEDIC.GETNAMEBYID
function TPKGTMEDIC.GETNAMEBYID(PMEDICID: Double): string;
begin
  GetQuery;
  OCPQuery.DeclareVariable('function_result', otString);
  OCPQuery.DeclareVariable('PMEDICID', otFloat);
  OCPQuery.SetVariable('PMEDICID', PMEDICID);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  :function_result := "MED"."PKGTMEDIC"."GETNAMEBYID"(PMEDICID => :PMEDICID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  Result := ConvertVariant(OCPQuery.GetVariable('function_result'));
end;

// PKGTMEDIC.GETUCHGRID
function TPKGTMEDIC.GETUCHGRID(PMEDICID: Double): Double;
begin
  GetQuery;
  OCPQuery.DeclareVariable('function_result', otFloat);
  OCPQuery.DeclareVariable('PMEDICID', otFloat);
  OCPQuery.SetVariable('PMEDICID', PMEDICID);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  :function_result := "MED"."PKGTMEDIC"."GETUCHGRID"(PMEDICID => :PMEDICID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  Result := ConvertVariant(OCPQuery.GetVariable('function_result'));
end;

// PKGTMEDIC.MEDIC_COMPLEX_ADD
procedure TPKGTMEDIC.MEDICCOMPLEXADD(PMEDICPARENT: Double; PMEDICITEM: Double);
begin
  GetQuery;
  OCPQuery.DeclareVariable('P_MEDIC_PARENT', otFloat);
  OCPQuery.SetVariable('P_MEDIC_PARENT', PMEDICPARENT);
  OCPQuery.DeclareVariable('P_MEDIC_ITEM', otFloat);
  OCPQuery.SetVariable('P_MEDIC_ITEM', PMEDICITEM);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  "MED"."PKGTMEDIC"."MEDIC_COMPLEX_ADD"(');
  OCPQuery.SQL.Add('    P_MEDIC_PARENT => :P_MEDIC_PARENT,');
  OCPQuery.SQL.Add('    P_MEDIC_ITEM => :P_MEDIC_ITEM);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
end;

// PKGTMEDIC.MEDIC_COMPLEX_CAN_DEL
function TPKGTMEDIC.MEDICCOMPLEXCANDEL(PMEDICITEM: Double): Double;
begin
  GetQuery;
  OCPQuery.DeclareVariable('function_result', otFloat);
  OCPQuery.DeclareVariable('P_MEDIC_ITEM', otFloat);
  OCPQuery.SetVariable('P_MEDIC_ITEM', PMEDICITEM);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  :function_result := "MED"."PKGTMEDIC"."MEDIC_COMPLEX_CAN_DEL"(P_MEDIC_ITEM => :P_MEDIC_ITEM);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  Result := ConvertVariant(OCPQuery.GetVariable('function_result'));
end;

// PKGTMEDIC.MEDIC_COMPLEX_DEL
procedure TPKGTMEDIC.MEDICCOMPLEXDEL(PMEDICPARENT: Double; PMEDICITEM: Double);
begin
  GetQuery;
  OCPQuery.DeclareVariable('P_MEDIC_PARENT', otFloat);
  OCPQuery.SetVariable('P_MEDIC_PARENT', PMEDICPARENT);
  OCPQuery.DeclareVariable('P_MEDIC_ITEM', otFloat);
  OCPQuery.SetVariable('P_MEDIC_ITEM', PMEDICITEM);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  "MED"."PKGTMEDIC"."MEDIC_COMPLEX_DEL"(');
  OCPQuery.SQL.Add('    P_MEDIC_PARENT => :P_MEDIC_PARENT,');
  OCPQuery.SQL.Add('    P_MEDIC_ITEM => :P_MEDIC_ITEM);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
end;

// PKGTMEDIC.MEDIC_COMPLEX_SET_AMOUNT
procedure TPKGTMEDIC.MEDICCOMPLEXSETAMOUNT(PMEDICITEM: Double; PAMOUNT: Double);
begin
  GetQuery;
  OCPQuery.DeclareVariable('P_MEDIC_ITEM', otFloat);
  OCPQuery.SetVariable('P_MEDIC_ITEM', PMEDICITEM);
  OCPQuery.DeclareVariable('P_AMOUNT', otFloat);
  OCPQuery.SetVariable('P_AMOUNT', PAMOUNT);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  "MED"."PKGTMEDIC"."MEDIC_COMPLEX_SET_AMOUNT"(');
  OCPQuery.SQL.Add('    P_MEDIC_ITEM => :P_MEDIC_ITEM,');
  OCPQuery.SQL.Add('    P_AMOUNT => :P_AMOUNT);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
end;

// PKGTMEDIC.DOSETUCHGRHISTORY
procedure TPKGTMEDIC.SETUCHGRCHANGEHISTORY (PMEDICID, PUCHGRID, PNEWUCHGRID, PMOID: Double );
begin
  GetQuery;
  OCPQuery.DeclareVariable('P_MEDICID', otFloat);
  OCPQuery.SetVariable('P_MEDICID', PMEDICID);
  OCPQuery.DeclareVariable('P_UCHGRID', otFloat);
  OCPQuery.SetVariable('P_UCHGRID', PUCHGRID);
  OCPQuery.DeclareVariable('P_NEWUCHGRID', otFloat);
  OCPQuery.SetVariable('P_NEWUCHGRID', PNEWUCHGRID);
  OCPQuery.DeclareVariable('P_MOID', otFloat);
  OCPQuery.SetVariable('P_MOID', PMOID);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  "MED"."PKGTMEDIC"."DOSETUCHGRHISTORY"(');
  OCPQuery.SQL.Add('    P_MEDICID => :P_MEDICID,');
  OCPQuery.SQL.Add('    P_UCHGRID => :P_UCHGRID,');
  OCPQuery.SQL.Add('    P_NEWUCHGRID => :P_NEWUCHGRID,');
  OCPQuery.SQL.Add('    P_MOID =>    :P_MOID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
end;

// PKGTMEDIC.DOSETUCHGRIDFORTKART
procedure TPKGTMEDIC.SETUCHGRFORKARTS(PMEDICID, PNEWUCHGRID: Double; PDATE: TDateTime);
begin
  GetQuery;
  OCPQuery.DeclareVariable('P_MEDICID', otFloat);
  OCPQuery.SetVariable('P_MEDICID', PMEDICID);
  OCPQuery.DeclareVariable('P_NEWUCHGRID', otFloat);
  OCPQuery.SetVariable('P_NEWUCHGRID', PNEWUCHGRID);
  OCPQuery.DeclareVariable('P_DATE', otDate );
  OCPQuery.SetVariable('P_DATE', PDATE);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  "MED"."PKGTMEDIC"."DOSETUCHGRIDFORTKART"(');
  OCPQuery.SQL.Add('    P_MEDICID => :P_MEDICID,');
  OCPQuery.SQL.Add('    P_NEWUCHGRID => :P_NEWUCHGRID,');
  OCPQuery.SQL.Add('    P_DATE =>    :P_DATE);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
end;

end.
