unit PKGTDOCS;

// Oracle Package Wizard 1.0.3
// File PKGTDOCS.pas generated by Delphi5 on 08.11.2006 13:22:11
// This unit contains interface objects for oracle package MED.PKGTDOCS
// WARNING: Modifications made to this file will be lost after regeneration!

interface

uses Classes, SysUtils, Oracle;

type
(*
package PKGTDOCS is

  -- Author  : DELPHI5
  -- Created : 08.11.2006 13:11:26
  -- Purpose : ДЛЯ ТАБЛИЦЫ TDOCS

FUNCTION GET_FL_EDIT(pDPID IN NUMBER) RETURN NUMBER;
/* Ф-ия возвращает: значение поля fl_edit*/

end PKGTDOCS;
*)
  TPKGTDOCS = class(TOracleCustomPackage)
  public
    function  GETFLEDIT(PDPID: Double): Double;
    procedure  SETFLEDIT(PDPID: Double; PFL_EDIT : Double = 0);    
  published
    property Name;
    property Session;
    property Cursor;
  end;

var
  DefaultPLSQLTableSize: Integer = 100; // Default size of a PL/SQL Table

implementation

// PKGTDOCS.GET_FL_EDIT
function TPKGTDOCS.GETFLEDIT(PDPID: Double): Double;
begin
  GetQuery;
  OCPQuery.DeclareVariable('function_result', otFloat);
  OCPQuery.DeclareVariable('PDPID', otFloat);
  OCPQuery.SetVariable('PDPID', PDPID);
  OCPQuery.SQL.Add('begin');
  OCPQuery.SQL.Add('  :function_result := "MED"."PKGTDOCS"."GET_FL_EDIT"(PDPID => :PDPID);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
  Result := ConvertVariant(OCPQuery.GetVariable('function_result'));
end;

procedure TPKGTDOCS.SETFLEDIT(PDPID: Double; PFL_EDIT : Double = 0);
begin
  GetQuery;
  OCPQuery.SQL.Add('begin');
  OCPQuery.DeclareVariable('PDPID', otFloat);
  OCPQuery.SetVariable('PDPID', PDPID);
  OCPQuery.DeclareVariable('PFL_EDIT', otFloat);
  OCPQuery.SetVariable('PFL_EDIT', PFL_EDIT);
  OCPQuery.SQL.Add('  "MED"."PKGTDOCS"."SET_FL_EDIT"(');
  OCPQuery.SQL.Add('    PDPID => :PDPID,');
  OCPQuery.SQL.Add('    PFL_EDIT => :PFL_EDIT);');
  OCPQuery.SQL.Add('end;');
  OCPQuery.Execute;
end;

end.
