DROP FUNCTION ASU.GET_DS_DP
/

--
-- GET_DS_DP  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU.GET_DS_DP
  RETURN NUMBER DETERMINISTIC
  IS -- Created by -= aAdmin.exe =-
     -- ATTENTION! DO NOT MODIFY THIS FUNCTION MANUALLY!!!
BEGIN
  Return -1;
END;
/

SHOW ERRORS;


