DROP FUNCTION ASU.GET_NOVOROGDOTD
/

--
-- GET_NOVOROGDOTD  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU."GET_NOVOROGDOTD" 
  RETURN NUMBER DETERMINISTIC
  IS -- Created by -= aAdmin.exe =- 
     -- ATTENTION! DO NOT MODIFY THIS FUNCTION MANUALLY!!!
BEGIN
  Return 26637;
END;
/

SHOW ERRORS;


GRANT EXECUTE ON ASU.GET_NOVOROGDOTD TO PUBLIC
/

