DROP FUNCTION ASU.GET_PAC_PRIZN_KODE
/

--
-- GET_PAC_PRIZN_KODE  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--   SYS_STUB_FOR_PURITY_ANALYSIS (Package)
--   TKARTA (Table)
--
CREATE OR REPLACE FUNCTION ASU."GET_PAC_PRIZN_KODE" 
  ( pFK_ID IN NUMBER)
  RETURN  NUMBER IS
  CURSOR c IS SELECT FK_PRIZN FROM TKARTA WHERE FK_ID=pFK_ID;
  i NUMBER;
BEGIN
  if c%ISOPEN THEN
    CLOSE c;
  END IF;
  OPEN C;
  FETCH C INTO i;
  CLOSE C;
  RETURN i;
END;
/

SHOW ERRORS;


