DROP FUNCTION ASU.GET_NEVRPROF
/

--
-- GET_NEVRPROF  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU."GET_NEVRPROF" 
  RETURN NUMBER DETERMINISTIC
  IS -- Created by -= aAdmin.exe =- 
     -- ATTENTION! DO NOT MODIFY THIS FUNCTION MANUALLY!!!
BEGIN
  Return 46988;
END;
/

SHOW ERRORS;


GRANT EXECUTE ON ASU.GET_NEVRPROF TO PUBLIC
/

