DROP FUNCTION ASU.GET_NAZ_AMPLIPH
/

--
-- GET_NAZ_AMPLIPH  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU."GET_NAZ_AMPLIPH" 
  RETURN NUMBER DETERMINISTIC
  IS -- Created by -= aAdmin.exe =- 
     -- ATTENTION! DO NOT MODIFY THIS FUNCTION MANUALLY!!!
BEGIN
  Return 352;
END;
/

SHOW ERRORS;


GRANT EXECUTE ON ASU.GET_NAZ_AMPLIPH TO PUBLIC
/

