DROP FUNCTION ASU.DOC_DONOR_OO
/

--
-- DOC_DONOR_OO  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU."DOC_DONOR_OO" 
  RETURN NUMBER DETERMINISTIC
  IS -- Created by -= aAdmin.exe =- 
     -- ATTENTION! DO NOT MODIFY THIS FUNCTION MANUALLY!!!
BEGIN
  Return 524;
END;
/

SHOW ERRORS;


GRANT EXECUTE ON ASU.DOC_DONOR_OO TO PUBLIC
/

