DROP FUNCTION ASU.GET_LAB_TYPE_VIDEL
/

--
-- GET_LAB_TYPE_VIDEL  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU."GET_LAB_TYPE_VIDEL" 
  RETURN NUMBER DETERMINISTIC
  IS -- Created by -= aAdmin.exe =- 
     -- ATTENTION! DO NOT MODIFY THIS FUNCTION MANUALLY!!!
BEGIN
  Return 860766;
END;
/

SHOW ERRORS;


GRANT EXECUTE ON ASU.GET_LAB_TYPE_VIDEL TO PUBLIC
/

