DROP FUNCTION ASU.GOTO_EXCURCION_VALID
/

--
-- GOTO_EXCURCION_VALID  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU.GOTO_EXCURCION_VALID( NPEOPLEID IN INTEGER, DDATE IN DATE )
 RETURN NUMBER
 IS
   NTYPEPERIOD NUMBER;
   ID NUMBER;
   DSTARTDATE DATE;
   DENDDATE DATE;

   CURSOR PERIOD( NFK_ID IN NUMBER ) IS
    SELECT FN_TYPE, FK_ID, FD_DATE_1, FD_DATE_2
      FROM TS_SROKY
     WHERE FK_PEOPLEID = NFK_ID
       AND DDATE >= FD_DATE_1
     ORDER BY FK_ID DESC;
 BEGIN
   OPEN PERIOD( NPEOPLEID );
   FETCH PERIOD
     INTO NTYPEPERIOD, ID, DSTARTDATE, DENDDATE;

     IF ( NTYPEPERIOD = 8 ) THEN
        IF ( DDATE < DENDDATE ) THEN
           RETURN 0;
         ELSE
           FETCH PERIOD
              INTO NTYPEPERIOD, ID, DSTARTDATE, DENDDATE;
        END IF;
     END IF;
   CLOSE PERIOD;

   IF ( NTYPEPERIOD IS NULL ) THEN
      RETURN 0;
    ELSE
      IF ( NTYPEPERIOD IN ( 2, 4, 5, 6 ) AND DDATE < DENDDATE ) THEN
         RETURN 1;
       ELSE
         RETURN 0;
      END IF;
   END IF;
END;
/

SHOW ERRORS;


