DROP FUNCTION ASU.GET_XRAYS_OTDEL
/

--
-- GET_XRAYS_OTDEL  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU."GET_XRAYS_OTDEL" 
  RETURN NUMBER DETERMINISTIC
  IS -- Created by -= aAdmin.exe =- 
     -- ATTENTION! DO NOT MODIFY THIS FUNCTION MANUALLY!!!
BEGIN
  Return 11010;
END;
/

SHOW ERRORS;


GRANT EXECUTE ON ASU.GET_XRAYS_OTDEL TO PUBLIC
/

