DROP FUNCTION ASU.GET_NAZOTLOG
/

--
-- GET_NAZOTLOG  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU."GET_NAZOTLOG" 
  RETURN NUMBER DETERMINISTIC
  IS -- Created by -= aAdmin.exe =- 
     -- ATTENTION! DO NOT MODIFY THIS FUNCTION MANUALLY!!!
BEGIN
  Return 0;
END;
/

SHOW ERRORS;


GRANT EXECUTE ON ASU.GET_NAZOTLOG TO PUBLIC
/

