DROP FUNCTION ASU.DOC_AMBUL
/

--
-- DOC_AMBUL  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU."DOC_AMBUL" 
  RETURN NUMBER DETERMINISTIC
  IS -- Created by -= aAdmin.exe =- 
     -- ATTENTION! DO NOT MODIFY THIS FUNCTION MANUALLY!!!
BEGIN
  Return 281;
END;
/

SHOW ERRORS;


GRANT EXECUTE ON ASU.DOC_AMBUL TO PUBLIC
/

