DROP FUNCTION ASU.GET_PARAKLINIK_BLOCK
/

--
-- GET_PARAKLINIK_BLOCK  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU."GET_PARAKLINIK_BLOCK" 
  RETURN NUMBER DETERMINISTIC
  IS -- Created by -= aAdmin.exe =-
     -- ATTENTION! DO NOT MODIFY THIS FUNCTION MANUALLY!!!
BEGIN
  Return 21467;
END;
/

SHOW ERRORS;


