DROP FUNCTION ASU.GET_OTDEL_REAN_NOV
/

--
-- GET_OTDEL_REAN_NOV  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU."GET_OTDEL_REAN_NOV" 
  RETURN NUMBER DETERMINISTIC
  IS -- Created by -= aAdmin.exe =- 
     -- ATTENTION! DO NOT MODIFY THIS FUNCTION MANUALLY!!!
BEGIN
  Return 39048;
END;
/

SHOW ERRORS;


GRANT EXECUTE ON ASU.GET_OTDEL_REAN_NOV TO PUBLIC
/

