DROP FUNCTION ASU.GET_KONSDIAGPOL
/

--
-- GET_KONSDIAGPOL  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU."GET_KONSDIAGPOL" 
      RETURN NUMBER DETERMINISTIC
      IS -- Created by -= aAdmin.exe =-
         -- ATTENTION! DO NOT MODIFY THIS FUNCTION MANUALLY!!!
   BEGIN
     Return 100;
   END;
/

SHOW ERRORS;


