DROP FUNCTION ASU.GET_FAMILY_DOC_ID
/

--
-- GET_FAMILY_DOC_ID  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU."GET_FAMILY_DOC_ID" 
  RETURN NUMBER DETERMINISTIC
  IS -- Created by -= aAdmin.exe =- 
     -- ATTENTION! DO NOT MODIFY THIS FUNCTION MANUALLY!!!
BEGIN
  Return 510;
END;
/

SHOW ERRORS;


GRANT EXECUTE ON ASU.GET_FAMILY_DOC_ID TO PUBLIC
/

