DROP FUNCTION ASU.DOC_AMBUL_ONKO
/

--
-- DOC_AMBUL_ONKO  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU.DOC_AMBUL_ONKO
  RETURN NUMBER DETERMINISTIC
  IS -- Created by -= aAdmin.exe =-
     -- ATTENTION! DO NOT MODIFY THIS FUNCTION MANUALLY!!!
BEGIN
  Return 1201;
END;
/

SHOW ERRORS;


