DROP FUNCTION ASU.GET_XRAY_STATUS_NEYAVKA
/

--
-- GET_XRAY_STATUS_NEYAVKA  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU."GET_XRAY_STATUS_NEYAVKA" 
  RETURN NUMBER DETERMINISTIC
  IS -- Created by -= aAdmin.exe =- 
     -- ATTENTION! DO NOT MODIFY THIS FUNCTION MANUALLY!!!
BEGIN
  Return 821998;
END;
/

SHOW ERRORS;


GRANT EXECUTE ON ASU.GET_XRAY_STATUS_NEYAVKA TO PUBLIC
/

