DROP FUNCTION ASU.GET_OFTALMOLOG_PROF
/

--
-- GET_OFTALMOLOG_PROF  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU."GET_OFTALMOLOG_PROF" 
  RETURN NUMBER DETERMINISTIC
  IS -- Created by -= aAdmin.exe =- 
     -- ATTENTION! DO NOT MODIFY THIS FUNCTION MANUALLY!!!
BEGIN
  Return 47228;
END;
/

SHOW ERRORS;


GRANT EXECUTE ON ASU.GET_OFTALMOLOG_PROF TO PUBLIC
/

