DROP FUNCTION ASU.GET_XRAY_FLUKAB
/

--
-- GET_XRAY_FLUKAB  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU."GET_XRAY_FLUKAB" 
  RETURN NUMBER DETERMINISTIC
  IS -- Created by -= aAdmin.exe =- 
     -- ATTENTION! DO NOT MODIFY THIS FUNCTION MANUALLY!!!
BEGIN
  Return 12073;
END;
/

SHOW ERRORS;


GRANT EXECUTE ON ASU.GET_XRAY_FLUKAB TO PUBLIC
/

