DROP FUNCTION ASU.GET_ZAVOTDEL
/

--
-- GET_ZAVOTDEL  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU."GET_ZAVOTDEL" 
  RETURN NUMBER DETERMINISTIC
  IS -- Created by -= aAdmin.exe =- 
     -- ATTENTION! DO NOT MODIFY THIS FUNCTION MANUALLY!!!
BEGIN
  Return 190;
END;
/

SHOW ERRORS;


GRANT EXECUTE ON ASU.GET_ZAVOTDEL TO PUBLIC
/

