DROP FUNCTION ASU.GET_PATANATOM_VRACH
/

--
-- GET_PATANATOM_VRACH  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU."GET_PATANATOM_VRACH" 
  RETURN NUMBER DETERMINISTIC
  IS -- Created by -= aAdmin.exe =- 
     -- ATTENTION! DO NOT MODIFY THIS FUNCTION MANUALLY!!!
BEGIN
  Return 560;
END;
/

SHOW ERRORS;


GRANT EXECUTE ON ASU.GET_PATANATOM_VRACH TO PUBLIC
/

