DROP FUNCTION ASU.GET_PRIMARY_OTDELID
/

--
-- GET_PRIMARY_OTDELID  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU.GET_PRIMARY_OTDELID
  RETURN NUMBER DETERMINISTIC
  IS -- Created by -= aAdmin.exe =-
     -- ATTENTION! DO NOT MODIFY THIS FUNCTION MANUALLY!!!
BEGIN
  Return 20000;
END;
/

SHOW ERRORS;


