DROP FUNCTION ASU.GET_VZRINFOTD
/

--
-- GET_VZRINFOTD  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU."GET_VZRINFOTD" 
  RETURN NUMBER DETERMINISTIC
  IS -- Created by -= aAdmin.exe =- 
     -- ATTENTION! DO NOT MODIFY THIS FUNCTION MANUALLY!!!
BEGIN
  Return 1220;
END;
/

SHOW ERRORS;


GRANT EXECUTE ON ASU.GET_VZRINFOTD TO PUBLIC
/

