DROP FUNCTION ASU.GET_PACVID
/

--
-- GET_PACVID  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--   SYS_STUB_FOR_PURITY_ANALYSIS (Package)
--   TVID (Table)
--
CREATE OR REPLACE FUNCTION ASU."GET_PACVID" 
  ( pFK_ID IN NUMBER)
  RETURN  VARCHAR2 IS
CURSOR c(pID NUMBER) IS SELECT FC_VID FROM TVID WHERE FK_ID=pID;
str VARCHAR2 (30);
BEGIN
  OPEN c(pFK_ID);
  FETCH c INTO str;
  CLOSE c;
  RETURN str;
END; -- Function GET_PACVID
/

SHOW ERRORS;


