DROP FUNCTION ASU.GET_STAT_FROM_SMID
/

--
-- GET_STAT_FROM_SMID  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--   SYS_STUB_FOR_PURITY_ANALYSIS (Package)
--   TSMID (Table)
--
CREATE OR REPLACE FUNCTION ASU."GET_STAT_FROM_SMID" 
  ( pFK_SMID IN NUMBER)
  RETURN  NUMBER IS
CURSOR c(pSMID NUMBER) IS SELECT /*+rule*/FL_STAT FROM TSMID WHERE FK_ID=pSMID;
i NUMBER;
BEGIN
  OPEN c(pFK_SMID);
  FETCH c INTO i;
  CLOSE c;
  RETURN i;
END; -- Function GET_STAT_FROM_SMID
/

SHOW ERRORS;


