DROP FUNCTION ASU.DOC_NOVOROZHD
/

--
-- DOC_NOVOROZHD  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU."DOC_NOVOROZHD" 
  RETURN NUMBER DETERMINISTIC
  IS -- Created by -= aAdmin.exe =- 
     -- ATTENTION! DO NOT MODIFY THIS FUNCTION MANUALLY!!!
BEGIN
  Return 341;
END;
/

SHOW ERRORS;


GRANT EXECUTE ON ASU.DOC_NOVOROZHD TO PUBLIC
/

