DROP FUNCTION ASU.GET_XRAY_RGKABINET1
/

--
-- GET_XRAY_RGKABINET1  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU."GET_XRAY_RGKABINET1" 
  RETURN NUMBER DETERMINISTIC
  IS -- Created by -= aAdmin.exe =- 
     -- ATTENTION! DO NOT MODIFY THIS FUNCTION MANUALLY!!!
BEGIN
  Return 12077;
END;
/

SHOW ERRORS;


GRANT EXECUTE ON ASU.GET_XRAY_RGKABINET1 TO PUBLIC
/

