DROP FUNCTION ASU.GET_PCR_NAZ_SOS
/

--
-- GET_PCR_NAZ_SOS  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--   SYS_STUB_FOR_PURITY_ANALYSIS (Package)
--   TLAB_PCR_AMPLIPH (Table)
--
CREATE OR REPLACE FUNCTION ASU."GET_PCR_NAZ_SOS" (pFK_REGISTID NUMBER, pFK_NAZSOSID NUMBER) RETURN  NUMBER IS
    CURSOR cAmp IS SELECT COUNT(*) FROM TLAB_PCR_AMPLIPH WHERE FK_REGISTID = pFK_REGISTID;
    nRes NUMBER;
BEGIN 
    OPEN cAmp;
    FETCH cAmp INTO nRes;
    CLOSE cAmp;
    
    IF nRes > 0 THEN
        RETURN 1;
    END IF;
    
    RETURN 0;
END;
/

SHOW ERRORS;


