DROP FUNCTION ASU.GET_NEED_AGENT_STATUS
/

--
-- GET_NEED_AGENT_STATUS  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU.GET_NEED_AGENT_STATUS
  RETURN NUMBER DETERMINISTIC
  IS -- Created by -= aAdmin.exe =- 
     -- ATTENTION! DO NOT MODIFY THIS FUNCTION MANUALLY!!!
BEGIN
  Return 0;
END;
/

SHOW ERRORS;


DROP PUBLIC SYNONYM GET_NEED_AGENT_STATUS
/

--
-- GET_NEED_AGENT_STATUS  (Synonym) 
--
--  Dependencies: 
--   GET_NEED_AGENT_STATUS (Function)
--
CREATE PUBLIC SYNONYM GET_NEED_AGENT_STATUS FOR ASU.GET_NEED_AGENT_STATUS
/


GRANT EXECUTE ON ASU.GET_NEED_AGENT_STATUS TO PUBLIC
/

