DROP FUNCTION ASU.GET_PAC_STOLID
/

--
-- GET_PAC_STOLID  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--   SYS_STUB_FOR_PURITY_ANALYSIS (Package)
--   TKARTA (Table)
--
CREATE OR REPLACE FUNCTION ASU."GET_PAC_STOLID" -- Created by TimurLan
  ( pFK_PACID IN NUMBER) RETURN VARCHAR2 IS
  CURSOR c IS SELECT FK_STOLID FROM TKARTA WHERE FK_ID=pFK_PACID ;
  nTemp NUMBER(15);
BEGIN
  OPEN c;
  FETCH c INTO nTemp;
  CLOSE c;
  RETURN nTemp;
END;
/

SHOW ERRORS;


