DROP FUNCTION ASU.GET_REANIMKAB
/

--
-- GET_REANIMKAB  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU."GET_REANIMKAB" 
  RETURN NUMBER DETERMINISTIC
  IS -- Created by -= aAdmin.exe =-
     -- ATTENTION! DO NOT MODIFY THIS FUNCTION MANUALLY!!!
BEGIN
  Return 11346;
END;
/

SHOW ERRORS;


