DROP FUNCTION ASU.GET_DEFECT_PODPIS
/

--
-- GET_DEFECT_PODPIS  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--   SYS_STUB_FOR_PURITY_ANALYSIS (Package)
--   TIBDEFEKT (Table)
--
CREATE OR REPLACE FUNCTION ASU."GET_DEFECT_PODPIS" 
  ( pFK_PACID IN NUMBER)
  RETURN  NUMBER IS
i NUMBER:=0;
CURSOR c IS SELECT FL_PODPIS FROM TIBDEFEKT WHERE FK_PACID=pFK_PACID;
BEGIN
  OPEN c;
  FETCH c INTO i;
  CLOSE c;
  RETURN i;
END; -- Function GET_DEFECT_PODPIS
/

SHOW ERRORS;


