DROP FUNCTION ASU.TYPE_IFA
/

--
-- TYPE_IFA  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU."TYPE_IFA" 
  RETURN NUMBER DETERMINISTIC
  IS -- Created by -= aAdmin.exe =- 
     -- ATTENTION! DO NOT MODIFY THIS FUNCTION MANUALLY!!!
BEGIN
  Return 826630;
END;
/

SHOW ERRORS;


GRANT EXECUTE ON ASU.TYPE_IFA TO PUBLIC
/

