DROP FUNCTION ASU.GET_ULUCHSHENIE
/

--
-- GET_ULUCHSHENIE  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU."GET_ULUCHSHENIE" 
  RETURN NUMBER DETERMINISTIC
  IS -- Created by -= aAdmin.exe =-
     -- ATTENTION! DO NOT MODIFY THIS FUNCTION MANUALLY!!!
BEGIN
  Return 790975;
END;
/

SHOW ERRORS;


