DROP FUNCTION ASU.GET_TSTANDART_GROUP_FL_TYPE
/

--
-- GET_TSTANDART_GROUP_FL_TYPE  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU."GET_TSTANDART_GROUP_FL_TYPE" 
  RETURN NUMBER DETERMINISTIC
  IS -- Created by -= aAdmin.exe =- 
     -- ATTENTION! DO NOT MODIFY THIS FUNCTION MANUALLY!!!
BEGIN
  Return 1;
END;
/

SHOW ERRORS;


GRANT EXECUTE ON ASU.GET_TSTANDART_GROUP_FL_TYPE TO PUBLIC
/

