DROP FUNCTION ASU.GET_CURR_CITY_KLADR_ID
/

--
-- GET_CURR_CITY_KLADR_ID  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU.Get_Curr_City_Kladr_Id
  RETURN NUMBER DETERMINISTIC
  IS -- Created by -= aAdmin.exe =- 
     -- ATTENTION! DO NOT MODIFY THIS FUNCTION MANUALLY!!!
BEGIN
  Return 2735;
END;
/

SHOW ERRORS;


GRANT EXECUTE ON ASU.GET_CURR_CITY_KLADR_ID TO PUBLIC
/

