DROP FUNCTION ASU.GET_UCH_VRACH
/

--
-- GET_UCH_VRACH  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU.GET_UCH_VRACH
      RETURN NUMBER DETERMINISTIC
      IS -- Created by -= aAdmin.exe =-
         -- ATTENTION! DO NOT MODIFY THIS FUNCTION MANUALLY!!!
   BEGIN
     Return -1979;
   END;
/

SHOW ERRORS;


