DROP FUNCTION ASU.GET_OPERBLOCK
/

--
-- GET_OPERBLOCK  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU."GET_OPERBLOCK" 
  RETURN NUMBER DETERMINISTIC
  IS -- Created by -= aAdmin.exe =- 
     -- ATTENTION! DO NOT MODIFY THIS FUNCTION MANUALLY!!!
BEGIN
  Return 284;
END;
/

SHOW ERRORS;


GRANT EXECUTE ON ASU.GET_OPERBLOCK TO PUBLIC
/

