DROP FUNCTION ASU.GET_NEED_ADRDOCWORK_OMS
/

--
-- GET_NEED_ADRDOCWORK_OMS  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU.GET_NEED_ADRDOCWORK_OMS
  RETURN NUMBER DETERMINISTIC
  IS -- Created by -= aAdmin.exe =-
     -- ATTENTION! DO NOT MODIFY THIS FUNCTION MANUALLY!!!
BEGIN
  Return 0;
END;
/

SHOW ERRORS;


