DROP FUNCTION ASU.GET_OPK_OSPK
/

--
-- GET_OPK_OSPK  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU."GET_OPK_OSPK" 
  RETURN NUMBER DETERMINISTIC
  IS -- Created by -= aAdmin.exe =-
     -- ATTENTION! DO NOT MODIFY THIS FUNCTION MANUALLY!!!
BEGIN
  Return 79666;
END;
/

SHOW ERRORS;


