DROP FUNCTION ASU.VARCHAR_TO_CLOB
/

--
-- VARCHAR_TO_CLOB  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DBMS_LOB (Synonym)
--   SYS_STUB_FOR_PURITY_ANALYSIS (Package)
--
CREATE OR REPLACE FUNCTION ASU."VARCHAR_TO_CLOB" (PSTR IN VARCHAR2) RETURN CLOB IS
  RESULT CLOB;
BEGIN
  DBMS_LOB.CREATETEMPORARY(RESULT,FALSE);
  DBMS_LOB.WRITE(RESULT,LENGTH(PSTR),1,PSTR);
  RETURN(RESULT);
END VARCHAR_TO_CLOB;
/

SHOW ERRORS;


