DROP FUNCTION ASU.GET_NAZ_PASP_ZD_ID
/

--
-- GET_NAZ_PASP_ZD_ID  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU.GET_NAZ_PASP_ZD_ID
  RETURN NUMBER DETERMINISTIC
  IS -- Created by -= aAdmin.exe =-
     -- ATTENTION! DO NOT MODIFY THIS FUNCTION MANUALLY!!!
BEGIN
  Return 1004936;
END;
/

SHOW ERRORS;


