DROP FUNCTION ASU.GET_CAN_USE_REG_ACCESS_KAB
/

--
-- GET_CAN_USE_REG_ACCESS_KAB  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU.GET_CAN_USE_REG_ACCESS_KAB RETURN NUMBER IS BEGIN RETURN 1; END;
/

SHOW ERRORS;


