DROP FUNCTION ASU.GET_AMBVOZR
/

--
-- GET_AMBVOZR  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--   SYS_STUB_FOR_PURITY_ANALYSIS (Package)
--   TAMBULANCE (Table)
--
CREATE OR REPLACE FUNCTION ASU."GET_AMBVOZR" 
  ( pFK_ID IN NUMBER)
  RETURN  NUMBER IS
  nTemp NUMBER;
  CURSOR cTemp IS SELECT ROUND((SYSDATE-FD_ROJD)/365) FROM TAMBULANCE WHERE FK_ID=pFK_ID;
BEGIN
  OPEN cTemp;
  FETCH cTemp INTO nTemp;
  CLOSE cTemp;
  RETURN nTemp;
END;
/

SHOW ERRORS;


