DROP FUNCTION ASU.GET_VID_OSMOTR_PERVICH
/

--
-- GET_VID_OSMOTR_PERVICH  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU.GET_VID_OSMOTR_PERVICH
  RETURN NUMBER DETERMINISTIC
  IS -- Created by -= aAdmin.exe =-
     -- ATTENTION! DO NOT MODIFY THIS FUNCTION MANUALLY!!!
BEGIN
  Return 935651;
END;
/

SHOW ERRORS;


