DROP FUNCTION ASU.GET_REGISTRATOR_FLUORO
/

--
-- GET_REGISTRATOR_FLUORO  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU."GET_REGISTRATOR_FLUORO" 
  RETURN NUMBER DETERMINISTIC
  IS -- Created by -= aAdmin.exe =- 
     -- ATTENTION! DO NOT MODIFY THIS FUNCTION MANUALLY!!!
BEGIN
  Return 2451;
END;
/

SHOW ERRORS;


GRANT EXECUTE ON ASU.GET_REGISTRATOR_FLUORO TO PUBLIC
/

