DROP FUNCTION ASU.GET_KART_PRER
/

--
-- GET_KART_PRER  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION ASU."GET_KART_PRER" 
  RETURN NUMBER DETERMINISTIC
  IS -- Created by -= aAdmin.exe =- 
     -- ATTENTION! DO NOT MODIFY THIS FUNCTION MANUALLY!!!
BEGIN
  Return 65923;
END;
/

SHOW ERRORS;


GRANT EXECUTE ON ASU.GET_KART_PRER TO PUBLIC
/

