CREATE FUNCTION ASU.GET_DEF_FUNCT(pFUNCT_NAME IN VARCHAR2, pDEF_VALUE NUMBER, pOwner VARCHAR2 DEFAULT 'ASU')
RETURN NUMBER
       IS
vRet NUMBER;
BEGIN
  vRet := pDEF_VALUE;

  IF ASU.GET_IS_EXIST_OBJECT(TRIM(pFUNCT_NAME), 'FUNCTION', TRIM(pOwner)) > 0
  THEN
     EXECUTE IMMEDIATE 'BEGIN :1 := ' || TRIM(pOwner) || '.' || TRIM(pFUNCT_NAME) || '; END;'
     USING OUT vRet;
  END IF;

  Return vRet;
END;
/
