/******************************************************************************/
/***               Generated by IBExpert 20.11.2013 11:26:54                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE TAGS (
    FC_TITLE               CHAR(15) NOT NULL,
    FC_IMAGETYPE_1         CHAR(5),
    FC_IMAGETYPE_2         CHAR(5),
    FC_STUDYID_1           CHAR(5),
    FC_STUDYID_2           CHAR(5),
    FC_PATIENTID_1         CHAR(5),
    FC_PATIENTID_2         CHAR(5),
    FC_STUDYDESCRIPTION_1  CHAR(5),
    FC_STUDYDESCRIPTION_2  CHAR(5),
    FC_ACCESSIONNUMBER_1   CHAR(5),
    FC_ACCESSIONNUMBER_2   CHAR(5),
    FC_DA_1                CHAR(5),
    FC_DA_2                CHAR(5),
    FC_DT_1                CHAR(5),
    FC_DT_2                CHAR(5),
    FC_STUDYUID_1          CHAR(5),
    FC_STUDYUID_2          CHAR(5),
    FC_SERIESUID_1         CHAR(5),
    FC_SERIESUID_2         CHAR(5),
    FC_SERNUM_1            CHAR(5),
    FC_SERNUM_2            CHAR(5),
    FC_PHYSNAME_1          CHAR(5),
    FC_PHYSNAME_2          CHAR(5),
    FC_PNAME_1             CHAR(5),
    FC_PNAME_2             CHAR(5),
    FC_PDATEBORN_1         CHAR(5),
    FC_PDATEBORN_2         CHAR(5),
    FC_PSEX_1              CHAR(5),
    FC_PSEX_2              CHAR(5),
    FC_AID_1               CHAR(5),
    FC_AID_2               CHAR(5),
    FC_ACQNUM_1            CHAR(5),
    FC_ACQNUM_2            CHAR(5),
    FC_INSTANCEUID_1       CHAR(5),
    FC_INSTANCEUID_2       CHAR(5),
    FC_KIN_1               CHAR(5),
    FC_KIN_2               CHAR(5)
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE TAGS ADD CONSTRAINT PK_TAGS PRIMARY KEY (FC_TITLE);


/******************************************************************************/
/***                          Fields descriptions                           ***/
/******************************************************************************/

DESCRIBE FIELD FC_TITLE TABLE TAGS
'AETITLE';

DESCRIBE FIELD FC_IMAGETYPE_1 TABLE TAGS
'Модальность (CS Modality)';

DESCRIBE FIELD FC_STUDYID_1 TABLE TAGS
'ID исследования (StudyID)';

DESCRIBE FIELD FC_PATIENTID_1 TABLE TAGS
'ID пациента (PatientID)';

DESCRIBE FIELD FC_STUDYDESCRIPTION_1 TABLE TAGS
'Комментарий-описание к исследованию (Study Description)';

DESCRIBE FIELD FC_ACCESSIONNUMBER_1 TABLE TAGS
'Номер протокола исследования';

DESCRIBE FIELD FC_DA_1 TABLE TAGS
'Дата исследования (Study Date)';

DESCRIBE FIELD FC_DT_1 TABLE TAGS
'Время исследования (Study Time)';

DESCRIBE FIELD FC_STUDYUID_1 TABLE TAGS
'Study Instance UID';

DESCRIBE FIELD FC_SERIESUID_1 TABLE TAGS
'Series Instanse UID';



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/
