ALTER TABLE ASU.TNAZPARAM
  DROP CONSTRAINT TNAZPARAM#VALUE
/


-- 
-- Foreign Key Constraints for Table TNAZPARAM 
-- 
ALTER TABLE ASU.TNAZPARAM ADD (
  CONSTRAINT TNAZPARAM#VALUE 
 FOREIGN KEY (FK_VALUEID) 
 REFERENCES ASU.TLECHPARAM (FK_ID)
    ON DELETE CASCADE)
/

