ALTER TABLE ASU.TRECIPE_DLO_EXP_REG_KATL
  DROP CONSTRAINT TRECIPE_DLO_EXP_REG_KATL_PK
/

-- 
-- Non Foreign Key Constraints for Table TRECIPE_DLO_EXP_REG_KATL 
-- 
ALTER TABLE ASU.TRECIPE_DLO_EXP_REG_KATL ADD (
  CONSTRAINT TRECIPE_DLO_EXP_REG_KATL_PK
 PRIMARY KEY
 (FK_ID))
/

