ALTER TABLE ASU.TPRIEMNAZ
  DROP CONSTRAINT TPRIEMNAZ_FKID
/

-- 
-- Non Foreign Key Constraints for Table TPRIEMNAZ 
-- 
ALTER TABLE ASU.TPRIEMNAZ ADD (
  CONSTRAINT TPRIEMNAZ_FKID
 UNIQUE (FK_ID))
/

