ALTER TABLE ASU.TTYPETIMESOTR
  DROP CONSTRAINT TTYPETIMSOTRE_FK_ID
/

-- 
-- Non Foreign Key Constraints for Table TTYPETIMESOTR 
-- 
ALTER TABLE ASU.TTYPETIMESOTR ADD (
  CONSTRAINT TTYPETIMSOTRE_FK_ID
 PRIMARY KEY
 (FK_ID))
/

