ALTER TABLE ASU.TREPORTSPREF
  DROP CONSTRAINT TREPORTSPREF_ID
/

-- 
-- Non Foreign Key Constraints for Table TREPORTSPREF 
-- 
ALTER TABLE ASU.TREPORTSPREF ADD (
  CONSTRAINT TREPORTSPREF_ID
 PRIMARY KEY
 (FK_ID))
/

