ALTER TABLE ASU.TRECIPE_DLO_REG_PAC
  DROP CONSTRAINT TRECIPE_DLO_REG_PAC_UNIQ
/

-- 
-- Non Foreign Key Constraints for Table TRECIPE_DLO_REG_PAC 
-- 
ALTER TABLE ASU.TRECIPE_DLO_REG_PAC ADD (
  CONSTRAINT TRECIPE_DLO_REG_PAC_UNIQ
 UNIQUE (UNIQCODE))
/

