ALTER TABLE ASU.TSTANDART_COST
  DROP CONSTRAINT TSTANDART_COST_PK
/

-- 
-- Non Foreign Key Constraints for Table TSTANDART_COST 
-- 
ALTER TABLE ASU.TSTANDART_COST ADD (
  CONSTRAINT TSTANDART_COST_PK
 PRIMARY KEY
 (FK_ID))
/

