ALTER TABLE ASU.TNEONATAL
  DROP CONSTRAINT TNEONATAL_PEOPL
/

-- 
-- Non Foreign Key Constraints for Table TNEONATAL 
-- 
ALTER TABLE ASU.TNEONATAL ADD (
  CONSTRAINT TNEONATAL_PEOPL
 PRIMARY KEY
 (FK_PEPLID))
/

