ALTER TABLE ASU.TRECIPE_DLO_PAC_ADRPREB
  DROP CONSTRAINT TRECIPE_DLO_PAC_ADRPREB_PK
/

-- 
-- Non Foreign Key Constraints for Table TRECIPE_DLO_PAC_ADRPREB 
-- 
ALTER TABLE ASU.TRECIPE_DLO_PAC_ADRPREB ADD (
  CONSTRAINT TRECIPE_DLO_PAC_ADRPREB_PK
 PRIMARY KEY
 (FK_ID))
/

