ALTER TABLE ASU.TFUS_SMIDLPU
  DROP CONSTRAINT TFUS_SMIDLPU_FK_FUSSMID
/


-- 
-- Foreign Key Constraints for Table TFUS_SMIDLPU 
-- 
ALTER TABLE ASU.TFUS_SMIDLPU ADD (
  CONSTRAINT TFUS_SMIDLPU_FK_FUSSMID 
 FOREIGN KEY (FK_FUSSMID) 
 REFERENCES ASU.TFUS_SMID (FK_ID))
/

