ALTER TABLE ASU.TBIRTH_CERTIFICATION
  DROP CONSTRAINT TBIRTH_CERTIFICATION_BY_ID
/

-- 
-- Non Foreign Key Constraints for Table TBIRTH_CERTIFICATION 
-- 
ALTER TABLE ASU.TBIRTH_CERTIFICATION ADD (
  CONSTRAINT TBIRTH_CERTIFICATION_BY_ID
 PRIMARY KEY
 (FK_ID))
/

