ALTER TABLE ASU.TNAZMEDLECH
  DROP CONSTRAINT TNAZMEDLECH_BY_ID
/

-- 
-- Non Foreign Key Constraints for Table TNAZMEDLECH 
-- 
ALTER TABLE ASU.TNAZMEDLECH ADD (
  CONSTRAINT TNAZMEDLECH_BY_ID
 PRIMARY KEY
 (FK_ID))
/

