ALTER TABLE ASU.TDISTRICT_HISTORY
  DROP CONSTRAINT TDISTRICT_HISTORY_PK
/

-- 
-- Non Foreign Key Constraints for Table TDISTRICT_HISTORY 
-- 
ALTER TABLE ASU.TDISTRICT_HISTORY ADD (
  CONSTRAINT TDISTRICT_HISTORY_PK
 PRIMARY KEY
 (FK_ID))
/

