ALTER TABLE ASU.TRECIPEDURATION
  DROP CONSTRAINT TRECIPEDURATION
/

-- 
-- Non Foreign Key Constraints for Table TRECIPEDURATION 
-- 
ALTER TABLE ASU.TRECIPEDURATION ADD (
  CONSTRAINT TRECIPEDURATION
 PRIMARY KEY
 (FK_ID))
/

