ALTER TABLE ASU.TRECIPETYPE
  DROP CONSTRAINT TRECIPETYPE_BY_ID
/

-- 
-- Non Foreign Key Constraints for Table TRECIPETYPE 
-- 
ALTER TABLE ASU.TRECIPETYPE ADD (
  CONSTRAINT TRECIPETYPE_BY_ID
 PRIMARY KEY
 (FK_ID))
/

