ALTER TABLE ASU.TTYPETIME
  DROP CONSTRAINT TTYPETIME_FK_ID
/

-- 
-- Non Foreign Key Constraints for Table TTYPETIME 
-- 
ALTER TABLE ASU.TTYPETIME ADD (
  CONSTRAINT TTYPETIME_FK_ID
 PRIMARY KEY
 (FK_ID))
/

