ALTER TABLE ASU.TRECIPE_DLO_PAC_SNP
  DROP CONSTRAINT TRECIPE_DLO_PAC_SNP_PAC_FK
/


-- 
-- Foreign Key Constraints for Table TRECIPE_DLO_PAC_SNP 
-- 
ALTER TABLE ASU.TRECIPE_DLO_PAC_SNP ADD (
  CONSTRAINT TRECIPE_DLO_PAC_SNP_PAC_FK 
 FOREIGN KEY (FK_REGPACID) 
 REFERENCES ASU.TRECIPE_DLO_REG_PAC (FK_ID))
/

