ALTER TABLE ASU.TNAZOPER_STATUS
  DROP CONSTRAINT TNAZOPER_STATUS_PK
/

-- 
-- Non Foreign Key Constraints for Table TNAZOPER_STATUS 
-- 
ALTER TABLE ASU.TNAZOPER_STATUS ADD (
  CONSTRAINT TNAZOPER_STATUS_PK
 PRIMARY KEY
 (FK_ID))
/

