ALTER TABLE ASU.TSIGN_SQL_RULES
  DROP CONSTRAINT TSIGN_SQL_RULES_PK
/

-- 
-- Non Foreign Key Constraints for Table TSIGN_SQL_RULES 
-- 
ALTER TABLE ASU.TSIGN_SQL_RULES ADD (
  CONSTRAINT TSIGN_SQL_RULES_PK
 PRIMARY KEY
 (FK_ID))
/

