ALTER TABLE ASU.TPEOPLE_LGOT
  DROP CONSTRAINT TPEOPLE_LGOT_PK
/

-- 
-- Non Foreign Key Constraints for Table TPEOPLE_LGOT 
-- 
ALTER TABLE ASU.TPEOPLE_LGOT ADD (
  CONSTRAINT TPEOPLE_LGOT_PK
 PRIMARY KEY
 (FK_ID))
/

