ALTER TABLE ASU.TRECIPE_DLO_EXP_EDMLF
  DROP CONSTRAINT TRECIPE_DLO_EXP_EDMLF_PK
/

-- 
-- Non Foreign Key Constraints for Table TRECIPE_DLO_EXP_EDMLF 
-- 
ALTER TABLE ASU.TRECIPE_DLO_EXP_EDMLF ADD (
  CONSTRAINT TRECIPE_DLO_EXP_EDMLF_PK
 PRIMARY KEY
 (C_MLF, C_FINL))
/

