ALTER TABLE ASU.TSOTRLACK
  DROP CONSTRAINT TSOTRLACK_BY_ID
/

-- 
-- Non Foreign Key Constraints for Table TSOTRLACK 
-- 
ALTER TABLE ASU.TSOTRLACK ADD (
  CONSTRAINT TSOTRLACK_BY_ID
 PRIMARY KEY
 (FK_ID))
/

