ALTER TABLE ASU.TPUTPLANDAYS
  DROP CONSTRAINT TPUTPLANDAYS_ID
/

-- 
-- Non Foreign Key Constraints for Table TPUTPLANDAYS 
-- 
ALTER TABLE ASU.TPUTPLANDAYS ADD (
  CONSTRAINT TPUTPLANDAYS_ID
 PRIMARY KEY
 (FK_ID))
/

