ALTER TABLE ASU.TDOPRIZYV
  DROP CONSTRAINT TDOPRIZYV_PEOPL
/

-- 
-- Non Foreign Key Constraints for Table TDOPRIZYV 
-- 
ALTER TABLE ASU.TDOPRIZYV ADD (
  CONSTRAINT TDOPRIZYV_PEOPL
 PRIMARY KEY
 (FK_PEPLID))
/

