ALTER TABLE ASU.TADR_HISTORY
  DROP CONSTRAINT TADR_HIST_BY_ID
/

-- 
-- Non Foreign Key Constraints for Table TADR_HISTORY 
-- 
ALTER TABLE ASU.TADR_HISTORY ADD (
  CONSTRAINT TADR_HIST_BY_ID
 PRIMARY KEY
 (FK_ID))
/

