ALTER TABLE ASU.TRECIPE_DLO_IMP_REQ
  DROP CONSTRAINT TRECIPE_DLO_IMP_REQ_PK
/

-- 
-- Non Foreign Key Constraints for Table TRECIPE_DLO_IMP_REQ 
-- 
ALTER TABLE ASU.TRECIPE_DLO_IMP_REQ ADD (
  CONSTRAINT TRECIPE_DLO_IMP_REQ_PK
 PRIMARY KEY
 (UNIQCODE))
/

