ALTER TABLE ASU.TS_PRINTIB
  DROP CONSTRAINT TS_PRINTIB_BY_ID
/

-- 
-- Non Foreign Key Constraints for Table TS_PRINTIB 
-- 
ALTER TABLE ASU.TS_PRINTIB ADD (
  CONSTRAINT TS_PRINTIB_BY_ID
 PRIMARY KEY
 (FK_ID))
/

