ALTER TABLE ASU.TRECIPE_DLO_REG_PAC_INFO
  DROP CONSTRAINT TRECIPE_DLO_RPAC_INFO_PK
/

-- 
-- Non Foreign Key Constraints for Table TRECIPE_DLO_REG_PAC_INFO 
-- 
ALTER TABLE ASU.TRECIPE_DLO_REG_PAC_INFO ADD (
  CONSTRAINT TRECIPE_DLO_RPAC_INFO_PK
 PRIMARY KEY
 (FK_ID))
/

