ALTER TABLE ASU.TRECIPE_DLO_PAC_ADRPREB
  DROP CONSTRAINT TRECIPE_DLO_PAC_ADRPREB_PAC_FK
/


-- 
-- Foreign Key Constraints for Table TRECIPE_DLO_PAC_ADRPREB 
-- 
ALTER TABLE ASU.TRECIPE_DLO_PAC_ADRPREB ADD (
  CONSTRAINT TRECIPE_DLO_PAC_ADRPREB_PAC_FK 
 FOREIGN KEY (FK_REGPACID) 
 REFERENCES ASU.TRECIPE_DLO_REG_PAC (FK_ID))
/

