ALTER TABLE ASU.TINSURANCE
  DROP CONSTRAINT TINSURANCE_BY_ID
/

-- 
-- Non Foreign Key Constraints for Table TINSURANCE 
-- 
ALTER TABLE ASU.TINSURANCE ADD (
  CONSTRAINT TINSURANCE_BY_ID
 PRIMARY KEY
 (FK_ID))
/

