ALTER TABLE ASU.TPRAVA_PASPORT
  DROP CONSTRAINT TPRAVA_PASPORT_ID
/

-- 
-- Non Foreign Key Constraints for Table TPRAVA_PASPORT 
-- 
ALTER TABLE ASU.TPRAVA_PASPORT ADD (
  CONSTRAINT TPRAVA_PASPORT_ID
 PRIMARY KEY
 (FK_ID))
/

