ALTER TABLE ASU.TNAPRAVLECH
  DROP CONSTRAINT TNAPRAVLECH_PK
/

-- 
-- Non Foreign Key Constraints for Table TNAPRAVLECH 
-- 
ALTER TABLE ASU.TNAPRAVLECH ADD (
  CONSTRAINT TNAPRAVLECH_PK
 PRIMARY KEY
 (FK_ID))
/

