ALTER TABLE ASU.TPATRONAT
  DROP CONSTRAINT TPATRONAT_PEOPLE
/

-- 
-- Non Foreign Key Constraints for Table TPATRONAT 
-- 
ALTER TABLE ASU.TPATRONAT ADD (
  CONSTRAINT TPATRONAT_PEOPLE
 PRIMARY KEY
 (FK_PEPLID))
/

