ALTER TABLE ASU.TLECHPARAM
  DROP CONSTRAINT TLECHPARAM#ID
/

-- 
-- Non Foreign Key Constraints for Table TLECHPARAM 
-- 
ALTER TABLE ASU.TLECHPARAM ADD (
  CONSTRAINT TLECHPARAM#ID
 PRIMARY KEY
 (FK_ID))
/

