ALTER TABLE ASU.TDISTRICT
  DROP CONSTRAINT TDISTRICT_PK
/

-- 
-- Non Foreign Key Constraints for Table TDISTRICT 
-- 
ALTER TABLE ASU.TDISTRICT ADD (
  CONSTRAINT TDISTRICT_PK
 PRIMARY KEY
 (FK_ID))
/

