ALTER TABLE ASU.TRECIPE
  DROP CONSTRAINT TRECIPE_BY_ID
/

-- 
-- Non Foreign Key Constraints for Table TRECIPE 
-- 
ALTER TABLE ASU.TRECIPE ADD (
  CONSTRAINT TRECIPE_BY_ID
 PRIMARY KEY
 (FK_ID))
/

