ALTER TABLE ASU.TSCREENING_SDIAG
  DROP CONSTRAINT TSCREENING_SDIAG_BY_ID
/

-- 
-- Non Foreign Key Constraints for Table TSCREENING_SDIAG 
-- 
ALTER TABLE ASU.TSCREENING_SDIAG ADD (
  CONSTRAINT TSCREENING_SDIAG_BY_ID
 PRIMARY KEY
 (FK_ID))
/

