ALTER TABLE ASU.TRECIPE_DLO_PAC_AMBKAR
  DROP CONSTRAINT TRECIPE_DLO_PAC_AMBKAR_PK
/

-- 
-- Non Foreign Key Constraints for Table TRECIPE_DLO_PAC_AMBKAR 
-- 
ALTER TABLE ASU.TRECIPE_DLO_PAC_AMBKAR ADD (
  CONSTRAINT TRECIPE_DLO_PAC_AMBKAR_PK
 PRIMARY KEY
 (FK_ID))
/

