ALTER TABLE ASU.TNAZWIZZARD_MEDPAR
  DROP CONSTRAINT TNAZWIZZARD_MEDPAR_WMEDNAZ
/


-- 
-- Foreign Key Constraints for Table TNAZWIZZARD_MEDPAR 
-- 
ALTER TABLE ASU.TNAZWIZZARD_MEDPAR ADD (
  CONSTRAINT TNAZWIZZARD_MEDPAR_WMEDNAZ 
 FOREIGN KEY (FK_NAZWIZZARD_MEDNAZ) 
 REFERENCES ASU.TNAZWIZZARD_MEDNAZ (FK_ID)
    ON DELETE CASCADE)
/

