ALTER TABLE ASU.TRECIPE_DLO_REG_PAC_INFO
  DROP CONSTRAINT TRECIPE_DLO_RPAC_INFO_FK
/


-- 
-- Foreign Key Constraints for Table TRECIPE_DLO_REG_PAC_INFO 
-- 
ALTER TABLE ASU.TRECIPE_DLO_REG_PAC_INFO ADD (
  CONSTRAINT TRECIPE_DLO_RPAC_INFO_FK 
 FOREIGN KEY (FK_REGPACID) 
 REFERENCES ASU.TRECIPE_DLO_REG_PAC (FK_ID))
/

