ALTER TABLE ASU.TPARTOGRAMMAPARAMS
  DROP CONSTRAINT TPARTPARAMS_ID_UNIQUE
/

-- 
-- Non Foreign Key Constraints for Table TPARTOGRAMMAPARAMS 
-- 
ALTER TABLE ASU.TPARTOGRAMMAPARAMS ADD (
  CONSTRAINT TPARTPARAMS_ID_UNIQUE
 UNIQUE (FK_ID))
/

