ALTER TABLE ASU.TRECIPE
  DROP CONSTRAINT TRECIPE_SERIAL_NUM_UNIQ1
/

-- 
-- Non Foreign Key Constraints for Table TRECIPE 
-- 
ALTER TABLE ASU.TRECIPE ADD (
  CONSTRAINT TRECIPE_SERIAL_NUM_UNIQ1
 UNIQUE (FN_NUM, FC_SERIAL, FL_DEL))
/

