ALTER TABLE ASU.TINSURDOCS
  DROP CONSTRAINT TINSURDOCS_PK
/

-- 
-- Non Foreign Key Constraints for Table TINSURDOCS 
-- 
ALTER TABLE ASU.TINSURDOCS ADD (
  CONSTRAINT TINSURDOCS_PK
 PRIMARY KEY
 (FK_ID))
/

