ALTER TABLE ASU.TCHILD_COMMON
  DROP CONSTRAINT TCHILD_PEOPL
/

-- 
-- Non Foreign Key Constraints for Table TCHILD_COMMON 
-- 
ALTER TABLE ASU.TCHILD_COMMON ADD (
  CONSTRAINT TCHILD_PEOPL
 PRIMARY KEY
 (FK_PEPLID))
/

