ALTER TABLE ASU.TRECIPE_DLO_PAC_TYPELPU
  DROP CONSTRAINT TRECIPE_DLO_PAC_TYPELPU_PK
/

-- 
-- Non Foreign Key Constraints for Table TRECIPE_DLO_PAC_TYPELPU 
-- 
ALTER TABLE ASU.TRECIPE_DLO_PAC_TYPELPU ADD (
  CONSTRAINT TRECIPE_DLO_PAC_TYPELPU_PK
 PRIMARY KEY
 (FK_ID))
/

