ALTER TABLE ASU.TOPER_SMID
  DROP CONSTRAINT TTOPERSMID_PRIMA_KEY
/

-- 
-- Non Foreign Key Constraints for Table TOPER_SMID 
-- 
ALTER TABLE ASU.TOPER_SMID ADD (
  CONSTRAINT TTOPERSMID_PRIMA_KEY
 PRIMARY KEY
 (FK_ID))
/

