ALTER TABLE ASU.TNAZWIZZARD_MEDNAZ
  DROP CONSTRAINT TNAZWIZZARD_MEDNAZ_PK
/

-- 
-- Non Foreign Key Constraints for Table TNAZWIZZARD_MEDNAZ 
-- 
ALTER TABLE ASU.TNAZWIZZARD_MEDNAZ ADD (
  CONSTRAINT TNAZWIZZARD_MEDNAZ_PK
 PRIMARY KEY
 (FK_ID))
/

