ALTER TABLE ASU.TCOMPANY_OTDEL
  DROP CONSTRAINT TCOMPANYOTDEL_PRIMA_KEY
/

-- 
-- Non Foreign Key Constraints for Table TCOMPANY_OTDEL 
-- 
ALTER TABLE ASU.TCOMPANY_OTDEL ADD (
  CONSTRAINT TCOMPANYOTDEL_PRIMA_KEY
 PRIMARY KEY
 (FK_ID))
/

