ALTER TABLE ASU.T_SDF_ELEMENT
  DROP CONSTRAINT T_SDF_ELEMENT_GLOBAL_UNIQ
/

-- 
-- Non Foreign Key Constraints for Table T_SDF_ELEMENT 
-- 
ALTER TABLE ASU.T_SDF_ELEMENT ADD (
  CONSTRAINT T_SDF_ELEMENT_GLOBAL_UNIQ
 UNIQUE (FK_GLOBALID))
/

