ALTER TABLE ASU.TLINK_SERV
  DROP CONSTRAINT TLINK_SERV_BY_ID
/

-- 
-- Non Foreign Key Constraints for Table TLINK_SERV 
-- 
ALTER TABLE ASU.TLINK_SERV ADD (
  CONSTRAINT TLINK_SERV_BY_ID
 PRIMARY KEY
 (FK_ID))
/

