ALTER TABLE ASU.TAPOSTAVSHIK
  DROP CONSTRAINT TAPOSTAVSHIK_PK
/

-- 
-- Non Foreign Key Constraints for Table TAPOSTAVSHIK 
-- 
ALTER TABLE ASU.TAPOSTAVSHIK ADD (
  CONSTRAINT TAPOSTAVSHIK_PK
 PRIMARY KEY
 (FK_ID))
/

