ALTER TABLE ASU.TNAZMON
  DROP CONSTRAINT TNAZMON_BY_ID
/

-- 
-- Non Foreign Key Constraints for Table TNAZMON 
-- 
ALTER TABLE ASU.TNAZMON ADD (
  CONSTRAINT TNAZMON_BY_ID
 PRIMARY KEY
 (FK_ID))
/

