ALTER TABLE ASU.TDISP_FILTER
  DROP CONSTRAINT TDISP_FILTER_BY_ID
/

-- 
-- Non Foreign Key Constraints for Table TDISP_FILTER 
-- 
ALTER TABLE ASU.TDISP_FILTER ADD (
  CONSTRAINT TDISP_FILTER_BY_ID
 PRIMARY KEY
 (FK_ID))
/

