ALTER TABLE ASU.TCHEMOTHERAPY_TEMPL
  DROP CONSTRAINT TCHEMOTHERAPY_TEMPL_PK
/

-- 
-- Non Foreign Key Constraints for Table TCHEMOTHERAPY_TEMPL 
-- 
ALTER TABLE ASU.TCHEMOTHERAPY_TEMPL ADD (
  CONSTRAINT TCHEMOTHERAPY_TEMPL_PK
 PRIMARY KEY
 (FK_ID))
/

