ALTER TABLE ASU.TNAZMED
  DROP CONSTRAINT TNAZMED_BY_ID
/

-- 
-- Non Foreign Key Constraints for Table TNAZMED 
-- 
ALTER TABLE ASU.TNAZMED ADD (
  CONSTRAINT TNAZMED_BY_ID
 PRIMARY KEY
 (FK_ID))
/

