ALTER TABLE ASU.TRECIPE
  DROP CONSTRAINT TRECIPE_TRECIPEPERCENT
/


-- 
-- Foreign Key Constraints for Table TRECIPE 
-- 
ALTER TABLE ASU.TRECIPE ADD (
  CONSTRAINT TRECIPE_TRECIPEPERCENT 
 FOREIGN KEY (FK_PERCENT) 
 REFERENCES ASU.TRECIPEPERCENT (FK_ID))
/

