ALTER TABLE ASU.TINSUR_PROGRAM
  DROP CONSTRAINT TINSUR_PROG_BY_ID
/

-- 
-- Non Foreign Key Constraints for Table TINSUR_PROGRAM 
-- 
ALTER TABLE ASU.TINSUR_PROGRAM ADD (
  CONSTRAINT TINSUR_PROG_BY_ID
 PRIMARY KEY
 (FK_ID))
/

