ALTER TABLE ASU.TCOMPANY
  DROP CONSTRAINT TCOMPANY_SYN
/

-- 
-- Non Foreign Key Constraints for Table TCOMPANY 
-- 
ALTER TABLE ASU.TCOMPANY ADD (
  CONSTRAINT TCOMPANY_SYN
 UNIQUE (FC_SYNONIM))
/

