DROP SEQUENCE ASU.SEQ_TDIALIZ_NAZMEDLECH_SHABLON
/

--
-- SEQ_TDIALIZ_NAZMEDLECH_SHABLON  (Sequence) 
--
CREATE SEQUENCE ASU.SEQ_TDIALIZ_NAZMEDLECH_SHABLON
  START WITH 1
  MAXVALUE 9999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER
/


