UPDATE MED.TDOCS set FK_SKLAD_ID = (select MAX(FK_ID) FROM MED.TSKLAD WHERE FC_SYNONIM = 'APTEKA');
UPDATE MED.TMEDIC set FK_SKLAD_ID = (select MAX(FK_ID) FROM MED.TSKLAD WHERE FC_SYNONIM = 'APTEKA');
UPDATE MED.TUCHGR set FK_SKLAD_ID = (select MAX(FK_ID) FROM MED.TSKLAD WHERE FC_SYNONIM = 'APTEKA');
UPDATE MED.TMO set FK_SKLAD_ID = (select MAX(FK_ID) FROM MED.TSKLAD WHERE FC_SYNONIM = 'APTEKA');
UPDATE MED.TTREB set FK_SKLAD_ID = (select MAX(FK_ID) FROM MED.TSKLAD WHERE FC_SYNONIM = 'APTEKA');
UPDATE MED.TPOSTAV set FK_SKLAD_ID = (select MAX(FK_ID) FROM MED.TSKLAD WHERE FC_SYNONIM = 'APTEKA');
UPDATE MED.TPRODCERT set FK_SKLAD_ID = (select MAX(FK_ID) FROM MED.TSKLAD WHERE FC_SYNONIM = 'APTEKA');
UPDATE MED.TZAYAVKA set FK_SKLAD_ID = (select MAX(FK_ID) FROM MED.TSKLAD WHERE FC_SYNONIM = 'APTEKA');
UPDATE MED.TMO set FK_SKLAD_ID = (select MAX(FK_ID) FROM MED.TSKLAD WHERE FC_SYNONIM = 'APTEKA');
commit;



