ALTER TABLE MED.TKARTCOMPOS ADD (FK_PRODUCE_TYPE NUMBER)
/
COMMENT ON COLUMN MED.TKARTCOMPOS.FK_PRODUCE_TYPE IS 'тип производства (med.tproduce_type)'
/
CREATE INDEX MED.TKARTCOMPOS_FK_PRODUCE_TYPE ON MED.TKARTCOMPOS
   (  FK_PRODUCE_TYPE ASC  ) 
 COMPUTE STATISTICS 
/

ALTER TABLE MED.TKARTCOMPOS ADD CONSTRAINT TKARTCOMPOS_CTPRODUCE_TYPE
  FOREIGN KEY (
FK_PRODUCE_TYPE
)
 REFERENCES MED.TPRODUCE_TYPE
 (
FK_ID
) 
/
