ALTER TABLE MED.TKARTCOMPOS ADD (FK_TREB_ID NUMBER)
/
COMMENT ON COLUMN MED.TKARTCOMPOS.FK_TREB_ID IS 'ссылка на требование, по которому сделано производство'
/
CREATE INDEX MED.TKARTCOMPOS_FK_TREB_ID ON MED.TKARTCOMPOS
   (  FK_TREB_ID ASC  ) 
 COMPUTE STATISTICS 
/
