ALTER TABLE MED.TTREB_DPC_BYNAZ 
 ADD (
  FK_NAZN_MEDIC_NAME NUMBER DEFAULT -1 NOT NULL
 )
/
COMMENT ON COLUMN MED.TTREB_DPC_BYNAZ.FK_NAZN_MEDIC_NAME IS 'медикамент, который назначил врач (из MED.TLATIN_NAMES)'
/
COMMENT ON COLUMN MED.TTREB_DPC_BYNAZ.FN_NAZNKOL_U IS 'Назначенное кол-во (кол-во фас. единиц)'
/

ALTER TABLE MED.TTREB_DPC_BYNAZ 
 ADD (
  FK_NAZN_EI NUMBER DEFAULT -1 NOT NULL
 )
/

COMMENT ON COLUMN MED.TTREB_DPC_BYNAZ.FK_NAZN_MEDIC_NAME IS 'медикамент, который назначил врач (из MED.TLATIN_NAMES)'
/
COMMENT ON COLUMN MED.TTREB_DPC_BYNAZ.FK_NAZN_EI IS 'единицы измерения назначаемого препарата (MED.TMassUnits)'
/
