CREATE TABLE MED.TTEMPLATE_DPC
  (
  FK_ID NUMBER,
  FK_TEMPLATE_DOC_ID NUMBER,
  FK_MEDIC_ID NUMBER,
  FN_KOL NUMBER
 )
/

COMMENT ON TABLE MED.TTEMPLATE_DPC IS 
'ѕозиции дл€ шаблонов документов (списани€ и требовани€). Author:Voronov'
/
COMMENT ON COLUMN MED.TTEMPLATE_DPC.FK_TEMPLATE_DOC_ID IS 'ссылка MED.TTEMPLATE_DOC.FK_ID'
/
COMMENT ON COLUMN MED.TTEMPLATE_DPC.FK_MEDIC_ID IS 'ссылка на медикамент MED.TMEDIC.MEDICID'
/
COMMENT ON COLUMN MED.TTEMPLATE_DPC.FN_KOL IS ' ол-во'
/

CREATE SEQUENCE MED.SEQ_TTEMPLATE_DPC
/

CREATE or replace TRIGGER MED.TTEMPLATE_DPC_INS
 BEFORE 
 INSERT
 ON MED.TTEMPLATE_DPC
 FOR EACH ROW 
begin
  if :NEW.FK_ID is null then
    select MED.SEQ_TTEMPLATE_DPC.NEXTVAL into :NEW.FK_ID from dual;
  end if;
end;
/



CREATE Unique INDEX MED.TTEMPLATE_DPC_FK_ID ON MED.TTEMPLATE_DPC
   (  FK_ID ASC  ) 
 COMPUTE STATISTICS 
/

CREATE INDEX MED.TTEMPLATE_DPC_FK_TEMPLATE_DOC ON MED.TTEMPLATE_DPC
   (  FK_TEMPLATE_DOC_ID ASC  ) 
 COMPUTE STATISTICS 
/

ALTER TABLE MED.TTEMPLATE_DPC ADD CONSTRAINT TTEMPLATE_DPC_MEDIC
  FOREIGN KEY (FK_MEDIC_ID)
 REFERENCES MED.TMEDIC
 (MEDICID) 
 ON DELETE CASCADE 
/
