DROP TABLE MED.TDOCS_AUTONUM
/
CREATE TABLE MED.TDOCS_AUTONUM
  (
  FK_ID NUMBER,
  FK_TDOCS_AUTONUM_COUNTER_ID NUMBER,
  FD_START DATE DEFAULT SYSDATE,  
  FP_VID NUMBER,
  FP_VIDMOVE NUMBER,
  FK_MOGROUP_ID NUMBER,
  FL_ENABLED NUMBER (1) DEFAULT 0,
  FN_TYPE_AUTONUM NUMBER DEFAULT 1
 )
/
COMMENT ON TABLE MED.TDOCS_AUTONUM IS 
'Информация по автонумерации документов. Author:Voronov'
/
COMMENT ON COLUMN MED.TDOCS_AUTONUM.FK_ID IS 'ключ'
/
COMMENT ON COLUMN MED.TDOCS_AUTONUM.FK_TDOCS_AUTONUM_COUNTER_ID IS 'ссылка на счетчик MED.TDOCS_AUTONUM_COUNTER.FK_ID'
/
COMMENT ON COLUMN MED.TDOCS_AUTONUM.FD_START IS 'дата начала действия новой нумерации'
/
COMMENT ON COLUMN MED.TDOCS_AUTONUM.FP_VID IS 'тип документа (1-приход, 2-движение, 3 - списание)'
/
COMMENT ON COLUMN MED.TDOCS_AUTONUM.FP_VIDMOVE IS 'подтип документа (med.get_decodedocvidmove)'
/
COMMENT ON COLUMN MED.TDOCS_AUTONUM.FK_MOGROUP_ID IS 'для какого отделения нумерация (null - для всех)'
/
COMMENT ON COLUMN MED.TDOCS_AUTONUM.FL_ENABLED IS '0 - выключен, 1 - включен'
/
COMMENT ON COLUMN MED.TDOCS_AUTONUM.FN_TYPE_AUTONUM IS 'тип автонумерации (расшифровки в функции med.get_docs_autonum_type_text)'
/

drop SEQUENCE MED.SEQ_TDOCS_AUTONUM
/
CREATE SEQUENCE MED.SEQ_TDOCS_AUTONUM
/
CREATE OR REPLACE TRIGGER med.tdocs_autonum_ins
 BEFORE
  INSERT
 ON med.tdocs_autonum
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
begin
  if :new.fk_id is null then
    select MED.SEQ_TDOCS_AUTONUM.NEXTVAL into :new.fk_id from dual;
  end if;
end;
/

CREATE Unique INDEX MED.TDOCS_AUTONUM_UK ON MED.TDOCS_AUTONUM
   (  FK_ID DESC  ) 
 COMPUTE STATISTICS 
/
CREATE INDEX MED.TDOCS_AUTONUM_DATE_VM ON MED.TDOCS_AUTONUM
   ( FD_START desc,  FP_VIDMOVE ASC) 
 COMPUTE STATISTICS 
/
CREATE INDEX MED.TDOCS_AUTONUM_FK_COUNTER ON MED.TDOCS_AUTONUM
   (  FK_TDOCS_AUTONUM_COUNTER_ID ASC  ) 
 COMPUTE STATISTICS 
/


drop TABLE MED.TDOCS_AUTONUM_COUNTER
/
CREATE TABLE MED.TDOCS_AUTONUM_COUNTER
  (
  FK_ID NUMBER,
  FN_STARTNUM NUMBER  DEFAULT 1,
  FN_CURNUM NUMBER  DEFAULT 1
 )
/
COMMENT ON TABLE MED.TDOCS_AUTONUM_COUNTER IS 
'Счетчики для автонумерации документов. Author:Voronov'
/
COMMENT ON COLUMN MED.TDOCS_AUTONUM_COUNTER.FK_ID IS 'ключ'
/
COMMENT ON COLUMN MED.TDOCS_AUTONUM_COUNTER.FN_CURNUM IS 'текущий свободный номер'
/

drop SEQUENCE MED.SEQ_TDOCS_AUTONUM_COUNTER
/
CREATE SEQUENCE MED.SEQ_TDOCS_AUTONUM_COUNTER
/
CREATE OR REPLACE TRIGGER med.TDOCS_AUTONUM_COUNTER_ins
 BEFORE
  INSERT
 ON med.TDOCS_AUTONUM_COUNTER
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
begin
  if :new.fk_id is null then
    select MED.SEQ_TDOCS_AUTONUM_COUNTER.NEXTVAL into :new.fk_id from dual;
  end if;
end;
/
CREATE UNIQUE INDEX med.tdocs_autonum_counter_uk ON med.tdocs_autonum_counter
  (
    fk_id                           ASC
  )
/
