-- !! сначала создать типы данных MED.ARRAY200_OF_INT, med.O_FC_POST_FIO_SOTR, MED.ARRAY200_OF_POST_FIO_SOTR
-- корректируем первичный ключ
ALTER TABLE MED.TINVLIST DROP CONSTRAINT PK_TINVLIST CASCADE;

DROP INDEX MED.PK_INVLIST;

ALTER TABLE MED.TINVLIST
  ADD CONSTRAINT PK_TINVLIST PRIMARY KEY (INVLISTID);
  
-- добавляем недостающие внешние ключи  
ALTER TABLE MED.TINVLIST
  ADD CONSTRAINT TINVLIST_TMO_MATOTVID_OWNER_FK FOREIGN KEY (MATOTVID_OWNER)
  REFERENCES MED.TMO (MOID);  
  
ALTER TABLE MED.TINVLIST
  ADD CONSTRAINT TINVLIST_TOGROUP_MATOTVID_FK FOREIGN KEY (MATOTVID)
  REFERENCES MED.TMO_GROUP (GROUPID);  
-------------------------------------------
-- источник фин-я 
ALTER TABLE MED.TINVLIST ADD FK_FINSOURCE_ID NUMBER;
 
COMMENT ON COLUMN MED.TINVLIST.FK_FINSOURCE_ID
  IS 'источник фин-я (ссылка med.tfinsource.fk_id)';
 
ALTER TABLE MED.TINVLIST
  ADD CONSTRAINT TINVLIST_TFINSOURCE_FK FOREIGN KEY (FK_FINSOURCE_ID)
  REFERENCES MED.TFINSOURCE (FK_ID);
-------------------------------------------  

-- флаг подписи 
ALTER TABLE MED.TINVLIST ADD FL_EDIT NUMBER(1) DEFAULT 1; 

COMMENT ON COLUMN MED.TINVLIST.FL_EDIT
  IS '0 - подписан, 1 - нет';  
-------------------------------------------
  
-- кем подписан 
ALTER TABLE MED.TINVLIST ADD FK_SIGNED_BY_MO NUMBER; 

COMMENT ON COLUMN MED.TINVLIST.FK_SIGNED_BY_MO
  IS 'кем подписан';
  
ALTER TABLE MED.TINVLIST
  ADD CONSTRAINT TINVLIST_TMO_SIGNED_BY_MO_FK FOREIGN KEY (FK_SIGNED_BY_MO)
  REFERENCES MED.TMO (MOID);
-------------------------------------------

-- когда подписан 
ALTER TABLE MED.TINVLIST ADD FD_SIGNED DATE; 

COMMENT ON COLUMN MED.TINVLIST.FD_SIGNED
  IS 'когда подписан';

-------------------------------------------

-- учетные группы спиртов
ALTER TABLE MED.TINVLIST ADD FARR_SPIRT_UCHGR MED.ARRAY200_OF_INT DEFAULT MED.ARRAY200_OF_INT();

COMMENT ON COLUMN MED.TINVLIST.FARR_SPIRT_UCHGR
  IS 'учетные группы спиртов';
-------------------------------------------

-- учетные группы дефицитных препаратов
ALTER TABLE MED.TINVLIST ADD FARR_DEFICIT_UCHGR MED.ARRAY200_OF_INT DEFAULT MED.ARRAY200_OF_INT();

COMMENT ON COLUMN MED.TINVLIST.FARR_DEFICIT_UCHGR
  IS 'учетные группы дефицитных препаратов';
-------------------------------------------

-- учетные группы наркотических, психотропных и ядовитых веществ
ALTER TABLE MED.TINVLIST ADD FARR_NARC_UCHGR MED.ARRAY200_OF_INT DEFAULT MED.ARRAY200_OF_INT(); 

COMMENT ON COLUMN MED.TINVLIST.FARR_NARC_UCHGR
  IS 'учетные группы наркотических, психотропных и ядовитых веществ';
-------------------------------------------

-- присутствующие лица 
ALTER TABLE MED.TINVLIST ADD FARR_ATTEND_PEOPLE MED.ARRAY200_OF_POST_FIO_SOTR DEFAULT MED.ARRAY200_OF_POST_FIO_SOTR();

COMMENT ON COLUMN MED.TINVLIST.FARR_ATTEND_PEOPLE
  IS 'присутствующие лица';
-------------------------------------------

-- дата создания документа
ALTER TABLE MED.TINVLIST ADD FD_CREATE DATE DEFAULT SYSDATE;
 
COMMENT ON COLUMN MED.TINVLIST.FD_CREATE
  IS 'дата создания документа';


-- ADD/MODIFY COLUMNS 
ALTER TABLE MED.TINVLIST MODIFY MATOTVID_OWNER NULL;
ALTER TABLE MED.TINVLIST MODIFY MATOTVID NULL;
ALTER TABLE MED.TINVLIST MODIFY FD_DATA1 NULL;
ALTER TABLE MED.TINVLIST MODIFY FD_DATA2 NULL;
