set define off
DROP TABLE MED.TIMP_DOC_ITEMS
/
CREATE TABLE MED.TIMP_DOC_ITEMS
  (
  FK_ID NUMBER,
  FK_IMP_DOC_ID NUMBER,
  FC_SRC_NUM VARCHAR2 (5),
  FC_SRC_MEDIC_TORG_NAME VARCHAR2 (300),
  FC_SRC_MEDIC_ID_THEIR VARCHAR2 (10),
  FC_SRC_MEDIC_ED_IZM VARCHAR2 (15),
  FC_SRC_MEDIC_KOLVO VARCHAR2 (10),
  FC_SRC_PARTY_SERIA VARCHAR2 (20),
  FC_SRC_PARTY_GODNOST VARCHAR2 (15),
  FC_SRC_PARTY_PRICE_BEZ_NDS VARCHAR2 (15),
  FC_SRC_PARTY_SUMM_NDS VARCHAR2 (15),
  FC_SRC_NDS VARCHAR2 (10),
  FC_SRC_PARTY_PROIZVODITEL VARCHAR2 (100),
  FC_SRC_PARTY_SERTIFIKAT VARCHAR2 (100),
  FD_INS_DATE DATE,
  FD_EDIT_DATE NUMBER,
  FK_INS_MO NUMBER,
  FK_EDIT_MO NUMBER,
  FK_PRS_MEDIC_ID_OUR NUMBER,
  FK_PRS_MEDIC_ID_THEIR NUMBER,
  FK_PRS_MEDIC_ED_IZM NUMBER,
  FN_PRS_MEDIC_KOLVO NUMBER,
  FD_PRS_PARTY_GODNOST DATE,
  FN_PRS_PARTY_PRICE NUMBER,
  FN_PRS_PARTY_SUMM_NDS NUMBER,
  FN_PRS_NDS NUMBER,
  FK_PRS_PARTY_PROIZVODITEL NUMBER,
  FK_PRS_PARTY_SERTIFIKAT NUMBER,
  FK_IMP_KARTID NUMBER,
  FK_IMP_TDPC NUMBER,
  FN_IMP_STATUS NUMBER
 )
/
COMMENT ON TABLE MED.TIMP_DOC_ITEMS IS 
'“аблица дл€ хранени€ позиций импорта ¬оронов ќ.ј. (05.05.2009)'
/
COMMENT ON COLUMN MED.TIMP_DOC_ITEMS.FK_ID IS 'ключ'
/
COMMENT ON COLUMN MED.TIMP_DOC_ITEMS.FK_IMP_DOC_ID IS 'ссылка на MED.TIMP_DOC.FK_ID'
/
COMMENT ON COLUMN MED.TIMP_DOC_ITEMS.FC_SRC_NUM IS 'пор€дковый номер позиции'
/
COMMENT ON COLUMN MED.TIMP_DOC_ITEMS.FC_SRC_MEDIC_TORG_NAME IS 'торговое название'
/
COMMENT ON COLUMN MED.TIMP_DOC_ITEMS.FC_SRC_MEDIC_ID_THEIR IS 'ID наименовани€ от поставщика (дл€ св€зки с нашим ID)'
/
COMMENT ON COLUMN MED.TIMP_DOC_ITEMS.FC_SRC_MEDIC_ED_IZM IS 'ед. изм.'
/
COMMENT ON COLUMN MED.TIMP_DOC_ITEMS.FC_SRC_MEDIC_KOLVO IS 'кол-во'
/
COMMENT ON COLUMN MED.TIMP_DOC_ITEMS.FC_SRC_PARTY_SERIA IS 'сери€'
/
COMMENT ON COLUMN MED.TIMP_DOC_ITEMS.FC_SRC_PARTY_GODNOST IS 'срок годности'
/
COMMENT ON COLUMN MED.TIMP_DOC_ITEMS.FC_SRC_PARTY_PRICE_BEZ_NDS IS 'цена без ндс'
/
COMMENT ON COLUMN MED.TIMP_DOC_ITEMS.FC_SRC_PARTY_SUMM_NDS IS 'сумма с ндс'
/
COMMENT ON COLUMN MED.TIMP_DOC_ITEMS.FC_SRC_NDS IS 'ндс'
/
COMMENT ON COLUMN MED.TIMP_DOC_ITEMS.FC_SRC_PARTY_PROIZVODITEL IS 'производитель'
/
COMMENT ON COLUMN MED.TIMP_DOC_ITEMS.FC_SRC_PARTY_SERTIFIKAT IS 'сертификат'
/
COMMENT ON COLUMN MED.TIMP_DOC_ITEMS.FD_INS_DATE IS 'дата вставки записи'
/
COMMENT ON COLUMN MED.TIMP_DOC_ITEMS.FD_EDIT_DATE IS 'дата редактировани€'
/
COMMENT ON COLUMN MED.TIMP_DOC_ITEMS.FK_INS_MO IS 'кто вставил'
/
COMMENT ON COLUMN MED.TIMP_DOC_ITEMS.FK_EDIT_MO IS 'кто редактировал'
/
COMMENT ON COLUMN MED.TIMP_DOC_ITEMS.FK_PRS_MEDIC_ID_OUR IS 'ID медикамента из MED.TMEDIC (разобрано)'
/
COMMENT ON COLUMN MED.TIMP_DOC_ITEMS.FK_PRS_MEDIC_ID_THEIR IS 'ID наименовани€ от поставщика (разобрано)'
/
COMMENT ON COLUMN MED.TIMP_DOC_ITEMS.FK_PRS_MEDIC_ED_IZM IS 'ед. изм. (разобрано)'
/
COMMENT ON COLUMN MED.TIMP_DOC_ITEMS.FN_PRS_MEDIC_KOLVO IS 'кол-во (разобрано)'
/
COMMENT ON COLUMN MED.TIMP_DOC_ITEMS.FD_PRS_PARTY_GODNOST IS 'срок годности (разобрано)'
/
COMMENT ON COLUMN MED.TIMP_DOC_ITEMS.FN_PRS_PARTY_PRICE IS 'цена без ндс (разобрано)'
/
COMMENT ON COLUMN MED.TIMP_DOC_ITEMS.FN_PRS_PARTY_SUMM_NDS IS 'сумма с ндс (разобрано)'
/
COMMENT ON COLUMN MED.TIMP_DOC_ITEMS.FN_PRS_NDS IS 'ндс (разобрано)'
/
COMMENT ON COLUMN MED.TIMP_DOC_ITEMS.FK_PRS_PARTY_PROIZVODITEL IS 'производитель (разобрано)'
/
COMMENT ON COLUMN MED.TIMP_DOC_ITEMS.FK_PRS_PARTY_SERTIFIKAT IS 'сертификат (разобрано)'
/
COMMENT ON COLUMN MED.TIMP_DOC_ITEMS.FK_IMP_KARTID IS 'ID партии (после импорта)'
/
COMMENT ON COLUMN MED.TIMP_DOC_ITEMS.FK_IMP_TDPC IS 'ID MED.TDPC.DPID (после импорта)'
/
COMMENT ON COLUMN MED.TIMP_DOC_ITEMS.FN_IMP_STATUS IS 'статус дл€ импорта'
/

ALTER TABLE MED.TIMP_DOC_ITEMS MODIFY (FC_SRC_PARTY_SERIA VARCHAR2 (40) )
/

ALTER TABLE MED.TIMP_DOC_ITEMS ADD (FD_IMPORT DATE)
/
COMMENT ON COLUMN MED.TIMP_DOC_ITEMS.FD_IMPORT IS 'дата импорта'
/

DROP SEQUENCE MED.SEQ_TIMP_DOC_ITEMS
/
CREATE SEQUENCE MED.SEQ_TIMP_DOC_ITEMS
 START WITH  1
 INCREMENT BY  1
 MINVALUE  1
/

CREATE OR REPLACE TRIGGER MED.TIMP_DOC_ITEMS_ins
 BEFORE
  INSERT
 ON MED.TIMP_DOC_ITEMS
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
begin
  if NVL(:NEW.FK_ID,-1) < 0 then
    select MED.SEQ_TIMP_DOC_ITEMS.NEXTVAL INTO :NEW.FK_ID from dual;
  end if;
  :NEW.FD_INS_DATE := sysdate;
end;
/

CREATE Unique INDEX MED.TIMP_DOC_ITEMS_FK_ID ON MED.TIMP_DOC_ITEMS
   (  FK_ID ASC  ) 
 COMPUTE STATISTICS 
/

CREATE INDEX MED.TIMP_DOC_ITEMS_FK_IMP_DOC_ID ON MED.TIMP_DOC_ITEMS
   (  FK_IMP_DOC_ID ASC  ) 
 COMPUTE STATISTICS 
/
