ALTER TABLE MED.TMEDIC ADD (FL_EQUIPMENT NUMBER (1) DEFAULT 0)
/
COMMENT ON COLUMN MED.TMEDIC.FL_EQUIPMENT IS '0 - не оборудование, 1 - оборудование'
/

CREATE INDEX MED.TMEDIC_FL_EQUIPMENT ON MED.TMEDIC (  FL_EQUIPMENT ASC  ) 
 COMPUTE STATISTICS 
/
