create public synonym VPREPRLS for RLS.VPREPRLS;
create public synonym VnomenRls for RLS.VnomenRls;
CREATE PUBLIC SYNONYM GET_ACTMATTERSLIST FOR RLS.GET_ACTMATTERSLIST;
CREATE PUBLIC SYNONYM GET_ATXLIST FOR RLS.GET_ATXLIST;
CREATE PUBLIC SYNONYM GET_ICD10LIST FOR RLS.GET_ICD10LIST;
CREATE PUBLIC SYNONYM GET_PHARMACTDESC FOR RLS.GET_PHARMACTDESC;
CREATE PUBLIC SYNONYM Get_PharmGroupList FOR Rls.Get_PharmGroupList;

