DROP INDEX ASU.TURALGOSMID_BY_ALGOID
/

--
-- TURALGOSMID_BY_ALGOID  (Index) 
--
CREATE INDEX ASU.TURALGOSMID_BY_ALGOID ON ASU.TURALGOSMID
(FK_ALGOID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


