DROP INDEX ASU.TQCSHUHART_BY_DATE
/

--
-- TQCSHUHART_BY_DATE  (Index) 
--
CREATE INDEX ASU.TQCSHUHART_BY_DATE ON ASU.TQCSHUHART
(FD_DATE)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          256K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


