DROP INDEX ASU.TGRAPH_RASPID_TIME
/

--
-- TGRAPH_RASPID_TIME  (Index) 
--
CREATE INDEX ASU.TGRAPH_RASPID_TIME ON ASU.TGRAPH
(FK_RASPID, FT_HOUR, FT_MIN, FD_DATE)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          12672K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


