DROP INDEX ASU.TSROKY_BY_ID_PACID_PRYB_D1_D3
/

--
-- TSROKY_BY_ID_PACID_PRYB_D1_D3  (Index) 
--
CREATE UNIQUE INDEX ASU.TSROKY_BY_ID_PACID_PRYB_D1_D3 ON ASU.TSROKY
(FK_ID, FK_PRYB, FK_PACID, FD_DATA1, FD_DATA3)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          3200K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


