DROP INDEX ASU.TCLNRS_BY_PALATA
/

--
-- TCLNRS_BY_PALATA  (Index) 
--
CREATE INDEX ASU.TCLNRS_BY_PALATA ON ASU.TCLEANERS
(FK_PALATAID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


