DROP INDEX ASU.TCERTIFICETE_BY_PEPLID
/

--
-- TCERTIFICETE_BY_PEPLID  (Index) 
--
CREATE INDEX ASU.TCERTIFICETE_BY_PEPLID ON ASU.TCERTIFICATE
(FK_PEPLID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


