DROP INDEX ASU.PK_TSTANDART_ICD10
/

--
-- PK_TSTANDART_ICD10  (Index) 
--
CREATE UNIQUE INDEX ASU.PK_TSTANDART_ICD10 ON ASU.TSTANDART_ICD10
(FK_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


