DROP INDEX ASU.DELETEIT2
/

--
-- DELETEIT2  (Index) 
--
CREATE UNIQUE INDEX ASU.DELETEIT2 ON ASU.TS_SPRAV
(FK_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


