DROP INDEX ASU.TPERESEL_LOG$FK_DOCOBSLID
/

--
-- TPERESEL_LOG$FK_DOCOBSLID  (Index) 
--
CREATE INDEX ASU.TPERESEL_LOG$FK_DOCOBSLID ON ASU.TPERESEL_LOG
(FK_DOCOBSLID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


