DROP INDEX ASU.K_TEXSLUCH_ERR_ARCHIVE_ID
/

--
-- K_TEXSLUCH_ERR_ARCHIVE_ID  (Index) 
--
CREATE UNIQUE INDEX ASU.K_TEXSLUCH_ERR_ARCHIVE_ID ON ASU.TEXSLUCH_ERR_ARCHIVE
(FK_ID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


