DROP INDEX ASU.TICD10$FC_NAME
/

--
-- TICD10$FC_NAME  (Index) 
--
CREATE INDEX ASU.TICD10$FC_NAME ON ASU.TICD10
(FC_NAME)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


