DROP INDEX ASU.TLABLOT_BY_DATE_NUM
/

--
-- TLABLOT_BY_DATE_NUM  (Index) 
--
CREATE UNIQUE INDEX ASU.TLABLOT_BY_DATE_NUM ON ASU.TLABLOT
(FD_DATE, FN_NUMBER)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


