DROP INDEX ASU.TIBSHABLONS_ID_SMID
/

--
-- TIBSHABLONS_ID_SMID  (Index) 
--
CREATE UNIQUE INDEX ASU.TIBSHABLONS_ID_SMID ON ASU.TIBSHABLONS
(FK_ID, FK_SMID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          384K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


