DROP INDEX ASU.TVACCANCEL_PREP$FK_VAC_CANCEL
/

--
-- TVACCANCEL_PREP$FK_VAC_CANCEL  (Index) 
--
CREATE INDEX ASU.TVACCANCEL_PREP$FK_VAC_CANCEL ON ASU.TVACCANCEL_PREP
(FK_VAC_CANCEL)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


