DROP INDEX ASU.TPAC_INSURANCE_BY_PACID
/

--
-- TPAC_INSURANCE_BY_PACID  (Index) 
--
CREATE INDEX ASU.TPAC_INSURANCE_BY_PACID ON ASU.TPAC_INSURANCE
(FK_PACID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          640K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


