DROP INDEX ASU.PK_TSTATCARDVMP
/

--
-- PK_TSTATCARDVMP  (Index) 
--
CREATE UNIQUE INDEX ASU.PK_TSTATCARDVMP ON ASU.TSTATCARDVMP
(FK_ID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


