DROP INDEX ASU.PK_PAC_VISITOR
/

--
-- PK_PAC_VISITOR  (Index) 
--
CREATE UNIQUE INDEX ASU.PK_PAC_VISITOR ON ASU.TPAC_VISITOR
(FK_ID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


