DROP INDEX ASU.TINSURDOCS_BY_PEPLID
/

--
-- TINSURDOCS_BY_PEPLID  (Index) 
--
CREATE INDEX ASU.TINSURDOCS_BY_PEPLID ON ASU.TINSURDOCS
(FK_PEPLID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          5712K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


