DROP INDEX ASU.TRESMEDCONT$MEDKARTID
/

--
-- TRESMEDCONT$MEDKARTID  (Index) 
--
CREATE INDEX ASU.TRESMEDCONT$MEDKARTID ON ASU.TRESMEDCONT
(FK_MEDKARTID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          640K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


