DROP INDEX ASU.VNAZ_BY_DATA_PACID
/

--
-- VNAZ_BY_DATA_PACID  (Index) 
--
CREATE UNIQUE INDEX ASU.VNAZ_BY_DATA_PACID ON ASU.VNAZ
(FD_RUN, FK_PACID, FK_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          15232K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


