DROP INDEX ASU.TSROKY_PRYB_PACID
/

--
-- TSROKY_PRYB_PACID  (Index) 
--
CREATE UNIQUE INDEX ASU.TSROKY_PRYB_PACID ON ASU.TSROKY
(FK_ID, FK_PRYB, FK_PACID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1280K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


