DROP INDEX ASU.TKLADR_UPDATE_PK
/

--
-- TKLADR_UPDATE_PK  (Index) 
--
CREATE UNIQUE INDEX ASU.TKLADR_UPDATE_PK ON ASU.TKLADR_UPDATE
(FK_ID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


