DROP INDEX ASU.TTABLES_LINKS_TABLE1
/

--
-- TTABLES_LINKS_TABLE1  (Index) 
--
CREATE INDEX ASU.TTABLES_LINKS_TABLE1 ON ASU.TTABLES_LINKS
(FC_TABLE1_NAME, FK_ID1)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


