DROP INDEX ASU.TSUBDIAG_BY_DIAGID_SUBDIAGID
/

--
-- TSUBDIAG_BY_DIAGID_SUBDIAGID  (Index) 
--
CREATE INDEX ASU.TSUBDIAG_BY_DIAGID_SUBDIAGID ON ASU.TSUBDIAG
(FK_DIAGID, FK_SMDIAGID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          3328K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


