DROP INDEX ASU.TPRIEMNAZ_BY_PARENTID
/

--
-- TPRIEMNAZ_BY_PARENTID  (Index) 
--
CREATE INDEX ASU.TPRIEMNAZ_BY_PARENTID ON ASU.TPRIEMNAZ
(FK_PARENTID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          8240K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


