DROP INDEX ASU.TGRAPH_CRITERIA_NAZ_CRIT
/

--
-- TGRAPH_CRITERIA_NAZ_CRIT  (Index) 
--
CREATE INDEX ASU.TGRAPH_CRITERIA_NAZ_CRIT ON ASU.TGRAPH_CRITERIA_NAZ
(FK_ID, FK_CRITERID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


