DROP INDEX ASU.I_TUSL_DBF_ARCHIVE_SLUCHID
/

--
-- I_TUSL_DBF_ARCHIVE_SLUCHID  (Index) 
--
CREATE INDEX ASU.I_TUSL_DBF_ARCHIVE_SLUCHID ON ASU.TUSL_DBF_ARCHIVE
(FK_SLUCHID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


