DROP INDEX ASU.TSOTR$NAME
/

--
-- TSOTR$NAME  (Index) 
--
CREATE INDEX ASU.TSOTR$NAME ON ASU.TSOTR1
(FC_FAM, FC_NAME, FC_OTCH)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


