DROP INDEX ASU.TCHEMO_AGGRAVATIONS_KURS
/

--
-- TCHEMO_AGGRAVATIONS_KURS  (Index) 
--
CREATE INDEX ASU.TCHEMO_AGGRAVATIONS_KURS ON ASU.TCHEMOTHERAPY_AGGRAVATIONS
(FK_TCHEMOTHERAPY_KURS)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


