DROP INDEX ASU.TNAZMED_CANSELOSMOTR
/

--
-- TNAZMED_CANSELOSMOTR  (Index) 
--
CREATE INDEX ASU.TNAZMED_CANSELOSMOTR ON ASU.TNAZMED
(FK_CANCELOSMOTRID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


