DROP INDEX ASU.TDISTRICT_VRACH
/

--
-- TDISTRICT_VRACH  (Index) 
--
CREATE UNIQUE INDEX ASU.TDISTRICT_VRACH ON ASU.TDISTRICT_VRACH
(FK_DIST_NAME_ID, FK_SOTR)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


