DROP INDEX ASU.TDSOCGROUP_FK_SOCGROUPID
/

--
-- TDSOCGROUP_FK_SOCGROUPID  (Index) 
--
CREATE INDEX ASU.TDSOCGROUP_FK_SOCGROUPID ON ASU.TDISPGROUPSOCGROUP
(FK_SOCGROUPID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


