DROP INDEX ASU.PK_TRECEPTION
/

--
-- PK_TRECEPTION  (Index) 
--
CREATE UNIQUE INDEX ASU.PK_TRECEPTION ON ASU.TRECEPTION
(FK_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


