DROP INDEX ASU.TPAY_TYPE_SPR_PK
/

--
-- TPAY_TYPE_SPR_PK  (Index) 
--
CREATE UNIQUE INDEX ASU.TPAY_TYPE_SPR_PK ON ASU.TPAY_TYPE_SPR
(FK_ID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


