DROP INDEX ASU.TIBDEFEKT_BY_VRACH_DATE_PODP
/

--
-- TIBDEFEKT_BY_VRACH_DATE_PODP  (Index) 
--
CREATE INDEX ASU.TIBDEFEKT_BY_VRACH_DATE_PODP ON ASU.TIBDEFEKT
(FK_VRACHID, FD_DATE, FL_PODPIS)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


