DROP INDEX ASU.TSECTION_RIGHTS_SOTR_SECID
/

--
-- TSECTION_RIGHTS_SOTR_SECID  (Index) 
--
CREATE INDEX ASU.TSECTION_RIGHTS_SOTR_SECID ON ASU.TSECTION_RIGHTS
(FK_SOTRID, FK_SECID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


