DROP INDEX ASU.TEFFECT_BY_PACID_VID
/

--
-- TEFFECT_BY_PACID_VID  (Index) 
--
CREATE UNIQUE INDEX ASU.TEFFECT_BY_PACID_VID ON ASU.TEFFECT
(FK_PACID, FP_VID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


