DROP INDEX ASU.TNAZOPER_NAZ_BY_NAZID_MEMTYPE
/

--
-- TNAZOPER_NAZ_BY_NAZID_MEMTYPE  (Index) 
--
CREATE INDEX ASU.TNAZOPER_NAZ_BY_NAZID_MEMTYPE ON ASU.TNAZOPER_NAZ
(FK_NAZID, FP_MEMTYPE)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


