DROP INDEX ASU.TSET_SOTR_SETID
/

--
-- TSET_SOTR_SETID  (Index) 
--
CREATE INDEX ASU.TSET_SOTR_SETID ON ASU.TSET_SOTR
(FK_SETID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


