DROP INDEX ASU.IDX_TCOMPANY_OTDEL_SYNC
/

--
-- IDX_TCOMPANY_OTDEL_SYNC  (Index) 
--
CREATE INDEX ASU.IDX_TCOMPANY_OTDEL_SYNC ON ASU.TCOMPANY_OTDEL
(FC_NAME)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


