DROP INDEX ASU.TVACCIN_PREP_STORE_FK_VACCIN_P
/

--
-- TVACCIN_PREP_STORE_FK_VACCIN_P  (Index) 
--
CREATE INDEX ASU.TVACCIN_PREP_STORE_FK_VACCIN_P ON ASU.TVACCIN_PREP_STORE
(FK_VACCIN_PREP)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


