DROP INDEX ASU.TMULTIVMSG_PK
/

--
-- TMULTIVMSG_PK  (Index) 
--
CREATE UNIQUE INDEX ASU.TMULTIVMSG_PK ON ASU.TMULTIMSG
(FK_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


