DROP INDEX ASU.TAMBULANCE_DOCOBSL
/

--
-- TAMBULANCE_DOCOBSL  (Index) 
--
CREATE INDEX ASU.TAMBULANCE_DOCOBSL ON ASU.TAMBULANCE
(FK_DOCOBSL)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          4224K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


