DROP INDEX ASU.TZAYAVKA_DPC_PARENT
/

--
-- TZAYAVKA_DPC_PARENT  (Index) 
--
CREATE INDEX ASU.TZAYAVKA_DPC_PARENT ON MED.TZAYAVKA_DPC
(FK_ZAYAVKA)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


