DROP INDEX ASU.TNAZID_BY_NAZID
/

--
-- TNAZID_BY_NAZID  (Index) 
--
CREATE INDEX ASU.TNAZID_BY_NAZID ON ASU.TNAZID
(FK_NAZID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


