DROP INDEX ASU.VRES$PACID$FK_SMID
/

--
-- VRES$PACID$FK_SMID  (Index) 
--
CREATE INDEX ASU.VRES$PACID$FK_SMID ON ASU.VRES
(FK_PACID, FK_SMID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


