DROP INDEX ASU.IDX_TSMID_GUID
/

--
-- IDX_TSMID_GUID  (Index) 
--
CREATE INDEX ASU.IDX_TSMID_GUID ON ASU.TSMID
(FK_GUID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


