DROP INDEX ASU.TADRESS_BY_PACID
/

--
-- TADRESS_BY_PACID  (Index) 
--
CREATE INDEX ASU.TADRESS_BY_PACID ON ASU.TADRESS
(FK_PACID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          3872K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


