DROP INDEX ASU.K_TPERESEL_DIAG_PERESEL
/

--
-- K_TPERESEL_DIAG_PERESEL  (Index) 
--
CREATE UNIQUE INDEX ASU.K_TPERESEL_DIAG_PERESEL ON ASU.TPERESEL_DIAG
(FK_PERESEL)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


