DROP INDEX ASU.TTEMPLIST_PACID
/

--
-- TTEMPLIST_PACID  (Index) 
--
CREATE INDEX ASU.TTEMPLIST_PACID ON ASU.TTEMPLIST
(FK_PACID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          4992K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


