DROP INDEX ASU.TRESKONS_BY_ID
/

--
-- TRESKONS_BY_ID  (Index) 
--
CREATE INDEX ASU.TRESKONS_BY_ID ON ASU.TRESKONS
(FK_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          768K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


