DROP INDEX ASU.PK_TOUTSOTRPARAM
/

--
-- PK_TOUTSOTRPARAM  (Index) 
--
CREATE UNIQUE INDEX ASU.PK_TOUTSOTRPARAM ON ASU.TOUTSOTRPARAM
(FK_ID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


