DROP INDEX ASU.TINSURDOCS_BYSERANDNUM
/

--
-- TINSURDOCS_BYSERANDNUM  (Index) 
--
CREATE INDEX ASU.TINSURDOCS_BYSERANDNUM ON ASU.TINSURDOCS
(TRIM("FC_SER"||"FC_NUM"), FK_COMPANYID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


