DROP INDEX ASU.TVAC_PEOPLES_TEST$FK_PEOPLE
/

--
-- TVAC_PEOPLES_TEST$FK_PEOPLE  (Index) 
--
CREATE INDEX ASU.TVAC_PEOPLES_TEST$FK_PEOPLE ON ASU.TVAC_PEOPLES_TEST
(FK_PEOPLE)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


