DROP INDEX ASU.PK_BILL_USLUG
/

--
-- PK_BILL_USLUG  (Index) 
--
CREATE UNIQUE INDEX ASU.PK_BILL_USLUG ON ASU.TBILL_USLUG
(FK_ID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


