DROP INDEX ASU.TCHILD_PEOPL
/

--
-- TCHILD_PEOPL  (Index) 
--
CREATE UNIQUE INDEX ASU.TCHILD_PEOPL ON ASU.TCHILD_COMMON
(FK_PEPLID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


