DROP INDEX ASU.TGRAPH_DATE_RASP
/

--
-- TGRAPH_DATE_RASP  (Index) 
--
CREATE INDEX ASU.TGRAPH_DATE_RASP ON ASU.TGRAPH
(FK_RASPID, FD_DATE)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          12672K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


