DROP INDEX ASU.TFISCALREPORT_IDX
/

--
-- TFISCALREPORT_IDX  (Index) 
--
CREATE INDEX ASU.TFISCALREPORT_IDX ON ASU.TFISCALREPORT
(FD_DATE, FC_KKM, FC_NUM)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


