DROP INDEX ASU.TNAZIS_BY_NAZOWNER
/

--
-- TNAZIS_BY_NAZOWNER  (Index) 
--
CREATE INDEX ASU.TNAZIS_BY_NAZOWNER ON ASU.TNAZIS
(FK_NAZOWNER)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


