DROP INDEX ASU.TPUTPLANDATA_BY_DAYSID_PUTID
/

--
-- TPUTPLANDATA_BY_DAYSID_PUTID  (Index) 
--
CREATE INDEX ASU.TPUTPLANDATA_BY_DAYSID_PUTID ON ASU.TPUTPLANDATA
(FK_DAYSID, FK_PUTID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          256K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


