DROP INDEX ASU.PK_TUSLUG_PAY_REQ
/

--
-- PK_TUSLUG_PAY_REQ  (Index) 
--
CREATE UNIQUE INDEX ASU.PK_TUSLUG_PAY_REQ ON ASU.TUSLUG_PAY_REQ
(FK_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


