DROP INDEX ASU.IDX_TUSLVID_GUID
/

--
-- IDX_TUSLVID_GUID  (Index) 
--
CREATE INDEX ASU.IDX_TUSLVID_GUID ON ASU.TUSLVID
(FK_GUID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


