DROP INDEX ASU.THEAL_SMID_DT_HEAL
/

--
-- THEAL_SMID_DT_HEAL  (Index) 
--
CREATE INDEX ASU.THEAL_SMID_DT_HEAL ON ASU.THEAL_SMID_DT
(FK_HEAL_SMID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


