DROP INDEX ASU.TRECIPE_FEDPAC_CATEG_PACID_IDX
/

--
-- TRECIPE_FEDPAC_CATEG_PACID_IDX  (Index) 
--
CREATE INDEX ASU.TRECIPE_FEDPAC_CATEG_PACID_IDX ON ASU.TRECIPE_DLO_FED_PAC_CATEG
(FK_FEDPACID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


