DROP INDEX ASU.TAMBHISTORY_BY_FK_TOOTD
/

--
-- TAMBHISTORY_BY_FK_TOOTD  (Index) 
--
CREATE INDEX ASU.TAMBHISTORY_BY_FK_TOOTD ON ASU.TDOCHISTORY
(FK_TOOTDELID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


