DROP INDEX ASU.TNAZKONS_BY_DATA_PACID
/

--
-- TNAZKONS_BY_DATA_PACID  (Index) 
--
CREATE UNIQUE INDEX ASU.TNAZKONS_BY_DATA_PACID ON ASU.TNAZKONS
(FK_PACID, FD_RUN, FK_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          6272K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


