DROP INDEX ASU.PK_TUSLUGMARK
/

--
-- PK_TUSLUGMARK  (Index) 
--
CREATE UNIQUE INDEX ASU.PK_TUSLUGMARK ON ASU.TUSLUGMARK
(FC_NAME)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


