DROP INDEX ASU.TLIN_PAC_MONITOR_BY_DATE
/

--
-- TLIN_PAC_MONITOR_BY_DATE  (Index) 
--
CREATE INDEX ASU.TLIN_PAC_MONITOR_BY_DATE ON ASU.TLIN_PAC_MONITOR
(FD_DATE)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


