DROP INDEX ASU.TUSL_KART_FK_HEALID_FK_GROUP
/

--
-- TUSL_KART_FK_HEALID_FK_GROUP  (Index) 
--
CREATE INDEX ASU.TUSL_KART_FK_HEALID_FK_GROUP ON ASU.TUSL_KART
(FK_HEALID, FK_GROUPID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


