DROP INDEX ASU.TNAZMED_FD_BEGIN
/

--
-- TNAZMED_FD_BEGIN  (Index) 
--
CREATE INDEX ASU.TNAZMED_FD_BEGIN ON ASU.TNAZMED
("FD_BEGIN" DESC)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


