DROP INDEX ASU.TINSURDOCS_BY_FD_END_PROLONG
/

--
-- TINSURDOCS_BY_FD_END_PROLONG  (Index) 
--
CREATE INDEX ASU.TINSURDOCS_BY_FD_END_PROLONG ON ASU.TINSURDOCS
(FD_END, FD_PROLONG)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


