DROP INDEX ASU.TRECIPE_FD_DATE
/

--
-- TRECIPE_FD_DATE  (Index) 
--
CREATE INDEX ASU.TRECIPE_FD_DATE ON ASU.TRECIPE
(FD_DATE)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


