DROP INDEX ASU.TVACCIN_PREP_INFECTION_FK_VI
/

--
-- TVACCIN_PREP_INFECTION_FK_VI  (Index) 
--
CREATE INDEX ASU.TVACCIN_PREP_INFECTION_FK_VI ON ASU.TVACCIN_PREP_INFECTION
(FK_VACCIN_INFECTION)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


