DROP INDEX ASU.TNAZAN_SOS_RASPIS
/

--
-- TNAZAN_SOS_RASPIS  (Index) 
--
CREATE INDEX ASU.TNAZAN_SOS_RASPIS ON ASU.TNAZAN
(FK_NAZSOSID, FL_IN_RASPIS)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          4352K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


