DROP INDEX ASU.TSHABLON_XRAY_ZAKL_ID
/

--
-- TSHABLON_XRAY_ZAKL_ID  (Index) 
--
CREATE UNIQUE INDEX ASU.TSHABLON_XRAY_ZAKL_ID ON ASU.TSHABLON_XRAY_ZAKL
(FK_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


