DROP INDEX ASU.TIBPAC_RAZ_PACID_RAZID_SMID
/

--
-- TIBPAC_RAZ_PACID_RAZID_SMID  (Index) 
--
CREATE INDEX ASU.TIBPAC_RAZ_PACID_RAZID_SMID ON ASU.TIBPAC_RAZ
(FK_PACID, FK_RAZID, FK_SMID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          3760K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


