DROP INDEX ASU.IX_TSTANDART$FK_RAZDEL
/

--
-- IX_TSTANDART$FK_RAZDEL  (Index) 
--
CREATE INDEX ASU.IX_TSTANDART$FK_RAZDEL ON ASU.TSTANDART
(FK_RAZDEL)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


