DROP INDEX ASU.TLABREG_BY_ID_REGIST
/

--
-- TLABREG_BY_ID_REGIST  (Index) 
--
CREATE UNIQUE INDEX ASU.TLABREG_BY_ID_REGIST ON ASU.TLABREG
(FK_ID, FD_REGIST)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1664K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


