DROP INDEX ASU.TPROFP_LIST_NAZ_BY_ACTID
/

--
-- TPROFP_LIST_NAZ_BY_ACTID  (Index) 
--
CREATE INDEX ASU.TPROFP_LIST_NAZ_BY_ACTID ON ASU.TPROFP_LIST_NAZ
(FK_ACTIONID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          5792K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


