DROP INDEX ASU.TSTATKARTA_LOG_VRACHID
/

--
-- TSTATKARTA_LOG_VRACHID  (Index) 
--
CREATE INDEX ASU.TSTATKARTA_LOG_VRACHID ON ASU.TSTATKARTA_LOG
(FK_VRACHID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          416K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


