DROP INDEX ASU.TAMBTALON_DIAGS_BY_TALON
/

--
-- TAMBTALON_DIAGS_BY_TALON  (Index) 
--
CREATE INDEX ASU.TAMBTALON_DIAGS_BY_TALON ON ASU.TAMBTALON_DIAGS
(FK_TALONID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


