DROP INDEX ASU.TSLPRINT_INFO
/

--
-- TSLPRINT_INFO  (Index) 
--
CREATE INDEX ASU.TSLPRINT_INFO ON ASU.TSLPRINT
(FK_INFOID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


