DROP INDEX ASU.TRSF_SAVED_REESTR_BY_INSURID
/

--
-- TRSF_SAVED_REESTR_BY_INSURID  (Index) 
--
CREATE INDEX ASU.TRSF_SAVED_REESTR_BY_INSURID ON ASU.TRSF_SAVED_REESTR
(FK_INSURDOCID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


