DROP INDEX ASU.TGRAPH_HOUR_MIN
/

--
-- TGRAPH_HOUR_MIN  (Index) 
--
CREATE INDEX ASU.TGRAPH_HOUR_MIN ON ASU.TGRAPH
(FT_HOUR, FT_MIN)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          2304K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


