DROP INDEX ASU.IQ_TSTANDART_ICD10$ALL
/

--
-- IQ_TSTANDART_ICD10$ALL  (Index) 
--
CREATE INDEX ASU.IQ_TSTANDART_ICD10$ALL ON ASU.TSTANDART_ICD10
(FK_STANDART, FK_ICD10)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          320K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


