DROP INDEX ASU.I_SLUCH_DBF_Q_U
/

--
-- I_SLUCH_DBF_Q_U  (Index) 
--
CREATE INDEX ASU.I_SLUCH_DBF_Q_U ON ASU.TSLUCH_DBF
(Q_U)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


