DROP INDEX ASU.TLASTFLUORO_PEPLID
/

--
-- TLASTFLUORO_PEPLID  (Index) 
--
CREATE UNIQUE INDEX ASU.TLASTFLUORO_PEPLID ON ASU.TLASTFLUORO
(FK_PEPLID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


