DROP INDEX ASU.TNAZKONS_DATE
/

--
-- TNAZKONS_DATE  (Index) 
--
CREATE INDEX ASU.TNAZKONS_DATE ON ASU.TNAZKONS
(FD_RUN)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          3712K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


