DROP INDEX ASU.TDEZHURSPECLINK_DEZHSPRAV
/

--
-- TDEZHURSPECLINK_DEZHSPRAV  (Index) 
--
CREATE UNIQUE INDEX ASU.TDEZHURSPECLINK_DEZHSPRAV ON ASU.TDEZHURSPECLINK
(FK_DEZHURSPECID, FK_SPRAVID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


