DROP INDEX ASU.I_PARPORT_MIC_FK_PEPL
/

--
-- I_PARPORT_MIC_FK_PEPL  (Index) 
--
CREATE INDEX ASU.I_PARPORT_MIC_FK_PEPL ON ASU.PASPORT_MIC
(FK_PEPL)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


