DROP INDEX ASU.TDNAZLIST_FK_PERIODSROKID
/

--
-- TDNAZLIST_FK_PERIODSROKID  (Index) 
--
CREATE INDEX ASU.TDNAZLIST_FK_PERIODSROKID ON ASU.TDISPGROUPNAZLIST
(FK_PERIODSROKID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


