DROP INDEX ASU.TDOCOBSL_STANDART_BY_DOCOBSL
/

--
-- TDOCOBSL_STANDART_BY_DOCOBSL  (Index) 
--
CREATE INDEX ASU.TDOCOBSL_STANDART_BY_DOCOBSL ON ASU.TDOCOBSL_STANDART
(FK_DOCOBSL)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


