DROP INDEX ASU.IX_TLABREPTESTINISM_FK_SMID
/

--
-- IX_TLABREPTESTINISM_FK_SMID  (Index) 
--
CREATE INDEX ASU.IX_TLABREPTESTINISM_FK_SMID ON ASU.TLABREPTEST_INISMID
(FK_SMID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


