DROP INDEX ASU.TSMINI_BY_SECTION
/

--
-- TSMINI_BY_SECTION  (Index) 
--
CREATE INDEX ASU.TSMINI_BY_SECTION ON ASU.TSMINI
(FC_SECTION)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


