DROP INDEX ASU.TSMID_SOOTV_OKB_SHABL$FK_ID
/

--
-- TSMID_SOOTV_OKB_SHABL$FK_ID  (Index) 
--
CREATE UNIQUE INDEX ASU.TSMID_SOOTV_OKB_SHABL$FK_ID ON ASU.TSMID_SOOTV_OKB_SHABL
(FK_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


