DROP INDEX ASU.TPATALOGY_VRACHID_SHOWN
/

--
-- TPATALOGY_VRACHID_SHOWN  (Index) 
--
CREATE INDEX ASU.TPATALOGY_VRACHID_SHOWN ON ASU.TPATALOGY
(FK_VRACHID, FL_SHOWN)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          512K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


