DROP INDEX ASU.TGRAPH_SHABLON$FK_SOTR
/

--
-- TGRAPH_SHABLON$FK_SOTR  (Index) 
--
CREATE INDEX ASU.TGRAPH_SHABLON$FK_SOTR ON ASU.TGRAPH_SHABLON
(FK_SOTR)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


