DROP INDEX ASU.TTEMPLIST_PAC_SMID_ZAPOLN
/

--
-- TTEMPLIST_PAC_SMID_ZAPOLN  (Index) 
--
CREATE INDEX ASU.TTEMPLIST_PAC_SMID_ZAPOLN ON ASU.TTEMPLIST
(FK_PACID, FK_SMIDID, FD_ZAPOLN)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


