DROP INDEX ASU.IQ_TSTANDART_TIPROOM$ALL
/

--
-- IQ_TSTANDART_TIPROOM$ALL  (Index) 
--
CREATE INDEX ASU.IQ_TSTANDART_TIPROOM$ALL ON ASU.TSTANDART_TIPROOM
(FK_STANDART, FK_TIPROOM)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          704K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


