DROP INDEX ASU.PK_T_SDF_ELEMENT
/

--
-- PK_T_SDF_ELEMENT  (Index) 
--
CREATE UNIQUE INDEX ASU.PK_T_SDF_ELEMENT ON ASU.T_SDF_ELEMENT
(FK_ID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


