DROP INDEX ASU.TSYNTEXT_BY_SYNONIM
/

--
-- TSYNTEXT_BY_SYNONIM  (Index) 
--
CREATE UNIQUE INDEX ASU.TSYNTEXT_BY_SYNONIM ON ASU.TSYNTEXT
(FC_SYNONIM)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


