DROP INDEX ASU.PK_TVACCIN_PREP_STORE_LOG
/

--
-- PK_TVACCIN_PREP_STORE_LOG  (Index) 
--
CREATE UNIQUE INDEX ASU.PK_TVACCIN_PREP_STORE_LOG ON ASU.TVACCIN_PREP_STORE_LOG
(FK_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


