DROP INDEX ASU.I_TARIFDETAIL_OWNER
/

--
-- I_TARIFDETAIL_OWNER  (Index) 
--
CREATE INDEX ASU.I_TARIFDETAIL_OWNER ON ASU.TARIFDETAIL
(FC_OWNER)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


