DROP INDEX ASU.TPRIEMNAZ$FK_NAZID
/

--
-- TPRIEMNAZ$FK_NAZID  (Index) 
--
CREATE INDEX ASU.TPRIEMNAZ$FK_NAZID ON ASU.TPRIEMNAZ
(FK_NAZID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


