DROP INDEX ASU.TDISTRICT_PK
/

--
-- TDISTRICT_PK  (Index) 
--
CREATE UNIQUE INDEX ASU.TDISTRICT_PK ON ASU.TDISTRICT
(FK_ID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


