DROP INDEX ASU.TPICS_NAZID
/

--
-- TPICS_NAZID  (Index) 
--
CREATE INDEX ASU.TPICS_NAZID ON ASU.TPICS
(FK_NAZID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          256K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


