DROP INDEX ASU.I_TUSL_DBF_STOR_PGSI
/

--
-- I_TUSL_DBF_STOR_PGSI  (Index) 
--
CREATE INDEX ASU.I_TUSL_DBF_STOR_PGSI ON ASU.TUSL_DBF_STOR
(FK_PREGROUPSLUCHID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


