DROP INDEX ASU.PK_TBLOB_ARRAY_FK_ID
/

--
-- PK_TBLOB_ARRAY_FK_ID  (Index) 
--
CREATE UNIQUE INDEX ASU.PK_TBLOB_ARRAY_FK_ID ON ASU.TBLOB_ARRAY
(FK_ID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


