DROP INDEX ASU.TPROFACTOR_BY_FK_PROFACTOR
/

--
-- TPROFACTOR_BY_FK_PROFACTOR  (Index) 
--
CREATE INDEX ASU.TPROFACTOR_BY_FK_PROFACTOR ON ASU.TPROFACTOR_SMIDKONS
(FK_PROFACTOR)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


