DROP INDEX ASU.IX_TSTANDART_HEAL$PERCENT
/

--
-- IX_TSTANDART_HEAL$PERCENT  (Index) 
--
CREATE INDEX ASU.IX_TSTANDART_HEAL$PERCENT ON ASU.TSTANDART_HEAL
(PERCENT)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          960K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


