DROP INDEX ASU.IDX_TICD10_MODERN_ICD10
/

--
-- IDX_TICD10_MODERN_ICD10  (Index) 
--
CREATE INDEX ASU.IDX_TICD10_MODERN_ICD10 ON ASU.TICD10_MODERN
(FK_ICD10)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


