DROP INDEX ASU.TS_COLUMNNAZ_OWNER
/

--
-- TS_COLUMNNAZ_OWNER  (Index) 
--
CREATE INDEX ASU.TS_COLUMNNAZ_OWNER ON ASU.TS_COLUMNNAZ
(FK_OWNER)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          192K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


