DROP INDEX ASU.PK_TREPETITION
/

--
-- PK_TREPETITION  (Index) 
--
CREATE UNIQUE INDEX ASU.PK_TREPETITION ON ASU.TREPETITION
(FK_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1280K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


