DROP INDEX ASU.IX_TVAC_STORE$FK_OTDEL
/

--
-- IX_TVAC_STORE$FK_OTDEL  (Index) 
--
CREATE UNIQUE INDEX ASU.IX_TVAC_STORE$FK_OTDEL ON ASU.TVAC_STORE
(FK_OTDEL)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


