DROP INDEX ASU.TSIGN_SQL_RULES_FC_TABLE
/

--
-- TSIGN_SQL_RULES_FC_TABLE  (Index) 
--
CREATE UNIQUE INDEX ASU.TSIGN_SQL_RULES_FC_TABLE ON ASU.TSIGN_SQL_RULES
(FC_TABLE)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


