DROP INDEX ASU.TCLN_BY_SOTR_PALATA
/

--
-- TCLN_BY_SOTR_PALATA  (Index) 
--
CREATE INDEX ASU.TCLN_BY_SOTR_PALATA ON ASU.TCLEAN
(FK_SOTRID, FK_PALATAID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


