DROP INDEX ASU.K_TEXSLUCHSAVEGROUPS_ID
/

--
-- K_TEXSLUCHSAVEGROUPS_ID  (Index) 
--
CREATE UNIQUE INDEX ASU.K_TEXSLUCHSAVEGROUPS_ID ON ASU.TEXSLUCHSAVEGROUPS
(FK_ID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


