DROP INDEX ASU.PK_TIS_FLUORO_POPULDATA_PATOLO
/

--
-- PK_TIS_FLUORO_POPULDATA_PATOLO  (Index) 
--
CREATE UNIQUE INDEX ASU.PK_TIS_FLUORO_POPULDATA_PATOLO ON ASU.TIS_FLUORO_POPULDATA_PATOLOG
(FK_ID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


