DROP INDEX ASU.TDISP_MK_FK_TALONID_1_IDX
/

--
-- TDISP_MK_FK_TALONID_1_IDX  (Index) 
--
CREATE INDEX ASU.TDISP_MK_FK_TALONID_1_IDX ON ASU.TDISP_MK
(FK_TALONID_1)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


