DROP INDEX ASU.TANONIM_ADRESS_BY_ID
/

--
-- TANONIM_ADRESS_BY_ID  (Index) 
--
CREATE UNIQUE INDEX ASU.TANONIM_ADRESS_BY_ID ON ASU.TANONYM_ADDRESS
(FK_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          3328K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


