DROP INDEX ASU.PK_TRICHVIEW_TEML_DEF
/

--
-- PK_TRICHVIEW_TEML_DEF  (Index) 
--
CREATE UNIQUE INDEX ASU.PK_TRICHVIEW_TEML_DEF ON ASU.TRICHVIEW_TEMPL_DEF
(FK_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


