DROP INDEX ASU.TPATNAME_BY_ID
/

--
-- TPATNAME_BY_ID  (Index) 
--
CREATE UNIQUE INDEX ASU.TPATNAME_BY_ID ON ASU.TPATNAME
(FK_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          3M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


