DROP INDEX ASU.PRIVATE_PLAN_BY_INFECTION
/

--
-- PRIVATE_PLAN_BY_INFECTION  (Index) 
--
CREATE INDEX ASU.PRIVATE_PLAN_BY_INFECTION ON ASU.TVAC_PRIVATE_PLAN
(FK_INFECTION)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


