DROP INDEX ASU.TGRAPH_ID
/

--
-- TGRAPH_ID  (Index) 
--
CREATE UNIQUE INDEX ASU.TGRAPH_ID ON ASU.TGRAPH
(FK_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1536K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


