DROP INDEX ASU.TPEOPLE_LGOT_PEOPLE_ID
/

--
-- TPEOPLE_LGOT_PEOPLE_ID  (Index) 
--
CREATE INDEX ASU.TPEOPLE_LGOT_PEOPLE_ID ON ASU.TPEOPLE_LGOT
(FK_PEOPLEID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


