DROP INDEX ASU.TAPRIH$AKOMUID
/

--
-- TAPRIH$AKOMUID  (Index) 
--
CREATE INDEX ASU.TAPRIH$AKOMUID ON ASU.TAPRIH
(FK_AKOMUID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


