DROP INDEX ASU.TSROKY_BY_D1_D3_P_VYB_PACID_ID
/

--
-- TSROKY_BY_D1_D3_P_VYB_PACID_ID  (Index) 
--
CREATE UNIQUE INDEX ASU.TSROKY_BY_D1_D3_P_VYB_PACID_ID ON ASU.TSROKY
(FD_DATA1, FD_DATA3, FK_PRYB, FK_VYB, FK_PACID, 
FK_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          3328K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


