DROP INDEX ASU.TPROFP_LIST_NAZ_BY_LISTACTID
/

--
-- TPROFP_LIST_NAZ_BY_LISTACTID  (Index) 
--
CREATE INDEX ASU.TPROFP_LIST_NAZ_BY_LISTACTID ON ASU.TPROFP_LIST_NAZ
(FK_LISTID, FK_ACTIONID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          7712K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


