DROP INDEX ASU.TSMIDNORMS_SMID_YEAR2
/

--
-- TSMIDNORMS_SMID_YEAR2  (Index) 
--
CREATE INDEX ASU.TSMIDNORMS_SMID_YEAR2 ON ASU.TSMIDNORMS
(FK_SMID, FN_YEAR2)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


