DROP INDEX ASU.TRECIPE_DLO_IMP_RECIPEGIUD_IDX
/

--
-- TRECIPE_DLO_IMP_RECIPEGIUD_IDX  (Index) 
--
CREATE UNIQUE INDEX ASU.TRECIPE_DLO_IMP_RECIPEGIUD_IDX ON ASU.TRECIPE_DLO_IMP
(RECIPEGUID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


