DROP INDEX ASU.TSMID_RIGHT_SOTR$SOTR
/

--
-- TSMID_RIGHT_SOTR$SOTR  (Index) 
--
CREATE UNIQUE INDEX ASU.TSMID_RIGHT_SOTR$SOTR ON ASU.TSMID_RIGHT_SOTR
(FK_SOTRID, FK_SMID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


