DROP INDEX ASU.TBIOSMID_SMID
/

--
-- TBIOSMID_SMID  (Index) 
--
CREATE INDEX ASU.TBIOSMID_SMID ON ASU.TBIOSMID
(FK_SMID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


