DROP INDEX ASU.I_TASKREPLYGROUP_TABLES
/

--
-- I_TASKREPLYGROUP_TABLES  (Index) 
--
CREATE INDEX ASU.I_TASKREPLYGROUP_TABLES ON ASU.TASKREPLYGROUP
(FC_ASK, FC_REPLY)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


