DROP INDEX ASU.TBLOBS_ID
/

--
-- TBLOBS_ID  (Index) 
--
CREATE UNIQUE INDEX ASU.TBLOBS_ID ON ASU.TBLOBS
(FK_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          256K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


