DROP INDEX ASU.I_TEXCHANGE_ELSELOG_OWNER
/

--
-- I_TEXCHANGE_ELSELOG_OWNER  (Index) 
--
CREATE INDEX ASU.I_TEXCHANGE_ELSELOG_OWNER ON ASU.TEXCHANGE_ELSELOG
(FC_TABLE, FK_OWNER)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


