DROP INDEX ASU.TCONFIRM_NAZ_NAZID
/

--
-- TCONFIRM_NAZ_NAZID  (Index) 
--
CREATE INDEX ASU.TCONFIRM_NAZ_NAZID ON ASU.TCONFIRM_NAZ
(FK_NAZID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


