DROP INDEX ASU.TANALPROC_FK_RESLECH_FK_RESAN
/

--
-- TANALPROC_FK_RESLECH_FK_RESAN  (Index) 
--
CREATE UNIQUE INDEX ASU.TANALPROC_FK_RESLECH_FK_RESAN ON ASU.TANALPROC
(FK_ANALID, FK_PROCID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


