DROP INDEX ASU.TPERIOD_COMPANY_COMPANYID
/

--
-- TPERIOD_COMPANY_COMPANYID  (Index) 
--
CREATE INDEX ASU.TPERIOD_COMPANY_COMPANYID ON ASU.TPERIOD_COMPANY
(FK_COMPANYID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


