DROP INDEX ASU.IDX_TCOUNTRY_GUID
/

--
-- IDX_TCOUNTRY_GUID  (Index) 
--
CREATE UNIQUE INDEX ASU.IDX_TCOUNTRY_GUID ON ASU.TCOUNTRY
(FK_GUID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


