DROP INDEX ASU.IDX_TVIDDOC_GUID
/

--
-- IDX_TVIDDOC_GUID  (Index) 
--
CREATE UNIQUE INDEX ASU.IDX_TVIDDOC_GUID ON ASU.TVIDDOC
(FK_GUID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


