DROP INDEX ASU.I_TUSL_DBF_TYPE_EO
/

--
-- I_TUSL_DBF_TYPE_EO  (Index) 
--
CREATE INDEX ASU.I_TUSL_DBF_TYPE_EO ON ASU.TUSL_DBF
(TYPE_EO)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


