DROP INDEX ASU.TRICHVIEWDATA_PACID
/

--
-- TRICHVIEWDATA_PACID  (Index) 
--
CREATE INDEX ASU.TRICHVIEWDATA_PACID ON ASU.TRICHVIEWDATA
(FK_PACID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          2176K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


