DROP INDEX ASU.TRESAN_BY_ID_PACID
/

--
-- TRESAN_BY_ID_PACID  (Index) 
--
CREATE UNIQUE INDEX ASU.TRESAN_BY_ID_PACID ON ASU.TRESAN
(FK_ID, FK_PACID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          13056K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


