DROP INDEX ASU.PK_DISPCARD_POS
/

--
-- PK_DISPCARD_POS  (Index) 
--
CREATE UNIQUE INDEX ASU.PK_DISPCARD_POS ON ASU.TDISPCARD_POS
(FK_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


