DROP INDEX ASU.TVRACHKAB_BY_SOTRID_SMID
/

--
-- TVRACHKAB_BY_SOTRID_SMID  (Index) 
--
CREATE INDEX ASU.TVRACHKAB_BY_SOTRID_SMID ON ASU.TVRACHKAB_NAZ
(FK_SOTRKABID, FK_SMID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          400K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


