DROP INDEX ASU.IX_NAZN_FBLOBS_U2
/

--
-- IX_NAZN_FBLOBS_U2  (Index) 
--
CREATE UNIQUE INDEX ASU.IX_NAZN_FBLOBS_U2 ON ASU.TRECEPTION_FBLOBS
(FK_FILE, FK_RECEPTION)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


