DROP INDEX ASU.PK_TICD10_MODERN
/

--
-- PK_TICD10_MODERN  (Index) 
--
CREATE UNIQUE INDEX ASU.PK_TICD10_MODERN ON ASU.TICD10_MODERN
(FK_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          448K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


