DROP INDEX ASU.TNAZVRACH#ID$DESC
/

--
-- TNAZVRACH#ID$DESC  (Index) 
--
CREATE UNIQUE INDEX ASU.TNAZVRACH#ID$DESC ON ASU.TNAZVRACH_OLD
("FK_ID" DESC)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          12672K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


