DROP INDEX ASU.TRECIPE_DLO_EXP_FK_RECIPE
/

--
-- TRECIPE_DLO_EXP_FK_RECIPE  (Index) 
--
CREATE INDEX ASU.TRECIPE_DLO_EXP_FK_RECIPE ON ASU.TRECIPE_DLO_EXP
(FK_RECIPE_ID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


