DROP INDEX ASU.TNAZMARK_X_NAZID
/

--
-- TNAZMARK_X_NAZID  (Index) 
--
CREATE UNIQUE INDEX ASU.TNAZMARK_X_NAZID ON ASU.TNAZMARK_X
(FK_NAZID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


