DROP INDEX ASU.TSLPERIOD_SOTR
/

--
-- TSLPERIOD_SOTR  (Index) 
--
CREATE INDEX ASU.TSLPERIOD_SOTR ON ASU.TSLPERIOD
(FK_SOTRID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


