DROP INDEX ASU.TNAZRASPRED_SPEC
/

--
-- TNAZRASPRED_SPEC  (Index) 
--
CREATE INDEX ASU.TNAZRASPRED_SPEC ON ASU.TNAZRASPRED
(FK_SPEC)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


