DROP INDEX ASU.IDX_EXP_SETTINGS_SYNONYM
/

--
-- IDX_EXP_SETTINGS_SYNONYM  (Index) 
--
CREATE INDEX ASU.IDX_EXP_SETTINGS_SYNONYM ON ASU.T_EXP_SETTINGS
(FC_SYNONYM)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


