DROP INDEX ASU.TBIRTH_CERTIFICATION_BY_ID
/

--
-- TBIRTH_CERTIFICATION_BY_ID  (Index) 
--
CREATE UNIQUE INDEX ASU.TBIRTH_CERTIFICATION_BY_ID ON ASU.TBIRTH_CERTIFICATION
(FK_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


