DROP INDEX ASU.TRECIPE_M_I_FK_VVODPATH
/

--
-- TRECIPE_M_I_FK_VVODPATH  (Index) 
--
CREATE INDEX ASU.TRECIPE_M_I_FK_VVODPATH ON ASU.TRECIPE_MEDIC
(FK_VVODPATH_ID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


