DROP INDEX ASU.TPUTS_BY_FK_PACID
/

--
-- TPUTS_BY_FK_PACID  (Index) 
--
CREATE INDEX ASU.TPUTS_BY_FK_PACID ON ASU.TPUTS
(FK_PACID, FC_PUT)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          512K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


