DROP INDEX ASU.KEY_SOPCLAIM_UNIQUE
/

--
-- KEY_SOPCLAIM_UNIQUE  (Index) 
--
CREATE UNIQUE INDEX ASU.KEY_SOPCLAIM_UNIQUE ON ASU.TSOPCLAIM
(FK_PACID, FK_DIAGID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


