DROP INDEX ASU.TDIGITAL_SIGNATURE_FK_SOTR_ID
/

--
-- TDIGITAL_SIGNATURE_FK_SOTR_ID  (Index) 
--
CREATE INDEX ASU.TDIGITAL_SIGNATURE_FK_SOTR_ID ON ASU.TDIGITAL_SIGNATURE
(FK_SOTRID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


