DROP INDEX ASU.TPAC_DISEASE_BY_PACID
/

--
-- TPAC_DISEASE_BY_PACID  (Index) 
--
CREATE INDEX ASU.TPAC_DISEASE_BY_PACID ON ASU.TPAC_DISEASE
(FK_PACID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


