DROP INDEX ASU.PK_TPHYSIOTHERAPY_MAPS
/

--
-- PK_TPHYSIOTHERAPY_MAPS  (Index) 
--
CREATE UNIQUE INDEX ASU.PK_TPHYSIOTHERAPY_MAPS ON ASU.TPHYSIOTHERAPY_MAPS
(FK_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


