DROP INDEX ASU.TKABSOOTVET_KEY_ID
/

--
-- TKABSOOTVET_KEY_ID  (Index) 
--
CREATE UNIQUE INDEX ASU.TKABSOOTVET_KEY_ID ON ASU.TKABSOOTVET
(FK_ID)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


