DROP INDEX ASU.TRECIPE_DLO_IMP_OST_SUBDIV
/

--
-- TRECIPE_DLO_IMP_OST_SUBDIV  (Index) 
--
CREATE INDEX ASU.TRECIPE_DLO_IMP_OST_SUBDIV ON ASU.TRECIPE_DLO_IMP_OST
(SUBDIVCODE)
NOLOGGING
TABLESPACE USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


